### ISSUE TITLE
PyCharm AWS Toolkit Not Setting Profiles Correctly

### ISSUE THREAD

**Issue by erpost** [aws/aws-toolkit-jetbrains#1032]
**Describe the bug**
I have PyCharm 2019.1 installed with the AWS Toolkit v1.4 Plugin setup. I have two profiles configured (default and readonly). However, when I select the readonly profile, PyCharm is still using the default profile.

I'm able to test this by having a working default profile and then purposely altering the readonly profile Secret Access Key. My code is a simple Python call to list S3 buckets.
This should allow my code to call to AWS and list my buckets with the default profile, but should fail when I switch to the readonly profile. Regardless what profile I have set, the call still goes through because it's only using the default profile. Can you assist? Thanks, Eric

What steps will reproduce the problem?

Setup PyCharm and AWS default profile
Setup second profile (readonly) and purposely alter the Secret Access Key
Run simple code to request S3 buckets using both profiles
What is the expected result?
Code should fail when altered profile (readonly) is run

What happens instead?
Code runs under both profiles, but should not

**Comment by zhangzhx** [comment]
Thanks for reporting this bug. What OS are you running in?

**Comment by zhangzhx** [comment]
@erpost If you altered the readonly profile, this would not be a valid AWS credential. When you pick this one, the Toolkit will check whether it is valid and if not falls back to previously selected profile in which case is still your default profile.

Did you run the unaltered readonly profile and still get this error behavior?

**Comment by abrooksv** [comment]
Changing to an invalid secret key should be showing very different behavior. The toolkit will make a call to `sts:GetCallerInfo` and if that fails will refuse to set the invalid credentials as active. You should be seeing a the following notification when that happens:

![Screen Shot 2019-06-13 at 9 36 10 AM](https://user-images.githubusercontent.com/8992246/59450731-b9156300-8dbe-11e9-97e0-2148ac514d51.png)

After that it should fal back to having no credentials active:
![Screen Shot 2019-06-13 at 9 38 35 AM](https://user-images.githubusercontent.com/8992246/59450858-07c2fd00-8dbf-11e9-98a8-e6738dcc6fbf.png)

Is this not what you are observing?

@zhangzhx Can we update that string so that it is a bit shorter so more info is shown without having to expand the notification?

**Comment by erpost** [comment]
I may have used a bad example, so let me try a different way.  I have two profiles created and being seen by PyCharm.  I have now purposely removed the permissions needed to run my code without errors (simple code to list buckets).  PyCharm sees both Profiles.  When I click on the Default Profile, I'm able to run my code and list the buckets.  I then switch Profiles in PyCharm to 'readonly' and I should get an error because that profile doesn't have the permissions needed to list buckets.  However, I'm still able to list buckets.  It seems to be using only the Default Profile.

I'm running MacOS Mojave (10.14.5).

Let me know if you need screenshots or anything additional for you to replicate what I'm seeing.

**Comment by abrooksv** [comment]
What do you mean by "run your code"? Are you using the toolkit to run a Lambda using a Lambda run configuration?

**Comment by erpost** [comment]
I have two different snippets of code I'm running.  The first [code](https://github.com/erpost/aws-boto3/blob/master/buckets/list_all_resource_profile.py) uses the profile parameter.  I can switch profiles by inputting the profile I'd like to use at runtime.  The second bit of [code](https://github.com/erpost/aws-boto3/blob/master/buckets/list_all_resource.py) does not use the profile parameter.  I'm trying to change which profile I'm using in PyCharm, but it's not working as expected.

**Comment by abrooksv** [comment]
Ah, since no profile/creds are set then the code will use the default credential chain which falls back to default profile. The toolkit does not inject active credentials for code launched through the IDE. There is an open feature request for that here: #926

**Comment by Ghilteras** [comment]
How do I change profile in Java? Is there an annotation that Intellij would recognize to get the right credentials of the many that I have in my credentials file? I can only use default because of this

**Comment by abrooksv** [comment]
@Ghilteras We do not inject the credentials into your program from the IDE, but you can set the profile you want to use with the SDK client by using `ProfileCredentialsProvider` from the SDK and tell it which profile to use and pass it to the client builders.

**Comment by zhangzhx** [comment]
Closing this issue in favor of the feature request #926.
