### ISSUE TITLE
Deploy Serverless Application fail - SAM did not complete successfully

### ISSUE THREAD

**Issue by JUNGQUI** [aws/aws-toolkit-jetbrains#1047]
**Describe the bug**

Before 3 weeks ago, My Pycharm project is well good at deploying. But now, there is error occur.
Error is that cannot find requirements.txt file in root directory.
But it is location at root directory. I don't know what is going on, help please.

**To reproduce**

1. Mouse over at project directory and right click.
2. Select 'Build function inside a container'
3. Click Deploy
4. see log failed. and log say 

`PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt`

**Expected behavior**

Deploying going on well.

**Screenshots**

![image](https://user-images.githubusercontent.com/39726558/59748854-e7aba600-92b6-11e9-9cf5-b8b8e7b4bfae.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: PyCharm 2019.1.3 (Professional Edition)
 - Toolkit Version: 1.4
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: python local interpreter is 3.7 and Deploying version is 3.6, but it is not related with this happen.

**Additional context**

I remember that my requirements.txt is maybe not installed by AWS SAM CLI. Maybe It created by just 'add new file' in PyCharm.
And of course requirements.txt located in source root.

**Comment by abrooksv** [comment]
Going across drive letters has issues in windows, will be fixed by #1034

**Comment by zhangzhx** [comment]
The fix was released in the [latest EAP version](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/65083). Feel free to give it a try and let us know if you still see the issue.

**Comment by JUNGQUI** [comment]
Thanks to fix it. I'll test this fix after intellij upload new AWS-toolkit version. Unfortunately for now, they did't update version 1.5.

Happy hacking!

**Comment by mikelyonsridgeline** [comment]
I ran into this and it was actually an odd permissions issue for me. doing `chmod a+r requirements.txt` fixed the inability to see the file.
