### ISSUE TITLE
AWS Toolkit for PyCharm does not find handlers when source roots are not set

### ISSUE THREAD

**Issue by chkothe** [aws/aws-toolkit-jetbrains#1054]
**Describe the bug**
When opening a pre-existing SAM project (e.g., the sam init hello-world example) with the AWS Toolkit for PyCharm and creating a launch configuration from the template.yaml, a broken launch configuration that reports the error "Cannot find handler 'app.lambda_handler' in project." is created.

**To reproduce**
1. Create SAM project outside PyCharm (e.g., `sam init --runtime=python3.6`)
2. Open project folder in PyCharm
3. Create new AWS Lambda [Local] launch configuration, choosing the template as the template
4. Observe that the generated launch configuration `[Local] HelloWorldFunction` is defunct, and shows the error "Error: Cannot find handler 'app.lambda_handler' in project." is displayed.

**Expected behavior**
The launch configuration should be runnable, or the error message should point at the likely issue.

**Your Environment**
 - OS: Windows 10 1803 x64
 - JetBrains' Product: PyCharm Professional Edition
 - JetBrains' Product Version: 2019.1.3 (Build #PY-191.7479.30, built on May 29, 2019)
 - Toolkit Version: v1.4
 - SAM CLI Version: 0.17.0
 - JVM/Python Version: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
 - Docker Desktop Version: Community Edition, Version 2.0.0.3 (31259)
 
**Additional context**
This seems to be because the hello_world folder is not marked as PyCharm Sources Root upon opening an external SAM project for the first time. Probably the toolkit could mark the SAM CodeUri as source root upon first-time opening (especially if there's only one CodeUri occurrence, where it's clearly the right way to fix the situation, and which seems to match what the toolkit sets up when it creates its own projects).

**Comment by abrooksv** [comment]
We should be able to infer it from the requirements.txt parent folder if source roots aren't set

**Comment by abrooksv** [comment]
The source roots come from when we did not use SAM, so it should probably actually be looked into and removed if no longer needed.

**Comment by zhangzhx** [comment]
The fix has been released in the [1.5 eap](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/64705). Can you try that out? If you still see this problem, feel free to open another issue.

**Comment by chkothe** [comment]
Great, confirmed that it's working now.
