### ISSUE TITLE
Using "Copy Configuration" in the launch config dialog does shallow copies for some fields

### ISSUE THREAD

**Issue by chkothe** [aws/aws-toolkit-jetbrains#1072]
**Describe the bug**
When one uses the button "Copy Configuration" in the dialog for editing a launch configuration, some of the field values (I noticed it for the File entry box under Input) are not copied but instead apparently referenced, so that when they are changed in the new launch config, it affects the value of the original launch config.

**To reproduce**
1. Create a new AWS Lambda Local project from the hello-world template
2. Create a launch configuration that uses the event.json file as the File in the Input category and confirm with OK
3. Edit the launch configuration and click the "Copy Configuration" button
4. type a unique name into the Name edit field for the new config (*) 
5. Change the File entry to event2.json and confirm with OK
6. Click on Edit Launch configurations, and observe that both launch configurations now refer to "event2.json", so editing the new config has affected the original config

**Expected behavior**
Properties of different launch configurations are independent

**Your Environment**
- OS: Windows 10 1803 x64
- JetBrains' Product: PyCharm Professional Edition
- JetBrains' Product Version: 2019.1.3 (Build #PY-191.7479.30, built on May 29, 2019)
- Toolkit Version: v1.4
- SAM CLI Version: 0.17.0
- JVM/Python Version: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
- Docker Desktop Version: Community Edition, Version 2.0.0.3 (31259)

**Additional context**
It seems that the issue is that copying the launch configuration only makes a shallow copy of some fields. Closing and re-starting PyCharm (and thus recreating these fields from file) now results in independently editable File properties for the two launch configs).

(*)  If you don't do this, an unrelated bug is triggered: while the initially proposed name for the newly copied launch config has a "(1)" appended, when you then start editing the File entry, the proposed name reverts back to the name of the original config. Thus it's no longer unique, and you can't save the new config before you change the Name.

**Comment by abrooksv** [comment]
I was able to reproduce the issues

**Comment by abrooksv** [comment]
This actually looks to be a bug in IntelliJ itself (at least the name part) using an Application run configuration.

**Comment by abrooksv** [comment]
To the name issue:
When IntelliJ does the clone it keeps the name marked as generated even though it modified it to add the `(1)`. This causes the save action to re-run the compute name logic on save so the name gets reset back to match.

**Comment by abrooksv** [comment]
The method `setName` that the framework calls is final so we can't patch it to say that it is no longer generated.

**Comment by abrooksv** [comment]
#1073 fixes the cloning issue

**Comment by abrooksv** [comment]
Fix merged to master, thank you for the detailed bug reports.
