### ISSUE TITLE
node10.x support

### ISSUE THREAD

**Issue by ghingis** [aws/aws-toolkit-jetbrains#1099]
**Is your feature request related to a problem? Please describe.**
During "Update Function Configuration" (after right click on a Lambda function in the AWS Explorer) the node10.x Runtime is missing. 

Also if your function is already on a node10.x with your functions, you are no longer able to update your functions, because upon saving you are getting a "Runtime must be specified error".

**Describe the solution you'd like**
I would like to see node10.x as a supported runtime.

**Describe alternatives you've considered**

**Additional context**
node10.x become available in 15 May: [https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/](url)
And it's already in the documentations: [https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html](url)

(I tried to find any related issue / commit, but I did not find anything)

**Comment by abrooksv** [comment]
Thanks for reporting this

**Comment by abrooksv** [comment]
Merged into master, will go out in the 1.5 release
