### ISSUE TITLE
Plugin breaks IntelliJ 2019.2

### ISSUE THREAD

**Issue by jonfreedman** [aws/aws-toolkit-jetbrains#1119]
**Describe the bug**
With the plugin installed it's no-longer possible to launch individual unit tests using the icons added to the left of the main code window.

**To reproduce**
1. Open a file containing some unit tests
2. Run individual test
3. Install plugin
4. Step #2 no-longer possible

**Expected behavior**
Prior to upgrading to 2019.2 this worked as expected, enabling this plugin should not break the functionality.

**Screenshots**
![intellij](https://user-images.githubusercontent.com/1092134/62126555-da2b0800-b2c7-11e9-86d7-318d18d0c49c.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version: 2019.10
 - Toolkit Version: 1.4
 - SAM CLI Version: aws-cli/1.16.198 Python/3.6.0 Windows/10 botocore/1.12.188
 - JVM/Python Version: 1.8.0_181

**Additional context**
https://intellij-support.jetbrains.com/hc/en-us/requests/2197772

**Comment by abrooksv** [comment]
I am not able to reproduce this with version 1.5 of the toolkit

**Comment by abrooksv** [comment]
What version of intellij are you running? Your description mentions 2019.10 and title says 2019.2. We also did not add 2019.2 support until V1.5

**Comment by jonfreedman** [comment]
Sorry I'm not sure where 2019.10 came from, that should read 2019.2

Is v1.5 released? IntelliJ wasn't offering me an upgrade yesterday... Happy to try the new version.

**Comment by abrooksv** [comment]
Yes, 1.5 has been released. Please let us know if you are still having the issue

**Comment by jonfreedman** [comment]
This specific issue does appear to be resolved with version 1.5 although IntelliJ would only let me upgrade by uninstalling 1.4, restarting and then installing 1.5
