### ISSUE TITLE
Intellisense for ECS Task Definition

### ISSUE THREAD

**Issue by seongmDevX** [aws/aws-toolkit-jetbrains#1133]
**Is your feature request related to a problem? Please describe.**
When users write ECS task definition inside their IDE, IntelliSense is not provided.

See:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html

https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019

**Describe the solution you'd like**
The Amazon ECS DevX team has generated a JSON schema file that will provide such IntelliSense. We propose inside your extension we include a file matching system that will activate the ECS task definition IntelliSense based on the file name.

**Describe alternatives you've considered**
A separate plugin or having a README file giving out instructions on how to modify their settings to have ECS IntelliSense but we want to incorporate our ideas into your plugin to have one AWS plugin

**Comment by rli** [comment]
Same request in VS Code: https://github.com/aws/aws-toolkit-vscode/issues/707

**Comment by seongmDevX** [comment]
Also was wondering if JetBrains team had documentation about JSON schemas like VScode

**Comment by rli** [comment]
You'll probably want to build a [JsonSchemaProviderFactory](https://github.com/JetBrains/intellij-community/blob/master/json/src/com/jetbrains/jsonSchema/extension/JsonSchemaProviderFactory.java) and [declare it as an extension](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_extensions_and_extension_points.html).

**Comment by abrooksv** [comment]
This has been added
