### ISSUE TITLE
Create new debug configuration panel shows error

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#1135]
**Describe the bug**
This is only happening on 2019.2. When creating a new debug configuration, an error shows in the panel as `Error: Debug: there are no runners for AWS Lambda: [Local] App`.

I still can proceed and debug the code, though.

**To reproduce**

1. Create a new hello world project with the new AWS project wizard. 
2. Target to the `App.java` and click the gutter icon to `debug`
3. After selecting a valid credentials provider and providing a valid input, there is still an error as above.

**Expected behavior**
No this error.

**Screenshots**
![Screen Shot 2019-08-01 at 4 45 28 PM](https://user-images.githubusercontent.com/7167513/62334473-a9d89a80-b47c-11e9-8248-564e90bf1eea.png)

**Your Environment**
 - OS:  MAC
 - JetBrains' Product: IntelliJ Ultimate, PyCharm Professional
 - JetBrains' Product Version: 2019.2
 - Toolkit Version: 1.5
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by zhangzhx** [comment]
It's due to a 2019.2 bug. An [Youtrack issue](https://youtrack.jetbrains.com/issue/IDEA-220403) was reported to JetBrains. Another similar issue on [DotNet project Debug](https://youtrack.jetbrains.com/issue/IDEA-218343) configuration was also reported in Youtrack.

**Comment by zhangzhx** [comment]
This bug will be fixed in 2019.2.1, (currently the fix is in the [eap](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2019.2+EAP) version).

**Comment by abrooksv** [comment]
JetBrains has released the fix
