### ISSUE TITLE
Gutter Icons Missing

### ISSUE THREAD

**Issue by Mike-Nahmias** [aws/aws-toolkit-jetbrains#1154]
**Describe the bug**
I'm not seeing any gutter icons in PyCharm even though they are set to show. Even after creating a debug configuration and running it, there is no gutter icon for Lambda.

**Your Environment**
 - OS: Windows 10 1903
 - JetBrains' Product: PyCharm Professional
 - JetBrains' Product Version: 2019.2
 - Toolkit Version: 1.5
 - SAM CLI Version: 0.19.0
 - JVM/Python Version: 3.7

**Comment by abrooksv** [comment]
Is the handler referenced by a cloud formation template?

**Comment by abrooksv** [comment]
There is a setting on the AWS preference page to show all possible Lambdas gutter icons, even if not referenced in a CFN template.

I was not able to reproduce this myself with the default sam init output.

**Comment by Mike-Nahmias** [comment]
That was it, thanks @abrooksv , not sure why that would be disabled by default.
