### ISSUE TITLE
Add ability to import env variables from file

### ISSUE THREAD

**Issue by Mike-Nahmias** [aws/aws-toolkit-jetbrains#1155]
**Describe the solution you'd like**
When creating a debug configuration in PyCharm for a Lambda function there is only an option to manually add environment variables. It would be nice if I could select an environment  variable file.

**Describe alternatives you've considered**
Instead of debugging I can run `sam local invoke` and specify the JSON file containing environment variables with the `--env-vars` flag.

**Comment by kiiadi** [comment]
What if we exposed the ability to pass arbitrary arguments to the `sam local invoke` command? Couple of benefits to this approach:
* it simplifies the UX
* it's extensible when new flags get added to the SAM CLI

**Comment by OscarVanL** [comment]
I like kiiadi's suggestion, it would allow me to add the --debug flag, like in my feature request https://github.com/aws/aws-toolkit-jetbrains/issues/1170

**Comment by kiiadi** [comment]
We accept pull requests :) should just be a case of adding the field to the [`SamSettingsEditorPanel.form`](https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/execution/local/SamSettingsEditorPanel.form) and feeding it through the persistence layer to the [`SamRunningState`](https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/execution/local/SamRunningState.kt).

**Comment by OscarVanL** [comment]
I've made some changes in a fork, although I can't work out how to compile it to test it. Do you have a readme that explains how to compile the project?

**Comment by OscarVanL** [comment]
I was just thinking, might it make more sense to have two boxes, one for additional Args for SAM build, and another for additional Args for SAM local?

The suggestion I opened was to allow the --debug arg during `SAM build`, whereas Mike-Nahmias wanted to add --env-var to `SAM local`. One textbox couldn't achieve these two cases, only one or the other.

In my pull request, I'm going to do both.

**Comment by kiiadi** [comment]
Ok that seems reasonable - so `Additional Build Args` and `Additional Invoke Args` boxes? Can we make them `com.intellij.ui.components.fields.ExpandableTextField` instead of just regular JTextFields - that'll make the UX more similar to the `Program Arguments` field in the Java Run Configuration.

**Comment by OscarVanL** [comment]
I called them `Additional Build Args` and `Additional Local Args` - might calling them Invoke args confuse people into thinking they might work on AWS itself, whereas they just run locally?

I'll look into using that UI element instead :)

**Comment by kiiadi** [comment]
I feel like the fact you're inside the Local Lambda Run Configuration is enough context - but it's fair feedback. What about dropping the "Additional" and just having `Build Args` and `Local Invoke Args` the tooltip's for the fields could explain more detail about the fact that these are added on as additional arguments to the relevant SAM CLI commands.

**Comment by OscarVanL** [comment]
OK - buttons renamed, changed to an ExpandableTextField, compiled and tested in PyCharm (You'll have to test it in IntelliJ, I don't have a Lambda environment setup in IntelliJ at the moment). The arguments work for both building and local invocations. 

I can reference local JSON files to add extra `--env-vars` as Mike-Nahmias wanted, and these are verified to set properly by printing os.environ and checking.

![image](https://user-images.githubusercontent.com/7999692/63363193-13a4df80-c36b-11e9-804c-2b230d21ed59.png)
![image](https://user-images.githubusercontent.com/7999692/63363239-26b7af80-c36b-11e9-9614-9e8317d52419.png)
![image](https://user-images.githubusercontent.com/7999692/63363277-3e8f3380-c36b-11e9-934b-44470b7eb55d.png)

Some screenshots above.
I'll make a PR now.

**Comment by kiiadi** [comment]
Awesome - one final nit-pick - can we left-align the labels?

**Comment by OscarVanL** [comment]
Of course :)

**Comment by OscarVanL** [comment]
Should this be closed now? @kiiadi

**Comment by abrooksv** [comment]
Ya, it can be. Thank you again!

Also it landed in last nights EAP build if you would like to use it: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/67554

**Comment by asyba** [comment]
@abrooksv how this work? I try this but I'm not getting this variables in my code:

Plugin settings:
Local InvokeArgs: --env-vars /home/xxxxx/lambda_parameters.json

File:
```
{
"test" : {
		"dynamodb_table_collections": "xxxx",
... } }
```
Code in Java:
System.getenv()

Can't find "dynamodb_table_collections"

**Comment by abrooksv** [comment]
@asyba Are you using a cloudfromation template in the run config or specifying the handler directly?

**Comment by asyba** [comment]
> @asyba Are you using a cloudfromation template in the run config or specifying the handler directly?

specifying the handler directly.

**Comment by abrooksv** [comment]
The logical ID in that situation is hard coded to be "Function" so 
```
{
"Function" : {
		"dynamodb_table_collections": "xxxx",
... } }
```

should work

**Comment by asyba** [comment]
@abrooksv I try that but same, the variables are not in System.getenv()

**Comment by asyba** [comment]
@abrooksv I found the issue, the definition off --env-vars "The shell and file vars you can define when running the cli only override the ones already declared in your template file".

I have zero variables declared with "specifying the handler directly", If I add one with "xxx"= "xxx" , then it gets replaces with the values from --env-vars.

I wanted to have a way to add environment variables, without setting one by one in the UI for the scenario "specifying the handler directly".

It seems that is not good for the thing I want to make.

**Comment by abrooksv** [comment]
True, we are generating a template on the fly for you when you don't use one.

What is the motivation for wanting the file? Is it just too many clicks in the UI?

**Comment by asyba** [comment]
@abrooksv For example I have a java project with 20 lambdas, in total I can have like 20 environment variables (some lambdas use the 20 others 10).
I'm constantly adding new lambdas and for each case I have to add each variable one by one with the button "+", I copy the key (txt file) and paste, then copy the value and paste and so on.

I don't setup the plugin with the Template because sometimes the Template is in a different way that the plugin can interpreted (codeURI location for example), so I specifying the handler directly.
Plus sometimes the client don't want SAM, and I have to use Serverless/Terraform, so with setup handler directly is more easy.

FYI: I use the plugin for Local/Debug Testing.

**Comment by abrooksv** [comment]
We could add support for pasting

```
Foo=Bar
Fooz=Baz
```

and have it create the table entries for you. This matches the behavior JetBrains added to their environment variable modal in recent versions.

**Comment by asyba** [comment]
@abrooksv that will be cool, to have a better way for this case.
FYI: I added a similar feature-request long time ago: https://github.com/aws/aws-toolkit-jetbrains/issues/790
