### ISSUE TITLE
Problem with making new AWS project inside IntelliJ Ultimate 

### ISSUE THREAD

**Issue by millevlada** [aws/aws-toolkit-jetbrains#1163]
**Problem Description**
Hi, 
I have installed AWS Toolkit v1.5 plugin to IntelliJ 2019, also have installed AWSCli using bundled distribution for Windows 10. AWSCli executable is in Path.

```
>where aws
C:\Program Files\Amazon\AWSCLI\bin\aws.exe
```

```
>SET PATH
shows C:\Program Files\Amazon\AWSCLI\bin\; as part of PATH
```

But, once I want to start new AWS Project within intelliJ, it aborts with following error (see screenshot attached).

**To reproduce**

1. Installed AWS Plugin, restarted IntelliJ
2. Installed AWSCli using official AWSCLI64PY3.msi distribution
3. Checked that AWSCli /bin is in PATH
4. In IntelliJ, when I try to start new AWS project, on [Finish] button I get the error (for both Maven and Gradle HelloWorld SAM template) 

**Screenshots**
[Error screen screenshot](https://drive.google.com/file/d/1cF5bj0dnCDOMsBF87F-2c40KUqaQCz1E/view?usp=sharing)

**Your Environment**
 - OS: Windows10
 - JetBrains' Product: IntelliJ IDEA 
 - JetBrains' Product Version: 2019.1.2 (Ultimate Edition)
 - Toolkit Version: 1.5
 - SAM CLI Version: aws-cli/1.16.217
 - JVM/Python Version:  Python/3.6.0

**Comment by abrooksv** [comment]
You are setting the CLI to the AWS CLI. It needs to be the SAM CLI: https://aws.amazon.com/serverless/sam/

**Comment by millevlada** [comment]
Ok, obviously I got confused by that, tnx ;) 
Interesting that form actually accepts the path of wrong software and error given by dialog seems a bit misleading.
Thanks for help.
