### ISSUE TITLE
debug console not interactive

### ISSUE THREAD

**Issue by pswenson** [aws/aws-toolkit-jetbrains#1165]
**Describe the bug**
debug console does not allow interaction at breakpoint

**To reproduce**
1. set a breakpoint in  a SAM project
2. launch debug config
3. when breakpoint is click `>console`

**Expected behavior**
the console should display an interactive prompt with the context of the breakpoint (all variables should be available)

see how interactive console should work here: https://www.jetbrains.com/help/pycharm/using-debug-console.html#actions

**Screenshots**
![image](https://user-images.githubusercontent.com/430370/63053908-18b3eb80-bea0-11e9-8c61-eb83428c1265.png)

**Your Environment**
 - OS: macos
 - JetBrains' Product: pycharm
 - JetBrains' Product Version: 2019.2
 - Toolkit Version:1.16.210
 - SAM CLI Version: 0.19.0
 - JVM/Python Version: 3.7

**Comment by abrooksv** [comment]
You need to click on the Debugger tab next to the Console tab.

**Comment by abrooksv** [comment]
Oh, I see what you are talking about. They changed the icon.
![Screen Shot 2019-08-14 at 1 53 30 PM](https://user-images.githubusercontent.com/8992246/63055556-008d9d80-be9b-11e9-88b5-cc9b49e906a1.png)

We do not support that today. You can emulate it today using the Evaluate Expression feature in the debugger tab though.
![Screen Shot 2019-08-14 at 1 55 36 PM](https://user-images.githubusercontent.com/8992246/63055704-5cf0bd00-be9b-11e9-9f69-a100555ecd46.png)

**Comment by pswenson** [comment]
Yep, expression editor is useful - but not as useful as the full console.  Curious, is there a technical hurdle to supporting this or just hasn't been done?

**Comment by abrooksv** [comment]
I looked through the code, it isn't trivial to implement from my first glance. The entire debug console for python differs from the current console window and their is not a straight forward way to create it.
