### ISSUE TITLE
Add checkbox to run the SAM command with --debug parameter

### ISSUE THREAD

**Issue by OscarVanL** [aws/aws-toolkit-jetbrains#1170]
**Is your feature request related to a problem? Please describe.**

It would be nice if there was a checkbox to run the SAM build command along with the --debug parameter. I've been chasing a bug and I could only find it by opening a separate command line window and adding this myself. It would be nice if there was some way to enable SAM debugging from within the application.

**Describe the solution you'd like**

A toggle could be in the 'Build Output' pane when right-clicking, along with the existing 'Show Warnings' and 'Show Successful Steps' options you could add a 'Show Debug' toggle.
![image](https://user-images.githubusercontent.com/7999692/63257897-ab72d280-c272-11e9-917c-7c56e39972c4.png)

**Describe alternatives you've considered**

A checkbox, perhaps on the Run/Debug Configurations pane. 

**Additional context**

**Comment by abrooksv** [comment]
We talked about allowing arbitrary stuff to be passed in https://github.com/aws/aws-toolkit-jetbrains/issues/1155, feel free to weigh in.

**Comment by kiiadi** [comment]
Can I close this in favour of #1155?

**Comment by OscarVanL** [comment]
Sure :)
