### ISSUE TITLE
Opening plugin in debug mode

### ISSUE THREAD

**Issue by OscarVanL** [aws/aws-toolkit-jetbrains#1177]
I'd like to run the plugin directly from IntelliJ [as described here](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/running_and_debugging_a_plugin.html), but can't work out how to do it. What folder should I add as a classpath? Is this setup possible?

What kind of development setup do you use? At the moment I'm making a change, compiling, opening PyCharm, installing the plugin, restarting, this is time-consuming and annoying. I'm sure there's a better way, but I can't figure it out.

**Comment by abrooksv** [comment]
See https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#testing-locally

You can also use a Gradle run config to do it and then debug it from your main IDE.

**Comment by OscarVanL** [comment]
Thanks!
