### ISSUE TITLE
PyCharm doesn't respect the locationField in creating a new sam project

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#1179]
**Describe the bug**
The PyCharmSDKSelection panel lost binding of the project Location field with the environment Location field after changing the Runtime.

**To reproduce**

1. Open the Create new serverless application page in PyCharm
2. Select new environment using VirtualEnv
3. Change the Runtime to a different python version
4. Update the location in the location field, the Location in Python SDK panel doesn't change.

**Expected behavior**
The Location in Python SDK panel should be changed along with the project Location field.

**Comment by OscarVanL** [comment]
Close this issue now?
