### ISSUE TITLE
Deploy Serverless Application can not find source root

### ISSUE THREAD

**Issue by JUNGQUI** [aws/aws-toolkit-jetbrains#1186]
**Describe the bug**
Deploy Serverless Application can not find source root. It must be mount source root, but it mount just D:\ where source's real root directory.
And than cannot find requirements.txt file.

**To reproduce**
1. In pycharm create AWS SAM Hello
2. coding
3. Deploy Serverless Application project
4. Build function inside a container check
5. see error

**Expected behavior**
Mounting Source root and find requirements.txt

**Screenshots**
![image](https://user-images.githubusercontent.com/39726558/63760515-6e55b280-c8fa-11e9-9090-f0a698c186a3.png)

**Your Environment**
 - OS: windows 10
 - JetBrains' Product: Pycharm
 - JetBrains' Product Version: 2019.2.1
 - Toolkit Version: 1.5
 - SAM CLI Version: 1.16.70
 - JVM/Python Version: 1.8.0_201/3.7.0

**Additional context**
HELP!

**Comment by abrooksv** [comment]
Closing due to SAM issue has been released.
