### ISSUE TITLE
Multiple requirements.txt files for different Lambda functions

### ISSUE THREAD

**Issue by OscarVanL** [aws/aws-toolkit-jetbrains#1197]
**Is your feature request related to a problem? Please describe.**

I have multiple Lambda functions in the same CloudFormation stack. One of these has quite a few requirements in `requirements.txt` (the size of the function is >60MB with the requirements), whereas the other has no external requirements so is only bytes/kilobytes. 

The issue is that when I `Deploy Serverless Application`, it uploads 60MB of stuff _twice_ (once for each Lambda function despite the second function not using these requirements). This slows down the whole deployment, as my upload speeds mean this can take a couple of minutes to upload, having to upload this a whole extra time unnecessarily is frustrating.

**Describe the solution you'd like**

The ability to define separate requirements.txt files for different functions in some way.

**Describe alternatives you've considered**

A given requirements.txt file could apply to all functions inside the folder it's contained in, so a hierarchy like this would mean that lambda-A is using one `requirements.txt` file, whereas lambda-B.py and lambda-C.py use the other `requirements.txt`.

```
/project/
    /function-group-1/
         lambda-A.py
         requirements.txt
    /function-group-2/
         lambda-B.py
         lambda-C.py
         requirements.txt
```

**Comment by abrooksv** [comment]
This should actually work today if each of the codeUri points to `/function-group-2` and `/function-group-1`

We may be doing it inefficiently (by not de-dupoing the lambdas first), though.

**Comment by OscarVanL** [comment]
Thanks, that change worked :) Much smaller uploads now.

**Comment by abrooksv** [comment]
Glad it worked for you. Please re-open if there is anything else related to this.
