### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {shap==0.30.1(wheel)}

### ISSUE THREAD

**Issue by AbhinavMudgal** [aws/aws-toolkit-jetbrains#1225]
In requirements.txt included-
shap
and got this error.;
Please help me out.

**Comment by Rubyj** [comment]
I am having the same issue with the package `scikit-allel` is it because there is no whl?

**Comment by abrooksv** [comment]
This would have to be fixed at the Lambda builders layer (https://github.com/awslabs/aws-lambda-builders/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by rli** [comment]
Closing due to issue inactivity. Please open a new issue if you are still experiencing issues.
