### ISSUE TITLE
Cannot "Update Function Code" with pip 19.3

### ISSUE THREAD

**Issue by gamename** [aws/aws-toolkit-jetbrains#1283]
**Describe the bug**

There is a known-to-be-good lambda function already installed on AWS.  When I try to update the function code, I get the following error:
```
/usr/local/bin/sam build --template /Users/tennis.smith/PycharmProjects/marsh_and_mclennan/.aws-sam/build/template.yaml --build-dir /Users/tennis.smith/PycharmProjects/marsh_and_mclennan/.aws-sam/build Function
Building resource 'Function'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```
Even if I comment out the entire file except the function handler, I get the same error.  

**To reproduce**
Right-click on the function name in the  "Lambda" area on the "AWS Explorer"
Choose "Update Function Code"

**Expected behavior**
It should have updated my lambda function 

**Screenshots**

**Your Environment**
 - OS:  Mac OS Catalina (10.15)
 - JetBrains' Product: PyCharm 
 - JetBrains' Product Version: 
PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Licensed to Tennis Smith
You have a perpetual fallback license for this version
Subscription is active until October 18, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Jenkins Control Plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.github.holgerbrandl.pasteimages/, com.godwin.json.parser, com.leinardi.pycharm.pylint, com.potterhsu.jsonviewer, com.atlassian.bitbucket.references, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.asciidoctor.intellij.asciidoc, com.perl5, org.intellij.plugins.hcl, com.jetbrains.intellij.datalore, BashSupport, com.intellij.plugin.adernov.powershell, AWSCloudFormation, aws.toolkit, com.intellij.kubernetes, org.logtalk, zielu.gittoolbox
 - Toolkit Version: 1.7 
 - SAM CLI Version: 0.22.0
 - JVM/Python Version: 3.7.5

**Additional context**

**Comment by hunterwerlla** [comment]
Did you happen to install pip 19.3? See this SAM issue: https://github.com/awslabs/aws-sam-cli/issues/1461

**Comment by gamename** [comment]
@hunterwerlla 

Yes.  That's it.  I have pip 19.3 installed.  I'll try lowering the pip version

**Comment by gamename** [comment]
@hunterwerlla 
That didn't work :(
I downgraded my pip to 19.2.3 and get the same error

![image](https://user-images.githubusercontent.com/42153/67106440-3fd4b500-f190-11e9-8fbf-6899cc0a2881.png)

**Comment by gamename** [comment]
@hunterwerlla 

I'm getting the same error when I try to create a function as well.   

I created a "foo" project with the following contents:

python code file "foo.py":
```
import boto3

def handler(event, context):
    print("Event:" + str(event))
    instance_id = event["ResourceProperties"]["Parameters"]["InstanceId"]
    ec2 = boto3.resource('ec2')
    instance = ec2.Instance(instance_id)
```

template file "template.yaml"
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: foo
      Handler: foo.handler
      CodeUri: ./
      Runtime: python3.7
      Timeout: 900
```

requirements file "requirements.txt":
```
boto3
```

The pip version is 19.0.3

The build output when trying to create the function is:
```
/usr/local/bin/sam build --template /Users/tennis.smith/PycharmProjects/test_lambda_toolkit_failure/.aws-sam/build/template.yaml --build-dir /Users/tennis.smith/PycharmProjects/test_lambda_toolkit_failure/.aws-sam/build Function
Building resource 'Function'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```

**Comment by abrooksv** [comment]
Sam uses the python on your PATH so check that. You could also try building in the container.

**Comment by gamename** [comment]
@abrooksv 

Good idea. Will try that.

**Comment by gamename** [comment]
@abrooksv 
I can rule out the path because I'm running in a venv.

As for the building in a container, I don't see that option on the upload dialog.  Where is it?

**Comment by hunterwerlla** [comment]
@gamename it's on the "SAM cli" page
<img width="737" alt="Screen Shot 2019-10-18 at 10 42 15 AM" src="https://user-images.githubusercontent.com/11964782/67108413-490b5500-f183-11e9-9c81-a50a8bc6b4b7.png">

**Comment by gamename** [comment]
@hunterwerlla @abrooksv 
Ok.  I found the option in "SAM CLI".  I enabled that option, then tried to upload the function again.  Same error.  

What does building it in a container prove?

**Comment by abrooksv** [comment]
Re-read the code, we didn't wire the create/update dialog to the build in container option. :/

Also SAM ignores virtualenvs since it needs to use the exact python version so that it can compile wheels that are compatible with Lambda. So it will take whatever Python is on your path that matches the runtime of the Lambda and use its pip.

**Comment by gamename** [comment]
@abrooksv 
I found the problem.  There *was* a 19.3 pip version in my environment.  Doing a `which -a` showed it.  

I downgraded the pip to 19.2 and everything works.  Thanks guys. :)
