### ISSUE TITLE
SAM Build fails until requirements.txt is manually copied to .aws-sam/build directory

### ISSUE THREAD

**Issue by gamename** [aws/aws-toolkit-jetbrains#1292]
**Describe the bug**
When updating an existing lambda function, the SAM build always fails with the following error:
```
/usr/local/bin/sam build --template /Users/tennis.smith/PycharmProjects/marsh_and_mclennan/.aws-sam/build/template.yaml --build-dir /Users/tennis.smith/PycharmProjects/marsh_and_mclennan/.aws-sam/build Function
Building resource 'Function'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /Users/tennis.smith/PycharmProjects/marsh_and_mclennan/.aws-sam/build/Function/requirements.txt
```
If I then copy the `requirements.txt` file to the `.aws-sam/build` subdirectory and retry the update, the SAM build will work (well, most of the time).

It is as if the tool doesn't "see" the `requirements.txt` file and include it in the build. 

Here is how I do the copy:
```
$ cp ./requirements.txt ./.aws-sam/build
```

**To reproduce**
1. Right-click on an existing lambda function in the `AWS Explorer` window in the `Lambda` section.
2. Choose `Update Function Code`
3. Select the s3 bucket from the dialog box 
4. Press the `Update` button
5. The build attempt will fail with the error listed above

**Expected behavior**
The build will not fail and the lambda function code will be updated.

**Screenshots**

**Your Environment**
 - OS: Mac OS Catalina (10.15)
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version:
PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Licensed to Tennis Smith
You have a perpetual fallback license for this version
Subscription is active until October 18, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Jenkins Control Plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.github.holgerbrandl.pasteimages/, com.godwin.json.parser, com.leinardi.pycharm.pylint, com.potterhsu.jsonviewer, com.atlassian.bitbucket.references, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.asciidoctor.intellij.asciidoc, com.perl5, org.intellij.plugins.hcl, com.jetbrains.intellij.datalore, BashSupport, com.intellij.plugin.adernov.powershell, AWSCloudFormation, aws.toolkit, com.intellij.kubernetes, org.logtalk, zielu.gittoolbox
 - Toolkit Version: 1.7 
 - SAM CLI Version:
$ sam --version 
SAM CLI, version 0.22.0

 - JVM/Python Version: Python 3.7.5

**Additional context**
As I mentioned above, copying the `requirements.txt` file does not always work the first time.  It normally takes once, but sometimes it takes 2 attempts

**Comment by matthewsommer** [comment]
I have this problem as well after updating the Toolkit and SAM CLI. Copying to the aws-sam/build directory does not fix it for me though. I've tried creating a new project with from the hello world template and problem still exists.

**Comment by abrooksv** [comment]
I was not able to reproduce this using sam 0.23 and the python3.7 hello-world tempalte:

```
/usr/local/bin/sam build --template /Users/<>/samPython/template.yaml --build-dir /Users/<>/samPython/.aws-sam/build
Building resource 'HelloWorldFunction'
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>
```

**Comment by matthewsommer** [comment]
I"m using SAM 0.23 and Python3.7, Toolkit 1.7, and Docker 2.1.0.4 and still getting the error. I've marked the directory as source. What version of  AWS Toolkit are you using?

**Comment by abrooksv** [comment]
1.8 snapshot. Can you post your logs to compare? We don't do the build so what matters is the arguments we went to Sam cli and its version.

**Comment by matthewsommer** [comment]
```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build --template C:\Users\%USERNAME%\source\repos\jira-sync-to-plm-db\template.yaml --build-dir C:\Users\%USERNAME%\source\repos\jira-sync-to-plm-db\.aws-sam\build --use-container HelloWorldFunction
Starting Build inside a container
Building resource 'HelloWorldFunction'

Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting C:\Users\%USERNAME%\source\repos\jira-sync-to-plm-db\hello_world as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt
```

**Comment by abrooksv** [comment]
Hmmmm. I did not try with --use-container, will try to replicate with that set

**Comment by matthewsommer** [comment]
I get the error below unless I run in a container. Also I'm on Windows.

```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build --template C:\Users\%USERNAME%\source\repos\jira-sync-to-plm-db\template.yaml --build-dir C:\Users\%USERNAME%\source\repos\jira-sync-to-plm-db\.aws-sam\build HelloWorldFunction
Building resource 'HelloWorldFunction'

Build Failed
Error: PythonPipBuilder:None - Binary validation failed!

```

**Comment by matthewsommer** [comment]
The issue for me was in Docker. I had to unshare and reshare the mounted drive within the Docker settings. Now it's building.

**Comment by gamename** [comment]
@abrooksv @matthewsommer  Anything more you need from me?

**Comment by abrooksv** [comment]
Did you mean to select the template in the sam build folder and not the one in your project root?

**Comment by gamename** [comment]
@abrooksv No. I'm not even sure how I would do that.

**Comment by abrooksv** [comment]
Oh right, was getting Deploy feature confused with Update Code feature.

For update code, we generate a template under the hood for you to make SAM build work. It requires a base directory (where requirements.txt is) to be provided. We locate it using this class: https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/python/PythonLambdaBuilder.kt

This means it currently suffers the limitation that if the requirements.txt file and handler must be in the same directory structure. Is your handler file in a subdirectory as your requirements.txt?

**Comment by gamename** [comment]
@abrooksv Stupid question: How do I identify the "handler"? Not sure what you mean.

**Comment by abrooksv** [comment]
Yes, I do

**Comment by gamename** [comment]
@abrooksv The handler and the requirements.txt are in the same directory.  
```
$ tree -L 1 
.
├── README.md
├── pylintrc
├── requirements.txt
├── resize.template
├── resize_instance.py
├── scLaunchPolicy.json
├── template.yaml
├── test_data.json
└── venv
```

**Comment by gamename** [comment]
@abrooksv @matthewsommer  Any other diagnostics you need?

**Comment by abrooksv** [comment]
It may be picking the wrong handler, we are working on a fix that may affect this.

**Comment by gamename** [comment]
I think we can close this now.  Ever since the latest PyCharm update, the problem has gone away. 

Here is the new PyCharm information:
```
PyCharm 2019.2.4 (Professional Edition)
Build #PY-192.7142.42, built on October 31, 2019
Licensed to Tennis Smith
You have a perpetual fallback license for this version
Subscription is active until October 18, 2020
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Jenkins Control Plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.github.holgerbrandl.pasteimages/, com.godwin.json.parser, com.leinardi.pycharm.pylint, com.potterhsu.jsonviewer, com.atlassian.bitbucket.references, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.asciidoctor.intellij.asciidoc, com.perl5, org.intellij.plugins.hcl, com.jetbrains.intellij.datalore, BashSupport, com.intellij.plugin.adernov.powershell, AWSCloudFormation, aws.toolkit, com.intellij.kubernetes, org.logtalk, zielu.gittoolbox
```
