### ISSUE TITLE
Using @ or % in credentials seems to fail

### ISSUE THREAD

**Issue by maartenba** [aws/aws-toolkit-jetbrains#1293]
At a conference, had a user report that using @ or % in credentials seem to fail. Unfortunately, that's all info I have.

**Comment by abrooksv** [comment]
Thank you for forwarding on this feedback. We appreciate it.

This is controlled by a regex in the Java SDK that needs to be relaxed. SDK issue: https://github.com/aws/aws-sdk-java-v2/issues/389

**Comment by abrooksv** [comment]
Fixed in master branch
