### ISSUE TITLE
Show the error message of "Credential should be scoped to a valid region, not 'ap-east-1'." when I launched IDEA

### ISSUE THREAD

**Issue by liuweigeek** [aws/aws-toolkit-jetbrains#1298]
**Describe the bug**
Show the error message of "Credential should be scoped to a valid region, not 'ap-east-1'." when I launched IDEA

**To reproduce**
When I launched my IDEA

**Screenshots**

<img width="458" alt="WechatIMG3" src="https://user-images.githubusercontent.com/7973228/67261804-c52fd080-f4d4-11e9-9d20-0918fcf9a12b.png">

**Your Environment**
 - OS: macOS 10.15
 - JetBrains' Product: IDEA
 - JetBrains' Product Version: 2019.2.3
 - Toolkit Version: 1.7
 - SAM CLI Version: 0.22.0
 - JVM/Python Version: 1.8.0_221-b11

**Comment by abrooksv** [comment]
ap-east-1 requires opt-in, are your default credentials enabled for that region?

**Comment by liuweigeek** [comment]
> ap-east-1 requires opt-in, are your default credentials enabled for that region?

Thanks for your reply, The region of default credentials is us-west-2, And when I deleted that profile of ap-east-1, It still shows that error message contains 'ap-east-1'.

**Comment by abrooksv** [comment]
The active region in the IDE is decoupled form the region in the credentials file. Switch it out to us-west-2 in the status bar (or gear menu in the AWS explorer tool window) should resolve the error message.

**Comment by liuweigeek** [comment]
> The active region in the IDE is decoupled form the region in the credentials file. Switching it out to us-west-2 in the status bar (or gear menu in the AWS explorer tool window) should resolve the error message.

Now it looks work well, thx.
