### ISSUE TITLE
Saved Edit Configurations size limit

### ISSUE THREAD

**Issue by asyba** [aws/aws-toolkit-jetbrains#1311]
**Describe the bug**

Creating a Lambda configuration from a java class code, after click the button "Apply" or "Done" the configuration is saved. But it only saving the last 5-6 configurations for different classes, I keep adding but the amount of saved is always the same and the old ones are beaning replaced.

**To reproduce**

In java class click the plugin icon, then "Create New AWS Lambda"
![image](https://user-images.githubusercontent.com/1466530/67596517-3c689d00-f73f-11e9-948a-26d0b3e07186.png)

![image](https://user-images.githubusercontent.com/1466530/67597538-d7627680-f741-11e9-8374-33cf518a0a66.png)

**Expected behavior**
Save any number of configurations.

**Your Environment**
 - OS: Ubuntu 18.04.3 LTS
 - JetBrains' Product: Intellij IDEA Ultimate
 - JetBrains' Product Version: 2019.2.3
 - Toolkit Version: 1.8.EAP.2019.10.25
 - SAM CLI Version:
 - JVM/Python Version:

**Comment by abrooksv** [comment]
This is IntelliJ behavior, but I can describe it.

These are considered temporary (you can tell since icon is a bit darker on all but the first one). There is a limit of 5 of those before the least recently used is replaced.

If you open up the run config menu and hit save, you should be able to have more.
![Screen Shot 2019-10-25 at 12 22 25 PM](https://user-images.githubusercontent.com/8992246/67598340-26001880-f722-11e9-8732-4d19b5e9c087.png)

**Comment by asyba** [comment]
@abrooksv oh I see, that can't be done in the AWS Lambda creation? like adding a new button like this: "Run", "Cancel", "Apply", "Save" ? or IntelliJ don't allow plugins to replicate the "Save" action?

**Comment by abrooksv** [comment]
We can't add additional buttons to the bottom right of the run config window, we only have control of the top half of that right panel (Above the Before Tasks section)

**Comment by asyba** [comment]
Ok, thanks. I will keep an eye in the "Save" icon to not forget doing that.

**Comment by abrooksv** [comment]
If you select Templates in the tree, you can increase the limit past 5:
![Screen Shot 2019-10-25 at 12 46 41 PM](https://user-images.githubusercontent.com/8992246/67599753-8d6b9780-f725-11e9-9158-7f02b5175b76.png)

**Comment by asyba** [comment]
> If you select Templates in the tree, you can increase the limit past 5:
> ![Screen Shot 2019-10-25 at 12 46 41 PM](https://user-images.githubusercontent.com/8992246/67599753-8d6b9780-f725-11e9-9158-7f02b5175b76.png)

Thanks! I didn't know this.
How I can know what's included in every new update for the EAP version plugin ? only through ZenHub ?

**Comment by abrooksv** [comment]
We publish change longs on each update. You can read them in the plugin marketplace per version or read it in the plugin details panel in the IDE plugin settings page 

We stopped using zenhub.

**Comment by asyba** [comment]
> We publish change logs on each update. You can read them in the plugin marketplace per version or read it in the plugin details panel in the IDE plugin settings page
> 
> We stopped using zenhub.

cool, and for the Road Map?
