### ISSUE TITLE
build fails with Task :jetbrains-rider:restoreReSharperPluginPackages FAILED

### ISSUE THREAD

**Issue by baronmog** [aws/aws-toolkit-jetbrains#1314]
**Describe the bug**
As of commit 48325aa094532a3429afac1758caf0a7305fb03f (Enable Rider tests with 193 SDK (#1255)), buildPlugin fails:

> Task :jetbrains-rider:prepareNuGetConfig
Caching disabled for task ':jetbrains-rider:prepareNuGetConfig' because:
  Build cache is disabled
Task ':jetbrains-rider:prepareNuGetConfig' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
SDK path: /Users/homedir/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2019.2/383f838ab2231a87f5cf55434ef2c370a1996
bb4/riderRD-2019.2
NuGet packages: /Users/homedir/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2019.2/383f838ab2231a87f5cf55434ef2c37
0a1996bb4/riderRD-2019.2/lib/ReSharperHostSdk
Writing /Users/homedir/src/aws-toolkit-jetbrains/jetbrains-rider/NuGet.Config
:jetbrains-rider:prepareNuGetConfig (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.002 secs.
:jetbrains-rider:restoreReSharperPluginPackages (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :jetbrains-rider:restoreReSharperPluginPackages FAILED

**To reproduce**
1. `git checkout master`
1. `./gradlew buildPlugin`

**Expected behavior**
Build the plugin

**Your Environment**
 - OS: MacOS Mohave (10.14.6 (18G95))
 - JetBrains' Product: aws-toolkit-jetbrains
 - Toolkit Version:
 - SAM CLI Version: 0.22.0
 - JVM/Python Version: JDK 12.0.2

**Comment by abrooksv** [comment]
That log doesn't show why restoreReSharperPluginPackages failed.

Do you have `msbuild` so that the ReSharper side of Rider can be compiled?

**Comment by abrooksv** [comment]
We have added a way to skip Rider when building due to the higher bar of system requirements. See https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md#building-from-source

**Comment by baronmog** [comment]
I do see a failure w/ Mono installed and msbuild in my path. However, I don't need Rider support in my local build, so using the `-PskipRider` param works for me.

**Comment by abrooksv** [comment]
Okay, closing since the build property works for you.
