### ISSUE TITLE
PyCharm 2019.2.3 is not compatible with newest version of SAM CLI 0.23.0

### ISSUE THREAD

**Issue by ZeteticElench** [aws/aws-toolkit-jetbrains#1325]
When attempting to create a new AWS Serverless project in PyCharm 2019.2.3 I get the error "Bad SAM executable version. Expected 0.14.1 <= version < 0.23.0 but was 0.23.0". 

0.23.0 is the version installed by homebrew and it doesn't seem possible to install older versions with homebrew. 

![image](https://user-images.githubusercontent.com/6778486/67828200-8edbed80-faa0-11e9-92e6-0b413ba89699.png)

**Comment by abrooksv** [comment]
Check your plugin version. We increased the max version in 1.7

**Comment by ZeteticElench** [comment]
Thanks, that was the issue. I have a subscription to PyCharm but was using a non-paid version of PyCharm in a Linux VM due to Docker and and VMWare Workstation not getting along on Windows and didn't realize the free version of PyCharm doesn't support plugins.
