### ISSUE TITLE
I have failed to install the AWS Toolkit for my PyCharm Professional on a Mac many times now. Can you please list in the versions of the AWS Toolkit, which version of PyCharm Professional is needed to use the AWS Toolkit.

### ISSUE THREAD

**Issue by Pastthesun** [aws/aws-toolkit-jetbrains#1333]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pastthesun** [comment]
**Is your feature request related to a problem? Please describe.**
I need need need the AWS Toolkit! I have no idea how to do what I need to do without it. :(
I get errors even trying to put the link in the "Manage repositories..." button in the Preferences/Plugins/Browse Repositories dialog...
Plugins - List of plugins was not loaded for the following hosts: https//plugins.jetbrains.com/plugin/11349-aws-toolkit/update/59972
Due to the following errors:
'plugins.jetbrains.com' for 'https//plugins.jetbrains.com/plugin/11349-aws-toolkit/update/59972'
(and it does not seem to matter how I put the URL in there!)

**Describe the solution you'd like**
Give me a plugin install that works for my 2016 PyCharm Professional on a Mac, 
OR
Show the help for how to do it for a Mac for my version

**Describe alternatives you've considered**
Asking my tech support for a newer version, though I don't know what version to ask for for sure...

Additional context

**Comment by kiiadi** [comment]
The current version of the toolkit ([1.7](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/70754)) requires a minimum version of 2018.3.1 of PyCharm. Future versions of the toolkit will require a minimum version of 2019.2.

**Comment by kiiadi** [comment]
Great! The plugin also works in PyCharm Community editions. Looking forward to getting your feedback. I'll close this issue for now.
