### ISSUE TITLE
NodeJS runtimes are not showing

### ISSUE THREAD

**Issue by vtatsakovich** [aws/aws-toolkit-jetbrains#1337]
**Describe the bug**
In Webstorm / Phpstorm when I'm trying to create a new project or to run the Local lambda, there is no NodeJS runtimes in the list.
However, NodeJS interpreter is available on the other tabs like Node.js, Node.js Express App etc.

**To reproduce**
1) File -> New Project -> AWS Serverless Application
2) Runtime: Empty list

**Expected behavior**
1) See a list of available runtimes

**Screenshots**
![image](https://user-images.githubusercontent.com/6977096/68027228-7e9f5a80-fcba-11e9-84c2-2805d8c79116.png)
![image](https://user-images.githubusercontent.com/6977096/68027232-8232e180-fcba-11e9-9069-1272aabd9371.png)
![image](https://user-images.githubusercontent.com/6977096/68027233-83fca500-fcba-11e9-879c-be3adefa092d.png)
![image](https://user-images.githubusercontent.com/6977096/68027241-865eff00-fcba-11e9-93bc-e85d15e86d76.png)

**Your Environment**
 - OS: macOS Cataline 10.15
 - JetBrains' Product: Webstorm
 - JetBrains' Product Version: 2019.2.4
 - Toolkit Version: 1.7
 - SAM CLI Version: 0.30.0
- NodeJS version: 8.10.0

**Additional context**
I've tried to change NodeJS version or to use PHPStorm instead - no luck.

**Comment by abrooksv** [comment]
WebStorm support has not been released yet, it is only available in our 1.8 EAP builds

**Comment by vtatsakovich** [comment]
> WebStorm support has not been released yet, it is only available in our 1.8 EAP builds

I see. Is there any deadlines when it can be released?

**Comment by abrooksv** [comment]
We current do not have a date. My suggestion to you is if you want to try it now you can:

1. Opt-in to our EAP builds: https://github.com/aws/aws-toolkit-jetbrains#eap-builds
2. Do a one time download from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions (switch to EAP channel on the right) and install it from disk through the Plugin preference page's Gear icon. (Select the zip, do not unzip it)

Feel free to provide feedback and report bugs.
