### ISSUE TITLE
Rider/Edit Configuration reports Error: Cannot find handler in project

### ISSUE THREAD

**Issue by koendhondt** [aws/aws-toolkit-jetbrains#1346]
**Describe the bug**
The handler completion does not work as expected when you define a 'public object FunctionHandler' Lambda function handler in Rider's Run/Edit configuration dialog. It provides no suggestions and displays the following message at the bottom of the window:

Error: Cannot find handler 'HelloWorld:HelloWorld.Function::FunctionHandler' in project

When changing the return type to one of the basic types (string, int, double, bool) or an AWS-specific object (APIGatewayProxyResponse, SNSEvent, S3Event, etc...), the handler is recognized.

**To reproduce**
Create a project using the following code snippet (example for processing a synchronous SES receipt rule lambda):

```csharp
using Amazon.Lambda.Core;
using Amazon.Lambda.SimpleEmailEvents;
using Amazon.Lambda.SimpleEmailEvents.Actions;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace HelloWorld
{
    public class Function
    {
        public object FunctionHandler(SimpleEmailEvent<LambdaReceiptAction> input, ILambdaContext context)
        {
            return new {disposition = "continue"};
        }
    }
}
```
- Go to: Run -> Edit Configurations...
- Select +, Lambda, Local
- Select Runtime: dotnetcore2.1
- Press Ctrl + Space: no suggestions appear
- Type the handler name: HelloWorld:HelloWorld.Function::FunctionHandler
- The dialog shows the error message at the bottom of the window

Now replace the code with the following code snippet and follow the same steps to create a Run/Debug configuration:

```csharp
using Amazon.Lambda.Core;
using Amazon.Lambda.SimpleEmailEvents;
using Amazon.Lambda.SimpleEmailEvents.Actions;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace HelloWorld
{
    public class Function
    {
        public string FunctionHandler(SimpleEmailEvent<LambdaReceiptAction> input, ILambdaContext context)
        {
            return "{\"disposition\": \"continue\"}";
        }
    }
}
```

This time, when pressing Ctrl + Space, the correct suggestion appears and the handler is recognized (this does not produce valid JSON output though).

**Expected behavior**
The handler is properly recognized when the FunctionHandler return type is any object that can be serialized by the default serializer (such as object, JObject, ...)

**Workaround**

This issue can be worked around as follows:
- defining the FunctionHandler as a string (or any other of the recognized AWS classes);
- create the Run/Debug configuration, press apply and close the dialog window;
- edit the code and change the FunctionHandler return type to an unsupported class (object, JObject, ...)

The configuration then remains valid until the Run -> Edit Configurations dialog is opened again. It does not persist after restarting Rider.

**Your Environment**

- OS: MacOS Mojave 10.14.6
- JetBrains' Product: Rider
- JetBrains' Product Version: 2019.2.3
- Toolkit Version: aws-jetbrains-toolkit-1.8-SNAPSHOT (master, git log shows 6b0f617496ba73dcfc285e012bcdd39964e7106a as last commit)
- SAM CLI Version: SAM CLI, version 0.22.0
- JVM/Python Version: jvm 1.8.0_202, Python 2.7.10, Python 3.7.4

**Comment by abrooksv** [comment]
The serialization library looks at the type at runtime, so the method is actually returning a Dictionary at runtime. Since we can't check the return type at compile time accurately, we will just remove validating the return type to determine if it is a handler, and only look at parameters.

**Comment by abrooksv** [comment]
This has been fixed

**Comment by koendhondt** [comment]
Thanks!
