### ISSUE TITLE
AWS Toolkit on PyCharm 2019.2.4 cannot create a new AWS Serverless project

### ISSUE THREAD

**Issue by dwhitla** [aws/aws-toolkit-jetbrains#1356]
**Describe the bug**
The new project dialog hangs forever and does not create the project.
The AWS Serverless Application pane in the New Project dialog is incredibly slow and unresponsive even prior to trying to change any fields.

**To reproduce**
1. Open the **File** menu.
2. Click on **New Project**
3. Click on **AWS Serverless Application**
4. Fill the form - this will take a while because it takes forever to respond to any interaction.
5. Click **Create**
6. <crickets/>

**Expected behavior**
A new project is created.

**Screenshots**
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/18676080/68646832-fe091580-0567-11ea-8a19-6d1d5b79e0bc.png">

**Your Environment**
 - OS: MacOS 10.14.6
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2019.2.4 (Professional Edition) Build #PY-192.7142.42
 - Toolkit Version: 1.7
 - SAM CLI Version: 1.38.0
 - JVM/Python Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o / Python 3.7.3
- Runtime version: 11.0.4+10-b304.77 x86_64

**Comment by justinmk3** [comment]
transcribing the error from the screenshot:

    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Commands': was expecting ('true', 'false' or 'null')
      at [Source: (String)" Commands * You can run commands with...

**Comment by dwhitla** [comment]
My apologies - I was too quick to log a bug. My SAM environment was broken after local python installation changes. After resolving this there is no issue. Interestingly the issue manifested very differently in the IntelliJ aws-toolkit plugin.
