### ISSUE TITLE
Support for AWS SSO

### ISSUE THREAD

**Issue by michaeljfazio** [aws/aws-toolkit-jetbrains#1360]
**Is your feature request related to a problem? Please describe.**

AWS CLI V2 recently added support for [Single Sign-On](https://aws.amazon.com/about-aws/whats-new/2019/11/use-the-aws-cli-v2-preview-with-aws-single-sign-on-to-increase-developer-productivity/). The feature is still in preview however it's something many AWS users have been long waiting for -- myself included. There are still some issues with the SSO process, for instance [#4645](https://github.com/aws/aws-cli/issues/4645), however these will soon be overcome and have workarounds.

Unfortunately, even after successful login using AWS CLI V2, it is not possible to use the SSO temporary credentials with the Jetbrains AWS Toolkit. The following error is shown in the IntelliJ UI:

> Profile 'default' is not using role-based, session-based, process-based, or basic credentials.
> Profile 'dev' is not using role-based, session-based, process-based, or basic credentials.
> Profile 'test' is not using role-based, session-based, process-based, or basic credentials.
> Profile 'prod' is not using role-based, session-based, process-based, or basic credentials.

**Describe the solution you'd like**

The toolkit should be enhanced to allow the use of AWS profiles using temporary AWS CLI SSO credentials, which I believe are cached under %USERPROFILE%/.aws/sso

**Describe alternatives you've considered**

Alternatives might also allow the SSO process to be initiated from within the IDE by selecting an existing profile which has not not yet been authenticated using the CLI. A nice feature perhaps but not critical to functionality.

**Additional context**

![Screen Shot 2019-11-13 at 12 09 20 pm](https://user-images.githubusercontent.com/1845178/68732464-74f8e980-060e-11ea-9002-a4a1092880b8.png)

<img width="425" alt="Screen Shot 2019-11-13 at 12 10 25 pm" src="https://user-images.githubusercontent.com/1845178/68732561-d325cc80-060e-11ea-8e5c-098fbd0a95ce.png">

**Comment by abrooksv** [comment]
We are very excited about adding SSO as well. We are currently waiting for the CLI to collect feedback and adjust the design based on that feedback before we integrate with it.

**Comment by charleswhite2020** [comment]
Is there any update on this? AWS CLIv2 was released just over 2 months ago. Currently this is Blocking our transition to SSO for our dev team

**Comment by abrooksv** [comment]
> Is there any update on this? AWS CLIv2 was released just over 2 months ago. Currently this is Blocking our transition to SSO for our dev team

Sorry, there is not. We are still discussing the APIs exposed by the SDKs so that the integration into the IDE is clean and provides the correct experience.

**Comment by abrooksv** [comment]
This has been released in version 1.18. If you encounter any issues please open a bug report

**Comment by jco-08** [comment]
Hello @abrooksv, this has really helped with reading data in using Python so thanks. I also have Athena set up as a database within PyCharm however, to use the query console, and there is no obvious way to work with SSO here. I've still been having to manually change over temporary credentials. Is there a way to save having to do this?

**Comment by abrooksv** [comment]
@jco-08 We do not actively monitor closed issues, please create a new feature request describing your Athena use case

**Comment by rv-bnowak** [comment]
@jco-08 Can you please link newly created issue (regarding @abrooksv comment) in this issue?

**Comment by bencodesall** [comment]
@jco-08 Can you please link newly created issue (regarding @abrooksv comment) in this issue?
