### ISSUE TITLE
Debug with Maven Module

### ISSUE THREAD

**Issue by MarcoAlessandroRiggio** [aws/aws-toolkit-jetbrains#1362]
**Describe the bug**
I can't debug a lambda function that is inside a maven module that refer to a parent pom.

**To reproduce**
1. Create an AWS Serverless Application via intelliJ
2. Inside the Maven generated project, remove src folder and generate a maven module
3. Implement inside the module a RequestHandler
4. Try to debug the Handler created in the previous point

Here an example project: https://fabricalabsrl-my.sharepoint.com/:u:/g/personal/marco_riggio_fabricalab_it/ERnksTiGSMZCgeMOwpgT0QkBuRLArFA4SuVH8NIFgBGNbA?e=mIWLva

The problem persist also if I build inside a container.

**Expected behavior**
I expect that the toolkit can compile correctly the project resolving the parent pom.
Actually, if I compile with ```mvn compile``` everything works.

**Screenshots**

![image](https://user-images.githubusercontent.com/10076343/68846459-69202c80-06cd-11ea-81d3-ba77cb9d0066.png)

**Your Environment**
 - OS: Windows 10 1803
 - JetBrains' Product: IntelliJ Idea 
 - JetBrains' Product Version: 2019.0.2 Ultimate
 - Toolkit Version: 1.7
 - SAM CLI Version: 0.31.0
 - JVM/Python Version: JVM Oracle 1.8.0_231

**Additional context**

**Comment by MarcoAlessandroRiggio** [comment]
*UPDATE:* Inside log we found:
``` /usr/local/bin/sam --debug build --{projectDir}/template.yaml --build-dir {PROJECTdIR}/{moduleName}/.aws-sam/build --use-container```
[...]
```Mounting {prjectDir}/{moduleName} as /tmp/samcli/source:ro,delegated inside runtime container```  

Maybe the problem is the mounted dir, the parent pom is in the project directory.

Regards

**Comment by juanfaustoperalta** [comment]
Hi! I have the same problem. Could you solve it?

**Comment by nick-winter-vector** [comment]
Any update on this have the same issue

**Comment by rli** [comment]
Closing in favor of https://github.com/aws/aws-toolkit-jetbrains/issues/3229
