### ISSUE TITLE
Launch slowed down by large number of AWS Profiles

### ISSUE THREAD

**Issue by luthes** [aws/aws-toolkit-jetbrains#1386]
**Describe the bug**
When launching with a large number of profiles (~170 in my case), the IDE attempts to verify all of them on every launch. There aren't any normal logs for this, all I'm seeing is `WARN - fileToolkitCredentialsProvider - Failed to determine STS region, falling back to US_EAST_1`. While this verification is happening, the IDE shows a dialogue as seen below in the screenshots .The cancel button, from what I can tell, will wait until the profiles are loaded before actually cancelling. I can't see a reason why it would need to do this, but I would think that it should attempt this verification when a profile is selected from within the IDE, rather than try to load them all on every start-up.

**To reproduce**
1. Have a large number of AWS Profiles. For example:
```
# ~/.aws/credentials
[MyRootCredentials]
aws_secret_key_id = AKIA...
aws_secret_access_key = abc123...
```

```
# ~/.aws/config
[profile MyProfile1]
source_profile=MyRootCredentials
role_arn=aws:iam::Account:role/MyRole
mfa_serial=arn:aws:iam::Account:mfa/MyUser

[ ... ]

[profile MyProfile200]
source_profile=MyRootCredentials
role_arn=aws:iam::Account:role/MyRole
mfa_serial=arn:aws:iam::Account:mfa/MyUser
```
2. Open the IDE
3. Wait 15-20 minutes until the IDE opens. 

**Expected behavior**
The IDE should wait to load and either verify these profiles when selected, or verify them in the background after the IDE has finished loading.

**Screenshots**

![image](https://user-images.githubusercontent.com/8879234/69488993-e878d300-0e26-11ea-919c-c9d8f5de8833.png)

**Your Environment**
 - OS: Fedora 31
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: Enterprise
 - Toolkit Version: 1.7
 - SAM CLI Version: SAM CLI, version 0.32.0
 - JVM/Python Version: 3.7

**Comment by rli** [comment]
Thanks for the report. We do credential validation to filter out invalid profiles for users, but that's clearly an issue if you have more than a couple of profiles.

**Comment by abrooksv** [comment]
Coincidentally, #1395 includes an updated design that would remove this issue.

**Comment by abrooksv** [comment]
A lot of this was refactored in 1.10, please let us know if you are still seeing this
