### ISSUE TITLE
Rider: cannot install aws-jetbrains-toolkit-1.8-EAP.2019.11.23-193.zip on MacOS 10.14

### ISSUE THREAD

**Issue by koendhondt** [aws/aws-toolkit-jetbrains#1387]
**Describe the bug**
Attempting to install aws-jetbrains-toolkit-1.8-EAP.2019.11.23-193.zip for Rider 2019.2 results in the following error being shown:

Error: Plugin 'AWS Toolkit' is incompatible with this installation

**To reproduce**
1. Download aws-jetbrains-toolkit-1.8-EAP.2019.11.23-193.zip  from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions;
2. Open Rider 2019.2, navigate to Preferences -> Plugins, click the cogwheel and select 'Install Plugin from Disk...'
3. Select aws-jetbrains-toolkit-1.8-EAP.2019.11.23-193.zip and press 'Open'

**Expected behavior**
Plugin properly installed.

**Your Environment**

- OS: MacOS Mojave 10.14.6
- JetBrains' Product: Rider
- JetBrains' Product Version: 2019.2.3
- Toolkit Version: aws-jetbrains-toolkit-1.8-EAP.2019.11.23-193.zip
- SAM CLI Version: SAM CLI, version 0.22.0
- JVM/Python Version: jvm 1.8.0_202, Python 2.7.10, Python 3.7.4

**Comment by hunterwerlla** [comment]
@koendhondt Hello, that is the version for 19.3, you need the version for 19.2 `1.8-EAP.2019.11.23-192` here: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/72947 . We recently split our build process to build for specific versions instead of having one version.

**Comment by koendhondt** [comment]
Thanks, my bad. Using the officially released version now, thanks!
