### ISSUE TITLE
Support Deployment of Nested Applications (CAPABILITY_AUTO_EXPAND)

### ISSUE THREAD

**Issue by dfreemyer** [aws/aws-toolkit-jetbrains#1394]
**Is your feature request related to a problem? Please describe.**
I'm working on a project that I would like to keep organized by nesting applications under a master template. Deployment via "Deploy Serverless Application" fails with the nested applications in status CREATE_FAILED because "Requires Capabilities: [CAPABILITY_AUTO_EXPAND]".

There seems to be no way to modify the command used by the "Deploy Serverless Application" in the context menu to include the additional capability required by CloudFormation.

**Describe the solution you'd like**
In the Deploy Serverless Application dialog, there could be an option to preview the commands that will be run and give the user a chance to edit the arguments as needed. 

Or better yet, there could be a project-wide setting somewhere, kind of like the credential chooser, where users could enable/disable capabilities a-la-carte. 

**Describe alternatives you've considered**
It looks like my only options are to deploy from the command line or reconsider my choice to nest templates. I really like being able to quickly deploy from within the ide (PyCharm in my case)

**Comment by rli** [comment]
Thanks for the feedback. We'll re-evaluate the UX here.

**Comment by Naturious** [comment]
Any advancement on this front?

**Comment by hunterwerlla** [comment]
@Naturious This will be in the next release, and will be available in next weeks EAP release

**Comment by abrooksv** [comment]
We have released support in 1.13, please let us know if there are any issues
