### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by SamHashemiCA** [aws/aws-toolkit-jetbrains#1397]
**Describe the bug**
Hi All,

I'm trying to build a Lambda Function using PyCharm AWS Toolkit and I receive this error which I couldn't track down:
```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```
**To reproduce**
fail to run both [local] and [remote] for a simple helloworld teplate

**Screenshots**
![Screenshot from 2019-11-26 11-40-50](https://user-images.githubusercontent.com/28886954/69667570-189cbd80-1043-11ea-80c3-bc01fc5f0673.png)

**Your Environment**
 - OS: Ubuntu 18.04
 - JetBrains' Product: Pro
 - JetBrains' Product Version: 2019.2.5
 - Toolkit Version: 4.4 
 - SAM CLI Version: 0.33.1
 - Python Version: 3.6

**Comment by rli** [comment]
Hi, can you run `/home/sam/anaconda3/bin/sam --info` and verify that the version returned is 0.33.1?

**Comment by SamHashemiCA** [comment]
```
aconda3/bin/sam --info
{
  "version": "0.33.1"
}
```

**Comment by rli** [comment]
Your screenshot implies that the IDE is setup to use `anaconda3`, not `aconda3`. Is that your issue?

**Comment by SamHashemiCA** [comment]
Sorry this was a complete response:
```
/home/sam/anaconda3/bin/sam --info
{
  "version": "0.33.1"
}

```

**Comment by rli** [comment]
Do you happen to be on pip v20 by any chance?

**Comment by SamHashemiCA** [comment]
No I'm on `pip 19.0.3 `.

**Comment by rli** [comment]
Can you try running the `... sam build --template ...` command in the screenshot manually?

If you get the same result I would cut an issue to the SAM CLI repo as they'd be better equipped to figure out your issue: https://github.com/awslabs/aws-sam-cli/issues/new?template=Bug_report.md

**Comment by rli** [comment]
Actually, before you do that, another issue it could be is if you're trying to run it as a `python2.7` lambda, but don't have pip installed for python2

**Comment by SamHashemiCA** [comment]
I got the same result `sam build ...` , it doesn't work. Although I'm using a SAM template it can't create a `template.yml`.
The Python --version == 3.6.8
Thanks @rli

**Comment by rli** [comment]
Sure, but the SAM CLI determines what version of python to use based on the declared `template.yaml`. I'd check your IDE run configuration or `/home/sam/PycharmProjects/lambda/.aws-sam/build/template.yaml`

<img width="790" alt="image" src="https://user-images.githubusercontent.com/742829/69676663-1001b280-1056-11ea-824d-e12c9828ccca.png">

**Comment by SamHashemiCA** [comment]
The runtime is on python3.6

**Comment by SamHashemiCA** [comment]
transferred to [here](https://github.com/awslabs/aws-sam-cli/issues/1613)
