### ISSUE TITLE
Support for Isolated Regions

### ISSUE THREAD

**Issue by gholt-aws** [aws/aws-toolkit-jetbrains#1405]
Add support for isolated regions like https://aws.amazon.com/govcloud-us/, and https://www.amazonaws.cn/about-aws/china/.

**Describe the solution you'd like**
* Customers can see and select isolated regions in the region selector
* Customers can deploy to isolated regions
* Customers can execute lambdas in isolated regions
* Customers can retrieve lambdas from isolated regions
* Customers can debug lambdas from isolated regions locally
* Customers can use cloud debug in isolated regions

**Comment by abrooksv** [comment]
We must first update the code according to: https://github.com/aws/aws-toolkit-jetbrains/commit/530c6ae1a60d742f36441ec10a8a9f994f4360d7

**Comment by abrooksv** [comment]
Remaining work:

1. Add partition selection to settings menus
2. Fix class with `AWS_GLOBAL` pseudo region (IAM)
3. Assume role calls to STS needs to be to the correct region/partition

**Comment by justinmk3** [comment]
.
