### ISSUE TITLE
Hot Swap for remote ECS debugging

### ISSUE THREAD

**Issue by DmPanov** [aws/aws-toolkit-jetbrains#1457]
It would be great to perform code hot swap at the same extent it's possible with local debugging.

Alternative is to restart application every time code is changed and wait.

**Comment by kiiadi** [comment]
Just to confirm here - are you talking about hotswapping code at runtime (e.g. via JRebel or something?) or something else?

**Comment by DmPanov** [comment]
Yes, runtime hot swap like https://dcevm.github.io or regular Java method bodies hot swap at least

**Comment by kiiadi** [comment]
What's the limitations that stop you from using this today? If you use a base-image thath as the DECEVM stuff already on it (e.g. https://github.com/HotswapProjects/hotswap-docklands) then you should be able to just spin up the application with the appropriate environment variables / JVM arguments and when the debugger attaches you should be able to hotswap.

Am I missing something? I must admit - but it seems like the required lifecycle hooks are there...

**Comment by DmPanov** [comment]
Actually I tried ECS debugging almost a year ago and at that time the request made sense for me. But now I'm not sure, it seems you are right, thanks
