### ISSUE TITLE
Fail to enable cloud debug for ecs task with app mesh enabled

### ISSUE THREAD

**Issue by zxkane** [aws/aws-toolkit-jetbrains#1463]
**Describe the bug**

Can not enable **cloud debug** for task with app mesh enabled with below error,

> Retrieving ECR image digest for image name='aws-appmesh-envoy', tag='v1.12.1.1-prod'
> errors":["failed to instrument ECS service name='eCommenceClusterStack-serviceproductservicemainlineService73FC2069-1XDET0PMTM548', cluster='eCommenceClusterStack-eCommenceCluster45FE7E00-VB4HI2GIUYM3' with iamRole='arn:aws:iam::845861764576:role/eCommenceClusterStack-TaskRoleproductserviceC08C5A-AYH5QG2WEK00', debugEntrypoint='' and restartCmd=''","enable debugging failed for the service \"eCommenceClusterStack-serviceproductservicemainlineService73FC2069-1XDET0PMTM548\" in cluster \"eCommenceClusterStack-eCommenceCluster45FE7E00-VB4HI2GIUYM3\"","failed to update the ECS task definition","failed to update ECS application container definitions","failed to retrieve entrypoint or command from Docker image metadata","could not get ECR image digest for name='aws-appmesh-envoy', tag='v1.12.1.1-prod', registryId='840364872350'","User: arn:aws:iam::845861764576:user/kane is not authorized to perform: ecr:DescribeImages on resource: arn:aws:ecr:ap-northeast-1:840364872350:repository/aws-appmesh-envoy"]}
> Error details:
> 	- failed to instrument ECS service name='eCommenceClusterStack-serviceproductservicemainlineService73FC2069-1XDET0PMTM548', cluster='eCommenceClusterStack-eCommenceCluster45FE7E00-VB4HI2GIUYM3' with iamRole='arn:aws:iam::845861764576:role/eCommenceClusterStack-TaskRoleproductserviceC08C5A-AYH5QG2WEK00', debugEntrypoint='' and restartCmd=''
> 	- enable debugging failed for the service "eCommenceClusterStack-serviceproductservicemainlineService73FC2069-1XDET0PMTM548" in cluster "eCommenceClusterStack-eCommenceCluster45FE7E00-VB4HI2GIUYM3"
> 	- failed to update the ECS task definition
> 	- failed to update ECS application container definitions
> 	- failed to retrieve entrypoint or command from Docker image metadata
> 	- could not get ECR image digest for name='aws-appmesh-envoy', tag='v1.12.1.1-prod', registryId='840364872350'
> 	- User: arn:aws:iam::845861764576:user/kane is not authorized to perform: ecr:DescribeImages on resource: arn:aws:ecr:ap-northeast-1:840364872350:repository/aws-appmesh-envoy

**To reproduce**

1. Add appmesh container *840364872350.dkr.ecr.ap-northeast-1.amazonaws.com/aws-appmesh-envoy:v1.12.1.1-prod* as sidecar in task definition,
2. enable *cloud debug* in intellij for above task

**Expected behavior**

Be able to enable **cloud debug** for any ECS task.

**Screenshots**

**Your Environment**
 - OS: macOSX 10.14.6
 - JetBrains' Product: IntelliJ community
 - JetBrains' Product Version: 2019.3.1
 - Toolkit Version: 1.9-193 / cloud-debug cli 1.0.233
 - SAM CLI Version:
 - JVM/Python Version:  java 11.0.5 2019-10-15 LTS

**Additional context**

**Comment by raducataws** [comment]
@zxkane, unfortunately cloud debug doesn't support app mesh enabled ECS services right now but we are actively working to implement it.

**Comment by raducataws** [comment]
@zxkane, we release a fix that addresses the issue you reported. Please let us know if you encounter additional issues.

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
