### ISSUE TITLE
The target group 'arn:aws:elasticloadbalancing:xxxxx' created by the instrumentation already exists, please revert the instrumentation and try again

### ISSUE THREAD

**Issue by pulpopurpura** [aws/aws-toolkit-jetbrains#1465]
**Describe the bug**

I'm not sure whether this is a bug or not, but it's left me dead in the water and googling didn't help me solve it.  I'm pretty new to AWS and completey new to Cloud Debugging (just trying it out).   I suspect that this problem is soluble by some action at my end, either by me or the AWS administrator.  But it's unclear what the instruction to "revert the instrumentation" means.  Thanks for any help.

**To reproduce**
Open ECS, open Clusters, open my cluster, open what I presume to be the task (?), right click and select 'enable cloud debugging (beta), then select the task role.  

**Expected behavior**
I'm not sure, but basically it should enable cloud debugging.

**Error log**
I got the following error.  (The names are not the originals, I've tried to anonymise a bit):

```
cloning target group. New target group configuration is '{
  HealthCheckEnabled: true,
  HealthCheckIntervalSeconds: 60,
  HealthCheckPath: "/",
  HealthCheckPort: "traffic-port",
  HealthCheckProtocol: "HTTP",
  HealthyThresholdCount: 5,
  Name: "cloud-debug-ecs-something",
  Port: 80,
  Protocol: "HTTP",
  TargetType: "ip",
  VpcId: "vpc-b6659dd1"
}'
https://elasticloadbalancing.ap-northeast-1.amazonaws.com (elasticloadbalancing:CreateTargetGroup) called with 3dcfa002-e6f6-43a1-962b-8b4cc82d09d2 ; status: "DuplicateTargetGroupName: A target group with the same name 'cloud-debug-ecs-something' exists, but with different settings\n\tstatus code: 400, request id: 3dcfa002-e6f6-43a1-962b-8b4cc82d09d2"
The target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again
errors":["failed to instrument ECS service name='something', cluster='something' with iamRole='arn:aws:iam::something', debugEntrypoint='' and restartCmd=''","enable debugging failed for the service \"something\" in cluster \"something\"","the target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again","target group with the same name but different settings already exists \"arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6\""]}
Error details:
	- failed to instrument ECS service name='something', cluster='something' with iamRole='arn:aws:iam::404738250837:role/something', debugEntrypoint='' and restartCmd=''
	- enable debugging failed for the service "something" in cluster "something"
	- the target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/ecs-something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again
	- target group with the same name but different settings already exists "arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/ecs-something/2195a2859f504af6"
```

**Your Environment**
 - OS: Mac OS 10.14.5
 - JetBrains' Product: WebStorm
 - JetBrains' Product Version: 2019.3

**Comment by raducataws** [comment]
Hi @pulpopurpura 

 Thanks for trying out Cloud Debugging.
 I agree the error message is not very suggestive and we took a note to update it. 
 
  The `revert the instrumentation`  message actually instructs you to disable the cloud debugging on that specific ECS service. Please let me know if disabling the debugging and re-enabling it worked for you. If not, please provide us the steps you followed to try to reproduce it.

**Comment by pulpopurpura** [comment]
@raducataws -- Thanks.  I'm new to AWS.  Could you tell me how to disable and re-enable debugging for the service?  ([This page](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html#ecs-cluster) didn't help me understand what to do).

**Comment by pulpopurpura** [comment]
@raducataws 

Thanks.  The problem I'm having is that if I follow steps 1-5 above, I get the error about "please revert the instrumentation".   Thus, I can't turn on debugging, nor disable it.  So I'm back where I started.  

`https://elasticloadbalancing.ap-northeast-1.amazonaws.com (elasticloadbalancing:CreateTargetGroup) called with 3dcfa002-e6f6-43a1-962b-8b4cc82d09d2 ; status: "DuplicateTargetGroupName: A target group with the same name 'cloud-debug-ecs-something' exists, but with different settings\n\tstatus code: 400, request id: 3dcfa002-e6f6-43a1-962b-8b4cc82d09d2"
The target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again
errors":["failed to instrument ECS service name='something', cluster='something' with iamRole='arn:aws:iam::something', debugEntrypoint='' and restartCmd=''","enable debugging failed for the service \"something\" in cluster \"something\"","the target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again","target group with the same name but different settings already exists \"arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/something/2195a2859f504af6\""]}
Error details:
	- failed to instrument ECS service name='something', cluster='something' with iamRole='arn:aws:iam::404738250837:role/something', debugEntrypoint='' and restartCmd=''
	- enable debugging failed for the service "something" in cluster "something"
	- the target group 'arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/ecs-something/2195a2859f504af6' created by the instrumentation already exists, please revert the instrumentation and try again
	- target group with the same name but different settings already exists "arn:aws:elasticloadbalancing:ap-northeast-1:404738250837:targetgroup/ecs-something/2195a2859f504af6"`

**Comment by ovidiupw** [comment]
@pulpopurpura

It seems like the target group 'cloud-debug-ecs-something' [1] already exists in your account and enabling the debugging doesn't work since it would overwrite the existing target group.

This may be caused by a previously failed Cloud Debug enabling operation or by someone else using the same AWS IAM user to use Cloud Debug. 

Please make sure you are running Cloud Debug in your personal development AWS account.

If you don't need the existing 'cloud-debug-ecs-something' [1] target group, you can delete it by following these steps:
1. In the AWS console home page select EC2 in the 'ap-northeast-1' region;
1. In the left side panel of the EC2 AWS console, select 'Target Groups';
1. Select the target group that you want to delete, in this case 'cloud-debug-ecs-something' [1];
1. Click on 'Actions', then select 'Delete';
1. Confirm the deletion of the target group.

After deleting the target group, you can try re-enabling the debugging for the desired service.

I tried this exact scenario in my account and managed to get it working as described. However, if you're still having trouble, please let me know.

[1] When referring to 'cloud-debug-ecs-something', I'm taking into account the anonymization you did, so the exact resource name might be different.

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
