### ISSUE TITLE
SAM Schema doesn't allow Globals property

### ISSUE THREAD

**Issue by Jeffmagma** [aws/aws-toolkit-jetbrains#1466]
**Describe the bug**
When using the SAM schema, the validation tells me that the 'Globals' property is not allowed. The only fix it provides is to remove it

**To reproduce**
1. Set the schema of the SAM file to "sam"
2. Paste their Globals sample, [taken from here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html) into the file
3. Hover over the warning

**Expected behavior**
No warning should appear to remove the Globals property

**Screenshots**
![image](https://user-images.githubusercontent.com/7827718/71451489-f03cd780-2744-11ea-9e7a-1a7260c57911.png)

**Your Environment**
 - OS: Windows 10 Home
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: 2019.3.1
 - Toolkit Version: Toolbox App 1.16.6207, OS kernel winnt 10.0.18363 on x86_64
 - SAM CLI Version: N/A
 - JVM/Python Version: N/A

**Comment by abrooksv** [comment]
We do not do CloudFormation validation. The CFN plugin (https://plugins.jetbrains.com/plugin/7371-aws-cloudformation) is not owned/maintained by AWS today.

**Comment by abrooksv** [comment]
You have a `sam` JSON schena set. That is not provided by the AWS plugin.

**Comment by hunterwerlla** [comment]
Hello, the schema comes from the `aws/goformation` repo, I opened an issue on it here: https://github.com/awslabs/goformation/issues/305
