### ISSUE TITLE
Add the ability to force disable cloud debugging

### ISSUE THREAD

**Issue by ErnstHaagsman** [aws/aws-toolkit-jetbrains#1471]
**Is your feature request related to a problem? Please describe.**
I have an application where I configure my AWS resources using Terraform. Then I ran `terraform destroy` in one of my workspaces where cloud debugging was enabled. The destroy operation wouldn't complete, because the cluster isn't empty (the cloud debugging copy is still there). At this point I'm stuck: "Disable Cloud Debugging" doesn't work, because the original service is gone. After `terraform apply`, it's still not allowing me to disable, because it's looking for some ARNs that were already deleted.

**Describe the solution you'd like**
I'd appreciate a "Force disable" option, which cleans up any and all resources created for cloud debugging, without attempting to recreate my resources. 

**Describe alternatives you've considered**
- Deletion protection for resources linked to cloud debugging, to make `terraform destroy` fail with an error message that makes it clear it's due to cloud debugging being enabled. ECS doesn't support deletion protection at this point in time, as far as I'm aware.
- Rediscover services based on something that stays constant when doing `terraform destroy && terraform apply`. This might lead to a broken application if the wrong service gets discovered

**Additional context**
-

**Comment by raducataws** [comment]
Hi @ErnstHaagsman,

  This is a miss on cloud debugging side and we are working to address it. 
  To get unblocked, please consider deleting the cloud debug specific AWS resources manually: the cloud debugging ECS service copy in the ECS cluster and potentially the S3 metadata bucket (name starts with `do-not-delete-cloud-debug-<AWS Region>-<AWS Account Id>`). Please note that deleting the S3 metadata bucket will delete all your cloud debug session for that account in that region.

**Comment by raducataws** [comment]
Hi @ErnstHaagsman,

  We implemented a fix for this issue and now the "Diable Cloud Debugging" option will work even if the original ECS service is gone.

**Comment by kiiadi** [comment]
Please feel free to re-open if this persists.
