### ISSUE TITLE
Add support to nodejs12.x and fix a bug when inferring nodejs lambda

### ISSUE THREAD

**Issue by fdiazaguirre** [aws/aws-toolkit-jetbrains#1483]
**Is your feature request related to a problem? Please describe.**
During "Update Function Configuration" (after right click on a Lambda function in the AWS Explorer) the node12.x Runtime is missing.

Also if your function is already on a node10.x with your functions, you are no longer able to update your functions, because upon saving you are getting a "Runtime must be specified error".

**Describe the solution you'd like**
I would like to see node12.x as a supported runtime.

**Additional context**
node12.x become available in 18 Nov: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/
And it's already in the documentations: https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html

(I tried to find any related issue/commit, but I did not find anything)

**Comment by abrooksv** [comment]
Node12 is in master but not released yet.

https://github.com/aws/aws-toolkit-jetbrains/commit/7bc9d7b43ae57f0a4e3d229e786a57ba913ae02f

**Comment by abrooksv** [comment]
Release is out
