### ISSUE TITLE
Allow use of empty parameter value

### ISSUE THREAD

**Issue by roneystein** [aws/aws-toolkit-jetbrains#1498]
**Is your feature request related to a problem? Please describe.**
When updating or creating a CF stack using AWS Console we may use empty parameters. Currently (version 1.10-192) the plugin doesn't allow a deploy with empty parameter values.

**Describe the solution you'd like**
Be consistent with the way CF Console works accepting empty values.

**Describe alternatives you've considered**
There's no alternative, the CloudFormation template has to be modified to work around this limitation.

**Additional context**
No additional context.

**Comment by abrooksv** [comment]
Validation logic is based around new stack, where each parameter is required.

We will need to revisit this and redo the UX for updating stacks.

**Comment by hunterwerlla** [comment]
a
