### ISSUE TITLE
pyCharm 2019.3 get an exception in plugin AWS Toolkit 1.10.193

### ISSUE THREAD

**Issue by bookavium** [aws/aws-toolkit-jetbrains#1500]
**Describe the bug**
Exception in plugin AWS Toolkit (1.10-193).

**To reproduce**

**Expected behavior**
Expected using aws toolkit to be able to run locally lambda functions and deploy them once tested.

**Screenshots**
<img width="823" alt="Screen Shot 2020-01-13 at 12 17 47 PM" src="https://user-images.githubusercontent.com/45601932/72251936-d33a4c80-35fe-11ea-8972-866e0a40c7ef.png">
 explain your problem. -->
I installed aws toolkit on pyCharm 2018.3 and then upgraded pyCharm. Then restarted pyCharm or another reason independent from this problem. After the restart I could not see the plugin icon aws-toolkit on the "start new project" list of plugins.

**Your Environment**
 - OS: 
 - JetBrains' Product: PyCharm Professional
 - JetBrains' Product Version: 2019.3
 - Toolkit Version: AWS Toolkit 1.10.193
 - SAM CLI Version: 0.40.0
 - JVM/Python Version: Python3.8

**Additional context**

**Comment by abrooksv** [comment]
Can you please copy paste the stack trace? The cause is cut off.

**Comment by hunterwerlla** [comment]
Closing inactive issue, there does not seem to be any other reports of this as well.
