### ISSUE TITLE
Parameter value containing spaces is truncated

### ISSUE THREAD

**Issue by roneystein** [aws/aws-toolkit-jetbrains#1502]
**Describe the bug**
A parameter containing a one (or more) blank space characters is truncated at the first blank space.

**To reproduce**
1. Create a new project template (AWS::Serverless-2016-10-31).
2. Define a String parameter with a default value of "cron(30 22 * * ? *)"
3. Define a resource (AWS::Events::Rule) with the ScheduleExpression property having the parameter above as its value.
3. Deploy the project.
4. Locate the new Change Set.
5. The parameter value will shown as "cron(30"
6. When executing the resource (CloudWatch rule) will fail with "Parameter ScheduleExpression is not valid."

**Expected behavior**
The parameter value "cron(30 22 * * ? *)" should be shown and used by the Change Set.

**Screenshots**

**Your Environment**
 - OS: Mac OS 10.14.6
 - JetBrains' Product: PyCharm 
 - JetBrains' Product Version: 2019.2.5 Community Edition
 - Toolkit Version: 1.10-192
 - SAM CLI Version: 0.40.0
 - JVM/Python Version: Python 3.7.3
[template.yaml.zip](https://github.com/aws/aws-toolkit-jetbrains/files/4061426/template.yaml.zip)

**Additional context**

**Comment by roneystein** [comment]
Found that this is caused by [https://github.com/awslabs/aws-sam-cli/issues/1652](https://github.com/awslabs/aws-sam-cli/issues/1652)

**Comment by hunterwerlla** [comment]
This is fixed in SAM 0.41, closing
