### ISSUE TITLE
PyCharm 2019.3.1 is not compatible with newest version of SAM CLI 0.40.0

### ISSUE THREAD

**Issue by v4l3nt1n** [aws/aws-toolkit-jetbrains#1509]
**Describe the bug**
Recent update of the SAM CLI 0.40.0 is not compatible. New Serverless Projects cant be created due to this restriction.
Please review, anything else let me know.

**Comment by abrooksv** [comment]
Can you please check you are on version 1.10 of the toolkkt? We increase the compatibility range in 1.10

**Comment by v4l3nt1n** [comment]
That was it, updated the toolkit and worked like a charm.
Thanks for the quick reply
