### ISSUE TITLE
Jetbrains 2020.1 EAP issues list

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#1519]
This is a list of issues to allow us to run on 2020.1 EAP. There aren't that many issues, and I have a branch that hacks around these here: `werlla/add20201`

- The gui test framework does not currently exist for 2020.1 EAP
- `TreeStructureProvider`'s functions has been updated to take `<*>`'s instead of `<Any>`'s
- `ToolWindow`'s `icon` has been made a `val`
- `PsiElementVisitor` has been made not nullable
- Rider isn't available yet

**Comment by abrooksv** [comment]
We support 2020.1 now
