### ISSUE TITLE
"Create New AWS Lambda..." context menu item disappears

### ISSUE THREAD

**Issue by press0** [aws/aws-toolkit-jetbrains#1520]
**Describe the bug**

"Create New AWS Lambda..." is a Lambda gutter Icon context menu item in the "AWS Toolkit for
JetBrains" plugin.  For some reason, this context menu item disappears after running "Run [Local] App"

**To reproduce**

1. Follow the complete AWS Toolkit forJetBrains plugin install process including aws sam, docker, linuxbrew, etc
2. Create a New Project -> AWS Serverless Application
3. Open App.java

4. Click on the Lambda gutter Icon.  See attached screenshot of the context menu *INCLUDING* "Create New AWS Lambda..." 
5. "Run [Local] App"
6. Click on the Lambda gutter Icon, again.  See attached screenshot of the context menu *MISSING* "Create New AWS Lambda..." 

**Expected behavior**

Run [Local] App works.  Run [Remote] works.
But the "Create New AWS Lambda..." context menu item is missing.  That is unexpected.

**Screenshots**

See 2 attached screenshots, before and after running "Run [Local] App"

![before](https://user-images.githubusercontent.com/94419/73116804-73974780-3f02-11ea-819d-777be2f44762.png)
![after](https://user-images.githubusercontent.com/94419/73116803-72feb100-3f02-11ea-816b-4bc2ac6991b3.png)

**Your Environment**
 - OS: Ubuntu
 - JetBrains' Product: IntelliJ IDEA 2019.3 (Ultimate Edition) 
 - JetBrains' Product Version: Build #IU-193.5233.102
 - Toolkit Version: 1.10-193
 - SAM CLI Version: 0.40.0
 - JVM/Python Version: java 1.8.0_172

**Additional context**

**Comment by abrooksv** [comment]
Hey @press0, sorry for not responding. 

The create action hides itself if it detects the Lambda handler is referenced in a CloudFromation template: https://github.com/aws/aws-toolkit-jetbrains/blob/50251ac7c503ef4b91c6b74bc1e9c3f5daab8760/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/upload/CreateLambdaFunction.kt#L59

Did you happen to have a tempalte with this handler in it?

**Comment by abrooksv** [comment]
Ah, I was able to reproduce this. 

The "dummy" template we generate to make SAM run when in "raw" lambda mode is getting indexed. This is a bug that we will need to fix.

**Comment by rli** [comment]
we exclude this directory now
