### ISSUE TITLE
"Failed to refresh process-based credentials." when connecting to AWS

### ISSUE THREAD

**Issue by jakul** [aws/aws-toolkit-jetbrains#1529]
**Describe the bug**
I cannot use my existing AWS profile inside AWS toolkit, as i receive the error `Failed to refresh process-based credentials.`

I use a custom process (an in-house Python cli called Wrench) to obtain time-limited credentials for a IAM role when connecting to AWS. This works fine on the command line, but not inside PyCharm. I have used this process for years now, so the problem is not there.

I install Wrench in a pyenv Python 3.6 environment. My system Python is 3.7. I recently had a very similar issue where it wasn't possible for the aws cli to get credentials from the custom process because I had `pip install awscli` into Python 3.7. That's fixed now, and `$ aws sts get-caller-identity` correctly gets the credentials from the custom process.

I am able to connect to AWS using a profile which does not use the custom process.

I'm unable to see any relevant info in the PyCharm log file. Is there somewhere else I can look to debug this?

**Expected behavior**
I am able to connect to AWS using the same profile in PyCharm that I use on the shell.

**Screenshots**
![Captura de Tela 2020-02-05 às 10 45 11](https://user-images.githubusercontent.com/862794/73835088-bad7df00-4804-11ea-9e79-882939b40f93.png)

**Your Environment**
 - OS: macOs Catalina 10.15.3
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2019.3
 - Toolkit Version: 1.10-193
 - SAM CLI Version: Not installed.
 - JVM/Python Version: JVM 11.0.5 (I think). System Python is Homebrew 3.7, AWS CLI and  Wrench installed into virtualenvs created from pyenv 3.6

**Comment by abrooksv** [comment]
Sadly the log statement we need to debug this has not been released to stable channel yet. If I had to take a shot in the dark, I would guess environment variables are causing issues since Mac apps launched from gui do not inherit them.

Things to try
1. Opt in to eap builds of the plugin (or do a one off download of latest eap from the plugin marketplace) and then look for the error in the idea.log
2. Try to launch the ide from a terminal
3. Wrap the credentials process command in a shell script so it runs in a terminal environment and had env vars / .bashrc info

**Comment by jakul** [comment]
Thanks for the quick response!

The problem is definitely the environment that PyCharm launches in - when I launch it from the terminal I'm able to connect using any of the AWS profiles I have setup. 

Thanks for the help @abrooksv

**Comment by FnTm** [comment]
For what it's worth - I had this exact same problem, and
1. Enabling shell scripts in the Toolbox https://blog.jetbrains.com/blog/2018/08/23/toolbox-app-1-11-whats-new/ , 
1. And launching from CLI (`$ idea`)

helped solve this.
