### ISSUE TITLE
Cant start Lambda

### ISSUE THREAD

**Issue by dtarczynski** [aws/aws-toolkit-jetbrains#1555]
**Describe the bug**

I created simple Lambda project using dotnetcore2.1 / C#. 

When I try to run I get this error log:

`

> "C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" local invoke --template C:\Users\tarcda\.nuget\packages\microsoft.net.test.sdk\16.0.1\build\netcoreapp1.0\.aws-sam\build\template.yaml --event "C:\Users\tarcda\AppData\Local\Temp\[Local] HelloWorldFunction-event9.json" HelloWorldFunction
> Invoking HelloWorld::HelloWorld.Function::FunctionHandler (dotnetcore2.1)
> 
> Fetching lambci/lambda:dotnetcore2.1 Docker container image.....
> Mounting C:\Users\tarcda\.nuget\packages\microsoft.net.test.sdk\16.0.1\build\netcoreapp1.0\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
> Traceback (most recent call last):
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 261, in _raise_for_status
>     response.raise_for_status()
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.35/containers/create
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
>   File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
>     cli(prog_name="sam")
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
>     raise exception  # pylint: disable=raising-bad-type
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
>     return_value = func(*args, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 86, in cli
>     parameter_overrides,
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 151, in do_cli
>     context.function_name, event=event_data, stdout=context.stdout, stderr=context.stderr
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 100, in invoke
>     self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 83, in invoke
>     self._container_manager.run(container)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 93, in run
>     container.create()
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\container.py", line 133, in create
>     real_container = self.docker_client.containers.create(self._image, **kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\models\containers.py", line 861, in create
>     resp = self.client.api.create_container(**create_kwargs)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\container.py", line 430, in create_container
>     return self.create_container_from_config(config, name)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\container.py", line 441, in create_container_from_config
>     return self._result(res, True)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 267, in _result
>     self._raise_for_status(response)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 263, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: lambci/lambda:dotnetcore2.1")

`

**To reproduce**

1. Create new Solution
2. Select AWS Serverless Application
3. Select Runtime: dotnetcore2.1
4. Try to Run Ctrl + F5.

**Expected behavior**
Lambda running from Rider.

**Your Environment**
- OS: Windows 10
- JetBrains product: Rider 2019.3
- AWS Toolkit version: 1.10-193
- SAM CLI version: SAM CLI, version 0.41.0
- Docker CE 2.1.0.0 Windows

**Comment by justinmk3** [comment]
> docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: lambci/lambda:dotnetcore2.1")

Seems like docker doesn't have that image. What happens if you run the sam command directly (from cmd.exe or Windows terminal)?

    C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" local invoke --template C:\Users\tarcda.nuget\packages\microsoft.net.test.sdk\16.0.1\build\netcoreapp1.0.aws-sam\build\template.yaml --event "C:\Users\tarcda\AppData\Local\Temp[Local] HelloWorldFunction-event9.json" HelloWorldFunction

**Comment by mbonig** [comment]
I'm getting the same problem. When I try to run it in the terminal (Webstorm 2020.1) I get the same error I see in the debug window.

**Comment by justinmk3** [comment]
@mbonig Are you also on Windows? This is likely a Docker sharing issue. https://github.com/aws/aws-sam-cli/issues/1126

> SAM CLI does a bind mount and if the share settings are not enabled for where you are working, then docker swallows the error and pretends everything is fine. On Windows, we have seen needing to toggle the share settings (on drives/directories) for Docker for Windows to pick up the settings. Both are really unclear and an issue with Docker.

Try refreshing the credentials for your shared drives.
