### ISSUE TITLE
Lambda must be written before creation

### ISSUE THREAD

**Issue by mchassy** [aws/aws-toolkit-jetbrains#1563]
**Lambda must be written before creation**
The first step in creating a new lambda should be to create a Hello World skeleton. But the plugin insists that the lambda already be written.

**Comment by justinmk3** [comment]
Could you share the exact steps you are taking to create a new lambda?

**Comment by mchassy** [comment]
- I create a new project using the aws toolkit template.
-- You can see the existing lambdas in the lower left hand window.
- I click to create a new lambda and fill out the info.
- The error message says that it can't find the handler.
-- Of course it can't, I am creating it now.
- It should create a file called hanlder.py
 

![labmda01](https://user-images.githubusercontent.com/15926092/75345969-9e741300-5895-11ea-9b2d-e4be56e1a18b.png)
![labmda03](https://user-images.githubusercontent.com/15926092/75345974-9fa54000-5895-11ea-935a-0aecb22a36b7.png)
![labmda04](https://user-images.githubusercontent.com/15926092/75345976-9fa54000-5895-11ea-824f-b1fe2b1d0037.png)

**Comment by abrooksv** [comment]
That dialog is not a wizard, but instead creates a new Lambda function in your account. That is why the handler must exist, because we will build and upload the code.

**Comment by mchassy** [comment]
That, I get. But then how is it expecting the code to be named? When executed this in a repo which had the files
- Lambda1.py
- Lambda2.py
- Lambda3.py
each containing the a function with the same name as the filename, that didn't work either.

**Comment by abrooksv** [comment]
It would be `<path relative to requirements.txt>/Lambda1.Lambda1` if Lambda1 is the module name and function name

**Comment by rli** [comment]
Closing in favor of https://github.com/aws/aws-toolkit-jetbrains/issues/1842
