### ISSUE TITLE
On first launch, a default region is not always set

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#1571]

**Comment by abrooksv** [comment]
May be a race condition if the endpoints data is not ready yet.

**Comment by kiiadi** [comment]
default credential isn't set either - and it should be.

**Comment by abrooksv** [comment]
> default credential isn't set either - and it should be.

That's definitely the async loading kicking in.

**Comment by justinmk3** [comment]
fixed by https://github.com/aws/aws-toolkit-jetbrains/pull/1756
