### ISSUE TITLE
Cannot use files in an excluded folder as lambda handlers

### ISSUE THREAD

**Issue by vordimous** [aws/aws-toolkit-jetbrains#1579]
**Describe the bug**
Using AWS Toolkit to test lambdas written in Typescript, the typscript output directory is marked `Excluded` so the IDEA doesn't index it. However this prevents the RunConfig from detecting the handler function.

**To reproduce**
1. Create the template project
2. Run the lambda Run Config against the app.js function
3. Run is successfull
4. mark the directory as `Excluded`
5. Run the lambda Run Config
6. Error message `Cannot find handler in project`

**Expected behavior**
Plugin should be able to find built package files in `Excluded` folders

**Screenshots**

**Your Environment**
- OS: MacOS 10.14.6
- JetBrains product: WebStorm
- JetBrains product version: 2019.3.3
- AWS Toolkit version: 1.11-193
- SAM CLI version: 0.43.0
- JVM/Python version: Node 13.8

**Comment by rli** [comment]
wontfix. marking a directory as excluded means that the toolkit won't ever find the handler
