### ISSUE TITLE
Project package : Cannot use zip file

### ISSUE THREAD

**Issue by cbm-saziri** [aws/aws-toolkit-jetbrains#1580]
Hello,

First congrats for the plugin, it's very useful, but the toolkit doesn't work with our zip file archive. 
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install "../../../../../../../project.zip" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar

**Our Environment**
- OS: MacOs Catalina and Linux
- JetBrains product: IntelliJ Ultimate
- AWS Toolkit version: 1.11-192
- SAM CLI version: 0.41.0
- JVM/Python version: NodeJS 10

Sam CLI and Lambda does support zip archive. 

Thank you

**Comment by justinmk3** [comment]
Please share the exact steps you took, and any additional logs.

**Comment by abrooksv** [comment]
This is caused by the fact the the toolkit relies on SAM build command. We are calling SAM build for you, but the template you are using is not compatible with sam build

**Comment by cbm-saziri** [comment]
Thank you for your feedback.
Our steps are : 
- We build the project (typescript to javascript)
- We zip the project with following structure : 
     the node_modules, 
     the src folder
     package.json
- the sam template references to the zip archive. It's working when we call the sam local invoke, sam local start api for every lambda but not with aws toolkit run command for the moment. 

Indeed it's seems it's sam build failed because it throws the following error : 

Building resource 'project'
Running NodejsNpmBuilder:NpmPack

Build Failed
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL

Thank you again for your precious help 

Bonne journée :)

**Comment by cbm-saziri** [comment]
Ok actually I find a way to get it work ! We did use the option "build function inside container' from the javascript file project.
But is there a way to use our zip instead and not use sam build when we run it with the toolkit ?
Thank you

**Comment by abrooksv** [comment]
Not today, we will always run SAM build.

**Comment by cbm-saziri** [comment]
Ok we will change our workflow to use sam build too. Thank you for your help.
