### ISSUE TITLE
there are some regions in China, but neither of them are listed in the IDE, nor can not be chosen

### ISSUE THREAD

**Issue by duzhengkun7145** [aws/aws-toolkit-jetbrains#1590]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment]
We have not finished refactoring the toolkit to support them. Tracking item is #1405
