### ISSUE TITLE
Sam weird debug issues on webstorm

### ISSUE THREAD

**Issue by mete89** [aws/aws-toolkit-jetbrains#1610]
**Describe the bug**
From time to time, the code is not updated when debugging the application. I'm having this issue more than 2 weeks. When I change the code sometimes not reflected on the file:///var/task/app.js. It tries to debug the old code. 

**To reproduce**
I couldn't find clear steps to reproduce yet. It seems random but if I create a new debug configuration it grabs the latest code. 

**Expected behavior**
After I click on debug it needs to get latest code on IDE.

**Your Environment**
- OS: 
- JetBrains product: Webstorm
- JetBrains product version: 2019.3.4
- AWS Toolkit version: 1.11-193
- SAM CLI version: 0.45.0 (0.43.0 has the same issue)
- JVM/Python version:

**Comment by abrooksv** [comment]
Can you try marking the `.aws-sam` folder as excluded?

**Comment by mete89** [comment]
Its already excluded.

**Comment by mete89** [comment]
@abrooksv any idea? When I change environment variables, this is also not detected as well. Run has similar issues in addition to debug. Do I need to trigger a rebuild after each code or env variable change?

**Comment by abrooksv** [comment]
We always run `sam build` whenever you use the run config.

We log the output to idea.log (Find it through the Help menu). It may shed some light on it.

Are you using a template or specifying the handler directly?

**Comment by rli** [comment]
Closing due to age. Please cut a new issue if this is still a problem.
