### ISSUE TITLE
Vertically align CloudWatch Log timestamps at the top

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-jetbrains#1645]
Currently, timestamps in CloudWatch logs are vertically aligned as center:

![image](https://user-images.githubusercontent.com/39839589/77809110-85ed4900-704b-11ea-8c09-e77abdab3b9e.png)

This gets confusing, particularly with larger entries. In the below example, I thought that the second log entry was part of the first one, but it turns out the timestamp is out of view:

![image](https://user-images.githubusercontent.com/39839589/77809142-a1585400-704b-11ea-9e73-1c68886ce19a.png)

Expected behavior: top align the timestamps

**Comment by hunterwerlla** [comment]
This is by design, when it was at the top it was weird for 3 or 4 line logs.  a 15+ line log like this is very exceptional
