### ISSUE TITLE
Link to file in CloudWatch Logs stream saved notice

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-jetbrains#1646]
When informing the user that the CloudWatch logs were saved, can the file be made into a clickable link?

![image](https://user-images.githubusercontent.com/39839589/77809306-50952b00-704c-11ea-9b3a-9f26c341e94b.png)

![image](https://user-images.githubusercontent.com/39839589/77809312-54c14880-704c-11ea-8691-06dafcec3b33.png)

**Comment by hunterwerlla** [comment]
Clickable link to do what though? maybe open in file explorer?

**Comment by awschristou** [comment]
Could it open the file in the IDE?

**Comment by hunterwerlla** [comment]
The point of downloading is the log stream is too large to open in the IDE (usually)

**Comment by abrooksv** [comment]
> 
> 
> The point of downloading is the log stream is too large to open in the IDE (usually)

Ya, but a downloaded file can trigger the IDE's large file mode. So we should offer to open it

**Comment by hunterwerlla** [comment]
Released as part of the feature
