### ISSUE TITLE
Intellij Idea 2018.3 is not compatible with newest version of SAM CLI 0.46.0

### ISSUE THREAD

**Issue by yubinchen18** [aws/aws-toolkit-jetbrains#1647]
![image](https://user-images.githubusercontent.com/13944768/77831485-c7572480-712f-11ea-8bc3-89e077c5535b.png)

Installed AWS Toolkit from Plugin market place, installed lateds aws-sam-cli via brew, set up correct sam cli executable. and got this when try to deploy

**Comment by justinmk3** [comment]
If you use an old version of an intellij, then an old version of the Toolkit + old version of SAM CLI is needed. Workaround is to upgrade intellij + Toolkit, then latest version of SAM CLI should work.

see also https://github.com/aws/aws-toolkit-jetbrains/issues/1551

**Comment by yubinchen18** [comment]
> If you use an old version of intellij, then an old version of the Toolkit + old version of SAM CLI is needed. Workaround is to upgrade intellij + Toolkit, then latest version of SAM CLI should work.
> 
> see also #1551

thanks, suspect it as much. But is there a way to downgrade aws-sam-cli?
using 'brew search aws-sam-cli' there's only 1 formulae, there are no older versions avaiable.

**Comment by justinmk3** [comment]
you could try the `brew install x@y` syntax ([ref](https://stackoverflow.com/a/4158763/152142)), but AFAIR brew is pretty aggressive about phasing out support for old stacks (partly due to macOS details, partly due to sheer maintenance burden). I would recommend upgrading intellij, just the free community version should work fine.

**Comment by justinmk3** [comment]
Actually the macOS asset (`aws-sam-cli-0.40.0.sierra.bottle.tar.gz`) from the SAM CLI releases should work: https://github.com/awslabs/aws-sam-cli/releases/tag/v0.40.0

**Comment by yubinchen18** [comment]
Hi thanks, it works on the newest Intellij Idea 2019.3, 

I couldn't get the version downgrading working.

I downloaded the tar.gz, extracted to the brew aws-sam-aws 0.39.0 folder, then 'brew switch aws-sam-cli 0.39.0'. 

but then if i type in 'sam' in console, it says it:

bad interpreter: @@HOMEBREW_CELLAR@@/aws-sam-cli/0.39.0/libexec/bin/python3.7: no such file or directory

Even if i changed the @@HOMEBREW_CELLAR@@ to my install path.

Anyway got it working now with a complete new install IDE

**Comment by yubinchen18** [comment]
Got new problem :) hope you can help as well:
#1649 1649
