### ISSUE TITLE
Cannot find handler, and no lambda icon next to handler

### ISSUE THREAD

**Issue by yubinchen18** [aws/aws-toolkit-jetbrains#1648]
For some reason a former employee of our company decided to use kotlin for this project, and then he left, and im stuck with this project. written in Kotlin, using Spring Boot, deploying as AWS Lambda. But on aws it now fails to boot. and I'm trying to debug locally but I just can't get it to work

Here's my project structure:
![image](https://user-images.githubusercontent.com/13944768/77832013-24080e80-7133-11ea-9670-f4623be4a3ea.png)

![image](https://user-images.githubusercontent.com/13944768/77832043-629dc900-7133-11ea-916d-eff0770ba4f8.png)

Here's code of my handler class

`package com.oceanpremium.api.locations

import com.amazonaws.serverless.exceptions.ContainerInitializationException
import com.amazonaws.serverless.proxy.model.AwsProxyRequest
import com.amazonaws.serverless.proxy.model.AwsProxyResponse
import com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler
import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestStreamHandler
import org.slf4j.LoggerFactory
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.domain.EntityScan
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer
import org.springframework.context.annotation.ComponentScan
import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.web.bind.annotation.RestController
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import kotlin.jvm.*
import kotlin.jvm.java as java1

/**
 * The main application entry point that spins up the API.
 *
 * IMPORTANT:
 *
 * instead of letting component scan automatically scan packages for injectable classes,
 * explicitly define classes in the import closure. The reason for NOT using component scan is:
 * to optimize cold starts (because we run the Spring application with Serverless) and component scan takes
 * A LOT of time (+30 seconds), therefore leading to high latency on cold start of serverless functions, and AWS lambda functions via API Gateway
 * have a limit of 30 (more ~28 / ~29) secs on cold startup.
 *
 * @see https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot#optimizing-cold-start-times
 * @see https://pattern-match.com/blog/2019/07/11/springboot2-and-aws-lambda-quick-fix/
 */
@ComponentScan(basePackages = ["com.oceanpremium.api.locations","com.oceanpremium.api.core"])
@SpringBootApplication
@EntityScan(basePackages =["com.oceanpremium.api.core.entity"])
@EnableJpaRepositories(basePackages = ["com.oceanpremium.api.core.repository"])
class LocationsDriver : SpringBootServletInitializer() {

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            SpringApplication.run(LocationsDriver::class.java1, *args)
        }
    }
}

/**
 * The AWS server-less main entry point that is called when function is triggered.
 */
@RestController
class Handler : RequestStreamHandler {

    companion object {
        private val logger = LoggerFactory.getLogger(this::class.java1)
        private var handler: SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse>? = null

        init {
            try {
                handler =
                    SpringBootLambdaContainerHandler.getAwsProxyHandler(LocationsDriver::class.java1)
            } catch (e: ContainerInitializationException) {

                e.printStackTrace()
                logger.error(e.message)

                // Re-throw exception to force a cold start
                throw RuntimeException("Could not initialize Spring Boot application", e)
            }
        }
    }

    @Throws(IOException::class)
    override fun handleRequest(inputStream: InputStream, outputStream: OutputStream, context: Context) {

        try {
            handler!!.proxyStream(inputStream, outputStream, context)
        } catch (e: ContainerInitializationException) {
            e.printStackTrace()
            logger.error(e.message)
        } finally {
            outputStream.close()
        }
    }
}`

**Comment by justinmk3** [comment]
regarding the "lambda icon":

> no lambda icon next to handler 

see https://github.com/aws/aws-toolkit-jetbrains/issues/142
