### ISSUE TITLE
Build Failed Error: JavaGradleWorkflow:Resolver - No Gradle executable found!

### ISSUE THREAD

**Issue by yubinchen18** [aws/aws-toolkit-jetbrains#1649]
Intellij Idea 2019.3

Trying to debug local handler, then got 

Build Failed Error: JavaGradleWorkflow:Resolver - No Gradle executable found!

![image](https://user-images.githubusercontent.com/13944768/77902518-9b4bb880-7281-11ea-8700-a993e6d25292.png)

But the project has gradle? how else would i be able to pull in all the dependencies?

**Comment by yubinchen18** [comment]
Ok this one is because the handler class is inside a sub module of the project, the gradle wrapper and gradlew is in the root. so apparently you need to have a local copy of gradle inside the same folder as the handler if you want to run this successfully

**Comment by VinodhThiagarajan1309** [comment]
What worked for me is this ,
- Installed Gradle using brew ( I didn't notice that it was a pre-requisite'
- ran the `gradle wrapper` command
- then `sam build ` worked for me

**Comment by infotoarunkumar** [comment]
> What worked for me is this ,
> 
> * Installed Gradle using brew ( I didn't notice that it was a pre-requisite'
> * ran the `gradle wrapper` command
> * then `sam build ` worked for me

Worked. Thanks

**Comment by terryjray** [comment]
Ran into this also. What I did to fix was

- update Preferences | Tools | AWS to set the path to the sam CLI (mine was installed with brew)
- installed gradle with brew
- restarted IntelliJ
