### ISSUE TITLE
Unable to run Lambda function locally.

### ISSUE THREAD

**Issue by TheTimKiely** [aws/aws-toolkit-jetbrains#1676]
Hi,
When trying to run a Lambda locally in PyCharm using the AWS Plugin, I get the error:
6:17 PM	Error running '[Local] HelloWorldFunction': Running/Debugging Lambdas locally requires Docker. Please make sure it is installed and running

I definitely have docker running.  
$ docker --version returns
Docker version 19.03.8, build afacb8b7f0

I am able to run the function locally using 'sam':
$ sam local invoke HelloWorldFunction 
builds a docker image and runs the function.

I haven't been able to figure out why the AWS Toolkit doesn't see docker.

Thank for the help,
Tim

**Comment by justinmk3** [comment]
can you provide this info about your environment:

    OS:
    pycharm version:
    AWS Toolkit version:
    SAM CLI version:

**Comment by TheTimKiely** [comment]
OS:Ubuntu 18.04.4 LTS
pycharm version: Professional 2019.3.4
AWS Toolkit version: 1.11-193
SAM CLI version:0.46.2

Thanks!

**Comment by abrooksv** [comment]
This usually indicates a PATH problem, we run `docker ps` and check if its exit code is 0.

https://github.com/aws/aws-toolkit-jetbrains/blob/32404a5b50822d6d259d5c75466432dd1f971842/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/execution/local/SamRunner.kt#L28

I would try to run intellij from a terminal and see if the issue goes away. This would point towards an issue with EnvVar inheritance from your shell.

**Comment by TheTimKiely** [comment]
Thanks for the help.  Launching PyCharm from the command line did it!

It looks like there something going on with permissions.
When launching PyCharm using the GUI shortcut, I get a permissions error running docker.

```
output = os.popen('whoami')
print(output.read())
```
Returns - Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied

My user account is in the docker group.  At the command line and in PyCharm after launching from the command line I can run docker commands without 'sudo'.

**Comment by abrooksv** [comment]
I am not sure what advice I can give you at this point to not require having to launch through a terminal since the issue is outside of the toolkit.

**Comment by TheTimKiely** [comment]
Thanks.
Launching from the terminal is fine with me.
I just thought I'd share what I found in case someone with more Linux experience than I knew what is happening.

**Comment by sharon-asana** [comment]
https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo#:~:text=If%20you%20don't%20want,writable%20by%20the%20docker%20group.&text=Either%20do%20a%20newgrp%20docker,activate%20the%20changes%20to%20groups.

**Comment by mskempri** [comment]
I'm currently experiencing this issue on the Mac
OS: 11.6.7
pycharm version: 2021.2.4 community edition
AWS Toolkit version: 1.4.26-212
SAM CLI version: 1.53.0

The error I get for the hello world function is:
`Validate Docker has failed: Cannot run program "docker": error=2, No such file or directory`

Did you even manage to figure out how to pass the permissions? I'm not even sure what is the issue
