### ISSUE TITLE
Open code from remote lambda

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#171]
Ability to open code from existing Lambda. Cloud9 currently has an experience wear a user can download the source-code from remote lambda for interpreted languages (Python, Node etc).

Being able to see what code is in a remote Lambda could be very useful - particularly if you're trying to debug a Lambda that isn't part of your direct project.

*Requires Investigation*
In theory it should be possible to even do this for Java - IntelliJ has a built-in decompiler - we could potentially load the remote Lambda's jar/zip file into a new scope, present a (read-only) view of the code and allow nagivation of that code within a scoped context.

This feature would be purely read-only - deploying from non-project resources that are not source controlled is a poor practice and we don't want to enable it.

**Comment by abrooksv** [comment]
We feel this goes encourages going against best practices and will not be supporting it
