### ISSUE TITLE
When are special regions will be supported?

### ISSUE THREAD

**Issue by demosunguohua** [aws/aws-toolkit-jetbrains#1719]
**Your Environment**

- OS: Win10
- JetBrains product: Intellj IDEA
- JetBrains product version: 2019.03
- AWS Toolkit version: 1.13-192
- SAM CLI version: not install 
- JVM/Python version:2.7

**Question**

When will China Region be supported？

**Comment by abrooksv** [comment]
Support is in 1.13 EAP builds, but not yet released to the Stable channel on the plugin marketplace

**Comment by justinmk3** [comment]
duplicate of https://github.com/aws/aws-toolkit-jetbrains/issues/699

**Comment by abrooksv** [comment]
Support has been released

**Comment by demosunguohua** [comment]
> Support is in 1.14 EAP builds, but not yet released to the Stable channel on the plugin marketplace

Thank you for your reply :)
