### ISSUE TITLE
Plans for AWS step functions.

### ISSUE THREAD

**Issue by jvidin** [aws/aws-toolkit-jetbrains#1720]
Any plans for AWS step functions in jetbrains toolkit ?
---
Toolkit: AWS Toolkit For JetBrains 1.13-201
OS: Windows 10 10.0
IDE: PyCharm Professional Edition 2020.1

**Comment by m-radzikowski** [comment]
Duplicate of #584 ?

**Comment by abrooksv** [comment]
Closing as duplicate of #584
