### ISSUE TITLE
How to debug typescript lamnda in webstorm

### ISSUE THREAD

**Issue by fyelci** [aws/aws-toolkit-jetbrains#1723]
**Your Environment**

- OS: Mac Os Catalina 10.15.3
- JetBrains product: Webstorm
- JetBrains product version: 2020.1
- AWS Toolkit version: 1.13-201
- SAM CLI version: 0.47.0
- JVM/Python version: Nodejs 12

**Question**

I have converted my SAM Lambda functions from javascript to typescript. 
I was able to debug nodejs code with this plugin, but now I can not configure my plugin to use typescript. 

I saw there are some solutions for vscode but couldn't find a solution for webstorm. Is there a way to debug typescript lambdas in webstorm?

**Comment by abrooksv** [comment]
We are working on getting TypeScript based Lambdas supported
