### ISSUE TITLE
Update function code, with function built inside a container

### ISSUE THREAD

**Issue by brunocuervo** [aws/aws-toolkit-jetbrains#1740]
**Your Environment**

- OS: macOS 10.15.4
- JetBrains product: WebStorm
- JetBrains product version: 2020.1.1
- AWS Toolkit version: aws-cli/2.0.10 Python/3.7.4 Darwin/19.4.0 botocore/2.0.0dev14
- SAM CLI version: SAM CLI, version 0.48.0
- node version: v12.16.2

**Question**

I'm building a lambda in node that uses a native module (canvas). When running the lambda locally, I can just check the "Build function inside a container", and things are built as expected against the correct image, and not my local env. But then when I right-click the lambda and select "Update Function Code" to deploy it, it is built without the `--use-container` (I can see it in the `sam build` command), and then execution fails when I run it remotely.
Is there any way to deploy the lambda built in a container with the toolkit? Am I missing something?

**Comment by abrooksv** [comment]
You are not missing anything, we added it to Deploy Serverless but not Update Function Code.

This was a miss on our part.

**Comment by hunterwerlla** [comment]
@brunocuervo our next EAP release (which should come out tomorrow) fixes this and it will part of the next release

**Comment by brunocuervo** [comment]
That was fast. Thanks for the great work with the toolkit!

**Comment by abrooksv** [comment]
This was released
