### ISSUE TITLE
Rider uses wrong build directory by default

### ISSUE THREAD

**Issue by citizenmatt** [aws/aws-toolkit-jetbrains#1747]
**Describe the bug**
Using the default Hello World sample, the build is invoked with the build directory pointing to a common NuGet cache folder, rather than to the project folder:

```
/usr/local/bin/sam build HelloWorldFunction --template /Users/matt/RiderProjects/HelloWorld2/template.yaml --build-dir /Users/matt/.nuget/packages/microsoft.net.test.sdk/16.0.1/build/netcoreapp1.0/.aws-sam/build
```

This is on Mac, and not tested on Windows.

**To reproduce**
1. Create a new project based on the Hello World template provided with the plugin
2. Go to the template.yaml file and click the "run" gutter icon
3. Populate the run configuration (credentials and events.json file)
4. Run the run configuration
5. Check the Build Output window, which will show the command line, and the wrong build directory
6. Check the Run tool window, and see the wrong directory used in the command line here, too.

```
/usr/local/bin/sam local invoke HelloWorldFunction --template /Users/matt/.nuget/packages/microsoft.net.test.sdk/16.0.1/build/netcoreapp1.0/.aws-sam/build/template.yaml --event "/private/var/folders/gf/gbf3dx712pbbg8xcpjd09x1r0000gn/T/[Local] HelloWorldFunction-event1.json"
Invoking HelloWorld::HelloWorld.Function::FunctionHandler (dotnetcore2.1)

Fetching lambci/lambda:dotnetcore2.1 Docker container image......
Mounting /Users/matt/.nuget/packages/microsoft.net.test.sdk/16.0.1/build/netcoreapp1.0/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
```

**Expected behavior**
The `.build` folder should be created in the root of the project

**Your Environment**
- OS: macOS Catalina, 10.15.4
- JetBrains product: Rider
- JetBrains product version: 2020.1.2
- AWS Toolkit version: 1.14-201
- SAM CLI version: `SAM CLI, version 0.47.0`
- JVM/Python version: N/A

**Comment by abrooksv** [comment]
Confirmed. We should be using the project root. Other IDEs do not seem to have this issue which points to the LambdaBuilder implementation

**Comment by abrooksv** [comment]
Build directory is calculated here: https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/LambdaBuilder.kt#L188

**Comment by abrooksv** [comment]
Looks like Rider has more content roots than other IDEs:

```
file:///Users/<user>/.nuget/packages/microsoft.net.test.sdk/16.0.1/build/netcoreapp1.0, 
file:///Users/<user>/.nuget/packages/xunit.runner.visualstudio/2.4.1/build/netcoreapp1.0/xunit.runner.reporters.netcoreapp10.dll, 
file:///Users/alfredbr/.nuget/packages/xunit.runner.visualstudio/2.4.1/build/netcoreapp1.0/xunit.runner.utility.netcoreapp10.dll, 
file:///Users/<user>/.nuget/packages/xunit.runner.visualstudio/2.4.1/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll, 
file:///Users/<user>/RiderProjects/HelloWorld3 <--- We want this
```
