### ISSUE TITLE
Support : in AWS profile names

### ISSUE THREAD

**Issue by stevesuh** [aws/aws-toolkit-jetbrains#1751]
**Is your feature request related to a problem? Please describe.**
As far as I can tell AWS does not disallow a : in a profile name.  Other tools I use accept :.

**Describe the solution you'd like**
Support : as a valid character for a profile name.

**Describe alternatives you've considered**
I currently copy the aws credentials everyday to one named jetbrains instead of my actual profile name.

**Comment by abrooksv** [comment]
This is a limitation of the Java SDK that we use to read the profile file: https://github.com/aws/aws-sdk-java-v2/blob/master/core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java#L45

We need them to make the change

**Comment by abrooksv** [comment]
Fix is in the SDK, we need to update our version to latest

**Comment by abrooksv** [comment]
@stevesuh Support for this has been released in our EAP builds if you want to try it. https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/eap/92563

**Comment by stevesuh** [comment]
Thanks so much!  Just tried it out.  Happy as a clam.
