### ISSUE TITLE
IntelliJ App Start : Error while getting SAM executable version.  java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by forgivegod** [aws/aws-toolkit-jetbrains#1757]
**Describe the bug**

Been working in Ultimate for about a week with 2020.1.1 on a project, IntelliJ will intermittently show red X's over run configs that use AWS Toolkit. Bringing up the run config will give the error. 

 This will usually happen after or during a command line of "sam build && sam deploy". Especially on app start.

**To reproduce**
1. start a "sam build & sam deploy" for an application with a few lambdas and open Intellij 
3.  Observe, that the run config for any lambda has a red x and the run config says "Error while getting SAM executable version.  java.util.concurrent.TimeoutException" at the bottom of the window.

**Expected behavior**
The run config should not have an X over it and there should be no "Error while getting SAM executable version.  java.util.concurrent.TimeoutException" error

**Screenshots**

**Your Environment**
- OS: Windows 10 Version 1909 (OS Build 18363.836)
- JetBrains product: IntelliJ IDEA 2020.1.1 (Ultimate Edition) 
- JetBrains product version: Build #IU-201.7223.91, built on April 29, 2020
- AWS Toolkit version: 1.14-201
- SAM CLI version: SAM CLI, version 0.48.0
- JVM/Python version: java version "1.8.0_251 (build 1.8.0_251-b08)

**Additional context**
Luckily there is a way to reset the error it w/o having to restart intellij, just 
1. Open up IntelliJ settings > Tools > AWS
2. Note the value in SAM CLI executable field
3. for SAM CLI executable field, Clear or specify another file (like Desktop\foo.txt)
4. Click Apply, ignore error
5. for SAM CLI executable field, clear it out (so it autodetects) or set it to the location of the sam executable (from step 2)
6. Click Apply (and all should be well again)

Please Note : logs incoming the next time this happens for me

edit 1 : added step 6 for additional context
edit 2 : grammar!

**Comment by forgivegod** [comment]
For hunterwerlla before they ask, 
The only virus application I have is windows defender.

**Comment by forgivegod** [comment]
And FWIW,  ty for this plugin. Its very helpful to have Intellij Run/Debug configs functionality applied to AWS SAM.

**Comment by hunterwerlla** [comment]
That is exactly what I was going to ask because that seems to be the issue most of the time (on my own machine I've seen SAM take > 3 seconds to start because of virus scanning). We cache SAM version after first run, so it should continue working if it worked once, which is why you are seeing it work after it works once. 

Can you post the portion of your IDEA.log that contains the timeout? [Here is how to get to the IDEA.log file](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files). Please post the timeout stacktrace and as many lines above and below as you feel comfortable with, thanks!

**Comment by forgivegod** [comment]
@hunterwerlla  gonna post the logs as soon as it happens again.  Thanks for being you and the quick replies.  Hope you are safe during these times (so you can make us more aws-toolit-jetbrains goodness).

**Comment by forgivegod** [comment]
[aws-toolkit-jetbrains-issue-1715.log](https://github.com/aws/aws-toolkit-jetbrains/files/4630892/aws-toolkit-jetbrains-issue-1715.log)

@hunterwerlla  here you go!

**Comment by hunterwerlla** [comment]
hm, this might potentially be an issue with our windows implementation, we're going to have to investigate this more

**Comment by adamdewing** [comment]
Got the same issue.  Here is the log for the error:
[idea-Invalid-sam-executable.log](https://github.com/aws/aws-toolkit-jetbrains/files/5255951/idea-Invalid-sam-executable.log)

Knowing that I have run aws lambda functions before, I knew that the sam-executable was configured properly.  So I decided to restart intellij out of a whim.  Now when I go into the run configuration for the my aws lambda, it properly displays that it cannot parse my template.yml properly as there was a problem with the yml file.  In my case the Handler property had a typo in it.  Here is the log for this exception, which properly displays the correct error message, as a comparison: 
[idea-ProcessCanceledException.log](https://github.com/aws/aws-toolkit-jetbrains/files/5256010/idea-ProcessCanceledException.log)

Hope this helps with this issue and if anyone else gets it, just restarting (not restarting and invalidating caches) seems to fix the issue.

Version: IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Licensed to Adam Dewing
Subscription is active until October 12, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 4
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: com.intellij.ideolog, Lombook Plugin, Property Sorter, de.juserv.intellij-propertiessort, net.seesharpsoft.intellij.plugins.csv, ru.trylogic.idea.gitlab.integration, AWSCloudFormation, org.zalando.intellij.swagger, org.sonarlint.idea, MavenRunHelper, aws.toolkit, com.intellij.plugins.html.instantEditing, sonnenhut.liveedit.patch

**Comment by forgivegod** [comment]
@hunterwerlla 
I'm pretty certain your team(s) fixed this bug in the release following this report.  Or maybe it was a bug within intellij itself.  
I'm going to close this issue as I can no longer repro.

(hope you, the fam, the workfam are all safe)
