### ISSUE TITLE
Run Time Handler not found error in lambda

### ISSUE THREAD

**Issue by karthikkangokar** [aws/aws-toolkit-jetbrains#1771]
I am developing a action on google for business in aws Lambda and my index.js file is as:-
'use strict';
const {Lambda} = require('actions-on-google');
const {app}=require('./app.js');

exports.handler = async (event,context,callback)=> {
    await app.handler(new Lambda(event,context,callback));
};

It is throwing error as 
{
“errorType”: “Runtime.HandlerNotFound”,
“errorMessage”: “index.handler is undefined or not exported”,
“trace”: [
“Runtime.HandlerNotFound: index.handler is undefined or not exported”,
" at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
" at Object. (/var/runtime/index.js:43:30)",
" at Module._compile (internal/modules/cjs/loader.js:1156:30)",
" at Object.Module._extensions…js (internal/modules/cjs/loader.js:1176:10)",
" at Module.load (internal/modules/cjs/loader.js:1000:32)",
" at Function.Module._load (internal/modules/cjs/loader.js:899:14)",
" at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
" at internal/main/run_main_module.js:18:47"
]
}

**Comment by justinmk3** [comment]
can you share your project tree (i.e. files/folder names)?

**Comment by rli** [comment]
We need more information to diagnose this issue. If you have more you can share, please go ahead and re-open the issue with details and we can take a look.
