### ISSUE TITLE
A "default" profile should not be required in credentials file

### ISSUE THREAD

**Issue by mattisking** [aws/aws-toolkit-jetbrains#1784]
**Describe the bug**
I don't use a default in my credentials file. The company where I work doesn't hand out service accounts so as a developer, I have to generate my tokens every few hours (as they expire) and modified a Windows tray application I found in github to keep it up to date. At my company we have different environments, each with a designated role. One for Production, one for non-production, one for "innovation". At any rate, these roles are regenerated and named in my credentials file after the environment they represent. I could certainly go into the file and rename the one I want to "default", but I shouldn't have to do that. 

In windows, I can simply set a couple of environment variables that satisfied most of the apps I use, including the AWS CLI. All I have to do is create two:
AWS_DEFAULT_REGION
AWS_DEFAULT_PROFILE

I can change the environment variable any time I want to re-target without having to touch the application running in the background keeping my token alive. 

The  bug is that there are not 4 profiles, there are 3. It's not a failure to load a profile that doesn't exist:
4 profiles found. Failed to load 1 profile.

**To reproduce**
1. Create a valid credentials file wherever yours is defined (on windows it's probably "C:\users\<you>\.aws\credentials" without a default profile.
2. Load up IntelliJ with AWS Toolkit installed.
3. See the message every time.

**Expected behavior**
I would expect it to look to see if an environment variable is set and if so load that profile as the default if I've not set one in the IDE. I would not throw an error because a non-defined profile doesn't exist. I would expect the error only if the currently selected profile in AWS Toolkit doesn't exist the next time I open the IDE, whatever that profile is. Default shouldn't matter. 

**Screenshots**
Really not necessary. Easily reproduced above but I'll attach.
![popup](https://user-images.githubusercontent.com/412168/82703133-5e78be00-9c41-11ea-85c3-d19d8d953940.PNG)
![event log](https://user-images.githubusercontent.com/412168/82703144-620c4500-9c41-11ea-8eb6-24f40a0a8185.PNG)

**Your Environment**
- OS: Windows 10 Pro
- JetBrains product: Intellij Ultimate
- JetBrains product version: 2020.1.1
- AWS Toolkit version:1.15-201 AWS
- SAM CLI version: N/A
- JVM/Python version: openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)

**Additional context**

**Comment by abrooksv** [comment]
There is not a requirement that you have to use a default profile, we just default to it. 

You can choose any profile that is supported by the toolkit (It seems you have 3) by clicking on the AWS section in the status bar or use the Gear menu on the explorer. We are working on making this more obvious in a future version.

We can not use Env Vars because those are static and you would need to restart the IDE for Winodows to give us the updated Env Vars.

The profile that is failing to load either lacks credentials, or is configured in a way the toolkit does not support, so we hide it.

**Comment by abrooksv** [comment]
We have overhauled the selecting of regions and credentials in order to clarify what you have selected/can select. It will be in the next release.
