### ISSUE TITLE
Aws Sam build failed Error: JavaMavenWorkflow:Resolver - No Maven executable found! on my hello world project

### ISSUE THREAD

**Issue by katchi7** [aws/aws-toolkit-jetbrains#1792]
**Your Environment**

- OS:Windows 10 
- JetBrains product: Intellij Idea 
- JetBrains product version: 2019.3.3

**Question**
I just started building serverless application with aws toolkit in intellij, and I got stuck in this error after executing the template.

Build Failed
**`Error: JavaMavenWorkflow:Resolver - No Maven executable found!`**
I tried a lot of solution in the aws documentation bad none of them works

**Comment by abrooksv** [comment]
It can't find Maven on your path

You can:
1. Install maven and make sure it gets added to your PATH env var
2. Use SAM's build in container feature to run the build inside of Docker which will already have Maven in the image

**Comment by CiciMa** [comment]
Do you have a detail link about how to set up step 2 you listed above?
I got same error here.

**Comment by abrooksv** [comment]
@CiciMa Yes, that is what I meant.
