### ISSUE TITLE
Unable to see CloudFormation Status Reasons

### ISSUE THREAD

**Issue by andrewryan1906** [aws/aws-toolkit-jetbrains#1858]
**Describe the bug**
When you view the CloudFormation stack status in order to determine why a stack failed, you are unable to fully see the status reason.

**To reproduce**
Pull up the AWS ToolKit
Go toe CloudFormation Stacks
Select an stack that has failed
Attempt to navigate to the failed event

The status reason is in the leftmost column and you cannot see the entire reason.

**Expected behavior**
A big reason why I would want the CloudFormation integration is to look at a stack and troubleshoot what went wrong. Currently I have to login to AWS to do this; this toolkit is great for that.

But when I want to figure out the reason for failure, I can't see all of the text. I should be able to see the status reason - that's kind of the most important thing in all of the events. Ether I should be able to click it and bring up a window that shows the entire reason, or even better - when I click the row of the CloudFormation event, the reason should show up in the bottom pane (which is now blank).

**Screenshots**
![image](https://user-images.githubusercontent.com/37671394/85205260-4354a900-b2e8-11ea-9627-b28854410f90.png)

**Your Environment**
- OS:  MacOS
- JetBrains product: WebStorm
- JetBrains product version: 2020.2
- AWS Toolkit version: 
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment]
Thanks for reporting this. Will look into what we can do.

**Comment by abrooksv** [comment]
The expanded items support in the JBTable does not take the container window into account so it is going off the screen.

<img width="577" alt="Screen Shot 2020-06-22 at 4 28 08 PM" src="https://user-images.githubusercontent.com/8992246/85344762-73957680-b4a5-11ea-9405-3ca09b58e2bf.png">

We will most likely need to roll our own solution.

**Comment by abrooksv** [comment]
Feature has been released in 1.17
