### ISSUE TITLE
Long messages in cloudwatch are impossible to read

### ISSUE THREAD

**Issue by strowk** [aws/aws-toolkit-jetbrains#1862]
**Describe the bug**

Any message that's longer than my screen is impossible to read in "cloudwatch logs" view. 

**To reproduce**

1. Open AWS Explorer
2. Click ECS, find any service that have logs with long messages
3. Right click on service, choose container, click "View container log stream"
4. No way to see long message completely inside IDE, workaround is right click and "copy message" and paste, which is very inconvenient. 

**Expected behavior**
CloudWatch in AWS webconsole allows to show complete message, it should be possible in IDE too

**Screenshots**

**Your Environment**
- OS: Windows
- JetBrains product: Intellij IDEA
- JetBrains product version: Community 2019.3
- AWS Toolkit version: 1.16-193
- SAM CLI version: -
- JVM/Python version: Openjdk 11, Python 3.7.3

**Comment by abrooksv** [comment]
Hey, can you try using the word wrap toggle on the right side of the table? It is not enabled by default.

**Comment by strowk** [comment]
Ah, sorry, I somehow missed that button. It works! 

Though I feel like it should be enabled by default or at least be enabled automatically on double click in the row - that'd be better UX, I think. Anyway that's more like a feature requiest.

**Comment by abrooksv** [comment]
I will talk to the dev that implemented it,  I think we talked about expand on click but it's been a while

**Comment by strowk** [comment]
Here's feature request for that - https://github.com/aws/aws-toolkit-jetbrains/issues/1863
