### ISSUE TITLE
Enable word wrap on double click in a long message

### ISSUE THREAD

**Issue by strowk** [aws/aws-toolkit-jetbrains#1863]
**Is your feature request related to a problem? Please describe.**

When long message is displayed in cloudwatch logs, the first user reaction is to double click it. Unfortunately that does nothing. 

**Describe the solution you'd like**

It would be nice to enable word wrap on double click in long message.

**Describe alternatives you've considered**

I can just click in the word wrap button, but that's not so intuitive, besides that button is small and very easy to miss.

**Additional context**
Preserve the scroll. One of the problem of current word wrap button is that pressing it while having a certain log entry selected, causes scroll to move, because all of previous messages are also expanded. That's a bit unfortunate. I think that either only clicked message should expand or scroll position regarding clicked message should be preserved to prevent loss of user focus.

**Comment by abrooksv** [comment]
Now wraps if the row is selected, will be in the next release

**Comment by abrooksv** [comment]
Feature has been released in 1.17
