### ISSUE TITLE
No debug option available in Rider when using runtime dotnetcore3.1

### ISSUE THREAD

**Issue by humblepie** [aws/aws-toolkit-jetbrains#1879]
**Describe the bug**
No debug option available when using dotnetcore3.1

**To reproduce**

1. Open Rider
2. Pick new solution
3. Choose **AWS Serverless Application**
4. Choose runtime **dotnetcore3.1**
5. Use SAM Template **AWS SAM Hello World**
6. Click on the create button
7. Solution is created with HelloWorld project
8. Look at the top right and you will see that a run configuration is available - but the **debug** button is disabled

**Expected behavior**
Debug button should be enabled.  Should be able to debug the lambda.  If I use **dotnetcore2.1** instead then the debug button is enabled.

**Screenshots**

**Your Environment**
- OS: macOS Catalina
- JetBrains product: Rider
- JetBrains product version: 2020.1.3
- AWS Toolkit version: 1.16-201
- SAM CLI version: 0.52.0
- JVM/Python version: Python 2.7.16

**Additional context**

**Comment by abrooksv** [comment]
We are blocked on changes in SAM CLI to enable debug on dotnet 3.1, sorry for the inconvenience.

**Comment by abrooksv** [comment]
Released in Toolkit 1.19 and SAM 1.4.0
