### ISSUE TITLE
unavailable EAP repository

### ISSUE THREAD

**Issue by BorzdeG** [aws/aws-toolkit-jetbrains#1881]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2332528/85923059-91d9e880-b890-11ea-855a-4fa0437f834a.png">

**Comment by kiiadi** [comment]
That's super weird - I just tried and was able to add the EAP repo successfully. Could it have been some sort of network blip? Which IDE (e.g. IntelliJ, PyCharm etc) and version (eg. 2019.3, 2020.1 etc) are you using?

**Comment by BorzdeG** [comment]
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.5958.24, built on June 25, 2020

**Comment by abrooksv** [comment]
We have not released a build for 2020.2 yet. Work was started in https://github.com/aws/aws-toolkit-jetbrains/tree/abrooksv-202Support

**Comment by abrooksv** [comment]
1.17 contains 2020.2 support
