### ISSUE TITLE
SAM stack deployment doesn't throw validation error which exists when deploying to beta/prod

### ISSUE THREAD

**Issue by ritika2291** [aws/aws-toolkit-jetbrains#1903]
On two occasions in the same day I faced the issue where when creating my SAM stack no validation error was throw for the following properties, however when deploying to my production account I got the following errors:
Policies: Value of property Policies must be a list of objects
 (works in sam, doesnt work in beta) 
Policies:
      - Fn::If:
          - RunLambdaInVPC
          - {Ref: LambdaVPCPolicy}
          - {Ref: 'AWS::NoValue'}
->
(works in both)
ManagedPolicyArns:
        - "Fn::If": [
          RunLambdaInVPC,
          {Ref: LambdaVPCPolicy},
          {Ref: 'AWS::NoValue'}
        ]

SecurityGroupIds: Value of property SecurityGroupIds must be of type List of String
 (works in sam, doesnt work in beta) {Ref: LambdaSecurityGroup} ->  (works in both) [{Ref: LambdaSecurityGroup}]

**Comment by abrooksv** [comment]
What do you mean by "works in sam"? Do you mean it works when using SAM CLI in a terminal?

Is the value of `RunLambdaInVPC` the same in your Beta and Prod?

**Comment by rli** [comment]
Closing due to issue inactivity. Please open a new issue if you are still experiencing issues.
