### ISSUE TITLE
Can't create or edit Local configuration after upgrade

### ISSUE THREAD

**Issue by genachka** [aws/aws-toolkit-jetbrains#1926]
**Describe the bug**
With IntelliJ 2019.3.5 and AWS Toolkit 1.12 I am able to edit and create new Local Configurations. When I upgraded to IntellIJ 2020.1 and AWS Toolkit 1.16 I clicking on the Local item when trying to add a new configuration has no affect (nothing appears on the right side and it doesn't create a new Local configuration). Remote still works.

I tried upgrading to IntelliJ 2020.1.3 and AWS Toolkit 1.17 and still same problem. However, if I open this same project with IntellIJ 2019.3.5 I am able to both edit and create new Local configurations.

![image](https://user-images.githubusercontent.com/7947294/87809580-a07d4500-c829-11ea-8447-1dd16c1d51ac.png)

I'm running on Linux, Ubuntu 20.04 x64.

**Comment by hunterwerlla** [comment]
@genachka I just tried this in 2020.1 and it works as expected from the gutter icon and the run/debug menu. Can you open your idea.log (Help->Show log in finder...) and copy the messages from a before and after you try to add the config? Thanks!

**Comment by genachka** [comment]
@hunterwerlla please see the attached requested before and after logs.
[idea-after.log](https://github.com/aws/aws-toolkit-jetbrains/files/4939243/idea-after.log)
[idea-before.log](https://github.com/aws/aws-toolkit-jetbrains/files/4939244/idea-before.log)

**Comment by hunterwerlla** [comment]
@genachka ah it looks like you don't have the docker plugin installed, it seems our detection logic is probably off? Is the plugin installed but deactivated?

**Comment by genachka** [comment]
@hunterwerlla yes, I did have the Docker plugin installed but disabled as I try to disable things I don't use directly or other plugins require. But of course enabling it resolved my issue right away! Thank you so much for your assistance with this. Not being able to debug locally has been a sore point and prevented moving to the newer versions of the IDE and plugin. Would be good if you can detect that the Docker plugin is either not installed or disabled and when someone tries to disable it that it warns that it's required by the AWS Toolkit plugin.

**Comment by hunterwerlla** [comment]
@genachka It should fail later with a helpful message, but failing at this point (silently) was a bug. I have a PR out to fix this scenario, which will be in next week's EAP build and the next release. Thanks for reporting this!
