### ISSUE TITLE
Using CodeCommit

### ISSUE THREAD

**Issue by jduckeck** [aws/aws-toolkit-jetbrains#1932]
Hello,
I was not able to use CodeCommit. Our admin activated MFA, so I need to add a security number for each push.
Idea git does not support MFA and as far as I understand the AWS plugin does not support CodeCommit access through CLI.
Do you plan to add CodeCommit support through CLI in the future?
cu
Jochen
---
Toolkit: AWS Toolkit For JetBrains 1.17-201
OS: Windows 10 10.0
IDE: WebStorm 2020.1.3

**Comment by hunterwerlla** [comment]
Hello, please +1 this issue for CodeCommit support: https://github.com/aws/aws-toolkit-jetbrains/issues/202
