### ISSUE TITLE
How do you generate an empty AWS SAM template without hello world? 

### ISSUE THREAD

**Issue by Shrined** [aws/aws-toolkit-jetbrains#1949]
**Your Environment**

- OS: 
- JetBrains product: intelliJ Community edition
- JetBrains product version: 2020.1.1

**Question**

There seems to only be an option for creating a template with hello world. Though for event bridges, there is the option to generate an empty template. Why is that option not available for a regular AWS SAM project?

![image](https://user-images.githubusercontent.com/45953733/88340061-b47ce700-cd00-11ea-983f-c053d8fb8f64.png)

**Comment by abrooksv** [comment]
Those templates map back to this repo: https://github.com/awslabs/aws-sam-cli-app-templates

An empty template has not been requested / created before to my knowledge.

**Comment by Shrined** [comment]
> Those templates map back to this repo: https://github.com/awslabs/aws-sam-cli-app-templates
> 
> An empty template has not been requested / created before to my knowledge.

Thank you for your response.

**Comment by rli** [comment]
Closing since it's unlikely that we can make this work with a good user experience
