### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by danbys** [aws/aws-toolkit-jetbrains#1952]
AWS support ruby 2.7, plugin yields _Error: The runtime 'ruby2.7' is unsupported._ 

![image](https://user-images.githubusercontent.com/459453/88535868-07111880-d00b-11ea-8d47-e682caf0b6f4.png)

**Comment by hunterwerlla** [comment]
Please +1 our issue for this: https://github.com/aws/aws-toolkit-jetbrains/issues/682
