### ISSUE TITLE
Support AWS::Serverless::StateMachine resource in SAM templates

### ISSUE THREAD

**Issue by alFReD-NSH** [aws/aws-toolkit-jetbrains#1953]
Currently AWS::Serverless::StateMachine resource in SAM templates is not supported. AWS::Serverless::StateMachine is new addition to the SAM resources and there's Stock Trader Step Functions Sample App that uses that. The sample app can be generated via `sam init`.

![image](https://user-images.githubusercontent.com/822510/88559911-b65ee700-d02d-11ea-83dc-a57ef4668423.png)

**Comment by abrooksv** [comment]
We do not have any CFN highlighting today. Are you using the AWS CloudFromation plugin? We do not own that.

We can add the template though.

**Comment by alFReD-NSH** [comment]
> Are you using the AWS CloudFromation plugin?

Yes, I should have created this for them.
