### ISSUE TITLE
SAM build failed without error message

### ISSUE THREAD

**Issue by michaelschem** [aws/aws-toolkit-jetbrains#1954]
**Describe the bug**
After a SAM build fails for AWS explorer lamba, it doesn't display the error.

**To reproduce**
1. Create bad AWS lambda project
2. Build it.
3. Event Log Displays: `SAM build command failed` with no error.

**Expected behavior**
When I run the same command from shell, I actually get a useful error:

```
% /usr/local/bin/sam build elasticsearchprocessalerts --template "/Users/michaelschem/PycharmProjects/AWS Lambdas/template.yaml" --build-dir "/Users/michaelschem/PycharmProjects/AWS Lambdas/.aws-sam/build"

Building function 'elasticsearchprocessalerts'

Build Failed
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/usr/bin/python'] which did not satisfy constraints for runtime: python3.7. Do you have python for runtime: python3.7 on your PATH?
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2836129/88706808-39338080-d0c6-11ea-8c21-d432ca4a1921.png)
![image](https://user-images.githubusercontent.com/2836129/88706835-43557f00-d0c6-11ea-96ca-cc6e13d90929.png)

**Your Environment**
- OS: macOS Catalina
- JetBrains product: PyCharm
- JetBrains product version: 2020.1.1
- AWS Toolkit version: 1.17-201
- SAM CLI version: 0.53.0
- JVM/Python version: 3.7

**Comment by abrooksv** [comment]
Do you have a tree on the left? Due to how IntelliJ builds the tree, the output goes to the parent node.

<img width="679" alt="Screen Shot 2020-07-28 at 5 06 03 PM" src="https://user-images.githubusercontent.com/8992246/88741509-b4139000-d0f4-11ea-88f7-e7b08a87dfb0.png">

**Comment by michaelschem** [comment]
You are the man, that's def there.

**Comment by abrooksv** [comment]
Thank you for reaching out
