### ISSUE TITLE
Create a serverless project ,but didn't have any .py file and .yaml file

### ISSUE THREAD

**Issue by steven130169** [aws/aws-toolkit-jetbrains#1964]
**Your Environment**

- OS: MacOS Catalina
- JetBrains product: Pycharm professiional 
- JetBrains product version: 2020.2
- AWS Toolkit version: 1.17-202
- SAM CLI version:1.0.0
- JVM/Python version:python3.8

**Question**
I create new project,use aws serverless application.
SAM template choose "AWS SAM Hello World"
but when I finish to create , my project file just has "venv" fold , and didn't have any other file.
Also didn't have any error message.
<img width="1440" alt="圖片" src="https://user-images.githubusercontent.com/27000465/89096031-981a3200-d405-11ea-91dc-5f8e1d0406d4.png">

Need someone to help me please!

**Comment by rli** [comment]
Closing due to age. Please cut a new issue if this is occurring on the latest version of the toolkit
