### ISSUE TITLE
Use SAM cli --s3-bucket in SAM deploy to avoid template size limit error

### ISSUE THREAD

**Issue by roneystein** [aws/aws-toolkit-jetbrains#1973]
**Is your feature request related to a problem? Please describe.**
When a project's template reaches the 51,200 bytes size limit we can't have the deployment/change set done using the UI as it errors.

**Describe the solution you'd like**
Use the SAM cli --s3-bucket option to avoid the first size limit.

**Describe alternatives you've considered**
Currently there's no other alternative other than running the command line manually adding the --s3-bucket option.

**Additional context**

**Comment by hunterwerlla** [comment]
@roneystein We already use `--s3-bucket` (here: https://github.com/aws/aws-toolkit-jetbrains/blob/7bb1c9df12f95be9783dd1564b1070731e9962ea/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/deploy/SamDeployDialog.kt#L128 ), what action are you taking that causes the error? And can you take a screenshot or copy paste the error? Thanks!

**Comment by jeremyc11** [comment]
I saw this bug should be fixed in version 1.18 but it still occur me in:
AWS Tooltip: **1.20** (2020-10-22)
PyCharm Community Edition 2019.3.4 on Windows

**Comment by hunterwerlla** [comment]
@jeremyc11 Hello, if you are having issues can you please open a new issue?
