### ISSUE TITLE
Runtime is not filtered based on what the IDE supports/create function shows up even when there are no runtimes we can build for

### ISSUE THREAD

**Issue by Kavin-Kannan** [aws/aws-toolkit-jetbrains#1980]
**Describe the bug**
When creating a Lambda function, and when I choose any of the runtime languages (Ruby 2.5, Java, Go, NodeJs,) for the Runtime option, I am seeing, "Deploying using the runtime<language_name> is not supported"

**To reproduce**

1. Go to AWS Explorer and choose default config
2. Right Click on 'Lambda
3. Create new Lambda function
4. In the Configuation Settings, enter all information except for Runtime
5. After entering all the information, now select a runtime language.
6. See Error

**Expected behavior**
I should be able to create the function without any issue.

**Screenshots**
<img width="784" alt="Screen Shot 2020-08-11 at 12 36 38 PM" src="https://user-images.githubusercontent.com/67066272/89924575-38bfdd00-dbd0-11ea-8a90-cc636bd92f2a.png">

**Your Environment**
- OS: Mac OS Catalina 10.15.6
- JetBrains product: Rubymine
- JetBrains product version: 2020.2
- AWS Toolkit version: 1.17-202
- SAM CLI version: SAM CLI, version 1.0.0
- JVM/Python version: N/A

**Additional context**

**Comment by hunterwerlla** [comment]
@Kavin-Kannan We currently do not support Ruby (issue here: https://github.com/aws/aws-toolkit-jetbrains/issues/682). Can you take a screenshot of the java one?

**Comment by Kavin-Kannan** [comment]
<img width="773" alt="Screen Shot 2020-08-11 at 3 48 58 PM" src="https://user-images.githubusercontent.com/67066272/89942423-877a7080-dbea-11ea-95a1-beaadb8d2100.png">
<img width="778" alt="Screen Shot 2020-08-11 at 3 48 52 PM" src="https://user-images.githubusercontent.com/67066272/89942425-88ab9d80-dbea-11ea-98e3-e78dad3c550c.png">

**Comment by hunterwerlla** [comment]
@Kavin-Kannan Ah I missed that you are using Rubymine. This menu should not be available in Rubymine if you don't have any additional languages installed. We currently require building the lambda to deploy it.

**Comment by Kavin-Kannan** [comment]
@hunterwerlla I have python 2.7 installed, but I still see the same error.

<img width="508" alt="Screen Shot 2020-08-11 at 4 26 02 PM" src="https://user-images.githubusercontent.com/67066272/89945482-7122e380-dbef-11ea-8bd7-064e45057fe3.png">

**Comment by abrooksv** [comment]
It is based on the languages installed into the IDE. Do you have the Python plugin installed?

**Comment by hunterwerlla** [comment]
I'm going to reopen this as an issue to track the UI issue.

**Comment by Kavin-Kannan** [comment]
Installed Nodejs, (both in the IDE and in the system)
Chose NodeJs 10.x 
Created an index.js with the example given in aws - https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html
Now when I try to create the lambda, I see the below error.

<img width="823" alt="Screen Shot 2020-08-11 at 4 46 40 PM" src="https://user-images.githubusercontent.com/67066272/89947316-40907900-dbf2-11ea-8793-41697415d90a.png">

**Comment by hunterwerlla** [comment]
@Kavin-Kannan The handler format can be confusing, in that case it would be `index.lambda_handler`. If you have any further issues, please file them separately.
