### ISSUE TITLE
Quote parameters strings so SAM CLI doesn't truncate them when containing spaces

### ISSUE THREAD

**Issue by roneystein** [aws/aws-toolkit-jetbrains#2007]
**Is your feature request related to a problem? Please describe.**
When using parameters values with spaces the SAM Cli truncates then. This is related to #1502 that I thought was fixed with newer SAM CLI version. There's an issue (https://github.com/awslabs/aws-sam-cli/issues/2018) and a PR (https://github.com/awslabs/aws-sam-cli/pull/2139) to address that, however, the value strings will need to be quoted using single quotes.

**Describe the solution you'd like**
Quote parameter values as required by SAM CLI. It still depends on a new SAM CLI release, as of today that is not supported.

**Describe alternatives you've considered**
Running the sam cli command by hand.

**Additional context**
https://github.com/awslabs/aws-sam-cli/pull/2139

**Comment by abrooksv** [comment]
Released in 1.18
