### ISSUE TITLE
Cannot use named profiles on Intellij, [default] is the only one that works

### ISSUE THREAD

**Issue by Ghilteras** [aws/aws-toolkit-jetbrains#2019]
- How to reproduce the Problem:
If I create a named profile in `Edit AWS Credential file(s)` and then select it Intellij will still use the `[default]` one when I run my code. AWS Explorer switches to the name profile just fine though. The `[default]` is only used when running code. 

- Version used:
This happens with plugin version 1.18-EAP.2020.08.25-202 and all previous versions.
Intellij version is 2020.2, but I get the same problem with previous ones too.

Nothing unusual about my env, this has actually never worked, the only way to make it work is to rename the named profile to `[default]`

**Comment by abrooksv** [comment]
Which file are you editing?

The `config` file and `credentials` files have slightly different syntax.

credentials:
```
[example]
aws_access_key_id = <ACCESS>
aws_secret_access_key = <SECRET>
```

config:
```
[profile example]
aws_access_key_id = <ACCESS>
aws_secret_access_key = <SECRET>
```

**Comment by abrooksv** [comment]
Sorry, misread your comment.

When running code there is a tab you select which region and credentials you want:
<img width="731" alt="Screen Shot 2020-08-25 at 3 26 27 PM" src="https://user-images.githubusercontent.com/8992246/91234063-61bf9200-e6e7-11ea-8b6d-be5aa58c79cf.png">

**Comment by abrooksv** [comment]
@Ghilteras Does that answer your question?

**Comment by abrooksv** [comment]
Closing due to no response

**Comment by zhcwang** [comment]
Hi @abrooksv , I have the same issue,  what I really want is switch profiles in AWS Explorer.
I have already add following config, e.g.
[default]
[qa]
aws_access_key_id = xxx
aws_secret_access_key =xx
[develop]
[production]

But only Profile:default in the dropdown list.

**Comment by omerxx** [comment]
@abrooksv We're trying to use profiles but only `default` works. Ignores any other given names. 
Can select them in the dropdown but the error keeps saying "Unable to locate credentials" when there's no default set

**Comment by kremkow** [comment]
+1... Having the same issue with intellij 2021.3

**Comment by schaudhry123** [comment]
@abrooksv +1 Encountering the same issue, specifically
> Can select them in the dropdown but the error keeps saying "Unable to locate credentials" when there's no default set

on PyCharm 2021.3

**Comment by yolanv** [comment]
IntelliJ 2022.1.3 and also having this issue still.

**Comment by dkblinux98** [comment]
I'm having this same problem with 2022.1.3 on new M1 mac. I've not previously had this problem. aws toolkit 1.47-221

**Comment by bin-shi-mulesoft** [comment]
Got the same issue and tried many ways. It only take the [default] one, even you have other profiles like [profile abc] in the ~/.aws/config file. The IntelliJ can recognize these profiles (see them in the dropdown list) but it doesn't take it. :(

**Comment by ArunJohnJ** [comment]
add this to VM options if we are running application with different aws profiles ->` -Daws.profile=<profile_name>` 

this worked for me and it was able to pick up the correct profile keys and secret
