### ISSUE TITLE
Security Token Issue

### ISSUE THREAD

**Issue by sarang-salvekar** [aws/aws-toolkit-jetbrains#2070]
I have been able to connect to AWS resources via Intellij IDEA + AWS Plugin. I can see AWS resources as well (like S3 buckets, Lambdas ect..). However whenever I am trying to connect to database table through java code getting exception : **The security token included in the request is invalid**

![Issue](https://user-images.githubusercontent.com/70722577/93578382-dfab4c00-f9ba-11ea-8c7a-2634b46e4e8b.jpg)

**Comment by hunterwerlla** [comment]
@sarang-salvekar Can you confirm the connection in the `AWS Connection` section of your run configuration matches the one you expect?
<img width="745" alt="Screen Shot 2020-09-18 at 8 39 32 AM" src="https://user-images.githubusercontent.com/11964782/93617205-85929280-f98a-11ea-8fa9-800ab9312406.png">

**Comment by abrooksv** [comment]
If this is a Lambda and Java8 runtime, there is currently a bug in SAM's images that makes the session token wrong if you aren't using one.

You can either:
1. Use session credentials
2. Use Java 11 to test

https://github.com/aws/aws-sam-cli/issues/2143

**Comment by sarang-salvekar** [comment]
@hunterwerlla  As you can see, List of aws objects/resources in Screenshot provided by me (Left hand upper corner) . 
I have successfully established the connection.

**Comment by sarang-salvekar** [comment]
@abrooksv  Let me try with Java 11 but in that case I need to change my code. 
My organization not yet started working on Java 11. 
As an alternative can I provide credentials via environment variable?

**Comment by sarang-salvekar** [comment]
@abrooksv  thanks issue resolved.  Local debugging used - java 11 & on AWS used EnvironmentVariableCredentialsProvider.

**Comment by ronakcshah** [comment]
@abrooksv I switched over to Java 11, it still did not resolve the issue. IntelliJ is able to pick up the credentials fine, however, running into issues when invoking it. 

![Screen Shot 2020-09-24 at 11 41 55 AM](https://user-images.githubusercontent.com/5214360/94187958-909f6400-fe5d-11ea-94e4-99a416868569.png)


Logfile -- I'm also passing the AWS credentials via --profile

`ron-mbp:G2Crowd ron$ sam local invoke --debug --profile psuser
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local invoke command is called
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='Function' and CodeUri='Function'
Found one Lambda function with name 'Function'
Invoking com.G2Crowd_Producer (java8)
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'psuser'
Resolving code path. Cwd=/Users/ron/workspace/professionalservices/Java/Internal/G2Crowd/.aws-sam/build, CodeUri=Function
Resolved absolute path to code is /Users/ron/workspace/professionalservices/Java/Internal/G2Crowd/.aws-sam/build/Function
Code /Users/ron/workspace/professionalservices/Java/Internal/G2Crowd/.aws-sam/build/Function is not a zip/jar file
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java8:rapid-1.3.0.

Mounting /Users/ron/workspace/professionalservices/Java/Internal/G2Crowd/.aws-sam/build/Function as /var/task:ro,delegated inside runtime container
Starting a timer for 900 seconds for function 'Function'
START RequestId: 0cf865fb-b50f-13f2-89b0-618d80850efd Version: $LATEST
The security token included in the request is invalid (Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: e17a58c6-cd6c-5a13-9f28-0f20277623ac): com.amazonaws.services.sqs.model.AmazonSQSException
com.amazonaws.services.sqs.model.AmazonSQSException: The security token included in the request is invalid (Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: e17a58c6-cd6c-5a13-9f28-0f20277623ac)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1742)
        at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1715)
        at com.G2Crowd_Producer.handleRequest(G2Crowd_Producer.java:50)
        at com.G2Crowd_Producer.handleRequest(G2Crowd_Producer.java:29)

END RequestId: 0cf865fb-b50f-13f2-89b0-618d80850efd
REPORT RequestId: 0cf865fb-b50f-13f2-89b0-618d80850efd  Init Duration: 2933.89 ms       Duration: 1316.49 ms    Billed Duration: 1400 ms        Memory Size: 768 MB     Max Memory Used: 102 MB     
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 5154, 'exitReason': 'success', 'exitCode': 0, 'requestId': 'e8de1c9a-998d-4d9f-9977-fa9e51b52e68', 'installationId': '75c86937-f492-4eae-b509-0e5e161be9b8', 'sessionId': '213ec4bc-b100-4301-b0e3-04111d946aaa', 'executionEnvironment': 'CLI', 'pyversion': '3.7.9', 'samcliVersion': '1.3.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

{"errorType":"com.amazonaws.services.sqs.model.AmazonSQSException","errorMessage":"The security token included in the request is invalid (Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: e17a58c6-cd6c-5a13-9f28-0f20277623ac)","stackTrace":["com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)","com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)","com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)","com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)","com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)","com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215)","com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182)","com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171)","com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1742)","com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1715)","com.G2Crowd_Producer.handleRequest(G2Crowd_Producer.java:50)","com.G2Crowd_Producer.handleRequest(G2Crowd_Producer.java:29)"]}
ron-mbp:G2Crowd ron$ 
`

**Comment by abrooksv** [comment]
@ronakcshah You are still running java8

```
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java8:rapid-1.3.0.
```

But the new images were pushed today that fixes it. You will need to remove them using docker CLI

```
docker image rm amazon/aws-sam-cli-emulation-image-java8:rapid-1.3.0
docker image rm amazon/aws-sam-cli-emulation-image-java8:latest
```

By the way, we do not monitor closed issues, please re-open for cut new issues in the future please.

**Comment by ronakcshah** [comment]
> @ronakcshah You are still running java8
> 
> ```
> Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java8:rapid-1.3.0.
> ```
> 
> But the new images were pushed today that fixes it. You will need to remove the old ones using docker CLI
> 
> ```
> docker image rm amazon/aws-sam-cli-emulation-image-java8:rapid-1.3.0
> docker image rm amazon/aws-sam-cli-emulation-image-java8:latest
> ```
> 
> By the way, we do not monitor closed issues, please re-open or cut new issues in the future please.

Noted, will open a new issue. Removing and using the new image worked! Thank you.
