### ISSUE TITLE
PyCharm SAM init with virtualenv reports "this directory is not empty"

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#2071]
Verified this happened on commits before my SAM init change, but when creating a new project with a virtualenv in Python, the IDE treats the virtualenv files it just made as "not empty". Pressing "open project" cancels the init flow and leaves the user with only the virtualenv and no sam init.

Found on Pycharm 2020.2 mac

**Screenshots**
<img width="698" alt="Screen Shot 2020-09-18 at 8 34 21 AM" src="https://user-images.githubusercontent.com/11964782/93616599-c8079f80-f989-11ea-81d3-22a5262dbfb7.png">

**Comment by hunterwerlla** [comment]
This is very difficult to fix, 
```
panel.getOrCreateSdk()?.also {
   SdkConfigurationUtil.addSdk(it)
}
```
is what actually creates the virutalenv which runs before we run the rest of the wizard. We probably need to redo how the pycharm wizard works to fix this.

**Comment by abrooksv** [comment]
This is due to we are supposed to create a PyLazySdk it seems, but....
New pycharm layer in #2131 does not have this bug
