### ISSUE TITLE
AWS Tool Kit For Scala

### ISSUE THREAD

**Issue by sarang-salvekar** [aws/aws-toolkit-jetbrains#2081]
How to debug scala lambda code using AWS Toolkit intellij idea ? 

![image](https://user-images.githubusercontent.com/70722577/93845006-e2f54f00-fcbc-11ea-9b4d-2a2b97e67e61.png)

**Comment by hunterwerlla** [comment]
Hello, we do not currently support Scala (or Kotlin), please see this issue: https://github.com/aws/aws-toolkit-jetbrains/issues/141 and this issue: https://github.com/aws/aws-toolkit-jetbrains/issues/2066 . Please +1 features you would like to see, thanks!
