### ISSUE TITLE
Get S3 object URL from context menu

### ISSUE THREAD

**Issue by liuweigeek** [aws/aws-toolkit-jetbrains#2082]
Could you guys add a feature to get the S3 object URL from the context menu? Thank you a lot!

**Comment by abrooksv** [comment]
Do you mean a presigned url?

**Comment by liuweigeek** [comment]
> Do you mean a presigned url? Or just an normal http url which would need public objects?

Both are ok, Because I'd like to upload my application package file to S3 through JetBrains AWS plugin, Then update my Lambda function by the S3 URL without open the S3 console on my browser.

**Comment by abrooksv** [comment]
Unsigned URLs have been added, created #2106 to track pre-signed

**Comment by abrooksv** [comment]
Released in 1.19
