### ISSUE TITLE
AWS Plugin Not Picking Up Credentials

### ISSUE THREAD

**Issue by erpost** [aws/aws-toolkit-jetbrains#2087]
**Describe the bug**
After installing the Toolkit for PyCharm, per the instructions (https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-toolkit.html), getting errors stating that no credentials are present

**To reproduce**
Click on the bottom tab, select a Region and profile (both are correctly picked up)
Run Python code and error is received

**Expected behavior**
The profile and region would be correctly picked up when running Python code.  In the CLI, there is no issue and the profile is picked up.

**Screenshots**

**Your Environment**
- OS: MacOS 10.15.6
- JetBrains product: PyCharm
- JetBrains product version: 2020.2.2
- AWS Toolkit version: 1.18-202
- JVM/Python version: Python 3.8.5

**Additional context**

**Comment by hunterwerlla** [comment]
Hello, do you mean you are running arbitrary python code, or running using the `lambda local` run configuration?

**Comment by erpost** [comment]
Hi, I'm running a simple Python script to list all running EC2's to test out the profile functionality, with no luck.

**Comment by abrooksv** [comment]
We currently do not support injecting the AWS credentials into arbitrary run configs.

The feature request for that is: https://github.com/aws/aws-toolkit-jetbrains/issues/926
We prototyped a bit of it in https://github.com/aws/aws-toolkit-jetbrains/commits/kiiadi/run-configuration-creds-nodejs

**Comment by psoares** [comment]
I also have an issue with credentials not being picked up, in IntelliJ (IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 14, 2020).

I tried deleting the .aws folder completely and clicked on "Edit AWS credentials". After I save the file, the plugin's refresh button remains grayed out and no credentials are available for selection.

**Comment by erpost** [comment]
> We currently do not support injecting the AWS credentials into arbitrary run configs.
> 
> The feature request for that is: #926
> We prototyped a bit of it in https://github.com/aws/aws-toolkit-jetbrains/commits/kiiadi/run-configuration-creds-nodejs

Ok, thanks.  I read this update [1] and got excited thinking there was overall support.  Looks like it might be best to move this over to #926.  It would be great to get the functionality in the future.

[1] https://aws.amazon.com/about-aws/whats-new/2020/09/now-available-aws-sso-credential-profile-support-in-aws-toolkit-for-jetbrains-ides/

**Comment by abrooksv** [comment]
We agree that it would be nice to support this.

Please +1 #926
