### ISSUE TITLE
Tool Window will not auto-hide when undocked without pointer interaction

### ISSUE THREAD

**Issue by constantology** [aws/aws-toolkit-jetbrains#2095]
First off I I want to say, thank you! This is a great plugin! 😁

I have a slight issue on WebStorm where the plugin's tool window will not automatically collapse when its view mode is set to `undock`.

In fact, the only way I can make it collapse is by clicking the tool window's `-` icon or name. 

If I try to make it hide/show using the keyboard shortcut I'd assigned to it — which works for all other tool windows — it does not work, I can't even make it focus on the tool window without using the pointer.

Apologies if this is outside of the scope of this plugin, at the same time, I thought it would be worth raising this issue here since this is the only plugin where I have this issue. If I select `View Log Streams` from the context menu of one of my lambdas, the `CloudWatch Logs` tool window will hide/show correctly with keyboard shortcuts, as will other plugins. 

Thank you for your time. 🙂

---
Toolkit: AWS Toolkit For JetBrains 1.18-202
OS: Mac OS X 10.15.6
IDE: WebStorm 2020.2.2

**Comment by hunterwerlla** [comment]
Confirmed this happens in intellij as well, that's strange.

**Comment by rli** [comment]
JetBrains appears to have fixed this now
