### ISSUE TITLE
Add Forward Proxy support for Cloud Debugger, or copy the image to the local ECR

### ISSUE THREAD

**Issue by damnhandy** [aws/aws-toolkit-jetbrains#2101]
**Is your feature request related to a problem? Please describe.**
The account my code runs in has outbound access controlled via a forward proxy. After a few attempts to get the Cloud Debugger to run, I realized the the thew debugger instance was failing with this message:

`
Status reason CannotPullContainerError: Error response from daemon: 
Get https://831759287394.dkr.ecr.us-west-2.amazonaws.com/v2/: 
net/http: request canceled while waiting for connection 
(Client.Timeout exceeded while awaiting headers))
`

The thing that was not clear from reading the documentation was that the IDE creates a new task definition that pulls a container image from another account. Our account uses private endpoints for ECS and ECR so we don't have to deal with the proxy in our local account. However, we cannot pull this image as there's no way to direct the agent to use the forward proxy or private endpoint. 

**Describe the solution you'd like**
There are a few possible solutions here:

- Add support for a Forward Proxy using `HTTP_PROXY` and `HTTPS_PROXY` environment variables somewhere in the AWS Toolkit preferences that can be passed to the Cloud Debugger task definition.  
- Add an option to copy the Cloud Debugger image to the local account, possibly using a lambda trigger. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by raducataws** [comment]
Hey Ryan, 

  Can you please provide more details on your network setup: you mentioned that your account uses private ECS and ECR endpoints which I assume are used to pull in your images. What access control policies or configurations are preventing ECS from using the same ECR endpoint to pull in the Cloud Debugger image?

Thanks, 
Radu.

**Comment by damnhandy** [comment]
Everything within our accounts restricts outbound network access to the public internet. For AWS services, we rely on public endpoints. For ECS, we have private endpoints for both ECR and ECS. For external and public internet, we route everything through a forward proxy and only permit access to specific domains. In this case, the debugger container instance resides in an ECR instance in another account, which would mean that it'd be routed through the forward proxy. Since the tooling does not support a forward proxy, it always receives a 403 response.

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
