### ISSUE TITLE
Plugin supporting feature (Run Configuration: Local) is currently not installed

### ISSUE THREAD

**Issue by cionz0** [aws/aws-toolkit-jetbrains#2102]
**Describe the bug**

A notification saying "Plugin supporting feature (Run Configuration: Local) is currently not installed" and asking for configuring plugin/ignoring unknown features appears any time Pycharm is run. Reinstalling/updating the AWS toolkit does not solve the problem. Of course, trying to run local configurations does not work.

This happens since Pycharm got updated to build py-202.7319.64.

**To reproduce**
Install suggested Pycharm/Plugin updates.

**Expected behavior**

Solve the problem.

**Screenshots**
<img width="371" alt="notification" src="https://user-images.githubusercontent.com/31845603/94271145-7fc81e80-ff41-11ea-878d-d5ea994737e1.png">
<img width="391" alt="popup" src="https://user-images.githubusercontent.com/31845603/94271147-8060b500-ff41-11ea-8b74-14b25ada23c2.png">

**Your Environment**
- OS: Mac Os Catalina 10.15.6
- JetBrains product: Pycharm
- JetBrains product version: py-202.7319.64
- AWS Toolkit version: 1.18.202
- SAM CLI version: SAM CLI, version 1.2.0
- JVM/Python version: 3.7

**Additional context**

**Comment by hunterwerlla** [comment]
Hello, I just tried it out and it works fine on my Catalina mac with the same version. I'm thinking that there is maybe another plugin that is conflicting in some way, can you provide logs? Under Help->Show Log in finder. To find AWS Toolkit related logs, search for `software.aws.toolkits`, and copy paste as much as you are comfortable with above and below. Thanks!

**Comment by cionz0** [comment]
Hi @hunterwerlla ,
don't know how and why but, at some point I closed all the open projects, closed pycharm and open it again.
Removed and installed again aws toolkit. Now it seems to work. 

What makes me feel uncomfortable is that this exact series of events already happened at least twice.

Please find logs.

[Archivio.zip](https://github.com/aws/aws-toolkit-jetbrains/files/5284048/Archivio.zip)

**Comment by hunterwerlla** [comment]
Hello, I'm not sure what these files are, sorry I forgot to specify. I'm looking for `idea.log`, thanks!

**Comment by rli** [comment]
Closing due to age. Please open a new issue if this is still a problem
