### ISSUE TITLE
MariaDB instance not listed in AWS Explorer

### ISSUE THREAD

**Issue by tunecrew** [aws/aws-toolkit-jetbrains#2132]
AWS Toolkit 1.19-202
DataGrip 2020.2.3
MacOS 10.15.7

Toolkit installed and correct region and credentials selected (IAM user with AdministratorAccess).

I have a MariaDB instance running in RDS.

AWS Explorer shows all of my resources in the region, e.g. CloudFormation, ECS, Lambda, etc. except in the RDS section it lists Aurora, MySQL and PostgreSQL (all say "empty"). There is no MariaDB listing at all. No other error messages or anything in the DataGrip console.

<img width="370" alt="Screenshot 2020-10-08 at 8 18 21 AM" src="https://user-images.githubusercontent.com/3431633/95463839-e2a4b700-093e-11eb-9f38-fb2bbe873111.png">

Is MariaDB supported? Am I missing a configuration step?

**Comment by hunterwerlla** [comment]
@tunecrew We currently don't list MariaDB (or SQL Server) because they do not support [IAM auth](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Availability). SecretsManger auth would work if we showed it, would you find that useful?

**Comment by tunecrew** [comment]
@hunterwerlla Thanks- is IAM auth support on the roadmap for MariaDB instances? My understanding is that there's not a huge amount of difference between MariaDB and MySQL at the API level. I don't use SecretsManager so no opinion there.

**Comment by abrooksv** [comment]
We will pass on the request for IAM auth in MariaDB to the service team.
