### ISSUE TITLE
Enabling cloud debugging fails, unable to update load balancer

### ISSUE THREAD

**Issue by d13g0** [aws/aws-toolkit-jetbrains#2149]
**Describe the bug**
Trying to enable cloud debugging in PyCharm 2020.2.2 with the AWS Toolkit 1.19-202

**To reproduce**
1. I select the service `dev-sense` in my ECS cluster `dev-ecs`

2. Select the option: Enable Cloud Debugging (Beta)

3. I see a warning: Unable to validate role. It may not work with cloud debugging:Error: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_- (Service: Iam, Status Code: 400, Request ID: f10e9efd-2fed-47df-973f-ab8f8474c898, Extended Request ID: null)

4. The name of the role seems to be ok: `dev_sense_task_role` but for some reason this appears in PyCharm as `ecs/dev_sense_task_role`.

5. I click on `OK`

**Expected behavior**

After few minutes, cloud debugging is enabled

**Screenshots**

<img width="1440" alt="Screen Shot 2020-10-16 at 4 16 18 PM" src="https://user-images.githubusercontent.com/976342/96304914-fac5a780-0fca-11eb-9340-a5b32c038052.png">

[PyCharm-log-aws-toolkit.txt](https://github.com/aws/aws-toolkit-jetbrains/files/5394099/PyCharm-log-aws-toolkit.txt)

**Your Environment**
- OS:  MacOS Catalina 10.15.6
- JetBrains product: Pycharm 
- JetBrains product version:2020.2.2
- AWS Toolkit version:1.19-202
- SAM CLI version: unknown
- JVM/Python version: 3.7

**Additional context**
None

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
