### ISSUE TITLE
using source

### ISSUE THREAD

**Issue by flyinprogrammer** [aws/aws-toolkit-jetbrains#2153]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment]
No content, I assume duplicate of #2154

**Comment by flyinprogrammer** [comment]
correct, how does chrome work, and how did this even get auto-submitted? need more :coffee:
