### ISSUE TITLE
i installed sam 1.6.2 but its not compatible with intellij,,

### ISSUE THREAD

**Issue by nagdommeti** [aws/aws-toolkit-jetbrains#2159]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: mac catalina 10.15.7
- JetBrains product: IntelliJ IDEA 2019.2.3 (ultimate edition)
- JetBrains product version:
- AWS Toolkit version: 1.15
- SAM CLI version: 1.6.2
- JVM/Python version:

**Additional context**
error - Invalid sam executable
Bad sam executable version. Expected 0.47.0 < version < 0.60.0 but was 1.6.2

**Comment by hunterwerlla** [comment]
@nagdommeti Hello, you have a very old version of the AWS Toolkit, we dropped support for 2019.2 a few months ago. Please update your version of Intellij to 2019.3 or above (preferably 2020.1+) for it to work with SAM 1.0+
