### ISSUE TITLE
Context menu should activate on differently named templates

### ISSUE THREAD

**Issue by sdole** [aws/aws-toolkit-jetbrains#2166]
At the moment, I must name my cloudformation file "template.yaml" for intellij context menu to activate the "Deploy Serverless Application" menu item. I should be able to deploy serverless application from any file name as per my project's and company's conventions.

---
Toolkit: AWS Toolkit For JetBrains 1.19-202
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 2020.2.3

**Comment by hunterwerlla** [comment]
Hello, currently we only check for name because we have no concept of what is a CloudFormation template/a random yaml file. In the long term we are planning on improving that, but would you find a good short term solution to be able to deploy templates from the `CloudFormation` node?
