### ISSUE TITLE
Upload an EAP Version for 2020.3 to Idea Plugins

### ISSUE THREAD

**Issue by MCMicS** [aws/aws-toolkit-jetbrains#2199]
**Question**
It is possible to create an EAP for 2020.3 EAP (or Beta) Version

_Build #IU-203.5784.10, built on November 10, 2020_

Thanks

**Comment by abrooksv** [comment]
Hi @MCMicS,

We just merged the initial 2020.3 support on Friday (https://github.com/aws/aws-toolkit-jetbrains/pull/2142). The only way to get it right now is to build master branch manually.

**Comment by MCMicS** [comment]
ok
thanks. is there any schedule to publish to EAP channel?

**Comment by abrooksv** [comment]
> ok
> thanks. is there any schedule to publish to EAP channel?

To our EAP channel (https://plugins.jetbrains.com/plugins/eap/aws.toolkit)? Not yet, but we are slowing getting all the required pieces in place.

**Comment by MCMicS** [comment]
OK thanks for the info

**Comment by abrooksv** [comment]
@MCMicS 

We only create EAP builds once a day and when we alter our changelog, so I have created #2206 to trigger that process. I am still stabilizing 203 (#2204, #2203), but you can track #2206

**Comment by abrooksv** [comment]
1.21 has been released with 2020.3 support
