### ISSUE TITLE
1.21-202 Update Function Code not working

### ISSUE THREAD

**Issue by dinnerdeal** [aws/aws-toolkit-jetbrains#2231]
Firstly, hats off to you for fixing by far THE MOST ANNOYING slow down ever with this version:  the delay in loading the S3 buckets when updating lambda code.  So thank you for that!

Unfortunately the action updating of the function code itself isn't working

It looks like the bundling/packaging phase is happening as well as uploading to S3, but it looks like something must be off during deploy as the I'm not longer able to find the lambda function ("Class not found" in cloud watch)

I've noticed the different packaging flow in this release.  Previous version would package the code as <function_name>.zip and that's what I see in my s3.  This new version packages as a random filename without an extension, ie: bf25534aeebf850d38d63255a38d03bb

I've reverted back to 1.20-202 for the time being, but am back in S3 loading hell :(

**Comment by abrooksv** [comment]
The new name for the S3 key is expected due to switching to using SAM CLI for the packaging / upload.

**Comment by abrooksv** [comment]
What language is your Lambda?

**Comment by dinnerdeal** [comment]
Java 8

**Comment by KFerkPerf** [comment]
Seems this is more because of how lambda is packaged in general. Previously it's the build as it should be but new plugin version uses the project root as CodeURI and uploaded package contains the whole project, not compiled sources and libs.

**Comment by abrooksv** [comment]
We are actively looking into this issue.

**Comment by hunterwerlla** [comment]
This will be in our next release, as well as our EAP that is going out tonight. Please try out the EAP if you get time, thanks!

**Comment by abrooksv** [comment]
Here is a direct link to our EAP build for 2020.2 with the bug fix: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/eap/103473

**Comment by dinnerdeal** [comment]
EAP Build is confirmed to be working for me!  Fantastic!  Thanks for the quick turnaround!

**Comment by KFerkPerf** [comment]
Yeah, looks good! Thanks!

**Comment by hunterwerlla** [comment]
@dinnerdeal @KFerkPerf thanks for reporting and confirming the fix works! We are looking to get this released soon

**Comment by abrooksv** [comment]
Release is out
