### ISSUE TITLE
Pycharm IDE crash on creating new serverless project 

### ISSUE THREAD

**Issue by altlifelab** [aws/aws-toolkit-jetbrains#2234]
Attempt to create a new serverless project . The IDE crashes. with the following error "**nsions.impl.ExtensionPointImpl - java.lang.AssertionError: Background task can't be run under write action**"

**To reproduce**

1. Open Pycharm IDE
2. Click on "New Project" 
3. Choose the AWS serverless template option
4.  Click next 
5. The IDE creates the folder, but crashes. 

- OS: Windows 10 Pro
- JetBrains product: Pycharm Community Edition 2020.2.3
- JetBrains product version: 2020.2.3
- AWS Toolkit version: 1.21-202
- SAM CLI version: 1.12.0
- JVM/Python version: Python 3.9
[Pycharm crash log.txt](https://github.com/aws/aws-toolkit-jetbrains/files/5599992/Pycharm.crash.log.txt)

**Additional context**

**Comment by hunterwerlla** [comment]
I was not able to reproduce this using 2020.2.4 and 1.21-202. In 1.22, we updated how this wizard worked, so please give it another try!

**Comment by altlifelab** [comment]
Thanks a lot for your response. After many attempts, I decided to uninstall Pycharm and reinstall it. That has fixed the issue. It is working well, now.
