### ISSUE TITLE
Just Thanks!

### ISSUE THREAD

**Issue by RokolyA94** [aws/aws-toolkit-jetbrains#2256]
It's a good feature, but when I put more than 1 profile into the config, I cannot change it. I must reload the tool. 
I think hot change can be more comfortable. 
But thanks for this. :) 

---
Toolkit: AWS Toolkit For JetBrains 1.22-203
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 2020.3

**Comment by abrooksv** [comment]
Both of those things should be supported. Does the combo box at the top of the AWS Explorer tool window (or status bar `AWS:` only list one option?

There is a difference between the `~.aws/config` and `~/.aws/credentials` files so make sure that you have them correct.

The config file must have all non-`default` profiles prefixed with profile:
ie.

```
[profile foo]
...
...

[profile bar]
...
```

while the credentials file lacks the word "profile"
