### ISSUE TITLE
Local Lambda debug not stopping on breakpoints

### ISSUE THREAD

**Issue by DavidCockerill** [aws/aws-toolkit-jetbrains#2274]
**Describe the bug**
When debugging Lambdas locally the debugger is not stopping, it just executes the function in full. Bug started after updating AWS toolkit plugin. 

**To reproduce**
- Add a breakpoint
- Run local debug

**Expected behavior**
IDE should stop at breakpoint

**Your Environment**
- OS: macOS Catalina
- JetBrains product: WebStorm
- JetBrains product version: 2020.3
- AWS Toolkit version: 1.22-203
- SAM CLI version: 1.13.2
- JVM/Python version:

**Comment by abrooksv** [comment]
To confirm, is this with a Node based runtime?

**Comment by DavidCockerill** [comment]
Yes

**Comment by abrooksv** [comment]
Are you running using a handler based run config, or a template file?

**Comment by DavidCockerill** [comment]
template file

**Comment by DavidCockerill** [comment]
`Invoking getRegions.lambdaHandler (nodejs12.x)
Building image..............
Skip pulling image and use local one: samcli/lambda:nodejs12.x-9eaa1117c9fdf3a9c7bbf820d.

Mounting /Users/Desktop/cloud_services/.aws-sam/build/getRegions as /var/task:ro,delegated inside runtime container
START RequestId: 5bdb503a-9931-4bef-8af9-5275852cd614 Version: $LATEST
Debugger listening on ws://0.0.0.0:61248/6b59016a-b1ad-4baa-8618-be9967b6ce8c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2020-12-08T22:26:54.103Z	5bdb503a-9931-4bef-8af9-5275852cd614	INFO	HDBRequestWithRetry: 324.377ms
END RequestId: 5bdb503a-9931-4bef-8af9-5275852cd614
REPORT RequestId: 5bdb503a-9931-4bef-8af9-5275852cd614	Init Duration: 0.13 ms	Duration: 2773.83 ms	Billed Duration: 2800 ms	Memory Size: 192 MB	Max Memory Used: 192 MB	
{"body":[{"label":"US West (N. California)","__updatedtime__":1603921852033,"value":"us-west-1","__createdtime__":1603921852033},{"label":"US East (N. Virginia)","__updatedtime__":1603921852033,"value":"us-east-1","__createdtime__":1603921852033},{"label":"US West (Oregon)","__updatedtime__":1603921852033,"value":"us-west-2","__createdtime__":1603921852033},{"label":"US East (Ohio)","__updatedtime__":1603921852033,"value":"us-east-2","__createdtime__":1603921852033}]}
Aborted!`

**Comment by DavidCockerill** [comment]
I get this output

**Comment by DavidCockerill** [comment]
The regions data can be ignored, my lambda is pulling it from my db.

**Comment by abrooksv** [comment]
Looks like its a path mapping regression since the debugger is attaching.

**Comment by DavidCockerill** [comment]
Is that something on my end that I can fix?

**Comment by abrooksv** [comment]
No, we dont expose that setting to users. What does your handler definition look like in the template?

**Comment by DavidCockerill** [comment]
`  getRegions:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getRegions.lambdaHandler
      Runtime: nodejs12.x
      Layers:
        - !Ref UtilsLayer
        - !Ref ConstructorsLayer
      CodeUri: getRegions/
      Description: ''
      MemorySize: 192
      Timeout: 120
      FunctionName: getRegions
      Role: 'arn:aws:iam::75012345678:role/getRegionsRole'`

**Comment by rdt712** [comment]
The breakpoints work if you add them to the js files within the .aws-sam/build directory. It doesn't work if you try adding them to the original source files outside of that directory. I don't think this is the intended functionality based on how debugging works in the other supported languages, but it is a work around until someone fixes it.

**Comment by DavidCockerill** [comment]
Thanks Ryan, I ended up installing an older version of AWS toolkit and that fixed it.

**Comment by abrooksv** [comment]
What version did you roll back to?

**Comment by DavidCockerill** [comment]
Webstorm 2020.2.4
AWS Toolkit 1.20-202

**Comment by rdt712** [comment]
> getRegions:
> Type: 'AWS::Serverless::Function'
> Properties:
> Handler: getRegions.lambdaHandler
> Runtime: nodejs12.x
> Layers:
> - !Ref UtilsLayer
> - !Ref ConstructorsLayer
> CodeUri: getRegions/
> Description: ''
> MemorySize: 192
> Timeout: 120
> FunctionName: getRegions
> Role: 'arn:aws:iam::75012345678:role/getRegionsRole'

@DavidCockerill Not related, but you may want to edit out your AWS account number for safety reasons

**Comment by DavidCockerill** [comment]
It's a fake number, thanks though

**Comment by spdaly** [comment]
Any ETA on a fix? I'm on the latest JetBrains versions and cannot install 1.20-202.

**Comment by abrooksv** [comment]
@spdaly I have not had a chance to try to build a project that can reproduce the issue yet.

**Comment by hunterwerlla** [comment]
I seem to be able to replicate this running based on a template but not based on a handler, will investigate further

**Comment by christoph-zero** [comment]
I can reproduce the problem and I think the issue isn't solved yet.
Breakpoints are getting hit only while setting them on files under the .aws-sam/build directory like @rdt712 described.

Environment details:
 - IntelliJ 2021.3.2
 - aws-cli/2.4.16
 - SAM CLI, version 1.37.0
 - Lambda runtime: NodeJS 14

**Comment by gmarshall56** [comment]
I guess AWS Toolkit is not the way to go.  It appears this issue is not being addressed.  What a big disappointment.   Could've really use the debugger.

I have the same problem:
AWS Toolkit version 1.46-221
IntelliJ IDEA 2022.1.3 Build #IU-221.5921.22, built on June 21, 2022
aws-cli/2.4.15 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
SAM CLI, version 1.53.0

**Comment by dnorton** [comment]
@gmarshall56 same... did you find a work around since debugging in AWS Toolkit doesn't work? I suppose I could run
`sam local invoke 'Function' -d {port}' and then attach a remote debugger.

**Comment by gmarshall56** [comment]
Breakpoints are working for me now:
AWS Toolkit 1.20-223
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    aws.toolkit (1.60-223)

Kotlin: 223-1.8.0-release-345-IJ8617.56

**Comment by rrodionov1991** [comment]
Same for me. Could you please reopen ticket and plan the fix?
