### ISSUE TITLE
Add Environment Variables with 'From template' option

### ISSUE THREAD

**Issue by AMcManigal** [aws/aws-toolkit-jetbrains#2282]
**Your Environment**

- OS: macOS Catalina
- JetBrains product: PyCharm
- JetBrains product version: 2020.3
- AWS Toolkit version:1.22-203
- SAM CLI version: 1.62
- JVM/Python version: 3.8.6

**Question**

I recently upgraded to the latest version of AWS Toolkit. Now when I use the 'From template' option in the 'Run/Debug Configurations' screen I can't see an option to add environment variables. It does appear if I use 'From handler' instead but then I lose the ability to run a function with layers. 

Is there a way to add environment variables with the 'From template' option? This could be done in AWS Toolkit version 1.16-193.

Thanks.

**Comment by rdt712** [comment]
You can do it in the run config by going to the SAM CLI tab and adding the `--env-vars` or `-n` flags and the absolute path to your `env.json` file in the local invoke args section.

**Comment by abrooksv** [comment]
Sorry for the inconvenience, it was removed as we re-did the UI and it was deemed confusing given the current UX and the actual limitations of SAM:

In handler mode, you could add any env vars you wanted, but in template mode, only env vars defined in the template would actually be overridden and that was not explained to the user leading to confusion.

We can look into fixing that UI to reveal that limitation. @rdt712 is correct on the current work around.

**Comment by kiiadi** [comment]
I also think what might be useful is an "import from remote lambda" feature for both template and handler modes - this would allow us to point at a remote Lambda function and automatically import the environment variables from it. Handy when you have environment variables that are populated by refs' in cfn/cdk.
