### ISSUE TITLE
Not letting me enter authentication code

### ISSUE THREAD

**Issue by balane** [aws/aws-toolkit-jetbrains#2287]
When I open the explorer it shows the link to enter AWS authentication code but when I click it the explorer refreshes and shows the different products but all say Access Denied.
---
Toolkit: AWS Toolkit For JetBrains 1.22-EAP.2020.12.02-203
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 2020.3

**Comment by abrooksv** [comment]
Do you mean the MFA auth code?

**Comment by balane** [comment]
Yes

**Comment by abrooksv** [comment]
Please see #2254, the profiles have to be written in a certain way to comply with the SDKs (CLI has slightly different behavior)

**Comment by balane** [comment]
I reduced my config file to this (removed several other profiles) and it still doesn’t work

[default]
region = us-east-1
mfa_serial=arn:aws:iam::812653080533:mfa/<email>
duration_seconds=3600

[profile sandbox]
source_profile=default
role_arn=arn:aws:iam::420998087895:role/managed-role/XXXXXAcctAdmin
mfa_serial=arn:aws:iam::812653890533:mfa/<email>
duration_seconds=3600

**Comment by balane** [comment]
It seems the MFA Auth popup will only show up for my projects that contain lambdas.

**Comment by abrooksv** [comment]
The contents of the account would not affect it, all SDKs use the same logic to retrieve the credentials.

Can you share your config and credentials files with profile keys using fake data so I can see what the profiles look like?

**Comment by balane** [comment]
Yeah, I don’t know what changed but today it’s working. I did install the new version of IDEA EAP?

**Comment by balane** [comment]
I take that back. MFA popup still doesn’t appear for projects without lambdas. Obviously there’s something else about these projects but no idea what it would be.

**Comment by abrooksv** [comment]
Hey Brad, I tried to reproduce this and was not able to. See gif for what I tried:

![MfaRepro](https://user-images.githubusercontent.com/8992246/102652189-8ae6b100-4122-11eb-9561-9027eeada2c5.gif)

Is this matching the the flow you tried?

**Comment by balane** [comment]
Okay, seeing you select different profiles made me realize it was happening when I hadn’t selected a profile and it was using the ‘default’ profile. The projects that are lambdas had the correct profile selected already. Sorry for the confusion and thanks for the help.

**Comment by abrooksv** [comment]
No problem, glad we got it working for you.
