### ISSUE TITLE
packageType parameter not supported in updateFunctionConfiguration

### ISSUE THREAD

**Issue by mattcaruso** [aws/aws-toolkit-jetbrains#2301]
**Describe the bug**
Since updating PyCharm to 2020.3 and updating the AWS Toolkit plugin along with it, I've been getting an error preventing me from updating the Lambda function configuration. 

`The packageType parameter is not supported in the updateFunctionConfiguration request. Service: Lambda, Code: 400`

**To reproduce**
1. Open the AWS Toolkit sidebar in PyCharm.
2. Right click on a Lambda function.
3. Click "Update configuration..."
4. Make any change in the dialog
5. Click "update" to see the error message.

**Expected behavior**
Expect the function's settings to update without error.

**Screenshots**
<img width="793" alt="Screen Shot 2020-12-21 at 10 01 12 AM" src="https://user-images.githubusercontent.com/6909800/102790577-a1377b80-4373-11eb-997d-726f4c7ebf54.png">

**Your Environment**
- OS: macOS 10.15.7
- JetBrains product: PyCharm
- JetBrains product version: 
```
PyCharm 2020.3 (Community Edition)
Build #PC-203.5981.165, built on December 1, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.tooltip.initialDelay=802
Non-Bundled Plugins: aws.toolkit, ru.meanmail.plugin.requirements
```
- AWS Toolkit version: 1.22-203
- SAM CLI version: 
- JVM/Python version: Python 3.7.6

**Additional context**
Around the same time, I also noticed that new deploys of my Lambda functions no longer overwrite the existing .zip in my S3 bucket and instead upload a new file with a UUID. 

<img width="1046" alt="Screen Shot 2020-12-21 at 10 05 29 AM" src="https://user-images.githubusercontent.com/6909800/102790856-1d31c380-4374-11eb-8547-1d0c61392dfb.png">

**Comment by abrooksv** [comment]
I believe this is fixed by https://github.com/aws/aws-toolkit-jetbrains/commit/dca58264645349900ca114b9c8f3dbb641542dd0#diff-3b6d5e110d2f1609032c179445e39e40bf76f1a531416cbada8f93023b4ceb75 and is pending release

**Comment by mattcaruso** [comment]
Excellent!! I had a feeling this was known but had a tough time finding other bugs on it. 

Is there a timeline for the release?

**Comment by abrooksv** [comment]
A release to our stable channel won't be until the new year.
I am working on trying to get our build stable enough to get a build to our EAP channel but not sure how much work is left to get it passing all tests.

**Comment by abrooksv** [comment]
I am still trying to fix our UI tests...

If this is blocking you, you can manually download a our SNAPSHOT build from our CI reports. Here is the latest commit build for 2020.3

https://d1ihu6zq92vp9p.cloudfront.net/ce8453db-e043-4d12-a428-5aa9cc99d5dd/report.html

The plugin artifact is a zip inside of a zip, only extract the outer zip and in the IDE plugins page, hit the gear and select Install from Disk and select the inner zip.
