### ISSUE TITLE
Invalid sam executable error when starting a new AWS project in IntelliJ

### ISSUE THREAD

**Issue by grgkro** [aws/aws-toolkit-jetbrains#2310]
**Describe the bug**
I want to use IntelliJ to create an AWS Lambda function, so I want to create a new AWS Serverless project in IntelliJ like described here:
https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/key-tasks.html#key-tasks-first-connect

I get following error, when I click on "File -> new-> new project -> AWS -> AWS Serverless Application -> Next -> Finish":
"Cannot save settings: Invalid sam executable: <html>Bad sam executable version. Expected 0.47.0 &le; version &lt; 0.60.0 but was 1.15.0.</html> Upgrade your AWS Toolkit plugin to resolve this issue."

I couldn't find a way to upgrade the Toolkit plugin, so I deinstalled it and reinstalled it. The version is 1.15. I also reinstalled the AWS SAM CLI
with following version:
 
C:\Users\Boommeister69>sam --version
SAM CLI, version 1.15.0

So they have the same version, but the error stayes the same.

**To reproduce**

1. In IntelliJ go on: "File -> new-> new project -> AWS -> AWS Serverless Application -> Next -> Finish"

**Expected behavior**
To create a new project

**Screenshots**
![image](https://user-images.githubusercontent.com/56633505/103135793-38c20480-46bb-11eb-9d22-6c1229d14b85.png)

**Your Environment**
- OS: Windows 10
- JetBrains product: IntelliJ IDEA 2019.2.4 Community Edition
- AWS Toolkit version: 1.15-192
- SAM CLI version: 1.15.0

**Comment by abrooksv** [comment]
The current minimum supported IDE version is 2020.1
 You will need to update the IDE to get newer updates.

**Comment by grgkro** [comment]
This solved it, thanks ; )
