### ISSUE TITLE
Run/Debug Icons Flicker

### ISSUE THREAD

**Issue by mousedownmike** [aws/aws-toolkit-jetbrains#2311]
**Describe the bug**

With the AWS Toolkit plugin enabled, I will have intermittent flashing of the run/debug icons.

**To reproduce**

1. Install AWS Toolkit Plugin v 1.22-203
2. Load IDEA with a project that has at least one Run/Debug icon.
3. Type fairly rapidly in the editor.
4. Observe, the Run/Debug icon changes from a "Disabled" state to an "Enabled" state briefly.

**Expected behavior**

The icon should not flicker.

**Screenshots**

Note that it doesn't matter what icon is in the Run/Debug menu.
![Peek 2020-12-28 12-28](https://user-images.githubusercontent.com/47116171/103256146-fad61200-4940-11eb-98b5-06c6eb7e0538.gif)
![Peek 2020-12-28 18-38](https://user-images.githubusercontent.com/47116171/103256155-0295b680-4941-11eb-8247-9670f9f63b44.gif)

**Your Environment**
```
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Subscription is active until June 24, 2021
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1892M
Cores: 8
Registry: dart.projects.without.pubspec=true
Non-Bundled Plugins: com.intellij.plugins.watcher, org.intellij.plugins.hcl, org.toml.lang, Dart, io.flutter, com.intellij.plugins.html.instantEditing, org.jetbrains.kotlin, intellij.prettierJS, com.dmarcotte.handlebars
Current Desktop: ubuntu:GNOME
```

**Additional context**

I originally opened this issue with JetBrains here: https://youtrack.jetbrains.com/issue/IDEA-258623

**Comment by rli** [comment]
I can reproduce without the toolkit installed, so I don't think this is a toolkit issue

**Comment by mousedownmike** [comment]
@rli Thank you for adding your experience to the JetBrains issue.  I was able reproduce the issue when I had the AWS Toolkit installed but it appeared to go away when I removed the plugin.

I thought I caught a glimpse of the issue again with it not installed but could not consistently reproduce it.  It sounds like you can and your added context in the issue is appreciated.

 I'm going to keep this issue open a little longer in case it helps get any more input from the community.

**Comment by mousedownmike** [comment]
If anyone else comes here, you can find the (currently open) JetBrains ticket here: https://youtrack.jetbrains.com/issue/IDEA-258623
