### ISSUE TITLE
CloudDebug can not pull amberwing-sidecar image from ECR

### ISSUE THREAD

**Issue by flo-mair** [aws/aws-toolkit-jetbrains#2318]
**Describe the bug**
Cloud Debug Sidecar Container can not be pulled from ECR.
CannotPullContainerError: Error response from daemon: pull access denied for 831759287394.dkr.ecr.us-west-2.amazonaws.com/amberwing-sidecar, repository does not exist or may require 'docker login': denied

**To reproduce**
1. Deployed Python app with fronting ALB to ECS
2. Setup Task Role according to documentation (Added AmazonSSMManagedInstanceCore to role)
3. Configured AWS Toolkit credentials (tested with AdministratorAccess)
4. Enabled Cloud Debug
The ECS Service for clouddebug never stabilises as the sidecar image cannot be pulled from ECR. Error:

**CannotPullContainerError: Error response from daemon: pull access denied for 831759287394.dkr.ecr.us-west-2.amazonaws.com/amberwing-sidecar, repository does not exist or may require 'docker login': denied**

**Expected behavior**

Successfully enable CloudDebug

**Screenshots**

**Your Environment**
- OS: macOS 10.15.7
- JetBrains product: PyCharm
- JetBrains product version: 2020.2.5
- AWS Toolkit version: 1.22-202
- SAM CLI version:
- JVM/Python version: 3.8

![Screenshot 2021-01-05 at 14 02 49](https://user-images.githubusercontent.com/61224241/103649417-b4933b00-4f5e-11eb-8ab6-dc010d5a4092.png)

![Screenshot 2021-01-05 at 14 04 20](https://user-images.githubusercontent.com/61224241/103649553-f7551300-4f5e-11eb-82c0-aabba9ae0132.png)

**Comment by flo-mair** [comment]
When pulling the docker image manually: 
Error response from daemon: Get https://831759287394.dkr.ecr.us-west-2.amazonaws.com/v2/amberwing-sidecar/manifests/1.0: no basic auth credentials

**Comment by rli** [comment]
Just to confirm, does your **task execution role** (as opposed to task role) on the task definition have the `AmazonECSTaskExecutionRolePolicy` managed policy attached?

**Comment by flo-mair** [comment]
@rli that was indeed the issue. 
I used the AWS CDK ECS Pattern construct, to create the role implicitly. The attached policy allowed the correct actions but had some resource constraints by default.
Thanks for the quick help!
