### ISSUE TITLE
Can't enter MFA token

### ISSUE THREAD

**Issue by jakobbraun** [aws/aws-toolkit-jetbrains#2324]
Hi,
I have an issue with entering my MFA token.

I've configured my `.aws/credentials` files as:
```
[default]
aws_access_key_id =  XXX 
aws_secret_access_key =  XXX
mfa_serial = arn:aws:iam::XXX:mfa/MyUser
```

After starting IDEA the AWS explorer shows the following view:

![grafik](https://user-images.githubusercontent.com/18247545/103867161-2d150b80-50c7-11eb-8945-b7e906d8ae78.png)

But when I click on `Enter MFA code` it directly shows the explorer and no dialog. In the explorer, I get `AccessDeniedExcptions` for most resources since our account is configured to block access if not MFA was used.

![grafik](https://user-images.githubusercontent.com/18247545/103867387-8d0bb200-50c7-11eb-86b1-5905e5e8e84e.png)

I would expect a dialog for entering my token.

Have I missed something?

**Comment by abrooksv** [comment]
The toolkit requires you to assume a role to use mfa:

```
[profile mfa]
source_profile=default
role_arn=...
mfa_serial = arn:aws:iam::XXX:mfa/MyUser
```

**Comment by abrooksv** [comment]
The fact that the messaging shows needing MFA is a bug in the heuristic to determine if we auto login. It is not indicative that we support it.

Does the CLI support the profile you provided?

**Comment by rli** [comment]
Closing due to age. Please open a new issue if this is still a problem.
