### ISSUE TITLE
Copy message contents from CloudWatch Logs

### ISSUE THREAD

**Issue by genachka** [aws/aws-toolkit-jetbrains#2333]
Using IntelliJ IDEA 2020.3.1 and AWS Toolkit 1.22-203. When I right click on Lambda function within the AWS Explorer and select `View Log Streams` and then open a specific stream, it has two columns, `Time` and `Message`. It used to be that I could right click on a row and there was a copy option which used to give me just the message contents for that row. Now right click on a row only has an option for `Show Logs Around`. If I use keyboard shortcut to copy (Ctrl+C) I get the entire row contents.

It would be very useful to have the right click popup menu have copy put back and to be able to right click and be able to have option to copy the entire row or option for that row's cell that was clicked on. As right now I have to take extra time each time to remove the extra data copied.

**Comment by hunterwerlla** [comment]
Hello, you should be able to box select just messages and copy just messages. Can you check if that works?

**Comment by abrooksv** [comment]
@hunterwerlla We fixed that for CFN but not CW Logs

**Comment by abrooksv** [comment]
Commit: https://github.com/aws/aws-toolkit-jetbrains/commit/679faa8a852b537a20b91ccda28e3b37e4ae0f66
