### ISSUE TITLE
Cloud Debug does not work with breakpoints

### ISSUE THREAD

**Issue by flo-mair** [aws/aws-toolkit-jetbrains#2334]
**Describe the bug**
I have a python app (flask restful) running in ECS. The debug functionality mostly works (shows logs, debugger can be paused,...) but unfortunately it does not respect Breakpoints or Code Changes i made locally. 

**To reproduce**
1. Enable Debugger
2. Make local changes / set breakpoint
3. Changes are not reflected within the container

**Expected behavior**
Working breakpoints and code reload

**Screenshots**

**Your Environment**
- OS: macOS 10.15.7
- JetBrains product: PyCharm
- JetBrains product version: 2020.2.1
- AWS Toolkit version: 1.22-202
- SAM CLI version:
- JVM/Python version: 3.8

**Comment by justinmk3** [comment]
Did you configure the path mappings?

**Comment by flo-mair** [comment]
Yes I configured the correct path

**Comment by abrooksv** [comment]
The debugger must be restarted, it will copy over modified files since the last restart, and then proceed to restart the python process.
