### ISSUE TITLE
Fail to run cloud debug enabled task

### ISSUE THREAD

**Issue by emaayan** [aws/aws-toolkit-jetbrains#2351]
**Describe the bug**
After enabling cloud debug for a task of ECS  the new cloud debug task failed to run due to script exiting with code 1.

**To reproduce**

 1.  create an ECS task with cloud debug enabled  

**Expected behavior**
task with debug is running as normal 

**Your Environment**
- OS: windows 10
- JetBrains product: intelij commercial 
- JetBrains product version: 2020.3 
- AWS Toolkit version: 1.23-EAP.2021.01.12-203
- JVM/Python version: 8 

**Additional context**
the logs indicate failure the to create 

[08:20:04-D] Failed to ensure that the root dir '/aws/cloud-debug/apps/container' exists: 'mkdir /aws/cloud-debug/apps: permission denied'
--
 
is it possible because the DockerFile is running with non root user? 

FROM openjdk:8u212-b04-jre-slim-buster

ARG PORTS='1411 4096 4100 61617 61616 12092/udp 12091/udp  1511/udp 1144/udp 8082 8099 9005 22 35000 443 8443 8883'
ARG USER='aeroscout'
ARG GROUP='aeroscout'
ARG UID=1001
ARG GID=1001
EXPOSE $PORTS

ARG VOL=/opt/aeroscout
ARG VER
ENV TERM xterm
ENV SHELL /bin/bash

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
ENV DEBIAN_FRONTEND noninteractive
#RUN printf '#!/bin/bash\nexit 0' > /usr/sbin/policy-rc.d

# because wrapper script specifies it needs to run as user
RUN addgroup --gid $GID $GROUP
RUN adduser  --shell /bin/bash --disabled-password --gecos '' --uid $UID --gid $GID $USER
RUN echo 'aeroscout ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/aeroscout;
RUN chmod 440 /etc/sudoers.d/aeroscout;

RUN mkdir $VOL
RUN chmod -R 0775 $VOL
RUN chown -R $UID:$GID $VOL

VOLUME $VOL

LABEL engversion=$VER
COPY maven/* /opt/AeroScoutService
USER $USER
CMD ["/opt/AeroScoutService/run/entrypoint.sh"]

**Comment by abrooksv** [comment]
I have forwarded this on to the service team

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
