### ISSUE TITLE
AWS Toolkit is not being installed on RubyMine

### ISSUE THREAD

**Issue by shqear93** [aws/aws-toolkit-jetbrains#2357]
**Describe the bug**
AWS Toolkit is not being installed

**To reproduce**
1. Open RubyMine
2. Go to plugins
3. Install AWS Toolkit
4. Restart RubyMine
5. AWS Toolkit still not installed

**Expected behavior**
AWS Toolkit to be installed or at least raise an error

**Screenshots**

**Your Environment**
- OS: macOS Big Sur / 11.1 (20C69)
- JetBrains product: RubyMine
- JetBrains product version: 2020.3.1 #RM-203.6682.166
- AWS Toolkit version: 1.22-203
- SAM CLI version: not installed
- JVM/Python version: not installed

**Additional context**

**Comment by hunterwerlla** [comment]
@shqear93 I was unable to reproduce this with a fresh install of Rubymine 2020.3.1 on my mac. The only weird thing was I did not get a restart notification on install. Can you try installing it from the splash page and waiting a few seconds to restart?

**Comment by shqear93** [comment]
@hunterwerlla sorry for reporing this, It was not installing for some reason, but it worked suddenly and it's most probably after I restart the machine.
Thank you very much
