### ISSUE TITLE
"Failed to load N profiles" dialogue is too noisy

### ISSUE THREAD

**Issue by l0b0** [aws/aws-toolkit-jetbrains#2408]
**Is your feature request related to a problem? Please describe.**

I'm using short-lived AWS authentication tokens, and more than one profile. Whenever I log into the account I'm working on IDEA pops up a dialogue mentioning how many profiles I have and how many of them failed to load because I'm not ever logged into all of them at once. This is distracting.

**Describe the solution you'd like**

It should be possible to hide this dialogue forever.

**Describe alternatives you've considered**

Uninstalling the plugin.

**Comment by abrooksv** [comment]
I am sorry you are experiencing this issue.

1. The "Failed to load" notification indicates that the profiles are written in a way the toolkit does not understand them, not that the credentials are invalid/expired.

Is there a type of credential profile that you use that the toolkit does not understand?

2. The notification can be turned off using the standard IntelliJ settings. Here is a screen shot of where it is located:
<img width="756" alt="Screen Shot 2021-02-02 at 9 33 09 PM" src="https://user-images.githubusercontent.com/8992246/106703040-46ae5380-659e-11eb-91ba-ebd034a3c081.png">

Looking at this in our code, we should split this more noisy pop-up from our other notifications. I can make that change but it will mean you will need to re-edit the setting when it is released.

**Comment by l0b0** [comment]
Thank you for the thorough reply @abrooksv! I'm using `aws-azure-login` to create credentials. Or do you mean the contents of ~/.aws/config?

**Comment by abrooksv** [comment]
I'm curious about the contents of the profiles that the toolkit is complaining about, what are the list of property keys in the profile?

**Comment by rli** [comment]
Looks like [it writes](https://github.com/sportradar/aws-azure-login/blob/main/src/configureProfileAsync.ts#L62-L69):
```
  azure_tenant_id
  azure_app_id_uri
  azure_default_username
  azure_default_role_arn
  azure_default_duration_hours
  azure_default_remember_me
```

**Comment by abrooksv** [comment]
> Looks like [it writes](https://github.com/sportradar/aws-azure-login/blob/main/src/configureProfileAsync.ts?rgh-link-date=2021-02-03T19%3A43%3A57Z#L62-L69):
> 
> ```
>   azure_tenant_id
>   azure_app_id_uri
>   azure_default_username
>   azure_default_role_arn
>   azure_default_duration_hours
>   azure_default_remember_me
> ```

Ah, ya if thats all the keys then toolkit will fail on them. Makes sense.

**Comment by steinsag** [comment]
I'm having the same problem. I only have 2 profiles defined. Here the content of my files in ~/.aws/*. I'm experiencing this problem with:

Toolkit: AWS Toolkit For JetBrains 1.23-203 AND also with 1.24-EAP.2021.02.09
OS: Linux 5.8.0-43-generic
IDE: PyCharm Professional Edition 2020.3.3

my ~/.aws/config:

    [default]
    output = json
    region = eu-central-1

my ~/.aws/credentials:

    [profile1]
    aws_access_key_id = SOME_AWS_KEY_1
    aws_secret_access_key = SOME_SECRET_1
    [profile2]
    aws_access_key_id = SOME_AWS_KEY_2
    aws_secret_access_key = SOME_SECRET_2

I created both profiles via AWS CLI:

    aws configure --profile=profile1

How can I fix that?
