### ISSUE TITLE
No stop button (Ctrl + F2)?

### ISSUE THREAD

**Issue by sdole** [aws/aws-toolkit-jetbrains#2418]
**Describe the bug**
Developers must have ability to stop a lambda function execution with the red stop button or the Ctrl + F2 combination (default IntelliJ keystroke)
**To reproduce**
I hit Shift F9 key stroke on IDEA to debug the last lambda function that I wanted to. However, I had forgotten to start the docker service on my computer before doing so. There is no way to stop the sam build or attempted execution. Further, instead of failing gracefully, I just got an IDE error as follows:
```I hit Shift F9 key stroke on IDEA to debug the last lambda function that I wanted to. However, I had forgotten to start the docker service on my computer before doing so. ```

**Expected behavior**
I should be able to stop by pressing a red stop button or the ctrl + F2 key stroke.
**Screenshots**
![image](https://user-images.githubusercontent.com/3978930/106963487-4630cc80-6706-11eb-86a2-129add37ed90.png)

**Your Environment**
- OS: Windows 10
- JetBrains product: IntelliJ IDEA
- JetBrains product version: latest
- AWS Toolkit version: 1.23-203
- SAM CLI version: latest
- JVM/Python version: 3.8

**Additional context**

**Comment by abrooksv** [comment]
Thank you for this bug report. It looks like we have 2 issues:

1. StepExecutor for SAM Build in the Build tool window lacks stop button. 
2. The Docker validate is throwing the wrong type of exception, it needs to be an ExecutionException (or at least caught and remapped to it)
