### ISSUE TITLE
AWS Toolkit Recognizes credentials file but not region.

### ISSUE THREAD

**Issue by GratefulDave** [aws/aws-toolkit-jetbrains#2437]
**Your Environment**

- OS: Big Sur 11.2.1
- JetBrains product Pycharm
- JetBrains product version: 2020.3
- AWS Toolkit version: Latest version. 
- AWS CLI: 2.1.26
- SAM CLI version:  1.18.1
- JVM/Python version: 3.9.1
The SAM CLI & AWS CLI 

**Question**

I have AWS Explorer installed on PyCharm. I use `aws configure --profile profile_name` to configure two sets of credentials as follows with sensitive information intentionally left blank.

```
[proa]
aws_access_key_id = ...
aws_secret_access_key = ...
[mrr_fd_prod]
aws_access_key_id = ...
aws_secret_access_key = ...
```

```
[profile proa]
region = us-east-2
output = json
[profile mrr_fd_prod]
region = us-east-2
output = json
```

When I change the profile in AWS Explorer between two different projects, the lambda function list is properly populated with the respective lambda functions of that AWS instance & region. When I try running a local script, I get a `botocore.exceptions.NoRegionError: You must specify a region.` error.  Prior to uninstalling AWS CLI 1.0 & installing AWS CLI 2.0 everything was working properly.

I have also tried setting AWS_DEFAULT_REGION & AWS_REGION env variables to us-east-2 and am encountering the same error. Each of these projects has its own virtual environment.

**Comment by abrooksv** [comment]
Are you referring to the region is not set when a script is executed through the IDE?

**Comment by abrooksv** [comment]
We don't inject the toolkits region / credentials into any running scripts today (it is an open feature request #926), so I do not think anything the toolkit is doing would be causing the behavior you are seeing.

**Comment by GratefulDave** [comment]
I am not getting errors for invalid credentials. I am getting an error for not specifying the region. This happened after I removed AWS CLI 1.0 via the instructions on AWS and installed AWS CLI 2.0 via brew. Both projects have separate virtual environments. 

Why would the IDE recognize the proper credentials/region for AWS Explorer and not locally during runtime? Why would it pick up the proper profile & region since they are recognized in AWS Explorer?

**Comment by abrooksv** [comment]
The toolkit does not leverage the AWS CLI nor boto (We are built upon the Java SDK V2), so it is hard to say. I do know that IntelliJ (or PyCharm in this case) caches environment variables so any changes to them will require a restart of the IDE.

I do not see any changes in https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html that may indicate the change in behavior.

**Comment by GratefulDave** [comment]
It looks like it may be a PATH or venv issue. I try to run a local script in a venv and I get the same error. I will post this somewhere else. Thank you for your help.

**Comment by GratefulDave** [comment]
For some reason, I am able to change credentials in PyCharm and they are reflected properly, but the current virtualenv does not reflect those changes properly. Why would AWS Explorer recognize the credentials, but not the local virtualenv?

**Comment by abrooksv** [comment]
The IDEs view of the world does not write any data back to your profile file, so changes to the IDE are not reflected in a terminal session or program executed through the IDE.

If this is not what you mean, can you please clarify

**Comment by rli** [comment]
Closing since this ticket is describing the "connected execution" feature, which is now active by default
