### ISSUE TITLE
Flag --s3-bucket is not used in SAM deploy to avoid template size limit error

### ISSUE THREAD

**Issue by jeremyc11** [aws/aws-toolkit-jetbrains#2440]
When a project's template reaches the 51,200 bytes size limit we can't have the deployment/change set done using the UI as it errors.

An issue was already opened in the past: #1973 and the bug should be fixed in version 1.18. But I'm using the version 1.20 and it still occur.

My Environment:
- AWS Tooltip version: 1.20 (2020-10-22)
- PyCharm Community Edition 2019.3.4 on Windows
- SAM CLI, version 0.47.0

![image](https://user-images.githubusercontent.com/69188912/108212315-63b65b00-7136-11eb-8821-6cf5944871eb.png)

**Comment by hunterwerlla** [comment]
You are running a very old version of SAM cli, please try updating to a newer version. We have a test for this scenario and only one path where we call it from, so I think it's probably the versions of SAM cli.

**Comment by jeremyc11** [comment]
I updated my SAM cli to 1.18.1 and Pycharm to Community 2020.3.3 and indeed the issue no more occur. thanks.

**Comment by hunterwerlla** [comment]
@jeremyc11 thanks for confirming!
