### ISSUE TITLE
No module named 'app'

### ISSUE THREAD

**Issue by RegisBouchard** [aws/aws-toolkit-jetbrains#2451]
Hi,

I am new to AWS functionalities. I followed the guide in order to be able to install the AWS toolkit.
My objective would be to debug locally a lambda function with layers import (to run the function)

I am using

    PyCharm 2020.3.3 (Community Edition)
    Windows 10 10.0 Pro
    AWS Toolkit 1.24-203

I tried to use the HelloWorldFunction template to test the functionalities and modified the function to import layers from my amazon account.
- The Amazon SciPy1x package
- A Layer_for_testing:1 where the `function3` module which run numpy package in the Scipy amazon layer to return a cosinus

**When I execute the program locally using the terminal**
sam build --template --template.yaml
then
sam local invoke -e events\event.json

Everything works fine:

    The .aws-sam is successfully build
    The layers imported in the AppData\Roaming\AWS SAM folder.
    The event.json used to run the function and print in the terminal the right return

![image](https://user-images.githubusercontent.com/79322681/108633929-4d323b80-7477-11eb-8568-eb0d25d6324d.png)
![image](https://user-images.githubusercontent.com/79322681/108633922-44da0080-7477-11eb-9540-0ad145e8bdd5.png)

**When I execute is through the PyCharm IDE**

![image](https://user-images.githubusercontent.com/79322681/108633946-5ae7c100-7477-11eb-8d69-d8b2b5a9312f.png)

The SAM build is executed successfully, but then it returns "No module named 'app', as if the asm build could not locate the packages when invoking the function...
(I previously installed the packages with "sam local invoke -e events\event.json" and didn't delete the folders)
![image](https://user-images.githubusercontent.com/79322681/108634071-2b858400-7478-11eb-9698-901129d9691f.png)

Best regards,

Régis

**Comment by hunterwerlla** [comment]
Hello, it seems like your app.py is outside of your base directory (`CodeUri: hello_world`). To fix this, move app.py to the folder hello_world or change your `CodeUri` to `.`. Since we know the logical id `HelloWorldFunction`, we are actually running `sam build HelloWorldFunction --template --template.yaml` which only builds that one function for speed.

**Comment by RegisBouchard** [comment]
Hello,

Thank you for the quick reply.

It works, thank you.

So we can move the app (lambda_handler) wherever we wants as soon as we identify the location in the "Code:" properties ?

In this case, what is the root directory and how is it identify in the code ? I mean, we run locally from the app.py, why do we need to move to the `.` directory in that case ?

![image](https://user-images.githubusercontent.com/79322681/108834835-ed4ea880-75ce-11eb-98cd-c7710ad05caf.png)

**Comment by RegisBouchard** [comment]
So how we know what SAM CLI consider the code or how can we check (like a syspath) ?

**Comment by hunterwerlla** [comment]
`CodeUri` determines is what is considered the code. Putting things outside of it can work, but code is not intended to be outside of the `CodeUri` folder.

**Comment by RegisBouchard** [comment]
I understand. But when you put `.` instead of `hello_world`. How is it interpreted as `hello_world` root directory since you don't declare anymore the `hello_world` folder.
The question is how the template identify the sys.path as `Layered_Hello_World` in this example when we type `.` in the `CodeUri`. Is it relatively to the template location ?

**Comment by hunterwerlla** [comment]
Ah, yes. `CodeUri` is relative to the template, so `.` specifies the same folder as the template.
