### ISSUE TITLE
Error: JavaGradleWorkflow:GradleBuild - Gradle Failed: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by SethCaparelli** [aws/aws-toolkit-jetbrains#2459]
**Describe the bug**
I am trying to run a Lambda function locally but encounter this error:
```Error: JavaGradleWorkflow:GradleBuild - Gradle Failed: java.io.FileNotFoundException: /var/folders/cw/lh6dgn356yv0vbpn0jv3_yq1lkf0sn/T/tmpbwzo305g/0697b551eaba49ef04e4747a4ec665697f66ac45/build/jacoco/test.exec (No such file or directory)```

Gradle builds the project successfully when there are no test classes, but when test classes are present the build error is thrown.

**Your Environment**
- OS: Catalina
- JetBrains product: IntelliJ Ultimate 
- JetBrains product version: 2020.3
- AWS Toolkit version: 1.24-203
- SAM CLI version: 1.18.2

**Comment by rli** [comment]
What I've noticed with `sam build`, is on the default Jacoco configuration is that jacoco-agent is passed a destination with a strange-looking relative path (`../../../var/folders.../build/jacoco/test.exec`), which it doesn't seem to like. Running the jacoco agent manually results in: `*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422`

I'm not sure what's causing this to occur, but explicitly setting the jacoco destination file resolves the issue:
```
test {
    jacoco {
        destinationFile = file("$buildDir/jacoco/${name}.exec")
    }
}
```

**Comment by SethCaparelli** [comment]
Amazing thank you!
