### ISSUE TITLE
Can I debug my lambda using basic AWS Serverless (Not SAM)

### ISSUE THREAD

**Issue by 6Hhcy** [aws/aws-toolkit-jetbrains#2482]
I have an app created with AWS Serverless (using: serverless.yaml, package.json, "sls deploy", etc.) 

I would like to debug my lambdas locally using this plugin. Is this possible?

Thank you

**Comment by abrooksv** [comment]
It depends. We can run a Lambda without a template (we generate a minimum one under the hood), but we still require that the code can be built by SAM. For a NodeJS lambda, SAM CLI should run a `npm pack` on it.

If that works for your use case, than the plugin should work.

**Comment by 6Hhcy** [comment]
Thank you. I don't know what the difference is between SLS CLI and SAM CLI. I suspect they are close.
