### ISSUE TITLE
Validate docker fails to find docker program , even thought i have docker-desktop running

### ISSUE THREAD

**Issue by emaayan** [aws/aws-toolkit-jetbrains#2489]
**Describe the bug**
when attempting to debug a local lambda intelij throws and error
Validate Docker has failed: Cannot run program "docker": CreateProcess error=2, The system cannot find the file specified

**To reproduce**

 1. create a new sample project for aws lambda 
 2. execute the launch config  (enter some random input)
 3. the build output errors will show 
 Validate Docker has failed: Cannot run program "docker": CreateProcess error=2, The system cannot find the file specified2 has failed: Cannot run program "docker": CreateProcess error=2, The system cannot find the file specified
 

**Expected behavior**
to launch a docker debug session

**Your Environment**
- OS:  windows 10
- JetBrains product: intelij idea 
- JetBrains product version: 2020.3.2
- AWS Toolkit version: 1.125-203
- SAM CLI version: 1.20
- JVM/Python version: 8

**Additional context**

**Comment by abrooksv** [comment]
Hi,

Is the docker executable on your `%PATH$?` Also, if you installed it after starting the IDE, you will need to restart the IDE for it to pick up the updated env vars since they are cached.

**Comment by emaayan** [comment]
Yea, i think you can close this, docker was installed before intelij yet,
intelij came up with a different path then my machine , and i don't know
why.

**Comment by abrooksv** [comment]
Okay, glad you found the reason.
