### ISSUE TITLE
Cannot find Node Interpreter if using NVM (Linux) to manage Node Versions. What is a workaround?

### ISSUE THREAD

**Issue by lvignals** [aws/aws-toolkit-jetbrains#2508]
**Describe the bug**
Cannot find Node Interpreter if using NVM (Linux) to manage Node Versions.

**To reproduce**
0) Prior to installing any version of Node and prior to installing NVM all any node version must be uninstalled from the system.
1) Install NVM on Ubuntu machine or other Linux distro.
2) Install a version of Node compatible with Lambda using NVM (currently v10, v12 or v14).
3) In Webstorm: File > New Project
4) Select: AWS Serveless Application
5) Select Runtime: nodejs12.x for example
6) Select SAM Template: AWS SAM HelloWorld
7) Select Node Interpreter: This is were the problem starts!!!

Node versions installed with NVM will be listed in Node Interpreter pick-list like that:
~/.nvm/versions/node/v12.x.x/bin/node
- However if you try to select one of those values and wait for a few seconds the value will be automatically deselected and returned to No Interpreter value. 
- If you ignore that and proceed then it is not possible to build locally, instead the following error emitted:

- Build Failed
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL

** Environment**
- OS: Ubuntu 18.04
- JetBrains product: Webstorm
- JetBrains product version: Latest as of March 17 2021
- AWS Toolkit version: Latest as of March 17 2021
- SAM CLI version: Latest as of March 17 2021
- JVM/Python version: No JVM installed / System Python is 2.7.17

**Comment by lvignals** [comment]
As a work around it is possible to select a specific version of now and ignore nvm by manually selecting node binary inside .nvm directory but that has the potential to create some conflicts since the Toolkit plugin and Terminal app may be relying on different node versions.

**Comment by abrooksv** [comment]
Hey @lvignals,

Sorry for not getting back to you faster. We offload this entire process to the IDE's framework so I do not think we are doing anything that would be causing this behavior.

I believe @hunterwerlla also uses NVM (but on Mac) without issues.

It may be that the IDE's view of the environment variables differs from your terminal's.

This is possible to check, but required debug logs and reading the IDE's log file

>If you go to Help->Diagnostic Tools->Debug Log Settings... and paste #com.intellij.execution.configurations.GeneralCommandLine, and try again, debug lines will show in the idea.log (Help->Show logs in finder...)

>Search for GeneralCommandLine in the log

**Please do not upload the logs, the debug log can contain sensitive info when ran in debug mode.**

**Comment by rli** [comment]
Closing in favor of https://github.com/aws/aws-toolkit-jetbrains/issues/3063
