### ISSUE TITLE
Environment Vars from Template Incorrectly Display In Run Config

### ISSUE THREAD

**Issue by AMcManigal** [aws/aws-toolkit-jetbrains#2509]
**Describe the bug**
Environment variables in the Run/Debug configuration are overwritten with the SAM template variables upon saving and closing the window for configurations loaded from the template. However the values are actually saved in the run config. They just aren't loaded correctly.

**To reproduce**
1. Set up a run configuration for locally running a Lambda and load the configuration from a SAM template. Ensure that the function has an environment variable defined in the template.
2. Overwrite an environment variable value that was loaded from the template with a new value.
3. Click OK to save the configuration and close the window.
4. Go back into the  run configuration screen. The old value from the template will have replaced itself.

**Expected behavior**
I expected the IDE to save the override values I entered so that template environment values could be overridden. However, since it does not I have no choice but to hardcode the variables directly into the template.

**Screenshots**
1. The function defined in the template.
![Template Configuration](https://user-images.githubusercontent.com/1545624/111683671-68306b00-87eb-11eb-8bbe-0335c0b61908.png)
2. The generated run configuration.
![Original Run Config](https://user-images.githubusercontent.com/1545624/111683785-8c8c4780-87eb-11eb-850e-604e3bb05485.png)
3. The variable is set to 120
![Setting the variable to a different value](https://user-images.githubusercontent.com/1545624/111684012-cd845c00-87eb-11eb-805c-4d19e16bb670.png)
4. After clicking OK and returning to the run config the original value has been restored.
![After clicking OK and going back into the run configuration](https://user-images.githubusercontent.com/1545624/111684184-002e5480-87ec-11eb-86ce-ba606ff009b6.png)
5. Code
![Screen Shot 2021-03-18 at 1 30 50 PM](https://user-images.githubusercontent.com/1545624/111685777-ef7ede00-87ed-11eb-8124-2eb9389a797a.png)
5. However when the code runs it uses the saved value.
![Screen Shot 2021-03-18 at 1 30 58 PM](https://user-images.githubusercontent.com/1545624/111685813-f9084600-87ed-11eb-89d9-d5ea58e1f30a.png)

**Your Environment**
- OS: Catalina 10.15.7
- JetBrains product: PyCharm
- JetBrains product version: PyCharm 2020.3.3
- AWS Toolkit version: 1.25-203
- SAM CLI version:  1.19.1
- JVM/Python version:java 11.0.4 2019-07-16 LTS/Python 3.8.8

**Comment by abrooksv** [comment]
Thanks for the bug report, I see the problem.
