### ISSUE TITLE
Failed to start the SSM port forwarding session

### ISSUE THREAD

**Issue by ilangrs** [aws/aws-toolkit-jetbrains#2518]
**Your Environment**

- OS: Windows 10
- JetBrains product: Pycharm 
- JetBrains product version: CE 2020.3.4
- AWS Toolkit version:  1.25-203
- SAM CLI version: 1.21.1
- Python version: 3.9

**Question**

Hi,
I'm trying to enable remote debugging on ECS.

I followed the following guide:

[https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html](url)

Unfortunately, when I try to debug I'm getting the following message:

 errors":["failed to enable debugging on ECS service name='dev_package_builder', cluster='dev_ecs_cluster' with iamRole='arn:aws:iam::801862747872:role/dev_pb_task_assume_role20200219095754578400000005', debugEntrypoint='' and restartCmd=''","failed to connect to the 'cloud-debug-dev_package_builder' service from the 'dev_ecs_cluster' cluster","failed to connect to the cloud-debug-dev_package_builder instrumented service from the dev_ecs_cluster cluster","failed to create an SSM session for the dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc target","dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc is not connected.","failed to start the SSM port forwarding session","failed to create session for 'dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc'","http request failed with response '\u0026{400 Bad Request 400 HTTP/1.1 1 1 map[Content-Length:[343] Content-Type:[application/json; charset=utf-8] Date:[Mon, 22 Mar 2021 08:20:37 GMT]] 0xc000386440 343 [] false false map[] 0xc0000da400 \u003cnil\u003e}'"]}
Error details:
	- failed to enable debugging on ECS service name='dev_package_builder', cluster='dev_ecs_cluster' with iamRole='arn:aws:iam::801862747872:role/dev_pb_task_assume_role20200219095754578400000005', debugEntrypoint='' and restartCmd=''
	- failed to connect to the 'cloud-debug-dev_package_builder' service from the 'dev_ecs_cluster' cluster
	- failed to connect to the cloud-debug-dev_package_builder instrumented service from the dev_ecs_cluster cluster
	- failed to create an SSM session for the dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc target
	- dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc is not connected.
	- failed to start the SSM port forwarding session
	- failed to create session for 'dev_ecs_cluster_5e089befebd44dca82d16b2c9b4dc06f_567b51d3e6d0518d7dad71ec2b116c1d8357c58660fb2431edb283137bb7d5cc'
	- http request failed with response '&{400 Bad Request 400 HTTP/1.1 1 1 map[Content-Length:[343] Content-Type:[application/json; charset=utf-8] Date:[Mon, 22 Mar 2021 08:20:37 GMT]] 0xc000386440 343 [] false false map[] 0xc0000da400 <nil>}'
Configure cloud-debug-dev_package_builder for Cloud Debugging has failed: Command did not complete successfully[dev_ecs_cluster] cloud-debug-dev_package_builder (beta)-7 has failed: Command did not complete successfullyCleaning up application in dev_package_builder has failed: Required element AttributeBagKey(key=targetMapping) not found in AttributeBagCleaning up applications has failed: Required element AttributeBagKey(key=targetMapping) not found in AttributeBagDisable forwarding remote port 32755 in dev_package_builder to local port 59756 has failed: Required element AttributeBagKey(key=targetMapping) not found in AttributeBagCleaning up port forwarding has failed: Required element AttributeBagKey(key=targetMapping) not found in AttributeBag

I assume there's an issue with SSM port mapping.
SSM is working when I try to run it manually.

Is there anything else I can do?
Did I miss something?

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
