### ISSUE TITLE
Cloudformation stack events not updated after reaching terminal state

### ISSUE THREAD

**Issue by manodnyab** [aws/aws-toolkit-jetbrains#2519]
**Describe the bug**

Cloudformation stack events not updated after a final/complete stage has been reached.

**To reproduce**

1) Open the stack window.
2) Delete the stack.
3) Observe the stack events

**Expected behavior**

The event status should be updated.

**Comment by hunterwerlla** [comment]
We already have an issue for this: https://github.com/aws/aws-toolkit-jetbrains/issues/2180
