### ISSUE TITLE
ECS Cloud Debug _not_ detecting that the role **has** the required permissions 

### ISSUE THREAD

**Issue by dennisroche** [aws/aws-toolkit-jetbrains#2585]
**Describe the bug**

JetBrains Rider fails to detect ECS task role for cloud debug has the required permissions

**To reproduce**

1. Followed guide https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html#ecs-task-role to create ECS task role to enable cloud debug.
2. Verified that the deployed role has `AmazonSSMManagedInstanceCore` managed policy is attached
3. Checked https://github.com/aws/aws-toolkit-jetbrains/blob/03f0f7cd1682f1712765ef6539ac1195a6351fe5/jetbrains-core/src/software/aws/toolkits/jetbrains/services/clouddebug/actions/InstrumentDialog.kt#L114 and
4. Confirmed that `ssmmessages:*` permissions attached to the role (they are included in `AmazonSSMManagedInstanceCore` managed policy but also added as an inline policy to be certain)

    ```
    "ssmmessages:CreateControlChannel",
    "ssmmessages:CreateDataChannel",
    "ssmmessages:OpenControlChannel",
    "ssmmessages:OpenDataChannel"
    ```

**Expected behavior**

Expect not to see the below error: `Role does not appear to have the required permissions...`

**Screenshots**

![role](https://user-images.githubusercontent.com/4949392/117286021-44a8a900-ae9b-11eb-8c8b-7b65707a1fe4.png)

**Your Environment**

- OS: Windows 10 10.0
- JetBrains product: JetBrains Rider
- JetBrains product version: 2021.1.2 (Build #RD-211.7142.19, built on April 22, 2021)
- AWS Toolkit version: 1.26-211
- SAM CLI version: N/A (not installed?)
- JVM/Python version: N/A

**Additional context**

It would be clearer if the `Click here for more information` deep linked to https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html#ecs-task-role (i.e. the part specifically about the ECS task role)

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
