### ISSUE TITLE
v1.27 - Typescript Example

### ISSUE THREAD

**Issue by masanaikeshima** [aws/aws-toolkit-jetbrains#2617]
- OS: MacOS BigSur 11.3
- JetBrains product: PHPStorm
- JetBrains product version: 2021.1.2
- AWS Toolkit version: 1.27
- SAM CLI version: 1.19.1
**Question**

Within the changelog of v1.27 there is a new feature for supporting running and debugging Typescript Lambdas. This sounds like a great feature but there doesn't seem to be much information on how we would go about using this.

Can anyone share how a basic example could be used so I can explore this further?

Thanks,

**Comment by abrooksv** [comment]
There is one in the AWS Serverless Application group in the IDE's New Project wizard, but only for Node12 right now

<img width="913" alt="Screen Shot 2021-06-01 at 8 41 29 AM" src="https://user-images.githubusercontent.com/8992246/120352083-48222b00-c2b5-11eb-991a-10729a877f6f.png">

**Comment by abrooksv** [comment]
@rli Is there anything special with raw lambda mode? Is it still just the handler path relative to `package.json` (e.g. `src/lib::handle`)?

**Comment by rli** [comment]
it should be the handler relative to tsconfig.json

**Comment by masanaikeshima** [comment]
> There is one in the AWS Serverless Application group in the IDE's New Project wizard, but only for Node12 right now, though it should be straight forward to upgrade to 14
> 
> <img alt="Screen Shot 2021-06-01 at 8 41 29 AM" width="913" src="https://user-images.githubusercontent.com/8992246/120352083-48222b00-c2b5-11eb-991a-10729a877f6f.png">

Ah this is great, thanks for pointer!
