### ISSUE TITLE
Overriding debug-port set by aws-toolkit when debugging lambda locally

### ISSUE THREAD

**Issue by Pol52** [aws/aws-toolkit-jetbrains#2638]
**Your Environment**

- OS: Windows 10 19042.985
- JetBrains product: Intellij Idea
- JetBrains product version: 2021.1.2
- AWS Toolkit version: 1.27-211
- SAM CLI version: 1.24.0
- Node version: 12

**Question**

I am trying to debug a node-based lambda locally but I can't attach to the debugger because the --debug-port options is set by aws-toolkit.
I have tried overriding it by using `--debug-port 5858` in the Local Invoke Args but the toolkit executes the following command and it does not accept my port:
`
C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" local invoke Function --template .aws-sam\build\template.yaml --event "C:\Users\utente\AppData\Local\Temp\[Local] Function-event2855.json" --debug-port 60940 --debug-port 5858
`

If I run `sam local invoke --debug-port 5858` manually, I can correctly debug the code.
Can anyone point me in the right direction on how to solve this?

**Comment by abrooksv** [comment]
Why do you need to attach manually? The toolkit is supposed to auto-start the debugger

**Comment by Pol52** [comment]
Yes, I actually see that, even if I don’t run a separate node debugger that
listens on a port, some other debugger attaches to the process. However in
that situation, no breakpoint is triggered, the lambda just runs to the
end, and I can’t debug.

So I tried with a separate debugger.

**Comment by abrooksv** [comment]
Sounds like a path mapping issue, would it be possible to build a minimal example that shows the same behavior?

**Comment by Pol52** [comment]
Thanks for helping,you pointed me in the right direction!
I was running the function in the docker container but I had previously run npm install without specifying the linux platform while on windows and I had some files missing in .bin/node_modules which were most likely causing some path mapping issues.

I rerun npm install with --platform=linux and I got the debugger working!
