### ISSUE TITLE
[0.5] Design: Update service/resource icons with new branding

### ISSUE THREAD

**Issue by nickkova4** [aws/aws-toolkit-jetbrains#265]
**Is your feature request related to a problem? Please describe.**
Yes, we need to update the Lambda icons to match new AWS branding. The icons marketing created for us for the overall app (e.g. Lambda) and it's child resources (e.g. apps and functions) need to communicate the proper hierarchical relationship. We also need to gauge the designs for the extension icons as they appear in the IDE panels. Finally we want the other icon instances covered [here](https://quip-amazon.com/ndV3ATiAUmiO) to be addressed. 

**Describe the solution you'd like**
New icons work well with the IDE in light and dark modes and on retina screens. 

**Describe alternatives you've considered**
We have considered having no icons and only using text.

**Additional context**
N/A

**Comment by abrooksv** [comment]
Fixed overlooked New Lambda icon: #293
