### ISSUE TITLE
Run->Debug [Local] HelloWorldFunction fails

### ISSUE THREAD

**Issue by autohandle** [aws/aws-toolkit-jetbrains#2662]
**Describe the bug**

Run->Debug [Local] HelloWorldFunction fails

**To reproduce**
Create the default hello world function:
Run->Run [Local] works
Run->Debug [Local] fails

**Expected behavior**

**Screenshots**

Configuration: Python 3.8
Build: from template
SAM configuration: inside a container

docker ps
/usr/local/homebrew/bin/sam build HelloWorldFunction --template /Users/david/Documents/amazonws/lambda/python/CrudInImage/template.yaml --build-dir /Users/david/Documents/amazonws/lambda/python/CrudInImage/.aws-sam/build --use-container
Starting Build inside a container
Building codeuri: /Users/david/Documents/amazonws/lambda/python/CrudInImage runtime: None metadata: {'DockerTag': 'python3.7-v1', 'DockerContext': '/Users/david/Documents/amazonws/lambda/python/CrudInImage/hello_world', 'Dockerfile': 'Dockerfile'} functions: ['HelloWorldFunction']
Building image for HelloWorldFunction function
Setting DockerBuildArgs: {} for HelloWorldFunction function
Step 1/4 : FROM public.ecr.aws/lambda/python:3.7
 ---> 23efe277ce24
Step 2/4 : COPY app.py requirements.txt ./
 ---> Using cache
 ---> 824a8db1bc33
Step 3/4 : RUN python3.7 -m pip install -r requirements.txt -t .
 ---> Using cache
 ---> 76da82dfb4d5
Step 4/4 : CMD ["app.lambda_handler"]
 ---> Using cache
 ---> 893ae41eaac9
Successfully built 893ae41eaac9
Successfully tagged helloworldfunction:python3.7-v1

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
    
/usr/local/homebrew/bin/sam local invoke HelloWorldFunction --template /Users/david/Documents/amazonws/lambda/python/CrudInImage/.aws-sam/build/template.yaml --event "/private/var/folders/41/y2p9txvd1tn65h_d42f2ffs80000gq/T/[Local] DefaultHelloWorld-event11.json" --debugger-path /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev --debug-args "**/var/lang/bin/python3.8** -u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 54330 --file /var/runtime/bootstrap.py" --debug-port 54330
Invoking Container created from helloworldfunction:python3.7-v1
Building image.........
Skip pulling image and use local one: helloworldfunction:rapid-1.23.0.

START RequestId: 305ac130-fb27-43f2-b7e1-00be75712965 Version: $LATEST
time="2021-06-18T17:06:01.106" level=error msg="Init failed" InvokeID= error="Couldn't find valid bootstrap(s): [**/var/lang/bin/python3.8**]"
time="2021-06-18T17:06:01.106" level=error msg="INIT DONE failed: Runtime.InvalidEntrypoint"

**Your Environment**
- OS: MacOs 11.4 Big Sur
- JetBrains product: PyCharm
- JetBrains product version: 2021.1.2
- AWS Toolkit version: 1.27.211
- SAM CLI version:1.23.0
- JVM/Python version: Python 3.8.5

**Additional context**

**Comment by abrooksv** [comment]
It looks like you built the image for Python 3.7:

"helloworldfunction:python3.7-v1"

but in the Run Configuration Python 3.8 is selected.

They have slightly different settings:
```
class Python37ImageDebugSupport : PythonImageDebugSupport() {
    override val id: String = LambdaRuntime.PYTHON3_7.toString()
    override fun displayName() = LambdaRuntime.PYTHON3_7.toString().capitalize()
    override val pythonPath: String = "/var/lang/bin/python3.7"
    override val bootstrapPath: String = "/var/runtime/bootstrap"
}

class Python38ImageDebugSupport : PythonImageDebugSupport() {
    override val id: String = LambdaRuntime.PYTHON3_8.toString()
    override fun displayName() = LambdaRuntime.PYTHON3_8.toString().capitalize()
    override val pythonPath: String = "/var/lang/bin/python3.8"
    override val bootstrapPath: String = "/var/runtime/bootstrap.py"
}
```
