### ISSUE TITLE
AWS::Serverless::LayerVersion when AWS::Serverless::Function/PackageType: Image

### ISSUE THREAD

**Issue by autohandle** [aws/aws-toolkit-jetbrains#2664]
if i define an image resource:

  ReadByIdFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      **Layers:
        - !Ref SharedMongoLayer
        - !Ref SharedDockerLayer**
      Events:
        ReadById:
          Type: Api
          Properties:
            Path: /read/{Id}
            Method: get
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./read
      Dockerfile: Dockerfile

with Layers, this works if i am using a zip, but fails if i am using an image. the Layers are created & mounted during the build:

**Building layer 'SharedMongoLayer'**
Fetching public.ecr.aws/sam/build-python3.7:latest Docker container image......
Mounting /Users/david/Documents/amazonws/lambda/python/SharedMongo as /tmp/samcli/source:ro,delegated inside runtime container
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
**Building layer 'SharedDockerLayer'**
Fetching public.ecr.aws/sam/build-python3.7:latest Docker container image......
Mounting /Users/david/Documents/amazonws/lambda/python/SharedDocker as /tmp/samcli/source:ro,delegated inside runtime container

but the python imports fail. i looked at the sys.path:
read.appRead.py.sys.path: ['/var/task', '/opt/python/lib/python3.7/site-packages', '/opt/python', '/var/runtime', '/var/lang/lib/python37.zip', '/var/lang/lib/python3.7', '/var/lang/lib/python3.7/lib-dynload', '/var/lang/lib/python3.7/site-packages', '/opt/python/lib/python3.7/site-packages', '/opt/python']

and printed all the directories on the sys.path & sure enough the Layers afren't on the path.

i could user a pointer to some documentation, so i can get this working. in the meantime, i'll move the Layers code to the requirements.txt file & see if pip will import them for me.

**Comment by abrooksv** [comment]
Sorry, I am not familiar with the nuances of layers and images in Lamda. You could try asking the SAM team over at aws/aws-sam-cli
