### ISSUE TITLE
confused about: --container-env-var

### ISSUE THREAD

**Issue by autohandle** [aws/aws-toolkit-jetbrains#2666]
**Question**
when it says:
Environment variables to pass to the build container.

if i pass via sam build:
--container-env-var ReadByIdFunction.GITHUB_TOKEN=TOKEN1 --container-env-var GLOBAL_GITHUB_TOKEN=GLOBAL_TOKEN

in the Dockerfile, should i be able to:
FROM public.ecr.aws/lambda/python:3.7
COPY appRead.py requirements.txt ./
RUN printenv
RUN echo "GLOBAL_GITHUB_TOKEN:" ${GLOBAL_GITHUB_TOKEN}

and see the environment variable?

**Comment by abrooksv** [comment]
My understanding is it should work. It may be a bug related to packaging type of Image.

I would cut an issue over to the SAM team at https://github.com/aws/aws-sam-cli
