### ISSUE TITLE
Exception enabling cloud debugging

### ISSUE THREAD

**Issue by mckeerod** [aws/aws-toolkit-jetbrains#2667]
**Describe the bug**
I followed the prescribed steps to enable cloud debugging on an ECS container.  I'm currently receiving a java.lang.Exception.  The exception suggests reporting it to AWS.

**To reproduce**
I used these steps from the AWS Explorer:
1. Browsed to the ECS container
2. Right clicked on the container
3. Selected "Enable Cloud Debugging"
4. Selected a role.  Clicked OK
5. Checked the box to confirm it's not a production environment.  Clicked OK
6. I observed the following output:
Checking for updates to cloud-debug CLI
Updating cloud-debug executable to version 1.0.357
cloud-debug installation completed successfully
7. Received the exception

**Expected behavior**

**Screenshots**
I ran this last week and received this exception:
![image](https://user-images.githubusercontent.com/86253167/122805997-67e2b880-d28f-11eb-8928-4223e41f396f.png)

I ran the same today and received this exception:
![image](https://user-images.githubusercontent.com/86253167/122806075-821c9680-d28f-11eb-8ef8-c7dfbdb4b123.png)

**Your Environment**
- OS:  Windows 10
- JetBrains product:  Rider
- JetBrains product version:  2021.1.3  Build #RD-211.7442.29
- AWS Toolkit version:  AWS 1.27-211
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
