### ISSUE TITLE
AWS Toolkit Plugin hides run configuration in test runner (java)

### ISSUE THREAD

**Issue by superwese** [aws/aws-toolkit-jetbrains#2691]
**Describe the bug**

With AWS Plugin 1.27-211 installed in IntelliJ IDEA 2021.1.2 (Ultimate Edition)
the "Run test" menu only shows the "Run / Debug Local" entries.
This is on a plain SpringBoot project not build with SAM or CDK or such.

**To reproduce**
Open a test class and right click the green triangle on a test method
<img width="433" alt="Bildschirmfoto 2021-06-30 um 12 11 59" src="https://user-images.githubusercontent.com/954116/123944184-2a6fe080-d99d-11eb-97f8-be218f276308.png">

**Expected behavior**
To at least have the usual run configuration available as shown here:
<img width="637" alt="Bildschirmfoto 2021-06-30 um 12 21 44" src="https://user-images.githubusercontent.com/954116/123944793-c0a40680-d99d-11eb-8df5-8145e39c9e10.png">

**Your Environment**
- OS: Mac OS BigSur (11.4)
- JetBrains product: IntelliJ IDEA 2021.1.2 (Ultimate Edition)
- JetBrains product version: Build #IU-211.7442.40
- AWS Toolkit version: 1.27-211

**Comment by abrooksv** [comment]
Can you share the class / method signature that is showing that behavior?

**Comment by superwese** [comment]
> Can you share the class and method signature that is showing that behavior?
```java 
@Slf4j
@ExtendWith(ExtRandomBeansExtension.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class ProductApiIT extends BaseIT { 

...
   @Test
    public void create_products_parallel_creates_ascending_sync_revs(
        @Random(type=Product.class, excludes = {"uuid", "syncRev", "tagUuid", "parentUuid"}) List<Product> productList,
        @Random BlueprintEntity blueprintEntity) {
   
   
```


}

**Comment by abrooksv** [comment]
We pushed some fixes for this in 1.29, can you check if you are still seeing this? We weren't able to reproduce it locally.

**Comment by rli** [comment]
sorry this was #2727

**Comment by superwese** [comment]
Yes with AWS-Toolkit 1.30 and IntelliJ 2021.2 it is gone
