### ISSUE TITLE
AWS Profiles are ignored, only default is being addressed

### ISSUE THREAD

**Issue by omerxx** [aws/aws-toolkit-jetbrains#2692]
**Describe the bug**
Using Pycharm to run against any `boto3` service with non-default profile is not working.
When there's no `default` profile set, the code outputs `Unable to locate credentials`.
If the dropdown shows a certain profile, yet another is set to `default` the one that's set to default will be used with the code.

**To reproduce**
Make sure there' no credentials named `default` either on `~/.aws/credentials` or `~/.aws/config`.
Pick one of the valid credentials in Pycharm and run.
See the error.
Set *a different* profile from the one picked in Pycharm to `default` and run.
See the code runs against the wrong profile.

**Expected behavior**
Code should run against the valid profile.

**Your Environment**
- OS: macOS Big Sur
- JetBrains product: Pycharm
- JetBrains product version: `2021.1`
- AWS Toolkit version: `1.27-211`
- JVM/Python version: `3.9.5`

**Additional context**
Using AWS SSO (setting config file with all the relevant parameters). 
Working fine with the CLI, all profiles are able to login and run with Boto3 too.
The toolkit however, is ignoring the profiles 🤷

**Comment by abrooksv** [comment]
Can you clarify your use case for me?

Are you running a Python Lambda or are you running an arbitrary Python script?

**Comment by omerxx** [comment]
@abrooksv Thanks for the next quick response!
Using boto3 with either dynamodb , s3 or really anything. Multiple workstations too.
I was expecting boto running from pycharm to see the env, instead we work around it by either changing the profile name, or setting AWS_PROFILE in the env. But it feels off...

**Comment by abrooksv** [comment]
Sounds like you want the features from #2644 which are new experimental features coming out soon (behind feature flags)

**Comment by omerxx** [comment]
@abrooksv I'm assuming you're referring to this?
> `ability to configure Run Configurations (e.g. JUnit, PyTest etc) to have the current AWS Connection injected as environment variables`

It sounds right, but feels like I'm missing something. This is an AWS toolkit for Pycharm, meaning anyone who's working with it is probably using boto3 and with high probability installed the toolkit to control the AWS environment. And if the toolkit's environment (specifically AWS profiles) not affecting boto is really the case, what is it used for? Just the terminal?

Thanks anyway, assuming we got the right feature coming we'll be waiting for it :)

**Comment by abrooksv** [comment]
The toolkit has focused on Lambda integration (Debugging python Lambdas using SAM CLI) as well as non-coding features in the IDE like an S3 browser, CloudWatch Logs viewing, etc so far.

**Comment by pablomitchell** [comment]
Experiencing identical issue as @omerxx.  I am not running a Python Lambda only my local scripts.  The environment is:

- macOS Big Sur
- PyCharm 2021.2.2 (Pro Edition)
- Python 3.9
- AWS Toolkit 1.29 thru 1.32 (all have the same issue)

The IDE only sees the 'default' profile when executing scripts.  Selecting other profiles from the AWS Explorer menu does not affect the python runtime.  Strangely, changing the profile does affect what one sees from AWS Explorer itself (e.g., I can browse through different S3 buckets associated with each profile as expected).

**Comment by abrooksv** [comment]
@pablomitchell do you mean running arbitrary python scripts? Not a Lambda?

If so, that feature is experimental and not enabled by default. You can enable it in the AWS preferences page:
![Screen Shot 2021-10-20 at 10 47 54 AM](https://user-images.githubusercontent.com/8992246/138144850-07ebb66c-d54d-43ab-b961-269b7977c5be.png)

That will add in a tab in the run config to configure passing in credentials and region as env vars:

![Screen Shot 2021-10-20 at 10 49 19 AM](https://user-images.githubusercontent.com/8992246/138144978-3554a998-37a7-4bfd-8021-39e33178547b.png)
