### ISSUE TITLE
Support for AWS Lambda using Container Image

### ISSUE THREAD

**Issue by vkchan** [aws/aws-toolkit-jetbrains#2701]
AWS released a new feature to allow deployment of Lambda function using a container image instead of a zip file, which raised the deployment size limit from 250MB to 10GB. Could we add support to this feature so that we can use PyCharm to deploy Lambda via container image? Thanks!

[https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/)

**Comment by abrooksv** [comment]
We do have support for Lambda container images, both deploy and local testing.

Is your version up to date? Latest is 1.27

**Comment by vkchan** [comment]
Hi Austin,

Thank you for your reply, I am using version 1.27. PyCharm keep deploying
my lambda function to zip file and gave me the error message for exceeding
250mb.

Is there any documentation on how I can ask PyCharm/AWS to deploy my lambda
using container image?

Thanks,
Vincent

**Comment by abrooksv** [comment]
That depends, are you using SAM templates to deploy? Or the Update Function Code dialog?

**Comment by vkchan** [comment]
I choose ‘Deploy Serverless Application’ in the context menu, I guess that’s the Update Function Code dialog?

I did have the “Build function inside a container” checked. I know pycharm is using the docker in my machine to build, but for some reasons it seems it’s still deploying with the Zip and I got stuck with the 250mb error. Is there any other option I need to set?

Thanks for your help in advance!

Regards,
Vincent

**Comment by abrooksv** [comment]
Ah, that is the SAM flow.

For that, you need to update the sam template to point to a dockerfile. Here are the fields: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html#build-container-image

There is a Image based template in the New Project wizard as well that contains Image based Lambda, you need to select Image as the packaging type. Or find it here: https://github.com/aws/aws-sam-cli-app-templates/tree/master/python3.8-image/cookiecutter-aws-sam-hello-python-lambda-image/%7B%7Bcookiecutter.project_name%7D%7D


The "Build in container" checkbox is to help build functions that need to pull native dependencies for the correct OS, it is not related to the Image packaging type.

**Comment by vkchan** [comment]
Thanks a lot Austin, that’s very helpful, that’s exactly what I’m looking for, I need to specify the packaging info in the Sam template. Thanks again!

**Comment by abrooksv** [comment]
You're welcome.
