### ISSUE TITLE
Lambda handler resolver for Java does not work correctly when using RequestHandler interface

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#271]
**To reproduce**
Given:
```
package helloworld;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class App implements RequestHandler<Object, Object> {

    public Object handleRequest(final Object input, final Context context) {
      return "Hello";
    }
}
```

The `Lambda#findPsiElementsForHandler` says `helloworld.App::handleRequest` is invalid, and requires it to be `helloworld.App` even though both are valid

**Comment by MariusVolkhart** [comment]
This appears to still be an issue in `v1.0`.

Generating a new Hello World sample, when I go to run the function locally, the IDE says "Cannot find handler 'helloworld.App::handleRequest' in the project.

**Comment by MariusVolkhart** [comment]
Nevermind, I forgot to package the project first
