### ISSUE TITLE
HTML files uploaded through S3 explorer has wrong content-type

### ISSUE THREAD

**Issue by mnin-tv2** [aws/aws-toolkit-jetbrains#2718]
**Describe the bug**
Whenever a a file is uploaded through the bucket-explorer to an S3 bucket, the content-type is set to application/octet-stream (which is belive is default for s3)
The problem is, that if you try to upload .html files to a bucket with a static webhosting enabled, the content-type should be text/html, otherwise the file is downloaded instead of shown in the browser.

**To reproduce**
1. Create S3 bucket
2. Make it public accessible
3. Enable static webste hosting
4. Upload index.html through intellij, via the bucke explorer
5. Go to the bucket website url

**Expected behavior**
The html page should be shown in the bworser, rather than downloaded

**Your Environment**
- OS: MacOS 11.3
- JetBrains product: IntelliJ Ultimate
- JetBrains product version: 2021.1
- AWS Toolkit version: 1.28-211
- SAM CLI version: 1.23.0
- JVM/Python version: python3.8.9 java1.8.0_252

**Comment by abrooksv** [comment]
#2721 will use the file extension and the SDK's mime type list to set the content type
