### ISSUE TITLE
Search bar?

### ISSUE THREAD

**Issue by BluJay-Dev** [aws/aws-toolkit-jetbrains#2729]
Insanely helpful tool, a search bar would be really nice for buckets that have a lot of noises but overall incredible plugin. 

---
Toolkit: AWS Toolkit For JetBrains 1.29-211
OS: Mac OS X 11.4
IDE: GoLand 211

**Comment by rli** [comment]
[Speed search](https://www.jetbrains.com/help/idea/speed-search-in-the-tool-windows.html) is enabled on the AWS Explorer if that is approximately what you're looking for

**Comment by BluJay-Dev** [comment]
@rli oh cheers I didn't know that was a feature :)
