### ISSUE TITLE
Cloudwatch logs - logstreams is not sorted by last event time 

### ISSUE THREAD

**Issue by viralddave** [aws/aws-toolkit-jetbrains#2737]
**Describe the bug**
When you right click on any lambda and open the cloudwatch logs for that , it shows two columns one is log streams and another one is last Event Time - in older version it used to load Log Streams sorted by Last event time - so either give sorting option or make it default sorted by latest timestamp
**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment]
It looks like it is behaving that way for me:
![Screen Shot 2021-07-29 at 7 33 21 AM](https://user-images.githubusercontent.com/8992246/127511042-3be2fa83-c9bf-4033-8eb3-e7917bf0d02d.png)

The event time is a snapshot in time from when the table loaded, you need to hit refresh to resort it if there are newer events

Is this not what you are seeing?

**Comment by viralddave** [comment]
No I tried refresh but still no issue 

Let me give you more details , am using latest Pycharm (professional edition - 2021.2 ) but still it is not 
Below is the screen shot

PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
Licensed to ---------------
Subscription is active until February 26, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: AWSCloudFormation (212.4746.57), com.intellij.plugin.adernov.powershell (2.0.7), com.jetbrains.intellij.datalore (0.1.13-212), aws.toolkit (1.29-212)

![image](https://user-images.githubusercontent.com/47645601/127516736-64cd7546-1a49-45bc-a09e-768da94db53b.png)

**Comment by abrooksv** [comment]
Interesting, seems we did not specify a custom String converter for that sorter so not 100% sure what it is sorting on. Will need to dig into it to validate

**Comment by viralddave** [comment]
Probably when will get this fix , any approximate time ?

**Comment by viralddave** [comment]
![image](https://user-images.githubusercontent.com/47645601/128528059-5890f28e-0561-4146-bf1a-2e69e389393c.png)

**Comment by viralddave** [comment]
This is still not fixed 
I updated plugin - did not work - I uninstalled and install it again did not work

PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
Licensed to Viral Dave
Subscription is active until February 26, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: AWSCloudFormation (212.4746.57), com.intellij.plugin.adernov.powershell (2.0.7), com.jetbrains.intellij.datalore (0.1.13-212), aws.toolkit (1.30-212)

**Comment by abrooksv** [comment]
Okay. We will take another look.

**Comment by viralddave** [comment]
no worries

**Comment by abrooksv** [comment]
I found the issue and fixed it.
![Screen Shot 2021-08-06 at 8 57 56 AM](https://user-images.githubusercontent.com/8992246/128538484-1c03c17c-1cf0-4630-94c2-eaf3d0c7ecc2.png)
