### ISSUE TITLE
Running lambda function locally makes PyCharm to crash

### ISSUE THREAD

**Issue by lorenooliveira** [aws/aws-toolkit-jetbrains#2758]
**Describe the bug**
I'm still new to Lambda so I created a test project for trying new stuff. 

My test project has only one script (lambda_function.py) with the contents below:

```
import json

def lambda_handler(event, context):
    message = event['Records'][0]['Sns']['Message']

    print(f"SNS message: {message}")
    print(f"Type: {type(message)}")

    return {
        'statusCode': 200,
        'body': json.dumps('Now reading an SNS Message!')
    }

```

I'm using the lambda icon, close to function declaration, for starting local executions:

![image](https://user-images.githubusercontent.com/266041/128647036-a2f58d53-c88e-456e-8400-5545922275d5.png)

Sometimes the function is executed as expected locally, but other times PyCharm crashes right after clicking on "Run [Local] lambda_function...". The same happens if I try to run using the top right button:

![image](https://user-images.githubusercontent.com/266041/128647098-8b03a520-b292-4803-a570-0a34289a3849.png)

There are no error messages or something. PyCharms just crashes.

**To reproduce**
1. Create a project with a single file _lambda_function.py_ and the previous content.
2. Run some local function executions. I haven't noted an exact number of repetitions for causing the crash

**Expected behavior**
Some executions should work as expected, but eventually some attempt will cause PyCharm to crash without any message.

**My Environment**
- OS: Windows 10 64bits
- JetBrains product: PyCharm Professional 2021.2
- JetBrains product version: Build #PY-212.4746.96
- AWS Toolkit version: 1.30-212
- SAM CLI version: SAM CLI, version 1.27.2
- JVM/Python version: 3.8.10

**Additional context**

**Comment by abrooksv** [comment]
Consolidating these under #2762,

if you are NOT using a file as your input, please reopen

**Comment by GiantFrog** [comment]
I would like to chime in that I have this exact same issue and do not use a file for any of my inputs! My functions don't need to do anything with the input, so I use either the "scheduled event" or "hello word" text template.

I have found that every time I edit my run configurations and the message "Error: Lambda handler validation is in progress" appears at the bottom of the window, PyCharm will hang if I try to run or debug. If I wait a couple minutes, reopen the run configurations window, and that error message appears for a split second then goes away, I will be able to run and debug my function, I think as much as I want until I change any tiny amount of code.

I am on Mac 11.5.1 Big Sur, PyCharm 2021.2, AWS Toolkit 1.30-212, SAM CLI 1.26.0
