### ISSUE TITLE
date sorting messed up in latest 2 updates

### ISSUE THREAD

**Issue by frank-unovica** [aws/aws-toolkit-jetbrains#2790]
**Describe the bug**

"Last Event Time" in a cloudwatch log streams page used to be in order (UTC timestamp), but now the datetime appears to be localized and literally sorted (i.e. day-month-year instead of year-month-day), which makes it almost impossible to work with. It is no longer in order of time.

Also, there are too many items for a scrollbar to be an appropriate choice of UX in the first place; you are forced to use the keyboard since 1 pixel skips more than a page, and have no sense of where you are. The autoload feature messes up the scrollbar while you are trying to find your pixel, and also does not appear to load in order of time.

There is no way of sorting or resizing the columns either.

**To reproduce**

Set a system time format that is not sortable.

**Expected behavior**

It used to be workable before the last 2 updates, even though CloudWatch is clearly not designed to integrate in a modern development workflow (such as Chrome DevTools or Webstorm debugging console) and slows it down considerably.

**Screenshots**

![Screenshot from 2021-09-04 08-12-17](https://user-images.githubusercontent.com/60439693/132084819-7e9e2836-45e1-41ec-a809-344e2ed2d7e2.png)

**Your Environment**
- OS: 
Ubuntu 20 PC in the CEST timezone using US English language and Dutch formatting
- JetBrains product:
Webstorm
- JetBrains product version:
2021.2.1
- AWS Toolkit version:
"1.29 -> 1.31-212"
- SAM CLI version:
N/A
- JVM/Python version:
openjdk version "1.8.0_292"
Python 3.8.10

**Additional context**

**Comment by abrooksv** [comment]
> "Last Event Time" in a cloudwatch log streams page used to be in order (UTC timestamp), but now the datetime appears to be localized and literally sorted (i.e. day-month-year instead of year-month-day), which makes it almost impossible to work with. It is no longer in order of time.

I thought I explicitly fixed this in #2753, I'll have to check again.

> Also, there are too many items for a scrollbar to be an appropriate choice of UX in the first place; you are forced to use the keyboard since 1 pixel skips more than a page, and have no sense of where you are. The autoload feature messes up the scrollbar while you are trying to find your pixel, and also does not appear to load in order of time.

On listing of CW Streams:
* If you know the name, there is a search bar in the top right to search by prefix.
* If you know part of the name, just start typing (with the table having focus) and IntelliJ's SpeedSearch should kick in. Arrow keys move to the next search hit

On the contents of the CW stream:
Speed search is also enabled here, and the top right search also does server side filtering.

**Comment by frank-unovica** [comment]
Nevermind, it is fixed after updating, but I'm used to Webstorm proposing plugin updates, which somehow didn't happen.

I also found an approach to using local webstorm debugging of lambda functions (expand logged objects etc.), using a customized docker lambda image that allows setting node js parameters (--inspect). The layering is easily solved with docker volumes.
