### ISSUE TITLE
Unable to debug ECS services - missing dependencies in manifest

### ISSUE THREAD

**Issue by adeeb-checkpoint** [aws/aws-toolkit-jetbrains#2799]
**Describe the bug**
I followed [this guide](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html) as well as [this video](https://www.youtube.com/watch?v=afj-VYl1_Ok) for debugging ECS Fargates.
In attempt to replicate the video, I have created a "blank" project in which the main program invokes simple arithmetic operations; so I can ensure I can debug the program somehow.

I configured the Dockerfile to be simplistic (more below), csproj file and main program cs file. Built the Docker and pushed to the ECR to which I used to create the simple, ECS Fargate machine.
Using Rider, with AWS Explorer plugin, clicking "Enable Cloud Debugging (beta)" for the corresponding ECS works fine, it creates a new "cloud-debug-..." ECS.
Following the Debug Configuration, the AWS Explorer manages to upload all sorts of Jetbrains / Rider / Debugger files into the debug ECS, specifically under path `/aws/DOTNET/aws_rider_debugger_files/`, all works well, but when it tries to invoke the debugger it fails:

Full error details (command included):
```bash
Error details:
	- failed to start the application: [18:25:49-D] Dispatcher: http response status code was '400'
[18:25:49-E] exit status 140: long-running 'entrypoint' cmd '[env REMOTE_DEBUG_PORT=20020 RESHARPER_HOST_LOG_DIR=/aws/DOTNET/aws_rider_debugger_files/Logs dotnet /aws/DOTNET/aws_rider_debugger_files/JetBrains.Debugger.Worker.exe --mode=server --frontend-port=20020 --backend-port=20021]' failed with output: 'Error:
  An assembly specified in the application dependencies manifest (JetBrains.Debugger.Worker.deps.json) was not found:
    package: 'Autofac', version: '1'
    path: 'NetCore/Autofac.dll'
': http request failed with response '&{400 Bad Request 400 HTTP/1.1 1 1 map[Content-Length:[511] Content-Type:[application/json; charset=utf-8] Date:[Fri, 10 Sep 2021 18:25:49 GMT]] 0xc00000c120 511 [] false false map[] 0xc0000bf700 <nil>}'

Starting application in EcsDebugContainer has failed: Command did not complete successfully
```

After further investigation (by invoking "start remote shell" on the cloud-debug ECS), it seems like simple program is fine, docker environment is in tact, and no issue regarding on my side. It's only that the files it uploaded are incomplete; the dependencies, lying within file `JetBrains.Debugger.Worker.deps.json`, are either not in the needed directory or entirely missing. Meaning:
- `Autofac.dll` exists, but is not under the directory "`NetCore/`"
- `ClrStack.dll` is entirely missing from the `/aws/DOTNET/aws_rider_debugger_files/` folder

**To reproduce**
1. Using the following file structure for an "empty" project:
EcsDebugging
├── Dockerfile
├── EcsDebugging.csproj
├── Program.cs
└── Properties
.............└── AssemblyInfo.cs

_Dockerfile_:
```Dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
USER root
RUN apt-get update -y
RUN apt-get install procps -y
WORKDIR /app
ADD . .
EXPOSE 420
ENTRYPOINT ["dotnet", "EcsDebugging.dll"]
```

_Program.cs_:
```cs
namespace EcsDebugging {
    internal class Program {
        public static void Main(string[] args) {
            int a = 5;
            a += 10;        // <--- point to debug
            a = a * a;
        }
    }
}
```

_EcsDebugging.csproj_:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <OutputType>Exe</OutputType>
        <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
        <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
        <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
</Project>
```

**Expected behavior**
It would able to run the Debugger as normal, like what's presented in the Documentation and Video

**Screenshots**

**Your Environment**
- OS: macOS Big Sur 11.5.2
- JetBrains product: Rider
- JetBrains product version: JetBrains Rider 2021.2.1 - Build #RD-212.5080.71
- AWS Toolkit version: 1.32-212
- JVM/Python version: python 3.9.1

**Additional context**
- Docker can be different, tried over multiple variations and the issue still persists
- The following Shell screenshot is from clicking the "start remote shell" on the debug cloud, on the container in use, which emphasize on the dependency issues:
```bash
/app> find / -name Autofac.dll
/aws/DOTNET/aws_rider_debugger_files/Autofac.dll
/app> find / -name ClrStack.dll
/app> 
```

**Comment by rli** [comment]
ECS Cloud Debug is no longer supported so issue will be closed. [ECS Exec](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-toolkit-jetbrains-ides-ecs-exec-containers/) is its replacement.
