### ISSUE TITLE
What Lambda update configuration command does the AWS Toolkit use?

### ISSUE THREAD

**Issue by Keremtspnr** [aws/aws-toolkit-jetbrains#2807]
**Question**

Hello everyone,
I've a very short question.

i built a system using Lambda and API Gateway. If i update the configurations of this lambda with Pycharm AWS Toolkit, the Lambda's ip range also changes.

But if i update the configurations from cmd with AWS CLI, this ip range doesn't change.
The code i use:
`aws lambda update-function-configuration --function-name cloud9-xxx`

I wonder what exactly is the update-function-configuration command that AWS Toolkit uses?
How can i use this myself from cmd

Thanks

**Your Environment**

- OS: Windows 10
- JetBrains product: Pycharm
- JetBrains product version: 2021.2
- AWS Toolkit version: 1.29-212
- SAM CLI version:
- JVM/Python version: 3.8.5

**Comment by abrooksv** [comment]
We use the same API:
https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/upload/FunctionDetails.kt#L33

Lambda does not guarantee anything about IPs of the running function instance as far as I am aware.

**Comment by abrooksv** [comment]
Closing, feel free to re-open if you still have questions
