### ISSUE TITLE
Not working with IntelliJ IDEA EAP 2021.3

### ISSUE THREAD

**Issue by doublefx** [aws/aws-toolkit-jetbrains#2836]
Incompatible: Requires IDE build 212.* or earlier

**Comment by abrooksv** [comment]
Sorry you hit this issue. Each IDE major version requires code changes and we are still figuring out how expensive those changes are.

I will update this issue when we release our first 213 builds.

**Comment by abrooksv** [comment]
First 201.3 build is available in our EAP channel https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/EAP/143984
