### ISSUE TITLE
Python Lambda gutter icon uses incorrect handler path when making run config

### ISSUE THREAD

**Issue by rsotogar** [aws/aws-toolkit-jetbrains#2853]
**Your Environment**

- OS: MacOS BigSur
- JetBrains product: PyCharm 
- JetBrains product version: 2020.3.1 
- AWS Toolkit version: 1.32
- SAM CLI version: 1.29.0
- JVM/Python version: Python 3.7

**Question**

I'm sure it's just a tiny conf issue but I can't seem to find the solution. In order to verify my installation works correctly I created a simple lambda function, with no imports, like this:

![image](https://user-images.githubusercontent.com/59261157/136057066-9718dc9f-a3d2-49cc-8cb2-8d168b7d4658.png)

Then I simulated an input json file as I would have when I deploy a production lambda to process changes in S3 buckets:

![image](https://user-images.githubusercontent.com/59261157/136058640-e2bf1d1a-ada6-4196-957c-94d3f42fa162.png)

But when I invoke a local run I get this error:

![image](https://user-images.githubusercontent.com/59261157/136057490-cd4bb042-9757-479a-9066-3ce296ae0839.png)

I added the project directory path to shared files in Docker. The problem persists and I can't seem to find out why. Anybody can help?

Thanks!

**Comment by abrooksv** [comment]
What is the layout on disk?

Do you have an `__init__.py` in the `lambda_test` directory?

**Comment by rsotogar** [comment]
I do yes:

![image](https://user-images.githubusercontent.com/59261157/136160724-52be5a15-4670-46d2-89c8-4c4459280918.png)
