### ISSUE TITLE
Refresh Explorer on create/delete

### ISSUE THREAD

**Issue by ghost** [aws/aws-toolkit-jetbrains#286]
creation/deletion of a resource should cause a refresh of the AWS Explorer for that resource type

**Comment by awschristou** [comment]
Marking as bug. Deleting a Lambda Resource should not leave it in the Explorer.

**Comment by hunterwerlla** [comment]
This is working for S3 but not for CF/Lambda (We can't delete a cluster in ECS/log groups in CWL/and schemas is a registry)
