### ISSUE TITLE
There is any way to start a local instance of API Gateway in debug mode?

### ISSUE THREAD

**Issue by 129lovely** [aws/aws-toolkit-jetbrains#2871]
**Your Environment**

- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Question**

I want to run API Gateway in debugging mode, becuase I need integration testing of API Gateway and AWS Lambda.
(I referred to [this](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-debugging.html#serverless-sam-cli-running-locally) topic)
However, in Jetbrains, only Lambda invoke was available in debugging mode.
If this feature already exists, please tell me how.
Thank you.

**Comment by boblund** [comment]
I created [this repo](https://github.com/boblund/localAwsApiGw) where you can locally run an AWS s3 static website, websocket server and rest api gw. I debug using vscodium.
