### ISSUE TITLE
Support the duraton seconds configuration when use mfa

### ISSUE THREAD

**Issue by niwatly** [aws/aws-toolkit-jetbrains#2897]
AWS CLI Configuration supports the `duration_seconds` variable that controls the role session duration, 

https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles

but we can not set this variable on aws-toolkit.

https://github.com/awsdocs/aws-toolkit-jetbrains-user-guide/blob/main/doc_source/key-tasks.md#--connect-with-access-keys--

I want to set this value to 12 hours...

**Comment by abrooksv** [comment]
You are correct, we do not support this today:

https://github.com/aws/aws-toolkit-jetbrains/blob/2ea9bbb050c7cec716ab98d064ff140176c507a6/jetbrains-core/src/software/aws/toolkits/jetbrains/core/credentials/profiles/ProfileCredentialProviderFactory.kt#L284-L305

**Comment by abrooksv** [comment]
PR to  SDK to add it to the list of keys: https://github.com/aws/aws-sdk-java-v2/pull/2812
