### ISSUE TITLE
Unable to Debug Lambda on initial AWS SAM Hello World template

### ISSUE THREAD

**Issue by jeremyforan** [aws/aws-toolkit-jetbrains#2983]
**Describe the bug**
 

**To reproduce**
1. In Goland I create a new project using the AWS Serverless Application.  
2. I create a default project using the SAM Hello World Template.  
3. I add a break point to line 25 (the first line of the handler function) of the /hello-world/main.go file and hit debug. 
4. I get the following error

```
Invoking hello-world (go1.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-go1.x:rapid-1.36.0-x86_64.

Mounting /Users/REDACTED/GolandProjects/REDACTED/untitled/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 366b81c6-5931-4a76-a731-6e5780d541a3 Version: $LATEST
API server listening at: [::]:65383
2021-11-25T17:07:21Z info layer=debugger launching process with args: [/var/task/hello-world]
could not launch process: fork/exec /var/task/hello-world: function not implemented
2021/11/25 17:07:21 exit status 1
25 Nov 2021 17:07:21,577 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 1 InvokeID=
API server listening at: [::]:65383
2021-11-25T17:07:21Z info layer=debugger launching process with args: [/var/task/hello-world]
could not launch process: fork/exec /var/task/hello-world: function not implemented
2021/11/25 17:07:21 exit status 1
END RequestId: 4ed46dfd-4677-4188-b5a7-5d6b66a82376
REPORT RequestId: 4ed46dfd-4677-4188-b5a7-5d6b66a82376	Init Duration: 1.02 ms	Duration: 1095.00 ms	Billed Duration: 1095 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
```

**Expected behavior**
I am able to debug and step through the code.

**Screenshots**

**Your Environment**
- OS: MacOS 12.0.1 7429.41.5. M1 / ARM
- JetBrains product: GoLand
- JetBrains product version: 2021.2.4 Build #GO-212.5457.54,
- AWS Toolkit version: 1.36-212
- SAM CLI version: 1.36.0
- JVM/Python version: NA / go version go1.17.2 darwin/arm64

**Additional context**
I appreciate you looking into this.  Kind Regards,

**Comment by yuki-snow1823** [comment]
@jeremyforan 
Hi. I'm sorry if this is wrong English.

I got the same error and solved it, so I'll share how to do it.

It is probably a Docker image related error.

Here are the steps. 1.

1. run `docker images` to see the list of images
2. specify the id of the image in **public.ecr.aws/sam/emulation-go1.x** and delete them all with the `docker rmi` command
3. You can't delete a container if it is already running, so delete the container first.
4. even if you can't see them in `docker ps`, you can delete them by specifying the container id with the `rm --force option`

Once you have done that, you can probably debug it.
I was able to access `localhost:3000/hello.`

**Comment by nhthai2207** [comment]
I'm getting the same problem and found this thread: https://www.higithub.com/aws/issue/aws-sam-cli/3283
Seems the issue comes from the M1 chip.

**Comment by rli** [comment]
Closing in favor of #3061
