### ISSUE TITLE
Lambda Update Function Code Fails

### ISSUE THREAD

**Issue by iheffernan** [aws/aws-toolkit-jetbrains#2984]
**Describe the bug**

Within the past week, attempting to use the AWS Toolkit to Update Function Code for Lambda fails stating that '`An update is in progress for resource.`' However, after inspecting the function in the AWS Console it appears that the Lambda function has been updated, based on the Last Modified timestamp. But I can't confirm it's using the correct payload that was uploaded to S3 because a local `shasum -a 256` output does not match the SHA256 Hash value in the Lambda console.

**To reproduce**
1. Write a Lambda function
2. Select that function in the AWS Toolkit Lambda window
3. Right click and select Update Function Code

**Expected behavior**
Previously, this would successfully update the function code without any error.

**Screenshots**
Here's the error message in the WebStorm terminal when running Update Function Code...
```/opt/homebrew/bin/sam build --template /var/folders/yg/bsgv7p8d1fz9ppyz_zrhmy7w0000gn/T/temp-template2389355132087099915.yaml --build-dir /Users/ian/WebstormProjects/api-node/.aws-sam/build
Building codeuri: /Users/ian/WebstormProjects/api-node/api-function runtime: nodejs14.x metadata: {} architecture: x86_64 functions: ['Function']
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc

Build Succeeded

Built Artifacts  : ../../../../../../Users/ian/WebstormProjects/api-node/.aws-sam/build
Built Template   : ../../../../../../Users/ian/WebstormProjects/api-node/.aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke -t ../../../../../../Users/ian/WebstormProjects/api-node/.aws-sam/build/template.yaml
[*] Deploy: sam deploy --guided --template-file ../../../../../../Users/ian/WebstormProjects/api-node/.aws-sam/build/template.yaml
        
/opt/homebrew/bin/sam package --template-file /Users/ian/WebstormProjects/api-node/.aws-sam/build/template.yaml --output-template-file /Users/ian/WebstormProjects/api-node/.aws-sam/build/packaged-temp-template.yaml --s3-bucket XXXXX
Uploading to 5a0a12aaaf4de83529b7d1a17539c570  17193497 / 17193497  (100.00%)
Successfully packaged artifacts and wrote output template to file /Users/ian/WebstormProjects/api-node/.aws-sam/build/packaged-temp-template.yaml.
Execute the following command to deploy the packaged template
sam deploy --template-file /Users/ian/WebstormProjects/api-node/.aws-sam/build/packaged-temp-template.yaml --stack-name <YOUR STACK NAME>


Updating Lambda has failed: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:API-NodeJS (Service: Lambda, Status Code: 409, Request ID: 319821bc-ff87-4539-8a30-01d75c0591d6, Extended Request ID: null)API-NodeJS has failed: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1: XXXXXXXXXXXX:function:ByrstAPI-NodeJS (Service: Lambda, Status Code: 409, Request ID: 319821bc-ff87-4539-8a30-01d75c0591d6, Extended Request ID: null)
```

**Your Environment**
- OS: MacOS 12.0.1
- JetBrains product: WebStorm
- JetBrains product version: 2021.3, build 213.5744.224
- AWS Toolkit version: 1.36-213
- SAM CLI version: 1.35.0
- JVM/Python version: N/A

**Additional context**

**Comment by iheffernan** [comment]
Not sure if this might be related to the recent AWS announcement about the expansion of Lambda states to all functions.

**Comment by hornmarc** [comment]
This was an issue for me last week. Any updates with this being a bug or is opt-out the only solution to this error by design?
