### ISSUE TITLE
Unknown resource type property: CapacityProviderStrategy in CloudFormation template

### ISSUE THREAD

**Issue by emiliopedrollo** [aws/aws-toolkit-jetbrains#2992]
**Describe the bug**
Code inspect for CloudFormation templates warns about n unknown resource type that is specified in the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-capacityproviderstrategy).

**To reproduce**
1. Create a template with an ECS service and a capacity provider

**Expected behavior**
To not show a warning/error, also correctly suggest to autocomplete the property as well as it's sub properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/6577541/144620621-046f6a0d-60a0-4d68-8533-28dedc7df452.png)

**Environment**
- OS: Ubuntu 21.10 
- JetBrains product: PHPStorm
- JetBrains product version: 2021.2.3
- AWS Toolkit version: 1.36-212

**Comment by rli** [comment]
The JetBrains toolkit doesn't provide schema support for CloudFormation at the moment. If you used the IDE-provided schema from SchemaStore.org, support for `CapacityProviderStrategy` was added in version [4.15.2](https://github.com/awslabs/goformation/pull/320).

![image](https://user-images.githubusercontent.com/742829/144656560-b18d7d7f-dd31-4c85-8621-e1015d8f5b28.png)

**Comment by rli** [comment]
Should be fixed in the latest version of the AWS CloudFormation plugin
