### ISSUE TITLE
Syntax highlighting issue with SAM; false-positive

### ISSUE THREAD

**Issue by JohnCover** [aws/aws-toolkit-jetbrains#3016]
**Describe the bug**
Syntax highlighting issue with SAM yaml for two resources types:
- AWS::ApiGatewayV2::ApiMapping: Implicit mapping of Stage resource is showing as invalid when it works as intended
- AWS::Serverless::Api: Domain is listed as an unknown property when it is infact supported by SAM/CloudFormation

**To reproduce**
1. AWS Toolkit 3.38
2. IntelliJ IDEA 2021.2.1 (Ultimate Edition), Build #IU-212.5080.55 built on August 23, 2021
3. Create a template.yaml file for a serverless SAM application
4. Defile an AWS::ApiGatewayV2::ApiMapping & AWS::Serverless::Api resource as depicted in the attach screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/16791747/147861410-1c62a423-c261-4470-a455-30a4216f2287.png)

**Your Environment**
- OS: Windows 11
- JetBrains product: IntelliJ IDEA 2021.2.1 (Ultimate Edition), 
- JetBrains product version: Build #IU-212.5080.55 built on August 23, 2021
- AWS Toolkit version:  AWS Toolkit 3.38
- SAM CLI version: SAM CLI, version 1.36.0
- JVM/Python version: OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc..jdk11u)

**Comment by rli** [comment]
As mentioned in #2992, the toolkit currently does not provide any schema support for SAM/CloudFormation templates. 

Though since it looks like Refs are being resolved perhaps you have the [AWS Cloudformation](https://plugins.jetbrains.com/plugin/7371-aws-cloudformation) plugin installed, which is currently maintained by JetBrains and not AWS

**Comment by rli** [comment]
Should be fixed in the latest version of the AWS CloudFormation plugin
