### ISSUE TITLE
ClassCastException on changing Lambda Run Config

### ISSUE THREAD

**Issue by chillbirdo** [aws/aws-toolkit-jetbrains#3064]
**Describe the bug**
This Exception is very likely also the cause for issue #3063

In the "Edit Run Configuration" Dialog for the AWS Lambda Function (see attached screenshot), when trying to change one of the following values: Timeout, Memory, Environment Variables, Input Text.
The edited values are not saved. Pressing OK and opening the dialog again shows the old values, not the edited ones. Editing did not succeed. Instead, an error is thrown (Exception log attached)

**To reproduce**
Versions:
IntelliJ: IntelliJ IDEA 2021.3 (Ultimate Edition), Build #IU-213.5744.223, built on November 27, 2021
AWS Toolkit Plugin: 1.37-213
SAM: SAM CLI, version 1.37.0
nodejs: v14.19.0
npm: 6.14.16

`sam init`, choose all standard options, but node14 and zip packaging. Open with IJ. Try to start the Hello World Lambda via the plugin.

**Expected behavior**
Edited values should be stored.

**Screenshots**
![image](https://user-images.githubusercontent.com/3681858/153588708-4ac9333a-b589-4244-a9e0-d2f6cf49675f.png)
Exception Logs:
[intellij-aws-plugin-ClassCastException.txt](https://github.com/aws/aws-toolkit-jetbrains/files/8048444/intellij-aws-plugin-ClassCastException.txt)

**Your Environment**
- OS: Linux Mint
- IntelliJ: IntelliJ IDEA 2021.3 (Ultimate Edition), Build #IU-213.5744.223, built on November 27, 2021
- AWS Toolkit Plugin: 1.37-213
- SAM: SAM CLI, version 1.37.0
- nodejs: v14.19.0
- npm: 6.14.16

**Additional context**

**Comment by rli** [comment]
Fixed in 1.38
