### ISSUE TITLE
No plugins found in repository

### ISSUE THREAD

**Issue by wolkenschieber** [aws/aws-toolkit-jetbrains#3065]
**Describe the bug**
I can't install the EAP version of the plugin into WebStorm.

**To reproduce**
* Add the URL https://plugins.jetbrains.com/plugins/eap/aws.toolkit to IDE's plugin repository preferences by going to Plugins->Gear Icon->Manage Plugin Repositories and adding the URL to the list
* Tooltip appears _No plugins found. Check the log file for errors._ 
* No entries in log file.

**Environment**
* Build version: WebStorm 2022.1 EAP Build: #WS-221.4165.163 February 11, 2022
* Theme: Darcula
* JRE: 11.0.14+9-b1982.1, JetBrains s.r.o.
* JVM: 11.0.14+9-b1982.1, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
* Operating System: Linux 5.16.8-arch1-1 (amd64)

**Comment by rli** [comment]
We currently don't have any 2022.1 EAP builds available
Work is being done in this PR: https://github.com/aws/aws-toolkit-jetbrains/pull/3058

On the JetBrains Marketplace page, you can see the available compatibility ranges: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/eap

**Comment by rli** [comment]
2022.1 is now available as part of our standard release builds

**Comment by kangabai3228-alt** [comment]
CSX : 
 https://raw.githubusercontent.com/SaurabhKaperwan/CSX/builds/CS.json
