### ISSUE TITLE
JUnit run config overridden for parameterized test with single param

### ISSUE THREAD

**Issue by mikelhamer** [aws/aws-toolkit-jetbrains#3075]
**Describe the bug**
When running a JUnit parameterized test from the gutter icon in IntelliJ, the AWS Toolkit run configuration overrides the run options and prevents running the test this way. 
This is extremely similar to to #1011, but interestingly when I add a second param, the issue goes away.

**To reproduce**
1. Create a JUnit test with a parameter
2. Click the run icon in the gutter
3. Click run

**Expected behavior**
This shouldn't happen

**Screenshots**
(not dependent on @ParameterizedTest or @ ValueSource annotations to recreate)
<img width="432" alt="image" src="https://user-images.githubusercontent.com/10012080/156062504-41a6dd69-5bbd-4530-9d96-89759c065466.png">

![image](https://user-images.githubusercontent.com/10012080/156062257-3e6894d2-d381-4384-b367-f3f8410e169d.png)

**Your Environment**
- OS: macOS 12.1
- JetBrains product: IntelliJ
- JetBrains product version: 2021.3.1
- AWS Toolkit version: 1.38-213
- SAM CLI version: n/a
- JVM/Python version: 11

**Comment by rli** [comment]
Released in 1.44
