### ISSUE TITLE
WebStorm 2022.1 Compatibility

### ISSUE THREAD

**Issue by s-abinash** [aws/aws-toolkit-jetbrains#3116]
Plugin is not supported with WebStorm 2022.1 build

Getting error: Incompatible. IDE build requires 213. or earlier*

**Comment by billylaing** [comment]
Same error here. Looks like there is a 1.41 described [here](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) but only 1.40 shows up in the plugins window.

**Comment by frank-unovica** [comment]
+1

**Comment by joelalves** [comment]
+1

**Comment by joelalves** [comment]
+1

**Comment by mohaqqani** [comment]
+1

**Comment by rli** [comment]
`1.42-221` has been released with support for 2022.1. Sorry for the inconvenience.
