### ISSUE TITLE
Incompatibility with Intellij (Build #IC-221.5080.210)

### ISSUE THREAD

**Issue by Kaushik27** [aws/aws-toolkit-jetbrains#3117]
**Describe the bug**
Incompatibility with Intellij version **Build #IC-221.5080.210**

**To reproduce**

1. Update Intellij community edition to latest version IC-221.5080.210 
2. See if AWS Toolkit is compatible

**Expected behavior**
AWS Toolkit should work the latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/8160199/163155129-d6916188-16be-4904-9b95-9b8a7b4a9a69.png)

**Your Environment**
- OS: Windows 10
- JetBrains product: Intellij Community Edition
- JetBrains product version: IC-221.5080.210
- AWS Toolkit version: 1.41-213
- SAM CLI version: 1.23.0
- JVM/Python version: 11.0.14.1" 2022-02-08/  3.9.2

**Additional context**
![image](https://user-images.githubusercontent.com/8160199/163155976-29532dc7-ac7e-47bf-88fa-813c3b156f66.png)

**Comment by rli** [comment]
`1.42-221` has been released with support for 2022.1. Sorry for the inconvenience.
