### ISSUE TITLE
AWS Toolkit not compatible with DataGrip 2022.1 

### ISSUE THREAD

**Issue by unfeelinghomer** [aws/aws-toolkit-jetbrains#3122]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product: Datagrip
- JetBrains product version: 2022.1
- AWS Toolkit version: none available for this version of DataGrip
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by rli** [comment]
`1.42-221` has been released with support for 2022.1. Sorry for the inconvenience.
