### ISSUE TITLE
AWS SAM template.yaml parser does not recognise `Architectures` property

### ISSUE THREAD

**Issue by Arakade** [aws/aws-toolkit-jetbrains#3132]
**Describe the bug**
AWS SAM `template.yaml` allows defining architecture to deploy to in a Lambda function's properties via the `Architectures` property per [spec](https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) and [website](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html).

Rider syntax checking says it's invalid.

**To reproduce**
1. `sam init -a arm64`
2. "Which template source would you like to use?" = 1
3. "Choose an AWS Quick Start application template" = 3
4. "Which runtime would you like to use?" = 2
5. Name the project
6. Import into WebStorm
7. Open `template.yaml`
8. Find `Architectures` line
9. Observe red error highlight

**Expected behavior**
Auto-suggestion and error checking should both show it as valid.

**Screenshots**

![image](https://user-images.githubusercontent.com/1194266/163672730-7bcf183c-c67f-4606-b412-3e2516b689d8.png)

**Your Environment**
- OS: Windows 10
- JetBrains product: WebStorm
- JetBrains product version: Build #WS-221.5080.193, built on April 10, 2022
- AWS Toolkit version: 221.5080.126
- SAM CLI version: SAM CLI, version 1.46.0
- JVM/Python version: Runtime version: 11.0.14.1+1-b2043.25 amd64, VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Additional context**

**Comment by Arakade** [comment]
It also fails to recognise `Tags` in `AWS::Logs::LogGroup` / `Properties` (despite being valid per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html ).

![image](https://user-images.githubusercontent.com/1194266/163812046-eae30a34-1169-476c-80f4-86d2dc468a82.png)

**Comment by rli** [comment]
JetBrains is the current maintainer of the CloudFormation language support and this should go out in their next release

https://github.com/JetBrains/intellij-plugins/commit/e86eb8c547590222d9f507020c7a93c955cac248#diff-2448159752a9471ebd0701fd25d14fe39233ae05d1709def96902ff278e31827R47

**Comment by rli** [comment]
Should be fixed in the latest version of the AWS CloudFormation plugin
