### ISSUE TITLE
IAM Credentials and Regions fields empty

### ISSUE THREAD

**Issue by rposcro** [aws/aws-toolkit-jetbrains#3133]
**Describe the bug**
I need to set up a new data source using Amazon Aurora MySQL with AWS IAM. I have AWS Toolkit installed, driver version is latest. When I open AWS Explorer tool, it finds correctly my profiles defined in ~/.aws/credentials, I can even find resources I want to connect to there. The problem starts when I want to create a new data source, I picked Amazon Aurora MySQL driver, next authentication method is AWS IAM, I entered User and ... the Credentials and Region dropdowns are empty! Why is it like this?

**To reproduce**
1. In Database Explorer panel click new Data Source
2. Select Amazon Aurora MySQL driver
3. In General tab, choose AWS IAM for Authentication method
4. Type in user name
5. Cannot select Credentials, drop down is empty

**Expected behavior**
I should see loaded AWS credentials and regions in the new Data Source dialog.

**Screenshots**
<img width="476" alt="Screenshot 2022-04-20 at 09 06 59" src="https://user-images.githubusercontent.com/22352352/164170554-7757581e-1cce-4fe8-8fb7-e1ee912a5be2.png">

**Your Environment**
- OS: macOS Monterey 12.2
- JetBrains product: DataGrip 
- JetBrains product version: 2022.1.1
- AWS Toolkit version: 1.42-221 AWS
- SAM CLI version: 
- JVM/Python version: 11.0.14.1.1-2043.25-jcef JetBrain Runtime Bundled

**Additional context**

**Comment by stefanopallicca-imagicle** [comment]
Same happens with Postgres, SecretsManager Auth.
Tried in both Goland and Datagrip

**Comment by rli** [comment]
Same as #3125, should be fixed with `1.43-221`

**Comment by gevorgPayability** [comment]
I can confirm. 1.43-221 has fixed the issue on my machine.
