### ISSUE TITLE
Python Debug is not showing the code but stops

### ISSUE THREAD

**Issue by picostef** [aws/aws-toolkit-jetbrains#3159]
**Your Environment**

- OS:  Windows 11 and mac OS
- JetBrains product: Pycharm community
- JetBrains product version: 2021-3.3
- AWS Toolkit version: 
- SAM CLI version: version 1.35.0
- JVM/Python version: JVM OpenJDK 64b 11.0.14.1+1-b1751.46 amd64 / python 3.9 

**Question**

Hello, 
I am running a  project where several lambda, using docker packaging,  are sharing code that I do not want to duplicate. I created a project where several lambdas are defined with the following mapping:

MAIN_PROJECT
 + events
 | - event files for the lambdas
 + DockerFile-lambda1
 + DockerFile-lambda2
 + template-lambda1.yaml
 + template-lambda2.yaml
 + lambda : code
 + shared_dir : share code
 + lambda1_dir: code specific for lambda1
 + lambda2_dir: code specific for lambda2

In each template file I use:
`    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile-lambda1
`
And in the Dockerfile, I add the code from the shared and specific lambda.
The lambdas can be deployed and are working fine, Running the lmabdas locally also works fine. However when I debug locally the  lambda, debugger is stopping but cannot reference the sources making debugging not usable.
The execution stops, the variable content are filled, but nothing appears on the source tab and the call stack.
How can I get the debugger to work correctly ?

thanks !

![lambda – Lambda_calculs_horairesapp py](https://user-images.githubusercontent.com/47384494/168769694-2c3aca51-599b-4aeb-bae9-66b8631e9260.jpg)
!

**Comment by rli** [comment]
We expose path mappings in the run configuration for this purpose.

Directory structure:
```
untitled1/
    Dockerfile
    hello_world/
        app.py
        requirements.txt
```
Dockerfile:
```Dockerfile
FROM public.ecr.aws/lambda/python:3.9

COPY hello_world/app.py hello_world/requirements.txt ./

RUN python3.9 -m pip install -r requirements.txt -t .

CMD ["app.lambda_handler"]
```

Mapping:
```
/absolute/path/to/untitled1/ -> /var/task
```

![image](https://user-images.githubusercontent.com/742829/169592207-aa8594ae-49f3-4ec8-aee2-5fb0952f5bce.png)

**Comment by picostef** [comment]
Great this works fine !!
Thanks a lot!
