### ISSUE TITLE
Plugin incompatible with 2022.2

### ISSUE THREAD

**Issue by SamD** [aws/aws-toolkit-jetbrains#3172]
**Your Environment**

- OS: Linux
- JetBrains product:
IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
Build #IU-222.2964.55, built on June 9, 2022
Licensed to IntelliJ IDEA EAP user: 
Expiration date: July 9, 2022
Runtime version: 17.0.3+7-b469.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-37-generic
- AWS Toolkit version: 1.43-221

**Question**
Current version of plugin is incompatible with the latest IntelliJ version

![image](https://user-images.githubusercontent.com/321576/173200862-25ff67ac-cc23-4510-9d7a-592d5481c338.png)

**Comment by rli** [comment]
WIP in https://github.com/aws/aws-toolkit-jetbrains/pull/3171

**Comment by rli** [comment]
`1.45-EAP.2022.06.15-222` is now available. keeping open to track any remaining work

**Comment by abdul-malek-octane** [comment]
Still incompatible with:
### Datagrip 2022.2 
- Build: `#DB-222.3345.83`
- OS: `macOS 10.15.7`

**Comment by magauthier-36pix** [comment]
Still not working.
ETA on this?

**Comment by tsposato** [comment]
Same issue here, more of a problem now as IntelliJ IDEA is recommending the upgrade to:
Build #IU-222.3345.118, built on July 26, 2022

**Comment by gmarshall56** [comment]
Yep... I also would like to know when this plugin will be available in IDEA 2022.2, not the EAP.
Thank you

**Comment by rli** [comment]
`1.47-EAP.2022.07.12-222` is available in the EAP channel and works in 2022.2.

`1.48`, which will support 2022.2 as part of the stable channel, should hopefully be out today.

**Comment by rli** [comment]
1.48 has been released
