### ISSUE TITLE
EAP AWS Toolkit - IntelliJ IDEA 2022.2 EAP Ultimate Edition (Build IU-222.2964.55)

### ISSUE THREAD

**Issue by Les-Linux** [aws/aws-toolkit-jetbrains#3176]
**Your Environment**

- OS: 
   - McOS Monterey 12.4
- JetBrains product:
  - IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
- JetBrains product version:
  - EAP Build #IU-222.2964.55, built on June 9, 2022
- AWS Toolkit version:
  - N/A
- SAM CLI version:
  - aws-cli/2.4.10 Python/3.8.8 Darwin/21.5.0 exe/x86_64 prompt/off 
- JVM/Python version:
  - openjdk 18.0.1.1 2022-04-22
     OpenJDK Runtime Environment (build 18.0.1.1+2-6)
     OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
  

**Question**
1. Is there an EAP version of the toolkit available for IntelliJ Ultimate IU-222.2964.55 ?
2. When I follow the instructions for adding the AWS Toolkit EAP Repository to IntelliJ and error is thrown (see attachment)

![Screenshot 2022-06-14 at 13 20 44](https://user-images.githubusercontent.com/1759713/173577527-6cedfe48-3230-4e04-8a31-ca4cc97df9b4.png)

With kind regards.

Les

**Comment by Les-Linux** [comment]
Pretty much identical to [#3172](https://github.com/aws/aws-toolkit-jetbrains/issues/3172) with the difference of it running on MacOS.

**Comment by rli** [comment]
`1.45-EAP.2022.06.15-222` is now available. closing in favor of #3172
