### ISSUE TITLE
Enable Lambda CFN function detection for templates

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#318]
#314 enables detecting function Types "AWS::Serverless::Function", we should enable "AWS::Lambda::Function" too - but it seems to have different properties.

**Comment by abrooksv** [comment]
This is working from our end, but broken on SAM's end: https://github.com/awslabs/aws-sam-cli/issues/728

**Comment by abrooksv** [comment]
Fix went out in SAM 0.8, but we should add an integration test.
