### ISSUE TITLE
Smoother 'getting started' experience

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#324]
Currently if an AWS client called is attempted before the customer has setup/selected their credential file, they get an ugly exception message. Like so:
![2018-10-22_13-22-55](https://user-images.githubusercontent.com/4661536/47317199-d57d4900-d5fd-11e8-9742-8426a0121223.gif)
Instead on the first **explicit** action that requires a valid AWS credential (e.g. clicking the refresh button in the explorer, trying to upload a lambda etc) we should automatically drop customers into the 'select/setup a credential' experience before we attempt the action.

**Comment by justinmk3** [comment]
The "Create new..." selection in the screencast is no longer available.

But going through the "Run Lambda..." dialog shows this now:

![Screen Shot 2020-01-10 at 4 11 41 PM](https://user-images.githubusercontent.com/55561878/72194760-edd4b180-33c3-11ea-96d9-3b2154aea50f.png)

see also recent credential improvements: https://github.com/aws/aws-toolkit-jetbrains/pull/1452 https://github.com/aws/aws-toolkit-jetbrains/pull/1395
