### ISSUE TITLE
"AWS Connection" tab not showing for Python Configuration

### ISSUE THREAD

**Issue by estahn** [aws/aws-toolkit-jetbrains#3253]
**Describe the bug**
I have installed AWS Toolkit and selected a profile but the python script configuration does not contain an "AWS Connection" tab. The experimental setting is enabled.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/362174/183851595-5a641f24-80bb-4d07-97c4-2b0a469a5653.png)
![image](https://user-images.githubusercontent.com/362174/183851773-fbd30b32-fb93-4b21-bbca-7ec6e9095cf2.png)
![image](https://user-images.githubusercontent.com/362174/183852179-9ab25c70-1d29-470e-a73a-9f5ca6e1ca7b.png)

**Your Environment**

PyCharm 2022.2 (Professional Edition)
Build #PY-222.3345.131, built on July 27, 2022
Licensed to New Energy Group Pty Ltd / Enrico Stahn
Subscription is active until April 14, 2023.
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.3)
    name.kropp.intellij.makefile (222.3345.108)
    me.lensvol.blackconnect (0.5.0)
    zielu.gittoolbox (212.9.7)
    org.sonarlint.idea (6.8.0.50884)
    ru.meanmail.plugin.django_command_runner (2020.1-222-EAP-SNAPSHOT)
    org.tonybaloney.security.pycharm-security (1.26.0)
    com.leinardi.pycharm.pylint (0.14.0)
    com.leinardi.pycharm.mypy (0.14.0)
    com.koxudaxi.pydantic (0.3.13)
    ru.adelf.idea.dotenv (2022.2)
    aws.toolkit (1.48-222)

**Comment by rli** [comment]
Released in 1.50
