### ISSUE TITLE
My connection security code is: 1 9 2 6, check that you see the same numbers in my connection approval dialog.

### ISSUE THREAD

**Issue by francopierre** [aws/aws-toolkit-jetbrains#3262]
`My connection security code is: 1 9 2 6, check that you see the same numbers in my connection approval [dialog.](url)`
---
Toolkit: [AWS]([url](url)) Toolkit For JetBrains 1.49-222
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 222

**Comment by rli** [comment]
Closing as the AWS Toolkit does not have any features relating to connection security codes.

If this is an issue with functionality provided by IntelliJ, you'll want to file a ticket directly with JetBrains on their YouTrack: https://youtrack.jetbrains.com/
