### ISSUE TITLE
AWS Toolkit v1.49-222 breaks fluent editing of markdown files

### ISSUE THREAD

**Issue by fbonin** [aws/aws-toolkit-jetbrains#3263]
**Describe the bug**
After installing AWS Toolkit v1.49-222, when filling a list of items in a markdown file, the caret position is not placed at the right place when using `Enter` (it works fine with v1.48)

**To reproduce**
1. Create a new markdown file
2. Enter a list of item like this
```
- Test1
- Test2
```
3. Press `Enter` after the `- Test2`
4. Bug : Cursor will not be be placed at the end of the line but at the beginning instead

**Expected behavior**
The cursor should be placed at the end of the line so that it is easy to enter a new item

**Screenshots**
- Bug:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/732394/184540409-f96f3e38-824e-4617-9a1c-43ac42b7c9db.png">

- Expected behavior:
<img width="94" alt="image" src="https://user-images.githubusercontent.com/732394/184540617-a6839571-d4ed-49fa-a6f2-7a26eac7c69d.png">

**Your Environment**
- OS: macOS Monterey
- JetBrains product: IntelliJ Idea 2022.2
- JetBrains product version: CE and Ultimate edition
- AWS Toolkit version: v1.49-222
- SAM CLI version: N/A
- JVM/Python version: N/A

**Additional context**
This issue happens on a fresh new installation of the plugin. I suspect it is related to the `Code Whisperer` integration but it is clearly disabled.

**Comment by rli** [comment]
Fixed by #3278

**Comment by rli** [comment]
Released in 1.50
