### ISSUE TITLE
[4] Create a UI to track a CFN stack create/update

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#330]
A UI should expose the state of a CFN stack create/update.

In order to give customers visibility into the status of their CloudFormation stacks we need to have a (tool window) UI to display the current, detailed status of a given stack. This would be similar to the CloudFormation UI accessible via the console - however instead of simply showing static content it should update to reflect the current status of updates/deployments.

Each change-set that gets applied to a CloudFormation stack includes the resource modifications that will occur - we can track these changes and 'tick' them off as they are completed giving the customer a much more details view of how 'complete' their stack deployment is. At its simplest, for an inflight create/update this would show a list of resources that require modification and then mark the modification as complete (make them go green?) when CloudFormation has completed that part of the deployment.

**Comment by awschristou** [comment]
Here is the VS Toolkit UI for CFN stack events. It refreshes periodically, adding more entries to the table (newest first): 
![image](https://user-images.githubusercontent.com/39839589/48222550-b266cf00-e349-11e8-952f-e85648d68ee4.png)

Here is the resources tab, which shows you the current state of each resource in the stack:
![image](https://user-images.githubusercontent.com/39839589/48222631-dde9b980-e349-11e8-809c-197cc8a8a54e.png)

**Comment by kiiadi** [comment]
I'd love for us to use 'collapse' the events to make a 'current-state' view for each resource; so building on the Visual Studio example above, we could remove the myS3Bucket 'create in progress' event when we got the 'create complete' event because we know that resource is done.

**Comment by gholt-aws** [comment]
Note: The UX from our add-in to Visual Studio is a reference only. We want to make sure the UX looks natural inside JetBrains IDEs and matches what our customers expect.

**Comment by kiiadi** [comment]
Per @IlyaKazakevich's suggestion in Slack - we could use something similar to the IntelliJ test-tree to show status. There's a few nice things about this:
1) It's already a familiar pattern in IDE
2) We can dynamically add new resources to the list as we 'discover' them (if we're not using a change-set we might not know all the changes up front)
3) There's already a pattern for showing 'in progress', 'success' and 'failure'
![image](https://user-images.githubusercontent.com/4661536/48495911-c8f7a500-e7e5-11e8-8cfe-1e83d7507f69.png)

**Comment by borlander** [comment]
I would also suggest looking at the [`remote-servers` API](https://github.com/JetBrains/intellij-community/tree/master/platform/remote-servers/api/src/com/intellij/remoteServer), which was originally introduced to support exactly the use cases similar to CloudFormation deployments.

**Comment by abrooksv** [comment]
Is remote-servers is all IDEs?

**Comment by abrooksv** [comment]
Our thought is that the system could take a CFN stack name (through a static method) and be able to open a window to show the status of the stack, including resources. If the stack is doing something, such a updating, the window should show new events and update resources based on the status of the resource (updating, rollback, etc)
