### ISSUE TITLE
Fix JavaLambdaHandlerResolver.findPsiElements in the scenario of inheritance

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#331]
**Describe the bug**

`JavaLambdaHandlerResolver.findPsiElements` doesn't correctly return a PsiElement when the target handler is implemented by super class

**To reproduce**
This test fails.
```kotlin
    @Test
    fun testClassHandler_inheritance() {
        val fixture = projectRule.fixture

        fixture.openClass(
                """
            package com.example;

            import com.amazonaws.services.lambda.runtime.Context;
            import com.amazonaws.services.lambda.runtime.RequestHandler;

            public class LambdaHandler {
                public String handleRequest(String request, Context context) {
                    return request.toUpperCase();
                }
            }
            """
        )

        runInEdtAndWait {
            val elements = Lambda.findPsiElementsForHandler(
                    fixture.project,
                    Runtime.JAVA8,
                    "com.example.LambdaHandler::equals"
            )
            assertThat(elements).hasSize(1)
        }
    }
```

**Expected behavior**

The `findPsiElementsForHandler` method should return a valid PsiElement `Object.equals`

**Screenshots**

**Your Environment**
 - OS: Mac
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version: 18.2
 - Toolkit Version:

**Additional context**

More edge cases should be tested:

1. there are multiple implementations in the inheritance chain, the `PsiElement` of the nearest implementation of the inheritance chain should be returned

2. `findPsiElementsForHandler` should be consistent to `LambdaHandlerIndex.listHandlers`, ie. all the handlers returned by the later one should return a valid `PsiElement`, and vise verser.

**Comment by hunterwerlla** [comment]
This was fixed (a long time ago) and has a test now
