### ISSUE TITLE
Mac本地IDEA构建lambda函数的时候发生报错

### ISSUE THREAD

**Issue by wanglin-art** [aws/aws-toolkit-jetbrains#3320]
**Your Environment**

- OS: macOS BigSur 版本11.3.1
- JetBrains product:IDEA
- JetBrains product version: 2021.2
- AWS Toolkit version:212.4746.57
- SAM CLI version: 1.23.0
- JVM/Python version:java 1.8 python 3.8

**Question**
我之前一直在本地idea里正常的上传更新lambda函数，今天照例更新的时候，却遇到了报错。报错截取主要的如下：
```
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('Function', 'property Architectures not defined for resource of type AWS::Serverless::Function')] ('Function', 'property Architectures not defined for resource of type AWS::Serverless::Function')
SAM Build has failed: Command did not exit successfully, exit code: 1
a has failed: Command did not exit successfully, exit code: 1
```

我尝试了创建新的aws lambda函数项目，但是发现新创建的项目也会报这个错误，不清楚问题出在了哪里。

**Comment by wanglin-art** [comment]
该问题已经解决，原因是sam cli 版本 与 aws tookit版本 不兼容导致。更新了sam cli的版本至最新的1.58后即可。

**Comment by angelarosario** [comment]
@wanglin-art Thank you!

**Comment by wanglin-art** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
