### ISSUE TITLE
Support for IntelliJ IDEA Ultimate 2022.3 (Build 223)

### ISSUE THREAD

**Issue by falnyr** [aws/aws-toolkit-jetbrains#3361]
**Describe the bug**
AWS Toolkit is not working with the EAP version of IntelliJ IDEA Ultimate.

**To reproduce**
1. Go to Plugins in IDE
2. Enter the url for the EAP plugin `https://plugins.jetbrains.com/plugins/eap/aws.toolkit` based on [documentation](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-toolkit.html).
3. Get the following error:
![image](https://user-images.githubusercontent.com/6673296/199374227-3c7c2314-3d8d-4a69-9fdf-3736893418f4.png)
4. Download the plugin instead from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/eap.
5. Install plugin from disk
6. Get the following error:
![image](https://user-images.githubusercontent.com/6673296/199374450-1d8e0c25-753a-4348-9697-f8c03ba8daa5.png)

**Expected behavior**
The latest release should support the latest build.

**Your Environment**
- OS: MacOS Ventura
- JetBrains product: IntelliJ IDEA Ultimate
- JetBrains product version: Build #IU-223.7255.1, built on October 25, 2022
- AWS Toolkit version: [1.52-222](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/EAP/241203)

**Comment by falnyr** [comment]
My apologies for labelling this as a bug, but the release `1.52` talks about adding support for `2022.3`.

**Comment by rli** [comment]
Ah sorry, we had issues with our automation that actually weren't resolved until the day you cut this issue.

1.53-EAP.2022.11.02-223 is available and should support #IU-223.7255.1

In the future we'll probably hold off on the changelog note until JetBrains starts releasing stable builds

**Comment by falnyr** [comment]
I can confirm that the new release works. Thank you @rli!
