### ISSUE TITLE
 Assembly AWSSDK.SSOOIDC could not be found or loaded.

### ISSUE THREAD

**Issue by VarukVlad** [aws/aws-toolkit-jetbrains#3365]
I am getting this error when connecting to the SSO aws profile using JetBrains Rider 2022.1.2. I've already found the solution for the Visual Studio 2022 https://github.com/aws/aws-toolkit-visual-studio/issues/268.

I am using the latest version of AWS Toolkit for the current day (1.52-221) 

Login failed for AWS SSO based profile sso-devXXX: Assembly AWSSDK.SSOOIDC could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.SSOAWSCredentials, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604.

**Comment by rli** [comment]
Are you sure this is coming from the toolkit? The error appears to be referring to a .NET assembly but we do not use those in the AWS Toolkit for Rider.

Could you provide some more context on how and when this occurs?
