### ISSUE TITLE
Support of NodeJS 18 runtime for debugging sessions

### ISSUE THREAD

**Issue by christoph-zero** [aws/aws-toolkit-jetbrains#3420]
**Is your feature request related to a problem? Please describe.**
While developing a AWS Lambda function with CDK/SAM I've noticed that AWS Toolkit don't support NodeJS 18 that has been recently released.

<img width="726" alt="Bildschirm­foto 2022-12-22 um 10 55 52" src="https://user-images.githubusercontent.com/98164650/209110847-64eb77f8-a26a-4ec0-94c1-ccf650bbcfbe.png">

Generally available runtimes are: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Are there any plans to support NodeJS 18 in the near future?

   
Environment:
* IntelliJ IDEA 2022.3.1 (Ultimate Edition)
* AWS Toolkit 1.57-223

**Comment by manodnyab** [comment]
Support for NodeJS 18 Lambda runtime is now added in the latest toolkit version 1.58
