### ISSUE TITLE
RDS IAM connectivity over a client VPN endpoint

### ISSUE THREAD

**Issue by silverring19** [aws/aws-toolkit-jetbrains#3525]
**Your Environment**

- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

Question
How to use RDS IAM connectivity over a client VPN endpoint?

I am trying to connect to AWS RDS(not public) using IAM authentication(SSO user) over a client VPN endpoint.My vpn and RDS instance security groups are configured to allow DB traffic from and to VPN network. The connection could be successfully established with  Master password but not with IAM user password(Generated Token). I have created iam user with the same name of dbuser and assigned iam policy as instructed in the AWS Doc.And I am connect to RDS using pgadmin4.

Error Log:

* Trying vpn.ip.xx.xx:1108...
* Connected to rdsauthproxy (vpn.ip.xx.xx) port 1108 (#0)
> POST /authenticateRequest HTTP/1.1
Host: rdsauthproxy:1108
Accept: */*
Content-Length: 1812
Content-Type: multipart/form-data; boundary=------------------------41deee0aeeae0277

* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Content-Type: text/html;charset=utf-8
< Content-Length: 0
< 
* Connection #0 to host rdsauthproxy left intact
2023-03-17 08:19:37 UTC:vpn.vpc.ip.xx(50249):iamuser/dbuser@postgres:[4319]:LOG: pam_authenticate failed: Permission denied
2023-03-17 08:19:37 UTC:vpn.vpc.ip.xx(50249):iamuser/dbuser@postgres:[4319]:FATAL: PAM authentication failed for user "iamuser"
2023-03-17 08:19:37 UTC:vpn.vpc.ip.xx(50249):iamuser/dbuser@postgres:[4319]:DETAIL: Connection matched

**Comment by silverring19** [comment]
Got it!!

**Comment by lorenyu** [comment]
@silverring193 I ran into a similar issue and am seeing the same logs. I'm curious if you could share what you did to resolve your issue and what the root cause was.

**Comment by silverring193** [comment]
@lorenyu PAM authentication failed error occurs if the authentication token is not generated by an IAM user id that is mapped with dbuser id. If u have mapped a dbuser to a SSO user or any IAM user(through IAM Policy), configure SSO  or IAM user profile in cli and generate the authentication token. This authentication token can be used to authenticate with the database instance.
