### ISSUE TITLE
Toolkit incompatible with 2023.1 update

### ISSUE THREAD

**Issue by Kaushik27** [aws/aws-toolkit-jetbrains#3567]
**Describe the bug**
Toolkit incompatible with new Jetbrains update

**To reproduce**
1. Update IntelliJ Community edition to 2023.1 
2. Even before the upgrade it would show error saying the AWS toolkit plugin is incompatible with new Jetbrains update

**Expected behavior**
AWS toolkit should be compatible with the new update

**Screenshots**
![image](https://user-images.githubusercontent.com/8160199/228445488-8213149c-4a2e-4294-9366-6ffb09c953a4.png)

**Your Environment**
- OS: Windows 10 Pro 22H2
- JetBrains product: IntelliJ
- JetBrains product version: IntelliJ IDEA 2022.3.3 (Community Edition)
- AWS Toolkit version: 1.62 223
- SAM CLI version: SAM CLI, version 1.23.0
- JVM/Python version: Python 3.9.13

**Comment by sebastian-zero** [comment]
Same, after upgrade, IDEA says plugin is incompatible. 
![image](https://user-images.githubusercontent.com/95087087/228467418-3f5dac2f-435b-421d-8c7c-ded73540e45c.png)

**Comment by didier-durand** [comment]
Same for me after upgrade of Intellij To 2023.1

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

Runtime version: 17.0.6+10-b829.5 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1

**Comment by GokhanDoganGit** [comment]
Same for me after the latest update

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0

**Comment by rli** [comment]
We will be releasing a 2023.1 compatible version later today
