### ISSUE TITLE
I can't log in ID using CodeWhisperer.

### ISSUE THREAD

**Issue by AeolusJack** [aws/aws-toolkit-jetbrains#3606]
**Your Environment**

- OS: MacOS  inter
- JetBrains product: IntelliJ IDEA 2022.2.3 (Ultimate Edition)
- JetBrains product version: IntelliJ IDEA 2022.2.3 (Ultimate Edition)
- AWS Toolkit version: 1.65-222
- SAM CLI version:  uninstalled
- JVM/Python version: 1.8

**Question**

I can't log in ID using CodeWhisperer. The CodeWhisperer page displays yellow exclamation marks.

What should I do, or is this a bug?

screenshot as follows：

![image](https://user-images.githubusercontent.com/70430961/232649739-77d1bfac-ce49-4ceb-81d1-d7f364bad589.png)

**Comment by vchikoti1998** [comment]
Hello,
Actually, this is not a bug in order to use Code Whisperer, you must sign in using your AWS builderID. Please use this [document](https://docs.aws.amazon.com/signin/latest/userguide/sign-in-aws_builder_id.html) to signUp/ signIn to an AWSBuilder ID.

**Comment by justinmk3** [comment]
- Read https://docs.aws.amazon.com/codewhisperer/latest/userguide/setting-up.html to ensure you have authenticated correctly
- If you are using "Enterprise" or "Professional" CodeWhisperer, read https://docs.aws.amazon.com/codewhisperer/latest/userguide/codewhisperer-setup-enterprise-admin.html

**Comment by AeolusJack** [comment]
Thank you. Problem solved .My version of idea has the id in the lower right corner.

**Comment by AeolusJack** [comment]
solved
