### ISSUE TITLE
CodeWhisperer has issues with Chinese comments

### ISSUE THREAD

**Issue by AnonymMa** [aws/aws-toolkit-jetbrains#3607]
注释的中文显示是乱码

---
Toolkit: AWS Toolkit For JetBrains 1.65-223
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 223

**Comment by rli** [comment]
Could you provide an example?

**Comment by yangqiaosvip** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/33507678/233673149-b59a6a06-5cca-49ad-b95f-44c04081f842.png">

**Comment by backtracker** [comment]
When will this problem be fixed?

**Comment by hengxingstu** [comment]
we need Chinese！！！And also need CodeWhisperer can write comment in Chinese!

**Comment by fe19880924** [comment]
When will this problem be fixed? we need Chinese！

**Comment by nwgdk** [comment]
Any progress? I've encountered the same issue, it seems that it doesn't support Chinese display.

**Comment by fanheyan** [comment]
Toolkit: AWS Toolkit For JetBrains 1.65-223
OS: Windows 10 10.0
IDE: IntelliJ IDEA Ultimate Edition 223

When will this problem be fixed?

**Comment by Github1258** [comment]
I have the same problem here, and I hope it can be resolved soon, please
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/128656262/44b6bd83-247d-4eca-9b00-6bcf932f06cf)

**Comment by backtracker** [comment]
一个乱码问题四个月没处理好，简直离谱

**Comment by cheng470** [comment]
I have same problem. I accepted the code that CodeWhisperer generated and then delete the comment manually :(

**Comment by yufire** [comment]
Why Chinese will display garbled characters。
At present, the code prompt shows a box, and the one inserted into the editor by pressing the Tab key is normal Chinese

**Comment by JackieLeee** [comment]
the same problem
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/50662706/c0df65c0-b70d-4085-885b-ae0a2e42e08f)

**Comment by looplouis** [comment]
Obviously, they've given up.

**Comment by duanluan** [comment]
![~63WRCW~BJQX%1~UD~KAEBB](https://github.com/aws/aws-toolkit-jetbrains/assets/14957667/556c5cef-206f-4747-a4d8-32e8342f2428)

**Comment by nwgdk** [comment]
> Change the editor font, such as `Microsoft YaHei Mono`.

更改这个字体有用吗？

**Comment by duanluan** [comment]
> 更改这个字体有用吗？

当然有用……不然我发出来干嘛

**Comment by Zakariyya** [comment]
> > 更改这个字体有用吗？
> 
> 当然有用……不然我发出来干嘛

我试了没用，不过还是谢谢你

**Comment by Zakariyya** [comment]
I have same problem

**Comment by ican2056** [comment]
instrumented-aws-toolkit-jetbrains-IU-1.77-232.jar中的CodeWhispererInlayRenderer.class替换下就中文正常不乱码了，修改后的源码如下：

**Comment by haitachi** [comment]
同じ問題に遭遇する
どうやって解決すればいいですか。

**Comment by duanluan** [comment]
> 我试了没用，不过还是谢谢你

我 IDEA 和 PyCharm 改了都有用，Codeium 也是同样的问题，我也是这样解决的。

**Comment by kkccboy** [comment]
> 确实. 进入[ 设置 ] ->[ 编辑器 ] ->[ 字体 ], 将字体修改位[ Microsoft YaHei UI ], 则没有乱码的问题了.

谢谢，这个方法的确有用

**Comment by fanpengfei1100** [comment]
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/37178193/4c4ac999-7719-40e7-9658-ff0e61e122da)

fuuuuuuuuuuuck!

**Comment by sunqb** [comment]
此方法有用，我的copilot遇到了同样的问题。最新版的。

**Comment by kv-chiu** [comment]
> 此方法有用，我的copilot遇到了同样的问题。最新版的。

+1，jetbrain的GitHub copilot 1.5.37-242，原本的字体是jetbrains mano，自动补全是方块（乱码），换成微软雅黑ui之后文字正常显示了

**Comment by sunqb** [comment]
> > 此方法有用，我的copilot遇到了同样的问题。最新版的。
> 
> +1，jetbrain的GitHub copilot 1.5.37-242，原本的字体是jetbrains mano，自动补全是方块（乱码），换成微软雅黑ui之后文字正常显示了
> 
> 给后来人补充一些建议，之前人说的把font改成微软雅黑，虽然不再乱码，但由于不是manospaced，terminal里面的字看起来间距会很大，为了解决这个问题，可以在manospaced字体里面选择不乱码的，我选择YaHei consolas Hybrid，同时解决了乱码和间距大的问题

给他们提bug了，，结果插件说是idea的问题，要到2025版才会解决

**Comment by sunqb** [comment]
这个字体比yahei的好看https://github.com/yakumioto/YaHei-Consolas-Hybrid-1.12/blob/master/YaHei%20Consolas%20Hybrid%201.12.ttf。确实。不过还是有点丑。比不上jetbrains mano。
