### ISSUE TITLE
SQL not supported by CodeWhisperer

### ISSUE THREAD

**Issue by thehesiod** [aws/aws-toolkit-jetbrains#3617]
**Describe the bug**
Per the documentation of CodeWhisperer: https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-codewhisperer-generally-available/ SQL is supported, however if I try to ask for suggestions for SQL I get a pop-up that states "SQL is currently not supported by CodeWhisperer"

**To reproduce**

1. Open SQL file
2. Ask for CodeWhisperer to give suggestions
 
**Expected behavior**
A suggestion

**Screenshots**

![Screenshot 2023-04-21 at 12 24 52 PM](https://user-images.githubusercontent.com/4001789/233718486-f7f96adc-8c4e-4704-94b8-e71525038624.png)

**Your Environment**
- OS: OSX 13.3.1
- JetBrains product: PyCharm Professional
- JetBrains product version:2023.1
- AWS Toolkit version: 1.64-231

**Comment by andrewyuq** [comment]
Hi @thehesiod, we started to support sql on Toolkit version 1.65, could you upgrade your plugin to the latest version? Thanks.

**Comment by thehesiod** [comment]
great works thanks!  I'll close.  It's unfortunate that codewhisper only gives you one line at a time suggestion instead of a larger snippet, any roadmap for that type of enhancement?
