### ISSUE TITLE
Codewhisperer not supported in IntelliJ

### ISSUE THREAD

**Issue by jwlogemann** [aws/aws-toolkit-jetbrains#3637]
**Describe the bug**

The howto video for the Codewhisperer installation shows a 'developer tools' tab in the AWS toolkit, however there is no such tabv in the IntelliJ version of AWS toolkit

**To reproduce**
- Install AWS toolkit
- Notice missing developer tools tab

**Expected behavior**

A developer tools tab, so I can login to codewhisperer

**Screenshots**

**Your Environment**
- OS:  Win 10
- JetBrains product: IntelliJ ultimate 
- JetBrains product version: 2020.2
- AWS Toolkit version: 1.32-202
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by justinmk3** [comment]
> AWS Toolkit version: 1.32-202

That's an old version of AWS Toolkit. Latest version is 1.67
