### ISSUE TITLE
AWS lambda configuration windows can't resize 

### ISSUE THREAD

**Issue by royassis** [aws/aws-toolkit-jetbrains#3657]
**Describe the bug**
Can't resize aws lambda configuration windows when **input text box** input is very wide.

**To reproduce**

1. click **Edit Configurations**
2. click the + sign, on the left upper side of the opened windows. 
3. click of AWS lambda local from the opened tab.
4. paste a very long string into the **Text** box.

**Expected behavior**
Can resize window.

**Screenshots**

![07 05 2023_09 49 25_REC](https://user-images.githubusercontent.com/34189329/236662389-7f90fee1-ef31-4189-b61f-2e6d7e9f3349.png)

**Your Environment**
- OS: windows 10
- JetBrains product: pycharm
- JetBrains product version: Build #PY-231.8770.66, built on April 27, 2023
- AWS Toolkit version: 1.67-231
- SAM CLI version: 1.79.0
- JVM/Python version: 3.9

**Additional context**

**Comment by genachka** [comment]
@rli thanks, sorry for the dupe, didn't notice this on my search before I opened a new issue. Just to note here as I did in #3676 this started happening with IntelliJ IDEA 2023.1 and just installed 2023.1.2 and same result in addition to the already reported PyCharm from original poster. Wasn't happening prior in case that helps.

**Comment by genachka** [comment]
Disappointing a fix for this didn't make it in to the just released 1.68. This bug makes working with local debug and AWS services like Lambda very frustrating for more than a month now.

**Comment by genachka** [comment]
Bump

Is no one else bothered by this? It's been 3 releases already since and looks like there's a pull request https://github.com/aws/aws-toolkit-jetbrains/pull/3737 to address it but still not part of release for something clearly broken for more than 3 months now. It's very frustrating to work like this and seems like a fairly simple fix. Can someone please address this!?

**Comment by saurabhajmera** [comment]
This issue should be resolved in version 1.72 of The Toolkit for JetBrains, please create a new issue if you are still experiencing this problem.
