### ISSUE TITLE
Unable to connect to AWS: The security token included in the request is invalid. (Service: Sts, Status Code: 403, Request ID: 35e57f3f-f201-4ac7-b521-4c5cfdba3241, Extended Request ID: null)

### ISSUE THREAD

**Issue by kuok246** [aws/aws-toolkit-jetbrains#3720]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by justinmk3** [comment]
Can you describe the steps you are taking when this happens? Does the issue happen consistently? This can sometimes be a result of intermittent network issues.
