### ISSUE TITLE
Security scans seem to scan the entire venv, not just the dependencies the file being scanned references

### ISSUE THREAD

**Issue by KevinDHunter** [aws/aws-toolkit-jetbrains#3739]
**Describe the bug**
When running a Python security scan in a PyCharm professional project that uses a virtual environment (venv), the security scan appears to always scan every file in the venv, not just files that are imported by the file being scanned.

**To reproduce**
1. Create a PyCharm Python project
2. In the project settings, create a new Python interpreter using a virtual environment in the project directory.
3. Add one or more Python packages to the virtual environment
4. Create a Python file that uses __only__ built-in Python functions.  (Example below)
5. Run a security scan
6. Observe that the list of files scanned includes packages in the venv that are not dependencies of the file being scanned.

Example file:

```
import sys

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
    sys.exit(0)
```

**Expected behavior**
The documentation says that it scans the file and its dependencies, so, in this case, I wouldn't expect it to be scanning packages like `numpy`, `git` etc.  Basically, the current behavior means that every time I want to scan a file, it's going to scan WAY more than is required.

**Screenshots**
List of files scanned:
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/103124531/c5150407-db18-4cf7-ae51-ab8647b942e5)

**Your Environment**
- OS: Windows 11
- JetBrains product: PyCharm Professional
- JetBrains product version: 2023.1.3, Build PY-231.9161.41
- AWS Toolkit version: 1.70-231
- SAM CLI version:
- JVM/Python version: Python 3.8.10

**Comment by zixlin7** [comment]
this is by design, please raise a feature request if you'd like it to be different
