### ISSUE TITLE
EC2 instance connect endpoint support especially in DataGrip

### ISSUE THREAD

**Issue by polyomino24** [aws/aws-toolkit-jetbrains#3741]
**Is your feature request related to a problem? Please describe.**

The AWS new feature EC2 instance connect endpoint(EIC endpoint) make a WebSocket tunnel to a instance, and by using it, we can connect to an AWS RDS/Aurora instance which is not publicly accessible.
DataGrip or IntelliJ's Database plugin doesn't support EIC endpoint setting, so we have to make a tunnel explicitly by ourselves before connecting to an instance.

**Describe the solution you'd like**

I want an EIC endpoint support like an existing SSH tunnel support. This feature will automatically make a tunnel when connecting to an instance, and we don't have to execute a command by ourselves.

**Describe alternatives you've considered**

**Additional context**

**Comment by polyomino24** [comment]
It seems that this service blocks any ports other than 22 (SSH) and 3389 (RDP) now.
So I close this issue.

**Comment by alexitheodore** [comment]
I am also looking for this feature. However, it seems like you @polyomino24 closed your request because "this service blocks any ports other than 22 (SSH) and 3389 (RDP) now." and I don't understand why that would make a difference or undermines the feature?
