### ISSUE TITLE
Datagrip IAM access control

### ISSUE THREAD

**Issue by malhotranishtha** [aws/aws-toolkit-jetbrains#3765]
I am using an AWS toolkit plugin for the Datagrip IDE to connect to the RDS database using IAM authentication. I have configured the sso in my local. When I try to connect the database using connect with the IAM authentication option, it got connected and I am able to see the tables and roles, etc. But my concern here is we are not using passwords for any user just the iam authentication, so I can see who all is having access to that database so anyone can go and login with any of the users present in the database and misuse it. 
So is there any way we can restrict the users to login with other users' accounts or am I missing something while configuring the AWS toolkit plugin?

**Comment by justinmk3** [comment]
This is not something that would be controlled by AWS Toolkit. Instead, you can control access using IAM policies and permissions: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/security_iam_id-based-policy-examples.html
