### ISSUE TITLE
Run local from template doesn't show debug

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#378]
**Describe the bug**

Run line marker on the template doesn't show the debug option until after the Run Configuration has been created.

After the runConfiguration has been created - the debug option appears.

**To reproduce**

1) with a new template (no existing run configurations)
2) click the run marker, only "Run" appears - not "Debug"

**Expected behavior**

should have debug and run options.

**Screenshots**

![screen shot 2018-11-05 at 1 35 46 pm](https://user-images.githubusercontent.com/4661536/48028270-eea6ef00-e0ff-11e8-96c0-d33dc1dfa9a2.png)

**Your Environment**
 - OS: mac
 - JetBrains' Product: pycharm
 - JetBrains' Product Version:
 - Toolkit Version:

**Additional context**

**Comment by abrooksv** [comment]
Fixed in #383
