### ISSUE TITLE
The Chinese characters in the code prompt are garbled

### ISSUE THREAD

**Issue by Github1258** [aws/aws-toolkit-jetbrains#3783]
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/128656262/14bc4b48-97ad-4651-a6f7-954743d94b9c)

---
Toolkit: AWS Toolkit For JetBrains 1.74-232
OS: Windows 10.0
IDE: IntelliJ IDEA Ultimate Edition 232

**Comment by rli** [comment]
Same as https://github.com/aws/aws-toolkit-jetbrains/issues/3607
