### ISSUE TITLE
Creates a new  listings item for a selling partner

### ISSUE THREAD

**Issue by kochanA** [aws/aws-toolkit-jetbrains#3791]
hello,
I try to connect with selling partner account by API I use this documentation: https://sp-api-docs.saleweaver.com/endpoints/listings_items/

Here is a endpoint put_listings_item, but I have no idea what should be included in body of this query. 
Is some precise documentation or tool wich will help me to create and manage listing item ?
I instaled AWS Toolkit but it is not helpful in this case.
Please give me some hints how to do it correctly.

**Comment by rli** [comment]
The linked documentation is not affiliated with Amazon/AWS. Please reach out to the library vendor for further guidance.
