### ISSUE TITLE
Request for Shortcut Toggle to Enable Codewhisperer

### ISSUE THREAD

**Issue by yafeng520** [aws/aws-toolkit-jetbrains#3795]
**Is your feature request related to a problem? Please describe.**
Codewhisperer always provides code insertion suggestions when I don't need them.
PS:I use Codewhisperer as a plugin in JetBrain's IDE

**Describe the solution you'd like**
Could we add a shortcut toggle so that I can press the shortcut when I need it, and then it provides code insertion suggestions?

**Describe alternatives you've considered**

**Additional context**

**Comment by rli** [comment]
This is currently bound to `Alt + C` (Windows/Linux) or `Option + C` (macOS)
https://docs.aws.amazon.com/codewhisperer/latest/userguide/actions-and-shortcuts.html

**Comment by yafeng520** [comment]
got it. thank you!
