### ISSUE TITLE
not display develop tools

### ISSUE THREAD

**Issue by wzglgo** [aws/aws-toolkit-jetbrains#3840]
<img width="427" alt="image" src="https://github.com/aws/aws-toolkit-jetbrains/assets/95947852/840dffc7-89c9-4016-9f0d-1067783813a6">
just have AWS explorer

**Comment by vchikoti1998** [comment]
I believe you are using an outdated version of the AWS Toolkit plugin, please update the plugin and the IDE version to the latest then you will find ```Developer Tools``` tab 
here's the AWS Toolkit plugin marketplace page https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions
