### ISSUE TITLE
tool bar covers the suggestion/ code

### ISSUE THREAD

**Issue by tapanp** [aws/aws-toolkit-jetbrains#3842]
code wisperer toolbar covers the suggestions. this makes difficult to see what it's suggesting.

---
Toolkit: AWS Toolkit For JetBrains 1.76-232
OS: Windows 10.0
IDE: IntelliJ IDEA Ultimate Edition 232

![wisperer](https://github.com/aws/aws-toolkit-jetbrains/assets/48896658/f721661b-2e16-4909-8353-425fd466dc9c)

**Comment by andrewyuq** [comment]
Hi @tapanp , in this case the suggestion is just that single line `assertEquals`, If there are multiple lines in the suggestions, the popup will not block the multi-line suggestion and shown below it.
