### ISSUE TITLE
在生成注释时中文是乱码的

### ISSUE THREAD

**Issue by 15678558873** [aws/aws-toolkit-jetbrains#3843]
---
Toolkit: AWS Toolkit For JetBrains 1.76-223
OS: Windows 11 10.0
IDE: IntelliJ IDEA Ultimate Edition 223

在生成注释时中文是乱码的,都是框框

**Comment by rli** [comment]
Same as https://github.com/aws/aws-toolkit-jetbrains/issues/3607
