### ISSUE TITLE
Please quit making me use a mouse while I'm writing code with a keyboard.

### ISSUE THREAD

**Issue by JonathanHenson** [aws/aws-toolkit-jetbrains#3864]
Hi team. I'm mostly loving code-whisperer, but for it to be useful to me rather than a complete pain that I end up turning off in a rage, I need  key bindings. I don't want to have to use my mouse constantly as I'd usually write the code myself faster than I can switch over to a mouse click. Using the same exact keybindings as the existing autocomplete would be ideal.

---
Toolkit: AWS Toolkit For JetBrains 1.77-223
OS: Mac OS X 13.5.2
IDE: IntelliJ IDEA Ultimate Edition 223

**Comment by JonathanHenson** [comment]
I thought some more about this today. At least in intellij I'd like to have an experience like:

codewhisperer has some suggestions and adds the autocomplete box. If I'm not interested in any suggestions at the moment or I actually want the autocomplete the IDE is trying to give me if the dialog wasn't active, I hit some key like "->". If i want to look at suggestions, I type the down arrow to get to the options. I can use the directional buttons to toggle between suggestions and other options as well. If I change my mind and want to continue with my business I can just hit the esc key to get me back to coding.  If i want to accept a suggestion I should just have to hit the enter key.

**Comment by zixlin7** [comment]
Please try out the key bindings and let us know if it doesn't work
