### ISSUE TITLE
I can connect the AWS Toolkit to AWS, but I get 'No IAM credentials linked' error

### ISSUE THREAD

**Issue by mmeeks100** [aws/aws-toolkit-jetbrains#3883]
**Your Environment**

- OS: macOS 13.6
- JetBrains product: PyCharm
- JetBrains product version: 2023.1.4 Professional Edition
- AWS Toolkit version: 1.79-231
- SAM CLI version: 1.78.0
- JVM/Python version: Python 3.11.2

**Question**

I am attempting to connect to AWS using the AWS toolkit.  I select the option 'Connect using AWS IAM Identify Center' and provide the URL for my AWS user that has already created a number of S3 resources.  I click on connect and go through the logon process successfully.  When I am done, the AWS Toolkit shows the connection:

<img width="866" alt="Screenshot 2023-09-25 at 9 22 40 PM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/2849874/07458ac2-f65f-421b-8203-e6fb43fb35b7">

However, as the screenshot shows, I can't access anything - I get the 'No IAM credentials linked' error.  I have searched the internet, but what I found didn't seem to apply to this case.  Any help would be greatly appreciated!

**Comment by Subhamkr** [comment]
Facing the same issue

**Comment by fangbichen98** [comment]
same issue
