### ISSUE TITLE
AWS Toolkit not compatible with 233 / 2023.3 EAP

### ISSUE THREAD

**Issue by Maksim20023** [aws/aws-toolkit-jetbrains#3913]
**Describe the bug**
The AWS-Toolkit is incompatible with the new RustRover 2023.3 EAP RR-233.8264.22

**To reproduce**
Update RustRover 2023.2 EAP RR-232.9921.62 with installed AWS Plugin 'AWS Toolkit' (version '1.81-232') to RustRover 2023.3 EAP and start.

**Expected behavior**
RustRover should start and not warn about the incompatibilities.

**Screenshots**

<img width="633" alt="Screenshot 2023-10-12 at 3 04 56 PM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/135699123/12b5dc81-f097-4b8d-8add-61b85832773a">

**Your Environment**
- OS: Mac OS X(x86_64) v14.0,
- JetBrains product: RustRover
- JetBrains product version: 2023.3 EAP  RR-233.8264.22
- AWS Toolkit version: 1.81-232
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by bassem-shoukry** [comment]
It's been two weeks;  any update on when this issue will be fixed?

**Comment by rli** [comment]
1.86-EAP.2023.11.08-233 is now available
