### ISSUE TITLE
Maximum recommendation count reached for this month

### ISSUE THREAD

**Issue by mirgong** [aws/aws-toolkit-jetbrains#3944]
**Your Environment**

- OS: 
- JetBrains product:golang
- JetBrains product version:2022.3
- AWS Toolkit version:1.84
- SAM CLI version:
- JVM/Python version:

**Question**
Maximum recommendation count reached for this month.

**Comment by andrewyuq** [comment]
Hi, we have a monthy limit of # of CodeWhisper suggestions available to individual tier users. This monthy quota will reset in November. This sounds expected unless you don't feel you have being using CodeWhisperer a lot.

**Comment by mirgong** [comment]
How do I increase Maximum?

**Comment by andrewyuq** [comment]
maximum is not configurable to individual users as the moment. If you have a specific usecase, please describe here and I can create a ticket to track this.

**Comment by mirgong** [comment]
Okay
