### ISSUE TITLE
EAP version not available at https://plugins.jetbrains.com/plugins/eap/aws.toolkit

### ISSUE THREAD

**Issue by henriquef-cit** [aws/aws-toolkit-jetbrains#3976]
**Describe the bug**
EAP version not available when adding the URL https://plugins.jetbrains.com/plugins/eap/aws.toolkit into Manage Plugin Repositories. I'm using Idea EAP.

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/4265408/bab81346-476e-4fc3-8259-1b2e38204f42)

**Your Environment**
- OS: Ubuntu 22.04.3
- JetBrains product: Idea
- JetBrains product version: Build #IU-233.11555.11, built on November 1, 2023
- AWS Toolkit version: 1.85
- SAM CLI version: 1.67
- JVM/Python version: 17.0.9+7-b1087.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by rli** [comment]
Related: #3913
1.86-EAP.2023.11.08-233 is now available
