### ISSUE TITLE
[0.5/2] Display all existing CloudFormation stacks in Explorer

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-jetbrains#398]
**Is your feature request related to a problem? Please describe.**

User should be able to see a listing of all current CloudFormation stacks in the AWS Explorer

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abrooksv** [comment]
@kiiadi has this in a stash on his laptop, so re-assigning
