### ISSUE TITLE
[CodeWhisperer] disable auto suggestions

### ISSUE THREAD

**Issue by jrieko** [aws/aws-toolkit-jetbrains#3986]
**Is your feature request related to a problem? Please describe.**
CodeWhisperer is useful, but I'm don't need suggestions for everything I write. The automatic popup gets in the way more often than not, so I'd like to disable that, instead use the keybind when suggestions are desired. I don't see any config to do this.

[This request](https://github.com/aws/aws-toolkit-jetbrains/issues/3795) seemed to ask for this, but it was closed without solution for disabling the automatic trigger.

**Describe the solution you'd like**
A config option to disable the unsolicited suggestion popup. Analogous to Idea's toggle for its code completion popup (Editor > Code Completion > Show suggestions as you type).

**Describe alternatives you've considered**
No alternatives I know of. I've disabled the plugin until resolution, because it's just too annoying to constantly press escape while coding.

**Additional context**

**Comment by laileni-aws** [comment]
If you would like to pause the suggestions, then you can goto` AWS Toolkit` > `Developer Tools` > `Pause Auto Suggestions`. This will help to pause the suggestions and if you want to `resume` in the future, you can resume in the same place.
Hope this helps.

**Comment by jrieko** [comment]
Thanks, that does seem to do what I'm asking for. 

Could this be moved into the CW settings section? This seems to me more config than action, as aforementioned analogous to the setting for Idea's code completion suggestions, and the Idea standard UX for config is in settings. If it were there, I would have found it naturally.

**Comment by laileni-aws** [comment]
Thank you for the feedback, we will keep this in the consideration.
