### ISSUE TITLE
Option to disable Amazon Q and CodeWhisperer

### ISSUE THREAD

**Issue by fayyazul-centaurlabs** [aws/aws-toolkit-jetbrains#4065]
**Is your feature request related to a problem? Please describe.**
The bundled plugin Full Line Code Completion by jetbrains gets disabled due to Amazon Q and CodeWhisperer

**Describe the solution you'd like**
The option to disable Amazon Q and CodeWhisperer so the aws toolkit plugin does not conflict with the bundled plugin

**Describe alternatives you've considered**
None so far

**Additional context**
I make use of the plugin mainly for the tools under Explorer, particularly the cloudwatch logs and s3 explorer. Additionally I've found use from the Lambda run configurations. I haven't touched the AI related tools nor do I plan to. I would like to be able to use this plugin alongside the FLCC plugin by jetbrains.

**Comment by TiansuYu** [comment]
It is so annoying that Amazon set the Amazon Q button on the top of the right click list. If you care about developer experience at all, you will not push such blatant marketing moves.

**Comment by justinmk3** [comment]
We are considering how to address this, though it may take some time.

**Comment by Syrus-at-Philips** [comment]
I don't have Codewhisperer or Q setup at all and I'm not allowed to use them in my corporate work environment. The addition of these to the AWS Toolkit has broken full line completion in PyCharm Professional. The features of the AWS Toolkit are essential--managing SSO and the explorer for S3 and Cloudwatch. If I cannot use full line completion, I might as well switch to VS Code fulltime.

**Comment by justinmk3** [comment]
> The addition of these to the AWS Toolkit has broken full line completion in PyCharm Professional.

That sounds like a serious bug, can you open a new issue with details about your system, and steps to reproduce (including things like the kind of code you're editing)?

**Comment by Syrus-at-Philips** [comment]
> > The addition of these to the AWS Toolkit has broken full line completion in PyCharm Professional.
> 
> That sounds like a serious bug, can you open a new issue with details about your system, and steps to reproduce (including things like the kind of code you're editing)?

I will attempt to verify today and follow up here.

**Comment by Syrus-at-Philips** [comment]
Here is the actual problem: 
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/119881585/c436d064-1212-4eeb-9496-b547b7e454bf)
So I cannot use the AWS toolkit to manage my SSO connection and browse S3 and CloudWatch if I want to use full line completion. In this context, it looks somewhat like a "feature" but I agree it is a serious bug.

**Comment by justinmk3** [comment]
That would be helpful as a new, separate issue.

**Comment by Syrus-at-Philips** [comment]
Issue submitted here: https://github.com/aws/aws-toolkit-jetbrains/issues/4076

**Comment by asnare** [comment]
To add a bit of context on this, I do work for several organisations that all have policies (enacted over the last year) banning the use of generative AI from vendors unless it's been through legal and procurement. It depresses me greatly to be writing this, but at the moment not being able to turn Q and CodeWhisperer off in the plugin is going to lead to org-level discussions about banning the plugin outright. Nobody will benefit from this.

**Comment by AutoMatt-ic** [comment]
How do we +1?  Same policy and same problem for me.

**Comment by Forfend** [comment]
Please, let us disable Q and CodeWhisperer. WIth the new release of IntelliJ 2024.1 it's now possible to use Full Line Code Completion due to conflict with plugin

**Comment by GrantGochnauer** [comment]
+1 bump!

**Comment by zixlin7** [comment]
this should be resolved that now Amazon Q is in its own plugin
