### ISSUE TITLE
CodeWhisperer cannot be disabled

### ISSUE THREAD

**Issue by axthosarouris** [aws/aws-toolkit-jetbrains#4068]
Although I have disabled all options, CodeWhisperer suggestions still appear:
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/4091790/ab404cb6-95cd-492b-8592-de0bdcde04e4)

---
Toolkit: AWS Toolkit For JetBrains 2.2-233
OS: Linux 6.2.0-37-generic
IDE: IntelliJ IDEA Ultimate Edition 233

**Comment by maciejb** [comment]
+1 for this. In order to use a different code completion plugin, one currently has to disable the entire AWS Toolkit.

**Comment by zixlin7** [comment]
this should be resolved that now Amazon Q is in its own plugin
