### ISSUE TITLE
Amazon CodeWhisperer Professional - Suggestions with Code References is disabled

### ISSUE THREAD

**Issue by selten** [aws/aws-toolkit-jetbrains#4089]
**Describe the bug**
In PyCharm, the settings for CodeWhisperer state that "Include suggestions with code references" is disabled, while on the AWS side this is enabled.

**To reproduce**
1.  Setup a Amazon CodeWhisperer Professional through IAM Identity Center (SSO) with "enable code references" to true
2. Setup AWS Toolkit on PyCharm
3. Enable code references is disabled in the PyCharm settings

**Expected behavior**
Enable code references box should be checked in the PyCharm settings.

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/961090/f2636bd2-319f-47c0-ad68-a36251156ce9)
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/961090/ff4db9c4-5b9d-4b2c-ac49-61946e79d1d0)

**Your Environment**
- OS: Ubuntu Linux 20.04
- JetBrains product: PyCharm Professional
- JetBrains product version: 2023.2.5
- AWS Toolkit version: 2.2-232
- SAM CLI version: 1.103.0
- JVM/Python version:

**Additional context**

**Comment by zixlin7** [comment]
Hi selten@, for professional users, the "includes code with reference" setting is controlled by your admin, the individual level setting in the plugin will not take effect.

**Comment by selten** [comment]
@zixlin7 hence why I created this issue. I set it on the AWS side to provide these references but that is not set on Jetbrains side.

**Comment by zixlin7** [comment]
understood, what I meant is regardless of how it shows in your JetBrains plugin, you will get suggestions with code references according to the admin setting on your console.
