### ISSUE TITLE
Using Amazon Q, the question prompt keeps focus preventing typing or editing code

### ISSUE THREAD

**Issue by andrewjroth** [aws/aws-toolkit-jetbrains#4100]
**Describe the bug**
When the "Amazon Q (preview)" panel is open, it takes and keeps the cursor focus, preventing any typed input into any other area of the IDE.

**To reproduce**
1. Install the AWS Toolkit and log in or initialize so that the "Amazon Q" feature can be used.
2. Open a project and open any file for editing.  Confirm that you can type in the file edit window.
3. Click the "Q" icon to open the "Amazon Q (preview)" panel.
4. Attempt to type in the previously opened file edit window.

**Expected behavior**
Typed text appears in the file edit window.

**Actual behavior**
Typed text appears in the Amazon Q input prompt.

**Your Environment**
- OS: Ubuntu 20.04.6 LTS
- AWS Toolkit version:  2.4-233

**IDE Details**
```
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Subscription is active until December 2, 2024.
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-91-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3966M
Cores: 16
Registry:
  ide.windowSystem.autoShowProcessPopup=true
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (233.13135.116)
  AWSCloudFormation (233.13135.65)
  ir.msdehghan.plugins.ansible (0.92)
  de.achimonline.ansible_lint (1.5.7)
  com.intellij.ml.llm (233.13135.116)
  com.atlassian.bitbucket.references (2022.1.242)
  Pythonid (233.13135.103)
  aws.toolkit (2.4-233)
Kotlin: 233.13135.103-IJ
Current Desktop: ubuntu:GNOME
```

**Comment by wheaney** [comment]
Just installed Amazon Q for the first time and hit the same thing. It steals the cursor and right-click menus don't appear.

**Comment by wheaney** [comment]
I've found a workaround for this that makes Amazon Q usable: go into the 3-dots menu in the Amazon Q view, and choose `View mode -> Float`

**Comment by alirs76** [comment]
I have this problem too

**Comment by andrewjroth** [comment]
I can confirm that version 2.9-233 has the issue fixed.  Thank you!
