### ISSUE TITLE
RDS datasource failed with error: Token refresh started before session initialized.

### ISSUE THREAD

**Issue by vhnguyenae** [aws/aws-toolkit-jetbrains#4145]
**My Environment**

- OS: MacOs 13.4 , Macbook M2 Pro
- JetBrains product: IntelliJ IDEA (Ultimate Edition)
- JetBrains product version: 2023.3.4 
- AWS Toolkit version: 2.9-233
- AWS Aurora MySQL driver is 1.1.9
- SAM CLI version: Not installed
- JVM/Python version: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9, Python 3.11

**Question**
I failed to setup a Datasource for Amazon Aurora MySQL with the error below:
"Token refresh started before session initialized."
Google search doesn't give back much result that is related 😅 
I'm not sure about the field Secret Name/ARN though. What's the correct syntax ? 

- SecretName SecretARN (with a space in between secret name and ARN)
- only secret Name (or ARN is enough)
Anyway, I tried all 3 possibles syntax but I still got the same error

I also tried to to specify the version 2.11.4 (which is from the Engine version of my RDS Aurora) but still get the same error.

Does anyone encounter the same issue before? How can I fix this?
Thanks in advance for your help.

<img width="972" alt="image" src="https://github.com/aws/aws-toolkit-jetbrains/assets/60604412/9aeab78c-a38a-4d46-a8f8-01bcea078de6">

**Comment by moduspwnens** [comment]
I'm new to DataGrip, but I think I just ran into and solved this issue on my end.

It seems the AWS Toolkit wants to manage its own temporary credentials outside the scope of the AWS CLI. In the main DataGrip window, at the bottom-right corner, you should see a notice about which AWS credentials are in use. For me, there was also a warning icon.

<img width="551" alt="Screenshot 2024-02-27 at 9 54 16 AM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/1111129/8a8713eb-2f44-4141-8018-fcedc4b6d393">

By clicking through that menu, it initiated a separate IAM Identity Center sign-in session in my web browser, and then stored the credential. The warning icon then disappeared, and I was able to connect to my RDS instance.

**Comment by vchikoti1998** [comment]
This has been addressed in #4278

**Comment by vchikoti1998** [comment]
This issue got released in AWS Toolkit version 3.2

**Comment by vhnguyenae** [comment]
@vchikoti1998 I updated the AWS Toolkit to version 3.4 but I still got the same error message :(
