### ISSUE TITLE
SAML auth doesn't work with AWS Toolkit

### ISSUE THREAD

**Issue by baduker** [aws/aws-toolkit-jetbrains#4174]
**SAML authentication doesn't seem to work. None of the profiles I have set up can be loaded.**

I keep getting this error:

`java.lang.IllegalArgumentException: Profile 'default' is not using role-based, session-based, process-based, or basic credentials.`

**To reproduce**
The only way to reproduce is to use the SAML authentication.

**Expected behavior**

Ability to choose profiles loaded via SAML.

**Screenshots**

![Screenshot 2024-03-11 at 11 17 11](https://github.com/aws/aws-toolkit-jetbrains/assets/17427706/238f408f-682a-4671-baee-0468b17b9b9b)

**Your Environment**
- OS: macOS Ventura 13.6.5
- JetBrains product: PyCharm Professional
- JetBrains product version: 2023.3.4
- AWS Toolkit version: 2.11-233
- SAM CLI version: N/A
- JVM/Python version: 3.11

**Comment by rli** [comment]
`saml_auth_url` is not a supported property of AWS-vended tooling

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
