### ISSUE TITLE
Create an option to turn off code suggestions in codewhisperer

### ISSUE THREAD

**Issue by bcmyguest** [aws/aws-toolkit-jetbrains#4247]
**Is your feature request related to a problem? Please describe.**
I want to be able to logout of codewhisperer or turn off suggestions without having to remove the profile from my credentials file.

**Describe the solution you'd like**
Copilot allows you to turn off code suggestions, I think this would be a good solution. 

**Describe alternatives you've considered**
Logout button in codewhisperer window?

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/29989722/428fc6f8-4047-44f3-ae46-d5879c1e1dbf)
No way to turn off code suggestions

**Comment by ankityyz** [comment]
You should see an option to pause auto-suggestions in the "Amazon Q + CodeWhisperer tab" if your Toolkit version is <2.14. On 2.14+, you can find this this option in the "Amazon Q" status bar menu.

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/160793085/1cdd43d6-edf0-46b3-ac1d-299009a733e2)

**Comment by andrewyuq** [comment]
With the latest version of Amazon Q plugin, you should be able to log out Amazon Q while keeping the profile in your aws credentials file. Closing as resolved.
