### ISSUE TITLE
Unable to connect to AWS

### ISSUE THREAD

**Issue by XPLing** [aws/aws-toolkit-jetbrains#4279]
**Your Environment**

- OS: Windows 10 Professional 22H2  19045.4291 Windows Feature Experience Pack 1000.19056.1000.0
- JetBrains product: Webstorm
- JetBrains product version: 2024.1 Build #WS-241.14494.235, built on March 27, 2024
- AWS Toolkit version: 2.18-241
- SAM CLI version: aws-cli/2.4.21 
- JVM/Python version: Python/3.8.8

**Question**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/15956969/d46a1b14-82c0-4e2c-8165-5d709c910ad8)

More Information
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/15956969/b48f6284-9c97-4cac-815e-f100f946b75a)

Proxy
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/15956969/bfcf1aa7-92df-4751-948d-682b189280b9)

I'm sure the network is fine, but after I turn on Webstorm, aws can't connect, it shows that proxyConfiguration and httpRoutePlanner can't be configured at the same time, I want to ask where httpRoutePlanner and proxyConfiguration are configured

**Comment by rli** [comment]
This is due to a recent AWS Java SDK change that attempts to read the proxy configuration from your environment variables (`HTTP_PROXY`, `HTTPS_PROXY`)

**Comment by breedloj** [comment]
Thanks for reporting! This has been addressed in #4291 and will be fixed in the next toolkit release.

**Comment by vchikoti1998** [comment]
The updated Toolkit 2.19 version addresses this issue.
