### ISSUE TITLE
[1] Add credential/region picker to toolwindow config

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#429]
Add this window:
<img width="248" alt="screen shot 2018-11-12 at 10 44 28 am" src="https://user-images.githubusercontent.com/4661536/48368197-f4548580-e667-11e8-9b97-10975ad2f9bf.png">
To the tool-window cog:
<img width="461" alt="screen shot 2018-11-12 at 10 44 13 am" src="https://user-images.githubusercontent.com/4661536/48368207-fb7b9380-e667-11e8-8cb2-a2e9c50c4c3b.png">

**Comment by gholt-aws** [comment]
This seems like a lower priority issue
