### ISSUE TITLE
New project wizzard error

### ISSUE THREAD

**Issue by vict0r81** [aws/aws-toolkit-jetbrains#441]
**Describe the bug**
Unable to create new project, using New project wizzard.

**To reproduce**
1. Go to 'File' -> 'New project...' -> 'SAM' -> 'AWS SAM DynamoDB Event Example'
2. Click on 'Next'
3. Follow the new project wizzard
4. Error window appeared with the text (see screen)

**Expected behavior**
* No error window
* No IDE alert and working New project wizzard.

**Screenshots**
![aws_sam_new_proj_err](https://user-images.githubusercontent.com/8981423/48422225-e0dc1400-e766-11e8-81cf-043f24f5748a.png)

**Your Environment**
 - OS: macOS 10.14.1
 - JetBrains' Product: IDEA
 - JetBrains' Product Version: 2018.2
 - Toolkit Version: '0.2-SNAPSHOT' (commit: e8f7f9d28dcc50cb3639bdf8f243f89db9195681)

**Additional context**
After that I've closed the IDE and tried to create a new project, but was unable to start the New project wizzard at all. All attempts finished with error alert from IDE, see stack-trace in attached gist.
[https://gist.github.com/vict0r81/4d98fb37759d91f5fd27b63d501e3784](https://gist.github.com/vict0r81/4d98fb37759d91f5fd27b63d501e3784)

**Comment by vict0r81** [comment]
P.S. Disabled plugin returns New Project wizzard back to working state

**Comment by abrooksv** [comment]
The stack trace shows you compiled your code with 10, but IntelliJ still runs on the JetBrains' JDK 8 fork. You need to either:
1. Compile with 8
2. Change the kotlin and java plugins to target 8

**Comment by abrooksv** [comment]
I looked and we do target 1.8 for our Kotlin code, but our Java code does not. We should make that change on our end

**Comment by abrooksv** [comment]
We now force the Java code to target 1.8
