### ISSUE TITLE
When selecting the "SAM CLI executable", path selector pop up reappears

### ISSUE THREAD

**Issue by IvanMwiruki** [aws/aws-toolkit-jetbrains#444]
**Describe the bug**
When selecting the "SAM CLI executable", the path selector pop up reappears after making a selection.

**To reproduce**
1. Go to Preferences > Tools > AWS
2. Select "[...]" in the box to the right of "SAM CLI executable"
3. Select Open or Cancel in the pop up -> Pop up reappears (only happens once, if you select Open or Cancel this time the pop is gone, as expected)

**Expected behavior**
Once I've made a selection the pop up no longer appears unless I reselect "[...]"

**Screenshots**
![before-pop-up](https://user-images.githubusercontent.com/13284085/48442893-55518b80-e744-11e8-8cca-b1686aa29330.png)

![during-pop-up](https://user-images.githubusercontent.com/13284085/48442895-584c7c00-e744-11e8-8781-5543d471b7cc.png)

**Your Environment**
 - OS: macOS 10.13.6
 - JetBrains' Product: IntelliJ IDEA 2018.2.6 (Ultimate Edition)
 - JetBrains' Product Version: Build #IU-182.5107.16
 - Toolkit Version: beta

**Comment by abrooksv** [comment]
Was able to reproduce
