### ISSUE TITLE
Amazon Q doesn't work with Flutter.

### ISSUE THREAD

**Issue by feinstein** [aws/aws-toolkit-jetbrains#4459]
**Describe the bug**
 I mainly work with Flutter in Android Studio and after I installed Amazon Q my code is all red, indicating errors all over the place. Probably Amazon Q screw the Dart LSP.

**To reproduce**
Install Amazon Q in Android Studio and open a Flutter app.

**Expected behavior**
Amazon Q should work with Flutter.

**Screenshots**

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/8120472/c921c42d-dd17-4380-aa1b-1f042f886038)

**Your Environment**
- OS: MacOS Sonoma 14.4.1
- JetBrains product: Android Studio
- JetBrains product version:  

Android Studio Iguana | 2023.2.1 Patch 2
Build #AI-232.10300.40.2321.11668458, built on April 4, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.marketplace (232.10300.41)
    Dart (232.10313)
    com.github.fawaz.flutter-freezed-snippets (1.0.9)
    String Manipulation (9.13.0)
    aws.toolkit.core (3.1-232)
    amazon.q (3.1-232)
    idea.plugin.protoeditor (232.10300.51)
    cn.neday.excavator (2.4.7)
    IdeaVIM (2.7.5)
    io.flutter (79.0.1)

**Comment by feinstein** [comment]
I tried it again, this time installing it in IntelliJ IDEA 2024.1.1 (Community Edition). It installs correctly, I can use the Chat, but there's no code auto-completion suggestions. I tried to pause/restart auto-suggestios, but it doesn't work.

**Comment by zixlin7** [comment]
dup of https://github.com/aws/aws-toolkit-jetbrains/issues/4464
