### ISSUE TITLE
Minor optimizations to create application ui

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#447]
Be great to add:
* defaulting the region to the currently active region
* change "(Create new)" drop-down entry into a radio-button style decision point similar to the run configuration input selection:
![screen shot 2018-11-13 at 2 00 51 pm](https://user-images.githubusercontent.com/4661536/48445869-8f269000-e74c-11e8-8bf6-bb680092338b.png)

**Comment by zhangzhx** [comment]
Talked to @kiiadi offline, will remove Region section in the panel to be consistent with create new lambda function panel.
