### ISSUE TITLE
AWS Identity center SSO IAM picker not functional with a large number of available roles

### ISSUE THREAD

**Issue by ethan-anthology** [aws/aws-toolkit-jetbrains#4482]
When authenticated to the toolkit via SSO Start URL, there is a button to `Add IAM Credentials` which brings up a pop up of available roles to choose from. 

<img width="466" alt="Screenshot 2024-05-16 at 10 10 50 AM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/129430577/ddd682d5-9db4-4ac1-975a-a9b8f3f86f95">
<img width="499" alt="Screenshot 2024-05-16 at 10 09 37 AM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/129430577/0284e8aa-9ccd-4155-baa5-4cd7337c4891">

There are a few issues with this view, that are likely only an issue when a very large number of roles are available. 

1. It seems like the list of roles from identity center is paginated and there is no mechanism to trigger it to fetch the next page of options. The pop up shows the first ~25 roles and there is no way to manually enter a role no in the list. That means if the role you are looking for is not available in the first batch, you are out of luck via the ui. 
2. Additionally, the roles do not seem to be sorted in any discernible order. They always appear in the same order, but they are not sorted by account or role name. 
3. The name of the account is also not displayed, just the name of the role and the account number. This view would be much more useful if the name of the account was visible.
<img width="439" alt="Screenshot 2024-05-16 at 10 16 45 AM" src="https://github.com/aws/aws-toolkit-jetbrains/assets/129430577/86ff2059-a42f-4d7d-8a7f-4215553c77e0">

I think the SSO feature is new, and I'm excited about it, it looks like it has the potential to be really helpful for dealing with SSO once these issues are addressed. 

Thank you!

---
Toolkit: AWS Toolkit For JetBrains 3.1-241
OS: Mac OS X 14.4.1
IDE: IntelliJ IDEA Ultimate Edition 241

**Comment by samgst-amazon** [comment]
I've attempted a fix for this here: https://github.com/aws/aws-toolkit-jetbrains/pull/4892

There you can find a 241 build including the fix under the checks-> Linux Unit [2024-1]-> details where you can directly download a .zip of the plugin for use.
