### ISSUE TITLE
Amazon Q Plugin on Intellij is stuck at authenticating in browser screen but browser does not open for SSO

### ISSUE THREAD

**Issue by elamaran11** [aws/aws-toolkit-jetbrains#4487]
**Describe the bug**
Amazon Q Plugin on Intellij is stuck at authenticating in browser screen but browser does not open for SSO

**To reproduce**
Use the latest version of IntellIj and Install latest Amazon Q plugin, try to authenticate via Pro License and provide SSO URL and region, browser open action is not triggered and auth is stuck at `Authentication in Progress` for ever.

**Expected behavior**
Authentication to happen redirected to browser

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/51791117/08312c41-2a6f-4ed0-808d-8436bf03f1ab)

**Your Environment**
- OS:  Mac M1
- JetBrains product: IJ
- JetBrains product version: latest
- AWS Toolkit version: Latest
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by bryceitoc9** [comment]
Hi @elamaran11 

Just checking, what version of the toolkit are you on? Additionally, do you have any existing/timed out SSO connections? If so, can you try signing out of them and signing back in?

**Comment by elamaran11** [comment]
Issue was with space delimitation in AWS credential and config file. Once i fixed it, everything worked.

**Comment by cw-pradyumna** [comment]
Faced the same issue when I migrated from 2022 to 2024 community pycharm. It worked when I uninstalled and reinstalled the aws plugins

**Comment by willmakley** [comment]
> Issue was with space delimitation in AWS credential and config file. Once i fixed it, everything worked.

Can you please clarify what you fixed?

**Comment by gunjanjain1** [comment]
I am having the same issue. Please suggest.

**Comment by badverybadboy** [comment]
To fix this invalidate caches and restart

Goto File > Invalidate caches > delete embedded browser engine caches and cookies
