### ISSUE TITLE
Amazon Q + AWS Core makes IntelliJ irresponsive

### ISSUE THREAD

**Issue by felipedeoliveirarios** [aws/aws-toolkit-jetbrains#4558]
**Describe the bug**
Once Amazon Q and AWS Core plugins updated today to 3.9.241, IntelliJ became irresponsive. I was unable to use commit or database sidebars, and most dialogues stopped opening. Deactivating the plugins makes the IDE work again.

**To reproduce**
1. Install/Enable Amazon Q plugin into IntelliJ 2024.1.2
2. The database sidebar shouldn't be working now, nor the commits sidebar or any run configurations at the gradle sidebar.

**Expected behavior**
IDE keeps working with updated plugins.

**Screenshots**
Plugin Disabled:
![Captura de tela de 2024-06-07 11-18-06](https://github.com/aws/aws-toolkit-jetbrains/assets/23152673/da13f759-b898-4a94-a1bf-361fce09d37c)

Plugin Enabled:
![Captura de tela de 2024-06-07 11-16-13](https://github.com/aws/aws-toolkit-jetbrains/assets/23152673/ea7cff47-78e1-4072-9e1b-0f3eed83cd46)

Error while running project with plugin enabled (gradle bootRun):
![Captura de tela de 2024-06-07 11-21-29](https://github.com/aws/aws-toolkit-jetbrains/assets/23152673/757b7946-56d5-4bfa-b39a-86c252bf7a71)

**Your Environment**
- OS: Ubuntu 22.04.4 LTS
- JetBrains product: IntelliJ
- JetBrains product version: 2024.2.1
- AWS Toolkit version: 3.9.241
- SAM CLI version:
- JVM/Python version: JVM Amazon Coretto 11.0.23

**Additional context**
Extra enabled plugins:
- Material Theme UI 9.3.1 by AtomMaterial
- Atom Material Icons 97.0.0 by AtomMaterial
- CodeGlance Pro 1.8.5 by Nasller
- Commit Message Template 1.8.0 by Eugene Kozhun

**Comment by rli** [comment]
Related https://github.com/aws/aws-toolkit-jetbrains/issues/4556

**Comment by Sangeethachan** [comment]
RELATED #4554

**Comment by rli** [comment]
Based on last screenshot, `getVirtualFile(...) must not be null`, implies same as #4554
