### ISSUE TITLE
Amazon Q break configuration and run java application java.lang.NullPointerException: getVirtualFile(...) must not be null

### ISSUE THREAD

**Issue by fabriciormartins** [aws/aws-toolkit-jetbrains#4559]
**Describe the bug**
After update for 3.9-241, my configured applications to run were broken when I try to start. The configuration of run open but don't show any data to try change.

**To reproduce**
You'll need a simple java application and a simple main method to startup and the version
1. Go to java class and main method
 2. Click on the play icon to run it
 3. Scroll go to notifications 
 4. See error java.lang.NullPointerException: getVirtualFile(...) must not be null

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: Windows 10 Enterprise - 22H2 - Compilation: 19045.4412
- JetBrains product: IntelliJ IDEA 2024.1.1 (Community Edition)
- JetBrains product version: #IC-241.15989.150, built on April 29, 2024
- AWS Toolkit version: 3.9.241
- SAM CLI version: -
- JVM/Python version: 17.0.10+1-b1207.14

**Additional context**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/32100573/06d21e8d-c046-4a8c-8fd2-f24daf73c608)

**Comment by rli** [comment]
Same as https://github.com/aws/aws-toolkit-jetbrains/issues/4554
