### ISSUE TITLE
Amazon Q break configuration and run java application java.lang.NullPointerException: getVirtualFile(...) must not be null 

### ISSUE THREAD

**Issue by Sangeethachan** [aws/aws-toolkit-jetbrains#4563]
After updating AWS TOOLKIT GOT THE ERROR Error Type:

java.lang.NullPointerException: This error occurs when an application attempts to use null in a case where an object is required. This usually happens when trying to call a method on a null object.
Specific Location:

software.aws.toolkits.jetbrains.services.codewhisperer.codescan.listeners.CodeWhispererCodeScanFileListener.editorCreated(CodeWhispererCodeScanFileListener.kt:18): The error occurs at line 18 of the CodeWhispererCodeScanFileListener.kt file in the editorCreated method.

**Your Environment**
- OS: WINDOWS
- JetBrains product:PYCHARM COMMUNITY EDITION
- JetBrains product version: 2023.3.5
- AWS Toolkit version: 3.9-233
- SAM CLI version:
- JVM/Python version:PYTHON 3.8

**Additional context**

**Comment by rli** [comment]
Same as https://github.com/aws/aws-toolkit-jetbrains/issues/4554
