### ISSUE TITLE
Cannot login with sso profile

### ISSUE THREAD

**Issue by go-gritsanapong-pun-nxz-group** [aws/aws-toolkit-jetbrains#4610]
When I update to 3.12-241 I can't login aws with sso profile

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/143983473/6714627f-e313-4f77-a1e6-92a7a7775aa6)

---
Toolkit: AWS Toolkit For JetBrains 3.12-241
OS: Mac OS X 14.2.1
IDE: IntelliJ IDEA Community Edition 241

**Comment by tomaszlukasik** [comment]
Not sure if it's gonna work in your case, but clearing `~/.aws/sso/cache/` solved the problem for me. 🤞

**Comment by steve-ochoa** [comment]
@tomaszlukasik fix works for me. I had the exact same issue with IDE: IntelliJ IDEA Ultimate Edition 232

**Comment by rli** [comment]
Fix released in 3.13
