### ISSUE TITLE
Amazon Q chat window frozen

### ISSUE THREAD

**Issue by millturnK** [aws/aws-toolkit-jetbrains#4628]
**Describe the bug**
I am using the Amazon Q plugin (v3.14) for JetBrains (Pycharm). I am logged in to my AWS Builder account. The Amazon Q chat window is blank (no way to enter a prompt).

**To reproduce**
1. Log into AWS Builder account
2. Click on the Chat icon

**Expected behavior**
A prompt to allow interaction with Amazon Q
**Screenshots**

**Your Environment**
- OS: Ubuntu 16
- JetBrains product: Pycharm 2023.2
- AWS Toolkit version: Amazon Q, AWS Core, AWS Toolkit 3.14, 
- JVM/Python version: 3.10

**Additional context**
It sometimes comes back after I repair the IDE and exit. But not anymore. I upgraded today to the latest versions of AWS plugins
![Screenshot from 2024-06-28 11-22-15](https://github.com/aws/aws-toolkit-jetbrains/assets/16495835/d2a8a2c1-9f42-47e9-8191-7f0660fbd884)

**Comment by manodnyab** [comment]
Hi, do you have external monitors attached to your system?

**Comment by aman-agarwal-299** [comment]
Hi @millturnK I am Aman and I have faced somewhat similar issue in my laptop. I use Intellij via WSL in my windows laptop. When I installed Amazon Q plugin and tried to open the chat box, I got the same blank screen. I installed Amazon Q cli in my WSL and then the blank screen disappeared and it started working. You can try this if you want. Hope this helps!
