### ISSUE TITLE
Support IntelliJ 2024.2 (EAP)

### ISSUE THREAD

**Issue by devurandom** [aws/aws-toolkit-jetbrains#4663]
**Is your feature request related to a problem? Please describe.**

JetBrains provides EAP versions of IntelliJ 2024.2, but the AWS Toolkit plugin does not have an (EAP) version that would support this IntelliJ version.

**Describe the solution you'd like**

An (EAP) version of the AWS Toolkit plugin that supports IntelliJ 2024.2.

**Comment by rli** [comment]
Released with 3.18
