### ISSUE TITLE
Azmaon DeveloperQ chat does not show up in Android Studio Koala Feature Drop | 2024.1.2 

### ISSUE THREAD

**Issue by mikegehard** [aws/aws-toolkit-jetbrains#4898]
**Describe the bug**
Amazon Q chat window does not show up in sidebar and can now be opened in Android Studio.

**To reproduce**

1. Click on Amazon Q in the bottom right corner of Android Studio
2. Click on "Open Chat Panel"
3. Nothing happens.

**Expected behavior**
I expected the chat panel to open.

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:

Android Studio Koala Feature Drop | 2024.1.2
Build #AI-241.18034.62.2412.12266719, built on August 22, 2024
Runtime version: 17.0.11+0-17.0.11b1207.24-11852314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2304M
Cores: 11
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  Key Promoter X (2024.2.0)
  aws.toolkit.core (3.29-241)
  Docker (241.18034.82)
  amazon.q (3.29-241)
  com.jetbrains.kmm (0.8.3(241)-9)

- SAM CLI version:
- JVM/Python version:

** Other information**
Option -  c code generation works.
inline code completion using // works fine.

**Comment by rli** [comment]
You can try enabling JCEF in the IDE registry
https://github.com/aws/aws-toolkit-jetbrains/issues/4124#issuecomment-2156786274

**Comment by mikegehard** [comment]
Thanks for the tip. That did not work. :-(

![image](https://github.com/user-attachments/assets/7f5613ee-fd3f-4b29-8b7a-5849edaae583)

![image](https://github.com/user-attachments/assets/8e43e408-6d09-4381-a4e3-6b2aee910d38)

**Comment by rli** [comment]
Glad that worked for you.

I guess select "last SDK" should be amended to be "latest JBR with JCEF".
