### ISSUE TITLE
WebStorm: Amazon Q: Fails with "Unable to load client registration from cache"

### ISSUE THREAD

**Issue by ljbrown238** [aws/aws-toolkit-jetbrains#4985]
**Description**
After using Amazon Q for about 30 minutes, an error suddenly occurs.
This has happened twice.
Must disable and re-enable to continue use.

> An error occurred while processing your request.
> This error is reported to the team automatically. We will attempt to fix it as soon as possible.
> 
> Details: Unable to load client registration from cache
> 
> Session ID: GUID

**To reproduce**
Run Amazon Q in WebStorm 2024.2.3
Interact for some amount of time.

**Environment**
- OS: MacOS: 14.6.1 (23G93)
- JetBrains product: WebStorm
- JetBrains product version: 2024.2.3
- AWS Toolkit version: 3.33 - 242

**Comment by karlkovaciny** [comment]
This also happened to me on RDS. Fixed it by deleting my ~/.aws/config and recreating with `aws configure sso`.

**Comment by ljbrown238** [comment]
3.34 Resolved my issue.  Thank you!!!
