### ISSUE TITLE
I am getting "Unable to load client registration from cache" error while using /transform operation  

### ISSUE THREAD

**Issue by vprudhvi01** [aws/aws-toolkit-jetbrains#4987]
Description
After using Amazon Q for about 1 week and i am getting "Unable to load client registration from cache" from last couple of days.
Tried deleting cache, disable and re-enable the plugin in IDE but still facing the issue 

---
Toolkit: Amazon Q For JetBrains 3.33-241
OS: Windows 11.0
IDE: IntelliJ IDEA Community Edition 241

**Comment by erikpragt-connectid** [comment]
Hi @vprudhvi01 , interesting, I've got exactly the same on my end:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/da0bdb6c-1dc9-470b-882d-72d8e7a82c50">

The code compiles fine, I'm getting "I was able to build your module and will start uploading your code.", but after that, nothing. I'm a Mac Btw, using IntelliJ Ultimate 2024.2.3.

**Comment by manodnyab** [comment]
Hi, sorry for this issue, we are working on this, will let you know when there is an update!

**Comment by manodnyab** [comment]
Hi, we've fixed this issue in v3.34. Can you please update to the latest version and check if this issue still persists?

**Comment by vprudhvi01** [comment]
Hi @manodnyab , Thanks for the update and i was able to /transform with V3.34
