### ISSUE TITLE
High CPU usage at IDLE

### ISSUE THREAD

**Issue by evstigneev-yus** [aws/aws-toolkit-jetbrains#5000]
**Describe the bug**
After enabling Amamzon Q plugin in IntelliJ my laptop blasting all fans and showing high CPU usage on any opened Java project at IDLE. 
Without Amazon Q plugin I open same project and see no load on CPU while IDLE.
From attached screenshots you can see that some background kotlin coroutines debug process is going on.

**To reproduce**
Enable Amazon Q plugin in IntelliJ
Open any Java project
Observe CPU load at IDLE 

**Expected behavior**
No background processes without indication to user. 
User able to stop unnecessary background processes.

**Screenshots**
Fans
![Screenshot from 2024-10-22 16-51-30](https://github.com/user-attachments/assets/4e081aa3-abf5-4074-94f0-9c0c1115ca9d)
Activity Monitor from IntelliJ
![Screenshot from 2024-10-22 16-50-25](https://github.com/user-attachments/assets/d9e067e3-86df-4beb-b601-e482d3e9162b)

**Your Environment**
OS: Ubuntu 22.04.5 LTS
IntelliJ: Build #IU-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Amazon Q plugin version: 3.34-242

**Comment by netojoaobatista** [comment]
I am experiencing the exact same issue in PHPStorm 2024.2.3 with the Amazon Q plugin version 3.34-242. After enabling the plugin, the CPU usage spikes significantly even when the IDE is idle, much like what was observed in IntelliJ.

**Comment by rli** [comment]
Do you have a process named `Amazon Q Helper` taking up CPU?

**Comment by evstigneev-yus** [comment]
> Do you have a process named `Amazon Q Helper` taking up CPU?

No, there are only idea processes in process list
![image](https://github.com/user-attachments/assets/13be95d2-0e5b-44cb-bdca-f6fa421ca895)
![image](https://github.com/user-attachments/assets/11ee95f5-d091-4a8c-91f8-75a5060c05aa)

**Comment by sam5827** [comment]
Same problem here. Was working fine up until about 22nd Oct 2024. Since then, CPU usage is high from the moment I open the IDE with a Java project and the plugin is idle. Had to disable the plugin as well because the high CPU is making fans go mad and slowing everything down!
It's the IntelliJ Java process that is consuming the CPU when the plugin is enabled. All returns to normal when the Amazon Q plugin is disabled.

OS: Ubuntu 20.04.5 LTS
IntelliJ: Build #IU-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Amazon Q plugin version: 3.34-243

**Comment by jhuebner79** [comment]
I just came here to say that I experience the same - without having changed a thing the CPU usage goes up when the Q plugin is enabled. It uses all four physical cores of my laptop, resulting in near 400% CPU usage.

**Comment by mmadrono** [comment]
I have the same problem with Intellij version :

![image](https://github.com/user-attachments/assets/53606c63-ab49-44eb-b8b6-65362ee9d5a6)

My OS is MacOS 15.1. and with the Amazon Q plugin enabled the CPU consumption is very high, I had to disable it, and once disabled the Intellij program returns to normal execution levels, this happened in all projects that are opened regardless of the code of the projects

**Comment by evstigneev-yus** [comment]
Update plugin to 3.36-242, fixed issue for me
