### ISSUE TITLE
Hide Deploy Application in unsupported environments

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#521]
**Describe the bug**

Deploy application is currently not supported in all IDE's - only Python is supported currently. 
**To reproduce**

**Expected behavior**

Deploy Application should not appear as an option in a Java project.

**Screenshots**

<img width="640" alt="screen shot 2018-11-19 at 10 42 36 am" src="https://user-images.githubusercontent.com/4661536/48727845-35104980-ebe8-11e8-85b2-e9fcad764aed.png">

**Your Environment**
 - OS: Mac
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version:
 - Toolkit Version: SNAPSHOT

**Additional context**

**Comment by yangnaihua** [comment]
It's not support language Java to deploy serverless application forever?

**Comment by zhangzhx** [comment]
Hi @yangnaihua , we are using [AWS SAM Builder](https://github.com/awslabs/aws-lambda-builders) under the hood for building the project. The Java runtime is currently not supported, but we'll support that once it is supported in AWS SAM Builder.
