### ISSUE TITLE
SAM CLI not auto-detected even though it is on the PATH

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#534]
**Describe the bug**

Reported by @danilop : SAM CLI executable is not auto-detected once home-brew version is removed and pip version is re-installed.

**To reproduce**

```
$ which sam
/Users/danilop/Library/Python/3.7/bin/sam
$ sam --version
SAM CLI, version 0.7.0
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/danilop/Library/Python/3.7/bin
```

**Expected behavior**

SAM is available on the PATH and should be auto-detected.

**Your Environment**
 - OS: Mac
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version:
 - Toolkit Version: feature/application-deploy

**Additional context**

**Comment by abrooksv** [comment]
Could not repro, was IntelliJ restarted after PATH was updated?

**Comment by abrooksv** [comment]
Could not repro, was IntelliJ restarted after updating PATH?

**Comment by kiiadi** [comment]
@danilop - that's a great point - if you updated the PATH after the IDE was started (ie: installed from pip) then the IDE won't see the changed environment variable - they only get assigned on startup.

Do you still see this issue if you restart PyCharm?

**Comment by abrooksv** [comment]
SAM team now treats installing through pip as an anti-pattern. I dont think we should support auto-detect with pip installs
