### ISSUE TITLE
Decent error handling when failed to load resources in ComboBox 

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#535]
**Describe the bug**
We currently don't handle exception in `UiUtils.populateValues` when the `block()` throws exception. We should show a validation failure when any exception is thrown.

**Comment by rli** [comment]
We also need to ensure the validation for a serverless deploy catches "Loading..." if the user is barreling through the dialogs

```
Unable to upload artifact HelloWorldFunction referenced by CodeUri parameter of HelloWorldFunction resource.
S3 Bucket does not exist. Execute the command to create a new bucket
aws s3 mb s3://Loading...
```
