### ISSUE TITLE
Python Intellij debug breakpoint not working

### ISSUE THREAD

**Issue by asyba** [aws/aws-toolkit-jetbrains#540]
**Describe the bug**
In Python with Intellij.

I tried to debug with breakpoints, but is not stopping in the breakpoints.
I check and there is no log in idea.log when doing debug.

```
/home/federico/.local/bin/sam local invoke --template "/tmp/[Local] TrackingPackageLambda-template233.yaml" --event "/tmp/[Local] TrackingPackageLambda-event832.json" TrackingPackageLambda --debug-port 45011 --debugger-path /home/federico/.IntelliJIdea2018.2/config/plugins/python/helpers/pydev --debug-args "-u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 45011 --file"
2018-11-19 23:11:09 Invoking src/main/python/test.lambda_handler (python3.6)
2018-11-19 23:11:09 Found credentials in environment variables.
2018-11-19 23:11:09 Decompressing /tmp/174723106203627107.zip

Fetching lambci/lambda:python3.6 Docker container image......
2018-11-19 23:11:14 Mounting /tmp/tmp_fdk1A as /var/task:ro inside runtime container
Connected to pydev debugger (build 182.5107.16)
START RequestId: 99de8c9d-9eaa-4ea5-8a93-2b2c01c24152 Version: $LATEST

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
<__main__.LambdaContext object at 0x7f0ba4873eb8>
{"key1": "value1", "key2": "value2", "key3": "value3"}
END RequestId: 99de8c9d-9eaa-4ea5-8a93-2b2c01c24152
REPORT RequestId: 99de8c9d-9eaa-4ea5-8a93-2b2c01c24152 Duration: 1 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 28 MB
```

**Your Environment**
 - OS: Ubuntu 18.04.01 LST
 - JetBrains' Product: IntelliJ IDEA 2018.2.4 (Ultimate Edition)
 - JetBrains' Product Version: Build #IU-182.4505.22, built on September 18, 2018
 - Toolkit Version: 0.1

**Comment by abrooksv** [comment]
Your 'src' is a source root, correct?

**Comment by abrooksv** [comment]
Merged some changes for this.

Using the src roots from project structure, this template should work:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  TrackingPackageLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: TrackingPackageLambda
      Handler: main/python/test.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: "TrackingPackageLambda"
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          test: test
          PYTHONPATH: "/var/runtime:/var/task/lib"
```

**Comment by asyba** [comment]
Okey it works!
Question: what I can do if the .py are in a "target/" folder outside of the "src" ?
Because now it failing for the libraries that are not in the "src", so I have installed them in a "target/" folder.

**Comment by abrooksv** [comment]
Like 3rd party dependencies? They get taken from your SDK's virtual env.

**Comment by asyba** [comment]
Yeah 3rd party, oh I am kind new beginner in aws and wasn't using virtual env in the lambda project.
Do you know easy way to configured, like a web page guide (prefer not from aws docs like they don't explain much of this)?

**Comment by abrooksv** [comment]
You have to make a new Python SDK in PyCharm with type Virtual Env and set that as the Project SDK.

Have you tried the Hello World example that you can get through File->New Project?

**Comment by asyba** [comment]
Yes I have that, but where I install the modules? rigth now I am going to any Terminal and I do "pip install or pip3 install" and just that.

**Comment by asyba** [comment]
Ho I have to install in the Packages in the UI of Intellij?

**Comment by asyba** [comment]
Okey that work! cool!
Should I close this issue? also the previous one.

**Comment by abrooksv** [comment]
You can use requirements.txt to install into the venv in IDE

https://www.jetbrains.com/help/pycharm/managing-dependencies.html or use pip to install into the venv

**Comment by abrooksv** [comment]
If its all working, I'll close them

**Comment by asyba** [comment]
@abrooksv other question if I have a file in the project /resource/driver.ll for example how can I add that file to sam local invoke so I can read in the python code that path file?
