### ISSUE TITLE
PyCharm new sam project UI not showing Edit button

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#544]
**Describe the bug**
During creating a new sam project in PyCharm, when sam cli is not configured correctly, the `edit` button is not shown correctly, and the UI cannot be resized or maximized. There is no way to proceed.

**Screenshots**
<img width="667" alt="pycharminitui" src="https://user-images.githubusercontent.com/7167513/48792321-ccd56c80-eca8-11e8-861b-d034df847b60.png">

**Your Environment**
 - OS: mac
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2018.2
 - Toolkit Version:

**Comment by rli** [comment]
Related to #525

**Comment by zhangzhx** [comment]
Dup to #525, closing
