### ISSUE TITLE
Can't create new project in PyCharm

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#551]
**Describe the bug**

New project screen locks up when trying to create an AWS Serverless Application. Reported by @normj 

**To reproduce**

1) SAM CLI is not installed
2) Open PyCharm
3) Select AWS Serverless App
4) Typing the name freezes for lengthy periods on each key-press

**Expected behavior**

Should be able to create a new project

**Screenshots**

**Your Environment**
 - OS: Windows
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: Community
 - Toolkit Version:

**Additional context**

**Comment by normj** [comment]
Actually I had SAM CLI installed. I just installed the latest MSI.

**Comment by kiiadi** [comment]
what version is that? (`sam --version`)

**Comment by normj** [comment]
Version: 0.7.0

**Comment by kiiadi** [comment]
Cool – that’s the correct version!
