### ISSUE TITLE
Plugin 'AWS Toolkit' is incompatible with this installation - IntelliJ IDEA 2016.3.3

### ISSUE THREAD

**Issue by torstenfeld** [aws/aws-toolkit-jetbrains#569]
**Describe the bug**
I wasn't able to install the plugin from disk as the version is not supported.

**To reproduce**
1. just following the installation instructions from the beta invite (Installation from disk)

**Expected behavior**
1. Plugin is installed

**Screenshots**

![image](https://user-images.githubusercontent.com/536913/48824673-34e98880-ed65-11e8-9548-003d77b46e9b.png)
![image](https://user-images.githubusercontent.com/536913/48824690-47fc5880-ed65-11e8-9735-ef50985368cc.png)

**Your Environment**
 - OS: Windows 10 DE
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: 2016.3.3
 - Toolkit Version: n/a

**Additional context**
Going to install latest IDE version.

**Comment by torstenfeld** [comment]
> @torstenfeld in the README for this repo _"Minimum supported version of IntelliJ platform is 2018.2"_ - I'd try again with 2018 version

you're right. Just update to the 2018 version and everything is working as expecting; hence closing the issue. Thanks!

**Comment by marakere** [comment]
I am having the same problem with the latest version 2018.2.6 Community Edition. 
Error: PLugin 'AWS Toolkit' is incompatible with this installation.

**Comment by abrooksv** [comment]
1.0 requires 2018.3 to run in prep for utilizing new APIs

**Comment by marakere** [comment]
Thanks, @abrooksv. Is version 2018.3 available? I don't see that version on JetBrains website.

**Comment by abrooksv** [comment]
https://www.jetbrains.com/pycharm/download/#section=mac and https://www.jetbrains.com/idea/download/#section=mac both are 2018.3 now.

**Comment by marakere** [comment]
ThankU @abrooksv. I can download and add the plugin. 
Appreciate your quick response.

**Comment by jeremyforan** [comment]
I was getting the same issue with 2019.2.6 Pycharm community macOS, updated to 2018.3 and it resolved the issue.
