### ISSUE TITLE
Credentials Update

### ISSUE THREAD

**Issue by nitinkurian** [aws/aws-toolkit-jetbrains#571]
**Describe the bug**
Credentials Update are not reflected immediately and requires an IDE restart.

**To reproduce**
1. Go to 'AWS Connection Settings' 
2. Click on 'Edit AWS Credential File'
3. Add a new profile
4. Newly created profile is not shown

**Expected behavior**

**Screenshots**

**Your Environment**
 - OS: Mac 10.13.6
 - JetBrains' Product: PyCharm Professional
 - JetBrains' Product Version: 2018.2
 - Toolkit Version: 0.2

**Additional context**

**Comment by abrooksv** [comment]
This is currently being tracked as feature request #260
