### ISSUE TITLE
Runtime in run configuration is not disabled on initial dialog open

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#618]
![untitled2](https://user-images.githubusercontent.com/742829/49099455-58f60f80-f226-11e8-873f-f7e690f5bde9.gif)

**Comment by zhangzhx** [comment]
This is due to race condition that the enability status of the combo box is accessed by multiple threads.

The fix is here https://github.com/aws/aws-toolkit-jetbrains/pull/620.

**Comment by abrooksv** [comment]
#620 is not the best way to fix this in this use case.
