### ISSUE TITLE
Cannot create a new SAM module in IntelliJ

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#626]
**Describe the bug**
Cannot create a new SAM module in an existing project.

**To reproduce**

1. Create a new SAM project in a new workspace from IntelliJ
2. Create a new SAM module in the project
3. An error dialog shows up telling some file already exists (see screenshot below)

**Expected behavior**
The module should be successfully created in the specified location.

**Screenshots**
<img width="980" alt="screen shot 2018-11-27 at 4 18 25 pm" src="https://user-images.githubusercontent.com/7167513/49120073-181aec80-f260-11e8-8321-efbe47f22da1.png">

**Your Environment**
 - OS: Mac OS
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version: 2018.3
 - Toolkit Version: 0.4-SNAPSHOT

**Additional context**

**Comment by abrooksv** [comment]
Should be fixed by the changes in #629

**Comment by zhangzhx** [comment]
Confirmed that it is fixed in the latest version.
