### ISSUE TITLE
 Error Loading Resources isn't very descriptive

### ISSUE THREAD

**Issue by jrbrodie77** [aws/aws-toolkit-jetbrains#634]
**Is your feature request related to a problem? Please describe.**
Just tried the plugin for the first time.  I don't have any credentials on my machine that provide Lambda or CloudFormation permissions.  All I get is "Error Loading Crendentials".  It took me a while to figure out that I could hover and get the actual AWS error.

**Describe the solution you'd like**
The error message should mention more detail like "Access Error, this account doesn't have access to CloudFormation" or at least some hint that it's related to my credentials.

**Comment by abrooksv** [comment]
Will be fixed in 1.1
