### ISSUE TITLE
Configure Docker IP for debugging

### ISSUE THREAD

**Issue by jpoissant** [aws/aws-toolkit-jetbrains#642]
**Is your feature request related to a problem? Please describe.**
Using Docker Toolbox (Windows 7) my docker server IP is `192.168.99.100` and not `localhost`. When a Lambda is run in locally the debugger (PyCharm) cannot connect to the debug port and it timeout.

I receive the following error: `Connection to the debugger script at localhost:53327 timed out` (The port change on each execution)

**Describe the solution you'd like**
Add a configuration to the Run/Debug configuration to specify the Docker Server IP with a default value to `localhost`

**Describe alternatives you've considered**
Having a static configuration of SAM `debug-port`, this will require a port forwarding in VirtualBox in that case.

**Additional context**
Using:
- PyCharm 2018.3.1
- AWS Toolkit v1.0

**Comment by abrooksv** [comment]
This was added a while back but forgot to close the issue.
