### ISSUE TITLE
[Question] Serverless focused or more like Eclipse Toolkit?

### ISSUE THREAD

**Issue by ngortheone** [aws/aws-toolkit-jetbrains#651]
Are there any plans to add more functionality, like Eclipse AWS Toolkit?
Or is this exceptionally Serverless focused ?
Any plans to add first-class CloudFormation edititing/completion/documentation/inspections support?

Thanks.

**Comment by abrooksv** [comment]
We have several non-serverless ideas our backlog (S3 browser, ECR, CloudWatch Logs, etc).

If there are specific features you want, please feel free to 👍 them, or cut feature requests if they do not already exist.
