### ISSUE TITLE
Credential should be scoped to a valid region, not 'aws.global'

### ISSUE THREAD

**Issue by serrien** [aws/aws-toolkit-jetbrains#656]
**Describe the bug**
I'm working with several AWS account. One shared account is used to centralize User. Connection to other account use assume role.

I have a credential file with my access and secrets keys from shared account user configuration: 
[default]
aws_access_key_id=<acces key>
aws_secret_access_key=<secret key>

and a config file with:
[profile sandbox-eu-west-1]
region = eu-west-1
role_arn = arn:aws:iam::<account to deploy number>:role/<role>
source_profile = default
mfa_serial = arn:aws:iam::<shared account number>:mfa/<user>

This work well with awscli.

When I wan't to deploy a serverless application in intellij with aws toolkit, I got the message : "Credential should be scoped to a valid region, not 'aws.global'" after I set my MFA code.

**Screenshots**
<img width="707" alt="capture d ecran 2018-12-01 a 11 30 22" src="https://user-images.githubusercontent.com/1093497/49327095-91665800-f55c-11e8-8860-e919d67a76ea.png">

**Your Environment**
 - OS: 
 - JetBrains' Product: Inetllij Idea
 - JetBrains' Product Version: IntelliJ IDEA 2018.3 (Ultimate Edition) Build #IU-183.4284.148
 - Toolkit Version: v1.0

**Comment by abrooksv** [comment]
SDK tracking issue: https://github.com/aws/aws-sdk-java-v2/issues/988

**Comment by abrooksv** [comment]
This manifests itself if the default chain can't find a region. As a workaround till the SDK is fixed, you could default a region in the default profile.

```
[default]
region = us-west-2
```

**Comment by abrooksv** [comment]
A fix has been checked into master

**Comment by abrooksv** [comment]
1.1 is now public on JetBrains plugin repository
