### ISSUE TITLE
Cannot create run configuration for python3.7 in PyCharm

### ISSUE THREAD

**Issue by tomekthecoder** [aws/aws-toolkit-jetbrains#657]
**Describe the bug**
When I'm trying to create run configuration for hello_world lambda in PyCharm I'm getting an error: **_Error: Must specify supported runtime_**

**To reproduce**
1. Go to 'Main Editor window'
2. Click on 'Add Configuration'
3. Click '+' then go to AWS Lambda/Local
4. From template - choose cloudformation template with python3.7 runtime
5. See error at the bottom of the window

*Environment**
 - OS: MacOS Mojave
 - JetBrains' Product: PyCharm Community Edition
 - JetBrains' Product Version:  2018.3
 - Toolkit Version: 1.0
> pip list
Package             Version
------------------- ----------
arrow               0.12.1
aws-lambda-builders 0.0.3
aws-sam-cli         0.8.1
aws-sam-translator  1.9.0

**Additional context**
sam-cli in terminal works without problems

**Comment by zhangzhx** [comment]
Python3.7 is not currently supported in the IDE toolkit. Stay tuned, we'll add this support soon.

**Comment by tomekthecoder** [comment]
Thank you!

**Comment by visini** [comment]
As I've had some Python-version related compatibility issues when installing AWS Toolkit for JetBrains (**PyCharm** in my case) on **macOS**, I've written up a blog post with full instructions go get it working (i.e. downgrade from Python 3.7 to 3.6): https://camillovisini.com/deploy-serverless-python-functions-aws-lambda-pycharm/
Hope this helps!

**Comment by abrooksv** [comment]
Nice blog post 😄

**Comment by abrooksv** [comment]
Lambci images for 3.7 do not currently allow for debugging, we are blocked on that.

**Comment by gabehollombe-aws** [comment]
@abrooksv  Is there an ETA on python 3.7 debugging support in Lambci?

**Comment by abrooksv** [comment]
I do not have an ETA

**Comment by CaseyKnauss** [comment]
> I do not have an ETA

Are we talking, days, weeks, months?

**Comment by rli** [comment]
Here's the tracking issue we're tracking in the LambCI repo: https://github.com/lambci/docker-lambda/issues/138

**Comment by abrooksv** [comment]
Support has been added in release 1.2
