### ISSUE TITLE
Rider support for .NET

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#683]
There have been several requests from customers to add .NET / Rider support to the toolkit. This issue acts as a tracking feature to gauge interest.

**Comment by koendhondt** [comment]
Currently, plugins exist for Microsoft Azure and Google Cloud. Is AWS really the only one remaining to not support Rider?

**Comment by abrooksv** [comment]
Work is being tracked in https://github.com/aws/aws-toolkit-jetbrains/tree/feature/rider-support

**Comment by ADGrant** [comment]
Please add .NET/Rider support to the AWS toolkit for Jetbrains.

**Comment by sliedig** [comment]
+1 to this feature!

**Comment by kr0g** [comment]
+1 to this feature!  I would prefer to use Rider but since there is no integration, many AWS lambda developers are switching to VSCode for this feature

**Comment by nomercy78** [comment]
+1 for this feature!

**Comment by manu-one** [comment]
+1 for this one!

**Comment by koendhondt** [comment]
I was using the rider-support branch for a while, much to my satisfaction, but this branch no longer appears to exist. Does this mean rider support is now part of the mainstream release, or was it dropped altogether (I hope not!)?

**Comment by abrooksv** [comment]
@koendhondt it was merged into master and is in the 1.8 EAP builds on the jetbrains plugin repository 😀

**Comment by koendhondt** [comment]
👍 Thank you - and I just did, sorry! (could not find an EAP build for master so I built from source)

**Comment by abrooksv** [comment]
Thank you. I noticed this morning that I forgot to add msbuild to our release build jobs so the rider module failed to build. Automated EAP builds should start working again soon.

**Comment by abrooksv** [comment]
Latest EAP build: https://plugins.jetbrains.com/files/11349/71104/aws-jetbrains-toolkit-1.8-EAP.2019.10.24.zip?updateId=71104&pluginId=11349

**Comment by abrooksv** [comment]
Rider support has been released.

Please file new issues with bugs/feature requests

**Comment by sliedig** [comment]
Nice! Thanks :-)

**Comment by ADGrant** [comment]
Very nice, particularly debugging in ECS containers. However, I cannot deploy SAM apps written in C#. Any plans to add this?

**Comment by abrooksv** [comment]
> Very nice, particularly debugging in ECS containers. However, I cannot deploy SAM apps written in C#. Any plans to add this?

You should be able to. Please open a new issue with details like project setup

**Comment by ADGrant** [comment]
The documentation says "SAM features are currently limited to Java and Python only".  Is this not correct?

**Comment by abrooksv** [comment]
> The documentation says "SAM features are currently limited to Java and Python only". Is this not correct?

Nope, we forgot to update that, we are working on updating that 😄 

Docs: https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/welcome.html

**Comment by ADGrant** [comment]
Ok, great. I will dig around the docs and try to troubleshoot.
