### ISSUE TITLE
Respect IDE HTTP Proxy settings

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#685]
Calls to AWS via the AWS clients should respect the IDE-wide HTTP settings.

We will need to create our own implementation of the `SdkHttpClient`, the JetBrains framework has a `com.intellij.util.net.HttpConfigurable` that we can use to create a `HttpUrlConnection` (which includes IDE proxy settings if present). We should switch from the AWS `ApacheHttpClient` (and remove the dependency from our dependency closure), to `UrlConnectionHttpClient` and then update the AWS SDK for Java so that it can accept a proxy configuration per request.

Also need to update `software.aws.toolkits.core.utils.RemoteResourceResolver`

**Comment by abrooksv** [comment]
SDK change was released in 2.2.0

**Comment by onedaywillcome1** [comment]
I downloaded aws toolkit in intellij plugins. Even though proxy is set in intellij network settings, toolkit doesn't connect to aws lambda or cloudformation. What is the situation of this issue? @abrooksv 

![image](https://user-images.githubusercontent.com/10813183/50592626-fbe51d80-0ea5-11e9-9271-4182e98f29cf.png)

![image](https://user-images.githubusercontent.com/10813183/50592649-17502880-0ea6-11e9-8541-7a24a8a83e5c.png)

**Comment by abrooksv** [comment]
We have not implemented it yet, this is a feature request. When attempting the change we found a bug in the SDK that will need to be fixed first. https://github.com/aws/aws-sdk-java-v2/issues/975

**Comment by abrooksv** [comment]
Bugfix against SDK: https://github.com/aws/aws-sdk-java-v2/pull/989

**Comment by abrooksv** [comment]
Another fix in Java SDK: https://github.com/aws/aws-sdk-java-v2/pull/990

**Comment by abrooksv** [comment]
Code changes have been made and hidden behind a feature flag to opt-in. There are known issues since the SDK issues have not been merged.

https://github.com/aws/aws-toolkit-jetbrains/pull/735

**Comment by abrooksv** [comment]
Tested the proxy integration does work but UrlConnectionClient fails with signature validation issues against some services, SDK issue: https://github.com/aws/aws-sdk-java-v2/issues/1078

**Comment by bikerp** [comment]
I'm facing the same issue. We use corporate proxy with authentication and the AWS Toolkit cannot connect to the AWS

**Comment by waSRull** [comment]
I'm facing the same issue too.

**Comment by Sipsip** [comment]
I have the same issue. Is there a workaround? I'm not very familiar with proxy-settings in general

**Comment by abrooksv** [comment]
Trying a different approach: https://github.com/aws/aws-sdk-java-v2/pull/1154

**Comment by abrooksv** [comment]
Proxy support has been re-written and showing good results. Will stay behind an experimental feature until we get some real-world users.

**Comment by abrooksv** [comment]
Experimental support landed in 1.3-EAP.2019.04.04.

@onedaywillcome1 @waSRull @bikerp If you would like to test it with your setup, please enable EAP builds (https://github.com/aws/aws-toolkit-jetbrains#eap-builds) and then enable the feature through the experimental actions system.

![Screen Shot 2019-04-04 at 9 45 22 AM](https://user-images.githubusercontent.com/8992246/55573266-6af92a80-56be-11e9-8c90-926e6a829628.png)
Then enable the `aws.toolkit.useProxy` feature and restart.
![Screen Shot 2019-04-04 at 9 50 09 AM](https://user-images.githubusercontent.com/8992246/55573532-11453000-56bf-11e9-9b0a-e11f15fb9817.png)

**Comment by netgitdom** [comment]
Works for me through our corporate proxy, thanks.

**Comment by bikerp** [comment]
@abrooksv Thanks for the update. It works.

**Comment by zhangzhx** [comment]
This has been released in [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424)
