### ISSUE TITLE
Error when loading resources in AWS Explorer

### ISSUE THREAD

**Issue by samkeen** [aws/aws-toolkit-jetbrains#686]
**Describe the bug**
I have a functional `~/.aws/credentials` file that I am able to use from the command line AWS CLI.  The credentials are for a user with AdministratorAccess (AWS Managed Policy).  This is the only set of credentials in my `~/.aws/credentials` file and it is under the `[default]` section.
When I load pycharm for the Cloudformation and the Lambda sections of AWS Explorer, I get the "Error loading resources..." error.

**To reproduce**
1. Open my pycharm created "AWS Serverless Application"
2. Click the "AWS Explorer tab to open that window"
3. Click the carrot next to Cloudformation to expand the resources
4. "Loading..." appears, then "Error Loading Resources..."
5. If I hover the error I get the message seen in the screenshot below

**Expected behavior**
Since I have a functioning `~/.aws/credentials` file with a single default user with AdministratorAccess I would expect the calls to gather information on both Lambda and Cloudformation to succeed. 

**Screenshots**

<img width="982" alt="screen shot 2018-12-04 at 7 29 57 pm" src="https://user-images.githubusercontent.com/17389/49488650-61d57b00-f7fc-11e8-9798-4f66359a5930.png">

If I expand the gear menu and click the "Edit AWS Credentials file" it opens the expected file so it "seems" it is pointing to the correct file
 
<img width="994" alt="screen shot 2018-12-04 at 8 05 28 pm" src="https://user-images.githubusercontent.com/17389/49489501-2341bf80-f800-11e8-967d-8d4a4969e7c6.png">

**Your Environment**
 - OS: OSX 10.13.6 (17G3025)
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: PyCharm 2018.3 (Professional Edition)
Build #PY-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
 - Toolkit Version: v1.0

**Additional context**

Logs:
[idea.log](https://github.com/aws/aws-toolkit-jetbrains/files/2647129/idea.log)

**Comment by samkeen** [comment]
Sorry, resolved, the one thing I should have tried before opening issue (*Invalidate Caches and Restart*), looks to have resolved the issue.

**Comment by waqasdilawar** [comment]
@samkeen I've invalidated the cache and restarted, but getting same error.
