### ISSUE TITLE
Add Configuration will not allow selection From template

### ISSUE THREAD

**Issue by Marakai** [aws/aws-toolkit-jetbrains#689]
Creating a new project based on Hello World, then trying to Add Configuration [Local] will not detect templates.yaml and won't extract runtime, function or any other information.

**To reproduce**
1. Create New Project
2. Select AWS Serverless Application
3. Choose a project name in Location or leave as untitled
4. Choose any supported interpreter or virtualenv
5. In SAM Template select AWS SAM Hello World

6. Without making any further changes, attempt to Add Configuration
7. Click '+'
8. Select AWS Lambda and Local
9. In the From template: file selection dialog, browse to to project directory

**templates.yaml does not show up in the directory and it is not possible to select only the directory as the button is greyed out.**

10. Manually enter the full path and file name for templates.yaml

**Information such as runtime, handler are not filled in, nor will the dropdown next to the From template file selector contain any choice, however the radiobox gets ticked.**

11. Untick the From template radiobox
12. Manually fill in the information
13. Select any event source text
14. Select OK

**Works as expected.**

15. Run the project/function

As per default you will get something  like

`{"statusCode": 200, "body": "{\"message\": \"hello world\", \"location\": \"your IP here\"}"}`

**Expected behavior**

According to 
[Danilo Poccia's blog](https://aws.amazon.com/blogs/aws/new-aws-toolkits-for-pycharm-intellij-preview-and-visual-studio-code-preview)
and
[Jetbrains AWS Toolkit page](https://plugins.jetbrains.com/plugin/11349-aws-toolkit)
selecting a templates file from the project should extract the information and pre-fill the fields.

**Your Environment**
 - OS: CentOS 7.6.1810
 - JetBrains' Product: Pycharm
 - JetBrains' Product Version: 2018.3 (PY-183.4284.139)
- JRE: 1.8.0_152-release-1343-b15 amd64
 - Toolkit Version: v1.0

**Additional context**

- PyCharm is running as the local user I'm logged in as. 
- Project files are owned by that user.
- AWS credentials are valid
- AWS Explorer works and is able to retrieve CFN and Lambda
- Possible related to https://github.com/aws/aws-toolkit-jetbrains/issues/421#issue-379346849 ?

**Comment by rli** [comment]
This should have been resolved in PR #622 and released in toolkit version 1.1.

Closing issue. Please feel free to reopen if this bug still exists.
