### ISSUE TITLE
"Error Loading Resources" when using MFA and multiple accounts

### ISSUE THREAD

**Issue by ccovarru** [aws/aws-toolkit-jetbrains#705]
**Describe the bug**
Our current AWS infrastructure is setup in as Hub -> Spoke configuration. We also require MFA before you can switch to a different role in a spoke account. Even after authenticating via CLI and selecting one of the spoke profiles in the connection settings, I am getting the error "Error Loading Resources" under the "CloudFormation" and "Lambda" sections in AWS Explorer. 

**To reproduce**

1. Authenticate via CLI using MFA credentials.
1. Start PyCharm and open an AWS Serverless project
1. Go to AWS Explorer and select the proper profile and region.
1. Expand the "CloudFormation" and "Lambda" sections.
1. Both give error "Error Loading Resources"

**Expected behavior**
Be able to see resources and CF as designed. 

**Screenshots**

![screen shot 2018-12-18 at 8 42 56 am](https://user-images.githubusercontent.com/1448342/50168761-04800600-02a1-11e9-8615-ae1b05470cb1.png)

**Your Environment**
 - OS: Mac OS X 10.14.1
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2018.3
 - Toolkit Version: 1.0

**Comment by ccovarru** [comment]
Restarting PyCharm got it working as expected. Leaving open for someone to decide if it is a worthwhile bug to pursue.

**Comment by abrooksv** [comment]
Reloading the credential file on changes is not implemented yet,
tracking issue is #260

**Comment by ccovarru** [comment]
Looks like a duplicate to me then. I'm good with you closing this ticket and tracking on #260 .

**Comment by abrooksv** [comment]
Cool, thank you.
