### ISSUE TITLE
Can Not Create new AWS Serverless Application Project '""' not recognized as a command

### ISSUE THREAD

**Issue by AliSajid** [aws/aws-toolkit-jetbrains#708]
**Describe the bug**
The new project creation wizard does not progress. Complains of the following:

__'""' is not recognized as an internal or external command, operable program or batch file.__

**To reproduce**
1. "New Project" -->
2. Click on AWS Serverless Application
3. See error at the bottom of the window.

**Expected behavior**
I should be able to create a new project

**Screenshots**

![pycharm aws toolkit error](https://user-images.githubusercontent.com/395482/50226085-1f976680-03c4-11e9-8db5-f0c9fc615e60.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: PyCharm 
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version: v1.0
 - AWS CLI Version: aws-cli/1.16.72 Python/3.6.0 Windows/10 botocore/1.12.62
 - AWS SAM CLI Version: 0.7.0

**Additional context**

**Comment by abrooksv** [comment]
Code has been pushed to indicate that SAM was too low of a version
