### ISSUE TITLE
Deployment for java8 runtime fails

### ISSUE THREAD

**Issue by georgevanvliet** [aws/aws-toolkit-jetbrains#712]
**Describe the bug**
Trying to deploy a serverless application using the  java8 runtime fails.
When trying to deploy a serverless application for runtime java8, the tooling invokes sam build. sam build does not support the java8 runtime (only python).

**To reproduce**
1. Create a new project
2. Select the helloworld template
3. Right click on template.yaml
4. Select deploy serverless application
5. Create a stack and bucket, click deploy
6. Log shows:
```
2018-12-20 16:02:42 Found credentials in shared credentials file: ~/.aws/credentials
2018-12-20 16:02:43 Building resource 'HelloWorldFunction'
Build Failed
Error: 'java8' runtime is not supported
```

**Expected behavior**
I expect the serverless application to be deployed to my (live) aws environment.

**Screenshots**
![screen shot 2018-12-20 at 16 34 00](https://user-images.githubusercontent.com/837402/50293974-1ca87e80-0475-11e9-91aa-d872bdb19993.png)

**Your Environment**
 - OS: Mac OS X 10.13.6
 - JetBrains' Product: IntelliJ Idea
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version: 1.0

**Comment by abrooksv** [comment]
Deployment is built on top of SAM CLI. They have to build Java support into this project: https://github.com/awslabs/aws-lambda-builders

**Comment by cliffordh** [comment]
@abrooksv it looks like Java support might be there now? https://github.com/awslabs/aws-lambda-builders/commit/aa9f73db3c97801905114dd828421aa30078d5ef

**Comment by abrooksv** [comment]
It was included in Sam version 0.13.0

**Comment by cliffordh** [comment]
Still getting an error after a brew upgrade brought me to 0.13.0:

22:15	AWS Toolkit: The runtime java8 is not supported for deploying the SAM template /Users/cliff/Work/aws-java-test/template.yaml

**Comment by abrooksv** [comment]
Ah, I forgot we had that check. I need to mark the Java RuntimeGroup as supporting SAM build.

**Comment by cliffordh** [comment]
This will make my day to use IntelliJ over Eclipse for authoring and deploying Java lambdas

**Comment by cliffordh** [comment]
@abrooksv Do you know when a new build will be available for testing?

**Comment by abrooksv** [comment]
@cliffordh The EAP builds are public, you can either opt in to EAP branch by following https://github.com/aws/aws-toolkit-jetbrains#eap-builds or installing manually from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/59415

**Comment by abrooksv** [comment]
1.2 has been released with support
