### ISSUE TITLE
Unrecognized token error in pycharm new project wizard

### ISSUE THREAD

**Issue by naveen-vijay** [aws/aws-toolkit-jetbrains#714]
**Describe the bug**
After installing the sam cli using brew and the AWS took kit plugin in i see the error 
"Unrecognized token 'Incorrect': was expecting 'null', 'true', 'false' or 'NaN'" Please see the error screenshot.

**Your Environment**
 - OS:  MacOS 10.14.2 (18C54)
 - JetBrains' Product: PyCharm 2018.3.2 (Professional Edition)
 - JetBrains' Product Version: Build #PY-183.4886.43, built on December 18, 2018
 - Toolkit Version: v1.0
-  JRE: 1.8.0_152-release-1343-b26 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Screenshots**
<img width="778" alt="pycharm-aws-toolkit" src="https://user-images.githubusercontent.com/342580/50452820-18131880-0902-11e9-916b-0d7374ebd8ec.png">

**Comment by rli** [comment]
Hi, looks like your version of the SAM CLI is out of date. The latest version right now is v0.10.0.

Can you verify that this is the version you are using?

```
$ sam --info
{
  "version": "0.10.0"
}
```

**Comment by naveen-vijay** [comment]
indeed, the problem went away after updating to version 0.10.0. Thanks !
