### ISSUE TITLE
python sdk can't find module

### ISSUE THREAD

**Issue by asyba** [aws/aws-toolkit-jetbrains#717]
**Describe the bug**
I can't execute locally a python lambda, can't find the modules, but I check and there are in the SDK.

```
/home/federico/.local/bin/sam local invoke --template /tmp/handler_swc_2019.lambda_handler-template1.yaml --event /tmp/handler_swc_2019.lambda_handler-event1.json
2019-01-02 12:08:44 Found credentials in environment variables.
2019-01-02 12:08:44 Invoking lambda/handler_swc_2019.lambda_handler (python3.6)
2019-01-02 12:08:44 Decompressing /tmp/8516626665729258067.zip

Fetching lambci/lambda:python3.6 Docker container image......
2019-01-02 12:08:48 Mounting /tmp/tmpvptv92cm as /var/task:ro inside runtime container
START RequestId: 20f39a93-306b-4d2b-a5af-5edb667ac3a6 Version: $LATEST
Unable to import module 'lambda/handler_swc_2019': No module named 'pushover'
END RequestId: 20f39a93-306b-4d2b-a5af-5edb667ac3a6
REPORT RequestId: 20f39a93-306b-4d2b-a5af-5edb667ac3a6 Duration: 140 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 24 MB

{"errorMessage": "Unable to import module 'lambda/handler_swc_2019'"}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1466530/50597900-c0d3f180-0e87-11e9-9051-55d835b89598.png)

![image](https://user-images.githubusercontent.com/1466530/50597831-84a09100-0e87-11e9-9a0b-19a8caeb951b.png)

**Your Environment**
 - OS: Ubuntu
 - JetBrains' Product: Build #IU-183.4886.37, built on December 17, 2018
 - JetBrains' Product Version:  2018.3.2
 - Toolkit Version: v1.0
 - SAM CLI Version: v0.10
 - JVM/Python Version: Python 3.6

**Comment by abrooksv** [comment]
What is the module SDK you have selected, is it the 3.6 one?

**Comment by asyba** [comment]
yeah, but probably I create the virtual env wrong, I always struggle with this..

**Comment by abrooksv** [comment]
I was not able to re-produce it. Make sure the Module SDK and Project SDK are both the correct SDK. It looks like you aren't actually using a virtual env inside of the IDE (since the Python home path in your screen shot is the system interpreter and not the venv folder)

**Comment by EKami** [comment]
I have the same issue with the HelloWorld example:
```
{"errorMessage": "Unable to import module 'app'"}
```

When unzipping the tmp archive I only have this in it:
```
unzip /var/folders/j1/jsk8lx9d6gs05l8mr33vl99m0000gp/T/7794967836097990930.zip
Archive:  /var/folders/j1/jsk8lx9d6gs05l8mr33vl99m0000gp/T/7794967836097990930.zip
  inflating: app.py
  inflating: __init__.py
  inflating: requirements.txt
```

So it looks like the plugin didn't package a `sam build` result into the zip. Any idea how I can fix it? Thanks.

**Comment by abrooksv** [comment]
@EKami We are migrating over to sam build in #811

**Comment by abrooksv** [comment]
We have migrated to sam build in 1.2.

This standardized how the dependencies get added and you should not see this anymore.

**Comment by asyba** [comment]
cool, will try that.
