### ISSUE TITLE
Error running '[Local] LambdaFunc': duplicate entry .DS_Store

### ISSUE THREAD

**Issue by sdillinger** [aws/aws-toolkit-jetbrains#725]
**Describe the bug**
When I try to run a lambda via run/debug config I get an error

**To reproduce**
Create config, click debug

**Expected behavior**
It works

**Screenshots**
![image](https://user-images.githubusercontent.com/2574161/50793662-88208780-128e-11e9-9460-102a84b2582e.png)

**Your Environment**
 - OS: mcOS Mojave 10.12
 - JetBrains' Product:  PyCharm
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version:1.2
 - SAM CLI Version: 0.10.0 
 - JVM/Python Version: 3.6

**Additional context**

**Comment by sdillinger** [comment]
I mass deleted all .DS_Store files and it fixed the issue.

**Comment by abrooksv** [comment]
The toolkit should auto-ignore .DS_Store, so I would consider this a bug.
