### ISSUE TITLE
Local run/debug failed when multiple app modules added

### ISSUE THREAD

**Issue by jameszh** [aws/aws-toolkit-jetbrains#728]
**Describe the bug**
Local run/debug failed when multiple app modules added

**To reproduce**
Just add 2nd app modules to the sample app hello world.
create folder second_app with simply simple lamba  and mark as sources.
once added, can't local-run either of the apps
sam local invoke still works  for both of them though

**Expected behavior**
should work

**Screenshots**
Error running '[Local]
SecondApp': 

**Your Environment**
 - OS:  Mac 10.14
 - JetBrains' Product: Pycharm 
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version: 1.0
 - SAM CLI Version: 0.10
 - JVM/Python Version: 3.6

**Additional context**

**Comment by abrooksv** [comment]
This should get fixed when we do #483

**Comment by abrooksv** [comment]
Switch to sam build has been done in 1.2 and is out now. This should solve your issue
