### ISSUE TITLE
Unable to create new Lambda function

### ISSUE THREAD

**Issue by thenewmr** [aws/aws-toolkit-jetbrains#731]
**Describe the bug**
Unable to create AWS Function

**To reproduce**
1. Click Lambda icon in gutter
2. Select Create new AWS Lambda
3. Enter details

IAM Role dropdown is disabled  (missing permission? - tried adding permission to user in AWS console but still nothing - can't restart computer just now to see if restarting AWS CLI or SAM will fix)

Create function button is enabled.  After clicking, it's disabled.  No feedback as to what's happened (or hasn't happened).

**Expected behavior**
Should be able to create a new lambda function

**Screenshots**
![2019-01-08 17_12_12-target-runner-aws-backend c__users_a_gam_ideaprojects_target-runner-aws-backend](https://user-images.githubusercontent.com/3169491/50848450-39491f80-136c-11e9-94e0-4dbe879f0cf2.png)
![2019-01-08 17_12_29-create function](https://user-images.githubusercontent.com/3169491/50848451-39e1b600-136c-11e9-8ce8-70fe7a081276.png)

**Your Environment**
 - OS: Windows 10 Pro
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version: IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Toolkit Version: 1e894c6bb1510e14a798fe11be2e5dcd1e438973
 - SAM CLI Version: SAM CLI, version 0.10.0
 - JVM/Python Version: Java 1.8.0_191 - Python v3.7.1

**Additional context**
None

**Comment by abrooksv** [comment]
I replicated and working on the fix now

**Comment by abrooksv** [comment]
1.1 is now public on JetBrains plugin repository
