### ISSUE TITLE
Only Java8 Runtime Available through Intellij New Project Wizard After Install

### ISSUE THREAD

**Issue by murphman300** [aws/aws-toolkit-jetbrains#743]
**Describe the bug**
There seems to be no other Runtime options except for Java8 via the New Project Wizard for Intellij once all the dependencies are insalled, and both the IDE and System are restarted

**To reproduce**
Install Toolkit Plugin for IntelliJ, AWS Connector and SAM CLI on macOS Mojave.

**Expected behavior**
NodeJS runtimes should be available..

**Screenshots**

**Your Environment**
 - OS: macOS
 - JetBrains' Product: Intellij 
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version: @Latest
 - SAM CLI Version:  @Latest
 - JVM/Python Version:  @Latest

**Additional context**

**Comment by abrooksv** [comment]
We currently only support Java and Python runtimes. The tracking issue for Webstorm / JavaScript is https://github.com/aws/aws-toolkit-jetbrains/issues/187

**Comment by abrooksv** [comment]
Please follow #187
