### ISSUE TITLE
Debugging python lambda

### ISSUE THREAD

**Issue by ro83rt** [aws/aws-toolkit-jetbrains#752]
**Describe the bug**
I'm unable to debug python lambda in PyCharm, due to the missing pydevd.py. Run same lambda works like a charm. 

C:\Users\robert\AppData\Roaming\Python\Python36\Scripts\sam.exe local invoke --template "C:\Users\robert\AppData\Local\Temp\[Local] app.lambda_handler-template11.yaml" --event "C:\Users\robert\AppData\Local\Temp\[Local] app.lambda_handler-event9.json" --debug-port 50936 --debugger-path "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.2\helpers\pydev" --debug-args "-u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 50936 --file"
2019-01-16 19:13:08 Found credentials in environment variables.
2019-01-16 19:13:08 Invoking app.lambda_handler (python3.6)
2019-01-16 19:13:08 Decompressing C:\Users\robert\AppData\Local\Temp\2434856511246420358.zip

Fetching lambci/lambda:python3.6 Docker container image......
2019-01-16 19:13:16 Mounting C:\Users\robert\AppData\Local\Temp\tmp8o7dgjq9 as /var/task:ro inside runtime container
/var/lang/bin/python3.6: can't open file '/tmp/lambci_debug_files/pydevd.py': [Errno 2] No such file or directory

**Your Environment**
 - OS: Windows 10 Home, Oracle VM + Docker Toolbox
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2018.3.2 (Community Edition)
 - Toolkit Version: 1.1
 - SAM CLI Version: 0.10.0 (installed using pip)
 - JVM/Python Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o / Python 3.6

**Comment by ro83rt** [comment]
yes

C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.2\helpers\pydev>dir /B /A-D
interpreterInfo.py
LICENSE
merge_pydev_pycharm.txt
pycharm-readme.txt
pycompletionserver.py
pydevconsole.py
pydevd.py
pydevd_file_utils.py
pydev_app_engine_debug_startup.py
pydev_coverage.py
pydev_pysrc.py
README.rst
runfiles.py
setup.py
setup_cython.py

**Comment by abrooksv** [comment]
Interesting. SAM should have mounted that folder. I wonder if docker doesn't have access to mount that directory.

**Comment by ro83rt** [comment]
seems to be ok, right?
robert@home MINGW64 /c/Program Files/JetBrains/PyCharm Community Edition 2018.3.2/helpers/pydev
$ ls -l pydevd.py
-rw-r--r-- 1 robert 197121 72956 Dec 18 12:19 pydevd.py

**Comment by abrooksv** [comment]
Mounting permission is controlled by Docker's File Sharing settings in Docker Preferences I believe. 

I am going to move this over to SAM since it relates to mounting and docker.

**Comment by ro83rt** [comment]
@abrooksv Solved by upgrading to W10Pro (for £8) and installing Docker for Win. Thank you for your support.

**Comment by shlomikushchi** [comment]
it is not uncommon to use docker toolbox on a win10 machine.
it there a solution for this issue or is it a deadend? 
@abrooksv

**Comment by jdlyga** [comment]
I'm having the exact same issue.  Windows 10 professional, Docker for Windows installed.  

/var/lang/bin/python3.8: can't open file '/tmp/lambci_debug_files/pydevd.py': [Errno 1] Operation not permitted

**Comment by yratush** [comment]
any updates on this? Got the same on Mac OS
