### ISSUE TITLE
Cannot connect to Dynamodb local in docker

### ISSUE THREAD

**Issue by AliSajid** [aws/aws-toolkit-jetbrains#756]
**Describe the bug**
I am trying to develop a dynamodb backed application based on the Hello World Template. I have dynamodb running as a docker container. However, I am unable to connect to that dynamodb instance. Instead, it raises a connection error. The invocation works perfectly when i connect to the the original dynamodb but not with local.

**To reproduce**

1. Create a new project.
2. Add a DynamoDB backed function
3. Run dynamodb-local docker image
4. Either invoke the function from source or run from template file.

**Expected behavior**
It should connect to local dynamodb

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: 2018.3.3
 - JetBrains' Product Version: PyCharm Professional
 - Toolkit Version:  1.1
 - SAM CLI Version: 0.7.0
 - JVM/Python Version: 3.6

**Comment by abrooksv** [comment]
I have never attempted this myself, did you trying following https://stackoverflow.com/questions/48926260/connecting-aws-sam-local-with-dynamodb-in-docker and setting the endpoint to `http://dynamodb:8000`?

We may have to expose the `--docker-network` setting first though.

**Comment by AliSajid** [comment]
I tried the mentioned approach but that did not work. Same error. I have to admit I had trouble finding and setting the `--docker-network` setting too. Which can possibly explain the error.

Is this something quick and doable?

**Comment by AliSajid** [comment]
So I have tried running the entire thing with the docker-network solution. It works for me, from the cli. But of course, not from within PyCharm.

Is it possible to hide this away and automatically create a docket network behind the scene and only launch functions inside that?

**Comment by abrooksv** [comment]
If/when we expose it, you could edit the run config template to change the default. I am not sure how we could do it for you since we wouldn't know which one you launched the DynamoDB docker as.

**Comment by abrooksv** [comment]
Support has been added and will be in the 1.2 release
