### ISSUE TITLE
Unable to edit AWS credential file via pycharm

### ISSUE THREAD

**Issue by Sunny-Engineer** [aws/aws-toolkit-jetbrains#759]
**Describe the bug**
When attempting to "configure AWS Connection" the error "Could not open empty credential file c:\users\<username>\.aws\credentials for editing, please delete the file and try again."

Deleting and trying again leads to same error.

**To reproduce**

1- Start PyCharm Professional 2018.3.3
2 - Open existing project.
3 - Open AWS Explorer
4 - Click on "Configure AWS Connection" or "Edit AWS Credential File"
5- Error is displayed.

**Expected behavior**
Tool Allows user to edit credentials or explains why the system cannot edit credential files so that user can take correct action.
![2019-01-19_11h08_05](https://user-images.githubusercontent.com/36799802/51429216-81710900-1bda-11e9-9345-83d9e3e62e32.png)

**Screenshots**

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: PyCharm Professional 2018.3.3
 - JetBrains' Product Version:
 - Toolkit Version: Latest
 - SAM CLI Version: 0.7.0
 - JVM/Python Version: Python 3.7

**Additional context**

**Comment by abrooksv** [comment]
To clarify, does the file exist before you attempt this action?

**Comment by Sunny-Engineer** [comment]
The file did exist after the installation.  However, based on the suggestion in the error message, I deleted the file.  The error message was the same after deleting the file.

**Comment by abrooksv** [comment]
I was not able to re-produce it on Mac. Will try on Windows.

**Comment by abrooksv** [comment]
Was not able to reproduce it, but the check should not actually exist so removed it
