### ISSUE TITLE
AWS Toolkit doesn't support 'credential_process' in credentials file

### ISSUE THREAD

**Issue by BStokes** [aws/aws-toolkit-jetbrains#767]
If the credentials file contains a profile with the key 'credential_process', editor will report that the credential file is invalid.  My case is around the use of Okta for credentials (https://www.okta.com/aws/).   Additioanlly, selecting profiles that don't contain that key doesn't correct the issue.

_credentials example:_
`[default]
aws_access_key_id=myAccessKeyId
aws_secret_access_key=mySecreyAccessKey

[okta_profile]
credential_process=aws-okta-processor ...
`

**Comment by abrooksv** [comment]
SDK support: https://github.com/aws/aws-sdk-java-v2/pull/1166

**Comment by abrooksv** [comment]
SDK support has been merged, will be released in next SDK release.

**Comment by zhangzhx** [comment]
Toolkit support has been released in the latest 1.3 version.
