### ISSUE TITLE
Fetching Docker container image stuck

### ISSUE THREAD

**Issue by asyba** [aws/aws-toolkit-jetbrains#773]
**Describe the bug**
Stuck like 20m downloading the "Fetching lambci/lambda:python3.6 Docker container image"

```
Fetching lambci/lambda:python3.6 Docker container image...................................
```

**Comment by asyba** [comment]
After 40m it finished, but then the 4 time that I execute again a lambda wit debug is try to download again the docker image .. WTF

**Comment by abrooksv** [comment]
We don't own hosting the images, they are on DockerHub

As for skipping on 2nd run, was requested in ##553

#775 should solve that

**Comment by asyba** [comment]
Nice, I will wait that merge.
