### ISSUE TITLE
Connection timeout when starting debugger

### ISSUE THREAD

**Issue by himanshu219** [aws/aws-toolkit-jetbrains#784]
**Describe the bug**
After starting the debugger with AWS Lambda configuration the following line gets printed but it fails with the connection timeout error
/Users/hpal/.pyenv/versions/3.7.0/envs/testonpy3.7/envs/inferface/bin/sam local invoke --template "/private/var/folders/lj/gtdzxy0d6975vtrkgrh8_5gr0000gn/T/[Local] ExamPhoto-template.yaml" --event "/private/var/folders/lj/gtdzxy0d6975vtrkgrh8_5gr0000gn/T/[Local] ExamPhoto-event.json" --debug-port 51962 --debugger-path /Applications/PyCharm.app/Contents/helpers/pydev --debug-args "-u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 51962 --file"
2019-02-03 12:18:05 Found credentials in environment variables.
2019-02-03 12:18:05 Invoking inferface.src.exam_photo.lambda_handler (python3.6)
2019-02-03 12:18:05 Decompressing /var/folders/lj/gtdzxy0d6975vtrkgrh8_5gr0000gn/T/1111133873687239728.zip

Connection to python debugger failed: Connection to the debugger script at localhost:51962 timed out

I have tried increasing the connection limit in  vmoptions settings but it seems it is not taking that value
-Didea.connection.timeout=20000000

**To reproduce**
Start the debugger

**Screenshots**
<img width="1677" alt="screen shot 2019-02-03 at 1 04 26 pm" src="https://user-images.githubusercontent.com/3620468/52174031-511d9300-27b4-11e9-82ed-1faeaec30066.png">

**Your Environment**
 - OS:  Mac OS High Sierra
 - JetBrains' Product: Pycharm Professional 
 - JetBrains' Product Version: 2018.3.3
 - Toolkit Version: v1.1
 - SAM CLI Version: SAM CLI, version 0.10.0
 - JVM/Python Version: java version "1.8.0_152"

**Additional context**

**Comment by abrooksv** [comment]
Does it run correctly when using Run?

**Comment by himanshu219** [comment]
yes I think it's because there is no connection to debugging server required in that case

**Comment by abrooksv** [comment]
Hmm... It could be the debugger is failing to mount into Docker, try adding `/Applications/PyCharm.app/Contents/helpers/` as a shared folder in docker.

**Comment by slichtenthal** [comment]
What would be the shared folder to mount in Windows?

**Comment by abrooksv** [comment]
@slichtenthal It depends on your PyCharm location. If you look at the sam command in the console window it will be the path after `--debugger-path`

**Comment by slichtenthal** [comment]
> @slichtenthal It depends on your PyCharm location. If you look at the sam command in the console window it will be the path after `--debugger-path`

What should I be mounting it as? IE, the folder name in the docker container?

**Comment by abrooksv** [comment]
Not sure if it works with Docker Toolbox. Wasn't that replaced with Docker Desktop?

**Comment by slichtenthal** [comment]
Only for Windows 10+.  Unfortunately still stuck on Windows 7 :-1:.  Running works perfectly- the only issue is with debugging.

**Comment by skinsman** [comment]
I too am stuck on Windows 7 so trying to use the toolkit in PyCharm with Docker Toolbox.  I'd really like to know if this is a dead-end or not; I haven't found any clear info one way or the other.

I've got to the point where mounting did work (through a "mount" command via ssh to the docker machine) and I was able to "more /tmp/lambci_debug_files/pydevd.py" successfully ... but I still get the "/var/lang/bin/python3.6: can't open file '/tmp/lambci_debug_files/pydevd.py': [Errno 2] No such file or directory" error.  I'm stuck.  Any ideas?  Thanks.

BTW the mount command I used was "sudo mount -t vboxsf -o uid=1000,gid=50 pydev /tmp/lambci_debug_files/" where "pydev" is my share name for the directory [assed to sam.cmd with the --debugger-path flag, and I verified my uid & gid are 1000 & 50.

**Comment by tbtmuse** [comment]
I have been struggling with debugging for a while, I could not get it working, however after browsing the mounted volumes and inspecting the containers, I found that everything is as it should be, the problem was that "localhost" is hard coded as the debugging server host, changing it to the IP address of the VirtualBox VM and recompiling the plugin fixed this.

This could be exposed as a configuration option under the AWS plugin global settings. It could default to localhost if not set. 

I'm happy to submit a PR on this but would need quite a bit of guidance as I am unfamiliar with intellij plugin development.

**Comment by justinmk3** [comment]
> changing it to the IP address of the VirtualBox VM and recompiling the plugin fixed this.

Nice! Please do send a PR, even if it only has your hard-coded change initially. Then we can provide guidance.

**Comment by Tantael** [comment]
Removine entrypoint should help

**Comment by breedloj** [comment]
Closing in favor of tracking timeout issue in #1399.
