### ISSUE TITLE
How to attach existing role

### ISSUE THREAD

**Issue by jjbuck** [aws/aws-toolkit-jetbrains#813]
**Describe the bug**
CloudFormation tries to create a Role resource even when I don't specify one (i.e., I'm trying to use an existing role).

**To reproduce**
This occurs with the Hello World demo. Within PyCharm, when I specify an existing role in my Lambda "Function Configuration" and delete the Output related to the role, the CloudFormation Stack fails with the following error: 

"iam:CreateRole User: < user > is not authorized to perform: iam:CreateRole on resource: < existing role I specified >"

When I look at the "Resources" tab of the CloudFormation stack, I see a resource called HelloWorldFunctionRole. 

**Expected behavior**
I expect the CloudFormation stack to be created with an existing role that I specified in the "Function Configuration" in PyCharm, not to attempt to create a new Resource.

**Screenshots**

**Your Environment**
 - OS: Mac OSX
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2018.3.5
 - Toolkit Version: 1.1
 - SAM CLI Version: 0.10.0
 - JVM/Python Version: Python 3.6

**Additional context**

**Comment by jjbuck** [comment]
It looks like I fixed this by just specifying the role in the Resources section of the template. Maybe this isn't a bug so much as a customer anecdote - it wasn't clear to me that the role I specified in the "Function Configuration" wouldn't be used by CloudFormation in the way I expected.

**Comment by abrooksv** [comment]
You can provide feedback on any documentation page on the AWS documentation website by clicking the feedback link in the footer.
