### ISSUE TITLE
GovCloud options are not available in region selection

### ISSUE THREAD

**Issue by belloacpace** [aws/aws-toolkit-jetbrains#816]
AWS Connection Settings does not allow for switching to access any of the Gov Cloud regions.

![awsconnectionsettings](https://user-images.githubusercontent.com/39655681/53834040-0b411f80-3f58-11e9-9602-c4a61fb6ad87.png)

Please add or allow for configuration to add additional regions.

Testing was done on:
IntelliJ IDEA Ultimate 2018.3.4
AWS Tollkit v1.1

**Comment by abrooksv** [comment]
Related issue for CN: #699

**Comment by specialbrew** [comment]
+1 for this feature, currently cannot remotely debug our lambda functions. Even if there were a manual configuration file in the toolkit install that would allow to add regions. Or glean them from the entries in the ~/.aws/config (or similar) file.

**Comment by vishalrp** [comment]
+1 for this. Keep getting error because the region is wrong.

**Comment by jdcrown** [comment]
+1 need this "feature"

**Comment by breedloj** [comment]
Closing since this is now available.
