### ISSUE TITLE
When selecting "build function inside a container" I get no such option: --use-container error when attempting to "debug" application

### ISSUE THREAD

**Issue by drewtenn** [aws/aws-toolkit-jetbrains#827]
Not sure why --use-container is being applied to the "invoke" step instead of the "build" step.

Running v1.2-EAP.2019.03.12
SAM CLI, version 0.13.0

/usr/local/bin/sam local invoke --template /private/var/folders/02/lvqr_vgs0pjgl0wmkpl8g27c0000gn/T/lambdaBuild2/template.yaml --event /private/var/folders/02/lvqr_vgs0pjgl0wmkpl8g27c0000gn/T/Test-event.json ETLImport --use-container --debug-port 56754 --debugger-path "/Users/drew/Library/Application Support/IntelliJIdea2018.3/python/helpers/pydev" --debug-args "-u /tmp/lambci_debug_files/pydevd.py --multiprocess --port 56754 --file"
Error: no such option: --use-container

**Comment by tbradley-sans** [comment]
I don't know the answer to this, but where do you find the "build function inside a container"? That's one workaround for a SAM build problem I'm having, but I have only done `--use-container` on the command line. I haven't seen how to tell the PyCharm plugin to use it.

**Comment by abrooksv** [comment]
@tbradley-sans Only the latest 1.2 EAP has it

**Comment by abrooksv** [comment]
Fix has been released in 1.2-EAP.2019.03.14 which is currently pending JetBrains approval
