### ISSUE TITLE
PhpStorm support

### ISSUE THREAD

**Issue by mnapoli** [aws/aws-toolkit-jetbrains#847]
Please make the plugin available in PhpStorm :)

**Comment by ahathaway** [comment]
I second this, would love to see this available on phpstorm for both nodejs and php runtimes.

**Comment by pedroapfilho** [comment]
UP

**Comment by cortet94** [comment]
Would seriously love to see a plugin for this as well!

**Comment by jeffbahns** [comment]
I am an employed software developer making quite a bit of money so I believe my word has a lot of value when I say that I want to see this plugin happen please, thank you.

**Comment by cwatts07** [comment]
I agree, not sure how hard it would be to add to phpstorm as it seems to be webstorm with extras added for php.

**Comment by abrooksv** [comment]
> I agree, not sure how hard it would be to add to phpstorm as it seems to be webstorm with extras added for php.
> EDIT:
> So I just installed it manually,download webstorm version and install plugin from disk, in phpstorm and it seems to work with just initial load

You are right, it does load. 😄 

We pushed some changes in the latest version to clean up the UX of the toolkit when run in those IDEs that lack any of the languages we support today.

**Comment by abrooksv** [comment]
We have enabled listing of the plugin in PhpStorm. 

To be clear, there are no Php specific features, but the features like S3 browser and CloudWatch logs are available as well as Node-based Lambdas like in Webstorm.

**Comment by anilsherkar** [comment]
> Please make the plugin available in PhpStorm :)

We are looking for PhpStrom support for AWS Code commit using SSO. Is it already part of this tool kit.

**Comment by abrooksv** [comment]
@anilsherkar 
SSO support is feature request #1360
There is no open feature request for code commit, please create an issue and describe the parts of CodeCommit you would like to see in the IDE
