### ISSUE TITLE
Lambda function in Gradle Project failed to deploy

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#854]
**Describe the bug**

The configuration of `build.gradle` from the Gradle project template is not correct that it does not recognize the `src/main/java` as the source root. This fails the Lambda handler deployment.

**To reproduce**

1. Install the latest version 1.2 of the plugin
2. Create a Gradle SAM application
3. Find `build.gradle` and right click `Import Gradle Project` 
4. Deploy the only Lambda function `helloworld.App` and it fails

**Expected behavior**

The expected behavior is to mark the project correctly and deploy this Lambda function successfully.

**Screenshots**

<img width="337" alt="Screen Shot 2019-03-27 at 10 46 00 AM" src="https://user-images.githubusercontent.com/7167513/55099761-8be9cc00-507d-11e9-88f0-d72d6555c6d5.png">

<img width="641" alt="Screen Shot 2019-03-27 at 10 34 59 AM" src="https://user-images.githubusercontent.com/7167513/55098982-2812d380-507c-11e9-8e6e-19931c6b95ca.png">

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by abrooksv** [comment]
```
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.0'
    testCompile 'junit:junit:4.12'
}
```

Should be used, its cleaner and more consistent

**Comment by abrooksv** [comment]
0.14.2 of SAM has been released with the fixed template
