### ISSUE TITLE
Gutter icons not shown on IDEA 2019.1 for macOS Mojave

### ISSUE THREAD

**Issue by merchanjavier** [aws/aws-toolkit-jetbrains#858]
**Describe the bug**
Unable to launch any Run/Debug configuration from the java Editor for a Lambda Handler

**To reproduce**
1. Create a new AWS Serverless Application
2. Choose a working AWS Profile and Region
3. Open the Lambda Handler in the Editor
4. No Gutter icons to Run/Debug the Lambda

**Expected behavior**
Gutter icons should be shown in the Editor for the Lambda Handler

**Screenshots**
![Screenshot 2019-03-28 at 16 34 01](https://user-images.githubusercontent.com/6906823/55171081-08f96c00-5178-11e9-9c29-f9b469c9c5f4.png)

![Screenshot 2019-03-28 at 16 34 26](https://user-images.githubusercontent.com/6906823/55171103-1151a700-5178-11e9-9f82-52a05ffc721c.png)

![Screenshot 2019-03-28 at 16 34 46](https://user-images.githubusercontent.com/6906823/55171113-16165b00-5178-11e9-9c66-caf3be19be2c.png)

**Your Environment**
 - OS: macOS Mojava 10.14.4
 - JetBrains' Product: IntelliJ IDEA Ultimate 2019.1
 - JetBrains' Product Version: Build #IU-191.6183.87
 - Toolkit Version: 1.2
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: JRE 11/0/2 JVM OpenJDK 64-Bit Server VM

**Comment by zhangzhx** [comment]
Hi @merchanjavier, what is the project's SDK version you are using? We currently only support `java8`, all other SDK versions of Java won't be shown the gutter icon.

We are considering to loose this restriction since you can set the bytecode version so that it doesn't matter what the Java SDK version you are using in the project.

**Comment by merchanjavier** [comment]
Hi @zhangzhx . Thank you for your quick answer and specially for this great plugin.
Actually, I had the JDK11 installed. After installing the JDK8 the gutter icons were displayed correctly.

These are the steps that I followed:
- Download the macOS X installer for JDK8 from https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
- Go through the install
- On IDEA, go to File/Project Structure. On Project Settings/Project click on New... Project SDK
- Chose JDK and then navigate to /Library/Java/JavaVirtualMachines/jdk1.8.... and click OK
- Gutter icons shall appear

**Comment by zhangzhx** [comment]
Hi, @merchanjavier 

Thanks for reporting this issue. This change #860 will show the Gutter icon whether or not you have Java11 used in your project. Please notice, at the moment Lambda only supports Java8 runtime, if you choose Java11, you need to set the bytecode version to Java8 from your builder's config file (`build.gradle` in Gradle, `pom.xml` in Maven).

**Comment by du-it** [comment]
Can you tell us when this restriction will be lost? I installed the latest version of OpenJdk (15) running language code 11.
