### ISSUE TITLE
Warn against deployments / lambda editing based on the presence of a CI/CD pipeline

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#867]
When deploying a stack / updating a lambda function / deleting a stack or lambda function, we should check for the presence of a CI/CD pipeline. If one is found we should inform the user to use their CI/CD infrastructure instead.

This only acts as a warning guard rail, they can then click ignore and continue using the toolkit to do the work.

### Acceptance Criteria
- **Warning is displayed** when deleting a CloudFormation stack or Lambda function which is part of an AWS CodePipeline.
- **Warning is displayed** when updating code/configuration of a Lambda function which is part of an AWS CodePipeline.
- **Warning is displayed** when updating a CloudFormation stack (while deploying serverless application) which is part of an AWS CodePipeline.

- _**Warning is not displayed**_ when deleting a CloudFormation stack or Lambda function which is not part of an AWS CodePipeline.
- _**Warning is not displayed**_ when updating code/configuration of a Lambda function which is not part of an AWS CodePipeline.
- _**Warning is not displayed**_ when updating a CloudFormation stack (while deploying serverless application) which is not part of an AWS CodePipeline.
- _**Warning is not displayed**_ when creating a new Lambda function or CloudFormation stack.

**Comment by kyoge** [comment]
If a CodeCommit repo (part of CodePipeline) is checked out locally in IDE and can be identified, we should mention that a `git push` should deploy the change.
