### ISSUE TITLE
AWS Explorer doesn't show the expand icon for the CloudFormation stack upon revisiting

### ISSUE THREAD

**Issue by kyoge** [aws/aws-toolkit-jetbrains#872]
**Describe the bug**
When I open AWS Explorer, it allows me to expand the cloud formation stack to see the lambda function deployed to it. If I keep the stack expanded and visit another view adjacent to AWS Explorer (e.g. Structure or Favorites) and then come back to see AWS Explorer, it doesn't show the expand icon for the CloudFormation stack until I refresh the AWS Explorer view.

**To reproduce**
1. Create an AWS Serverless Application using a SAM Template, "AWS SAM Hello World (Gradle)" and deploy it to your AWS account.
2. Open AWS Explorer, expand CloudFormation and the Stack under it, it should show the lambda function just deployed in Step 1.
3. Visit another view adjacent to AWS Explorer (e.g. Structure or Favorites) and then come back to see AWS Explorer.
4. It doesn't show the expand icon for the CloudFormation stack until I refresh the AWS Explorer view.

**Expected behavior**
The state of the CloudFormation stack should persist i.e. it should show the expand icon upon revisiting.

**Screenshots**
![image](https://user-images.githubusercontent.com/11089351/55429648-d3220200-5540-11e9-9ff1-4107b141bec0.png)

**Your Environment**
 - OS: macOS Mojave (Version 10.14.4)
 - JetBrains' Product: IntelliJ IDEA Ultimate
 - JetBrains' Product Version: 2019.1
 - Toolkit Version: 1.2
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: 1.8 (Java)

**Additional context**
None.

**Comment by abrooksv** [comment]
Fixed as collateral damage (collateral fix?) in #878
