### ISSUE TITLE
"Deploy Serverless Application" fails to deploy Lambda with third-party dependencies in virtualenv

### ISSUE THREAD

**Issue by GreatNewHope** [aws/aws-toolkit-jetbrains#873]
**Describe the bug**
My problem has to do with the "Deploy Serverless Application" and third-party dependencies. Currently using Python 3.6, with a virtualenv environment.

When I want to deploy a Lambda function, I usually follow this series of steps:
`pip freeze > requirements.txt`
`pip install -r requirements.txt -t /path/to/function/with/lambda_handler`
`sam build`
`sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket my-bucket`
`sam deploy --template-file packaged.yaml --stack-name my-stack`

And I expected "Deploy Serverless Application" would do something along those lines but in a more elegant and professional way. Unfortunately, it doesn't work as expected because when I use that button, I get an error saying that pip doesn't exit. Refer to the screenshots for more information on how the project is built, what the environment consists of and the exact error message.
**To reproduce**

Just click Deploy Serverless Application with a project depending on virtualenv

**Expected behavior**

Deployment of a working remote lambda using the included third-party dependencies

**Screenshots**
![Selección_001](https://user-images.githubusercontent.com/23639693/55436487-c16e4800-559c-11e9-9bb8-2e480b2a3fa1.png)
![Selección_002](https://user-images.githubusercontent.com/23639693/55436493-c3d0a200-559c-11e9-8fba-08270486a93d.png)
![Selección_003](https://user-images.githubusercontent.com/23639693/55436500-c6cb9280-559c-11e9-815d-d0c0f9c40ed8.png)

**Your Environment**
 - OS: Ubuntu 18 LTS
 - JetBrains' Product: Pycharm
 - JetBrains' Product Version: 2019.1
 - Toolkit Version: 1.2
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: 3.6

**Additional context**

**Comment by zhangzhx** [comment]
Hi @margaro95 , do you still see this error? `sam build` helps the project resolve the dependencies, and you don't have to run `pip install`. It installs the dependency packages to the sam build folder.

**Comment by rli** [comment]
Closing due to age. Please cut a new issue if you are still seeing this problem.
