### ISSUE TITLE
Deploy Serverless Application dialog doesn't complain when putting an existing stack name in 'Create Stack' input

### ISSUE THREAD

**Issue by kyoge** [aws/aws-toolkit-jetbrains#887]
**Describe the bug**
When deploying serverless application, the dialog doesn't complain if I put the name of an existing stack (available in 'Update Stack' field) in 'Create Stack' input field and the deployment runs successfully as if I am updating the existing stack.

**To reproduce**

**Expected behavior**
The dialog should complain / shouldn't allow deployment.

**Screenshots**
<img width="1280" alt="0" src="https://user-images.githubusercontent.com/11089351/55648845-41133700-5796-11e9-8d78-eb10453e4346.png">

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by zhangzhx** [comment]
This fix has been released in [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424).
