### ISSUE TITLE
List prerequisites and add installation instructions to the plugin's splash page on plugins.jetbrains.com

### ISSUE THREAD

**Issue by pccornel** [aws/aws-toolkit-jetbrains#889]
List the plugin's prerequisites and add installation instructions to the plugin's splash page at https://plugins.jetbrains.com/plugin/11349-aws-toolkit. 

For example: 

Prerequisites:

- Create an AWS account, if you don't already have one. (https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account)
- Create an AWS IAM user in the account, if you don't already have one. (https://docs.aws.amazon.com/IAM/latest/UserGuide/getting-started_create-admin-group.html#getting-started_create-admin-group-console)
- Create AWS access credentials for the IAM user, if you don't already have them. (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey)
- To use the Toolkit to work with AWS serverless applications, you must also install the following tools in this order: 

1. The AWS Command Line Interface (AWS CLI). (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html)
1. Docker, which must be running at all times while working with AWS serverless applications. (https://docs.docker.com/install/)
1. The AWS Serverless Application Model Command Line Interface (AWS SAM CLI). (https://docs.docker.com/install/)

Installation instructions:

1. In IntelliJ IDEA or PyCharm, on the **File** menu, choose **Settings**.
1. Choose **Plugins**.
1. In **Search plugins in marketplace**, begin typing **AWS Toolkit**. When **AWS Toolkit by Amazon Web Services** displays, choose it.
1. Choose **Install**.
1. When the **Third-party Plugins Privacy Note** displays, choose **Accept**.
1. Choose **Restart IDE**.
1. When prompted, choose **Restart**.

To start using the Toolkit, see the Quick Reference (https://docs.aws.amazon.com/console/toolkit-for-jetbrains/quick-reference).

**Comment by abrooksv** [comment]
The same instructions will show in the IDE marketplace

**Comment by pccornel** [comment]
Instead of my preceding proposal, use the following one instead, adding the following section just before the **Feature** section:

-----

### Installation ### 

See [Installing the AWS Toolkit for JetBrains](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/install) in the _AWS Toolkit for JetBrains User Guide_. 

To use this AWS Toolkit, you will first need an AWS account, a user within that account, and an access key for that user. To use the AWS Toolkit to do AWS serverless application development and to run/debug AWS Lambda functions locally, you will also need to install the AWS CLI, Docker, and the AWS SAM CLI. The preceding link covers setting up all of these prerequisites.

**Comment by abrooksv** [comment]
Changed made, market place pulls the data from the uploaded ZIP file so changes will take effect next release

**Comment by zhangzhx** [comment]
This has been released in [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424). The [plugin marketplace](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) has been updated.
