### ISSUE TITLE
Add "Learn more" links from plugin's splash page's feature bullets into the tech docs

### ISSUE THREAD

**Issue by pccornel** [aws/aws-toolkit-jetbrains#890]
Provide “Learn more” links after each of the bullets in the “Features” section of the plugin splash page at https://plugins.jetbrains.com/plugin/11349-aws-toolkit over to the _AWS Toolkit for JetBrains User Guide_ docs, for example to docs that details how to create new serverless projects, run/debug local Lambda functions, browse resources, invoke remote Lambda functions, and deploy serverless apps.

**Comment by pccornel** [comment]
For each of the bullets in the **Features** section:

* For the **New Project Wizard** bullet, add this [Learn more](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/new-project) link.
* For the **Run/Debug Local Lambda Functions** bullet, add this [Learn more](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/lambda-local) link.
* For the **AWS Resource Explorer** bullet, add this [Learn more](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/aws-explorer) link.
* For the **Invoke Remote Lambda Functions** bullet, add this [Learn more](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/lambda-remote) link.
* For the **Deploy SAM-based Applications** bullet, add this [Learn more](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/sam-deploy) link.

I would also recommend adding the following section just before the **Feature** section:

-----

### Installation ### 

See [Installing the AWS Toolkit for JetBrains](https://docs.aws.amazon.com/console/toolkit-for-jetbrains/install) in the _AWS Toolkit for JetBrains User Guide_. 

To use this AWS Toolkit, you will first need an AWS account, a user within that account, and an access key for that user. To use the AWS Toolkit to do AWS serverless application development and to run/debug AWS Lambda functions locally, you will also need to install the AWS CLI, Docker, and the AWS SAM CLI. The preceding link covers setting up all of these prerequisites.

**Comment by abrooksv** [comment]
Changed made, market place pulls the data from the uploaded ZIP file so changes will take effect next release

**Comment by zhangzhx** [comment]
This has been released in [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424). The [plugin marketplace](https://plugins.jetbrains.com/plugin/11349-aws-toolkit) has been updated.
