### ISSUE TITLE
OneLogin support

### ISSUE THREAD

**Issue by davidahern** [aws/aws-toolkit-jetbrains#904]
OneLogin is enabled on our AWS account for one time passcodes.
Currently i cannot logon to AWS with the plugin because of this.
Do you plan to support these kind of logins in the future? 
Unless i've missed something, i don't see any support currently (just installed the plugin today)

**Comment by abrooksv** [comment]
I am not familiar with OneLogin, I read https://developers.onelogin.com/api-docs/1/samples/aws-cli.

If you are working with that, if you use the `--profile`  the toolkit will see the same profile.

You will need to use the CLI to refresh credentials when they expire, the toolkit will auto-detect changes to the profile files.

**Comment by davidahern** [comment]
indeed, that worked
after running onelogin in the console, the plugin did pick up the changes eventually after i manually reloaded the profile a few times 
thanks
