### ISSUE TITLE
Create credentials has Create in quotes

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#909]
![Screen Shot 2019-04-11 at 5 17 36 PM](https://user-images.githubusercontent.com/8992246/56003882-b80c6c00-5c7d-11e9-849b-7002f99109af.png)

**Comment by zhangzhx** [comment]
This fix has been released in [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424).
