### ISSUE TITLE
Create new Serverless Java Project, can't debug because handler isn't found

### ISSUE THREAD

**Issue by leepa** [aws/aws-toolkit-jetbrains#913]
**Describe the bug**

When trying to debug locally the UI just complains the handler `helloworld.App::handleRequest` cannot be found in the project. The function deploys fine to Lambda and it does execute in AWS.

**To reproduce**
1. Create new AWS Serverless project.
2. Try  debug or run locally

**Expected behavior**
Being able to debug.

**Your Environment**
 - OS: Mojave
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: 2019.1
 - Toolkit Version: (whatever the latest on this date is... that's not easy to find)
 - SAM CLI Version: SAM CLI, version 0.14.2
 - JVM/Python Version:

```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
```

**Comment by leepa** [comment]
I also tried this with

```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

And no joy either

**Comment by leepa** [comment]
Digging deeper - it appears that the folder types when the project initially loads aren't set and because the .pom isn't in the root, IDEA doesn't treat it as a Java project and that seems to confuse the discovery of classes etc.

I can't seem to get this to work from the basic/default project so any pointers would be great.

**Comment by abrooksv** [comment]
You can right click the pom.xml and import it into IntelliJ.

![Screen Shot 2019-04-15 at 9 31 37 AM](https://user-images.githubusercontent.com/8992246/56149369-46743c80-5f61-11e9-82f8-910bbdd1d6b2.png)

Tracking issue for automating this: #608

**Comment by leepa** [comment]
Amazing - thanks!
