### ISSUE TITLE
Do we know if this plugging is supported in WebStorm too

### ISSUE THREAD

**Issue by karlismelderis** [aws/aws-toolkit-jetbrains#914]
**Is your feature request related to a problem? Please describe.**
I would love to use this plugin in WebStorm too and skip IntelliJ

**Describe the solution you'd like**
be able to install the plugin in WebStorm

**Describe alternatives you've considered**
:) switching to IntelliJ but would like to avoid if possible

**Comment by abrooksv** [comment]
We do not currently support NodeJS, so we have not enabled WebStorm yet.

Tracking issue #187
