### ISSUE TITLE
Automatically create Lambda local Run Configurations

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#916]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When a project is created via the SAM New Project wizard it would be great if the toolkit could automatically create some temporary local run configurations for each of the functions that existed in the template.

**Describe alternatives you've considered**

Having to manually create configurations can be painful

**Additional context**

**Comment by abrooksv** [comment]
Implemented and released
