### ISSUE TITLE
Way to Search All Lambdas

### ISSUE THREAD

**Issue by markoleary** [aws/aws-toolkit-jetbrains#921]
My project has lots of lambdas (300+), and it's hard to find the one I'm looking for. You have to scroll or search through the list and then double-click "Results truncated" to view more, which is time consuming.

The existing search (by just typing) is great, but it doesn't search the truncated results. It would be great if it could search all lambdas.

I suppose the feature could either search for the lambda remotely, or just have an option to show all available lambdas, without truncating the results, and the existing search would work.

**Comment by abrooksv** [comment]
Truncation has been removed. All lambdas will load in a single expansion now.
