### ISSUE TITLE
NodeJs serverless new project wizard support

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#933]
**Is your feature request related to a problem? Please describe.**
Provide support to NodeJs AWS serverless project template checkout similar as Python and Java.

**Describe the solution you'd like**

Unlike Java or Python, NodeJs doesn't need to provide an SDK, instead NodeJs interpreter should be selected and the JavaScript language level should be configured.

**Comment by abrooksv** [comment]
Blocked on #1033
