### ISSUE TITLE
Edit Run/Debug configuration panel not working correctly for Function Selection Combo box.

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#955]
**To reproduce**
1. Create a new Run/Debug configuration opens the edit configuration panel.
1. Select **From template:** and select one function from the combo box to the right
1. Click **SAM CLI** tab and type something to the **Docker Network**
1. An error shows in the below that says `Error: Function logical name must be specified.`

**Expected behavior**
The function combo box should not be reloaded.

**Screenshots**
<img width="622" alt="Screen Shot 2019-05-09 at 2 47 16 PM" src="https://user-images.githubusercontent.com/7167513/57488919-5c77d300-7269-11e9-8fec-7ac8e05f755f.png">

**Your Environment**
 - OS: Mac
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version: 2019.1
 - Toolkit Version: 1.3
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by glambert22** [comment]
Any updates on this issue. I experiencing same behavior :
- OS: Mac
- JetBrains' IntelliJ Ultimate: 2019.3
- Toolkit Version: 1.10-193
- SAM CLI Version: 0.41.0
- JVM/Java Version: 8

**Comment by CQBB** [comment]
this tool is so hard to use.
