### ISSUE TITLE
Run and debug lambda with "Layers" defined in template.yaml

### ISSUE THREAD

**Issue by alanrothschild** [aws/aws-toolkit-jetbrains#964]
I would like to be able to locally debug functions with layers defined in the sam template of my project

![image](https://user-images.githubusercontent.com/9385023/57804694-4c5c6980-7729-11e9-87c6-e6875f767de4.png)

Currently when I attempt to debug I get the following error

[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'scipy'

I attempted to find a workaround and found that the temporary template.yaml that is created by the toolkit and passed to the SAM CLI has the layers property removed

Resources:
  Function:
    Properties:
      CodeUri: Function
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 900
    Type: AWS::Serverless::Function

If add the layer into this temporary file and call the SAM CLI directly from the command line it nicely downloads the layer and then runs successfully

Please let me know if there is any additional information I can provide.  This is a great tool overall.

**Comment by abrooksv** [comment]
How are you creating the Run config? That looks like the template for "raw" lambda (Where a template is not used)

**Comment by alanrothschild** [comment]
Ahhh - Thank you!  I was right clicking on my function in python and chosing debug - I didn't realize that I needed to chose the template.yaml in the debug config window since it worked just fine until I started doing stuff that the raw template didn't support.

Now that I chose the template in the debug window it is beautifully downloading the layer

Downloading arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x

Thank you and the community for such an awesome tool:)
