### ISSUE TITLE
Existing directory will not run properly

### ISSUE THREAD

**Issue by Rubyj** [aws/aws-toolkit-jetbrains#972]
@abrooksv @zhangzhx 
If I open an existing directory in PyCharm (that follows the correct format for a SAM project) I can not get the lambda to run. I receive the error "Can not find app.lambda_handler" while I am sure everything is set up correctly. However, If I create a new SAM project in PyCharm (hello_world) and then I drag the contents of my project over replacing the contents of hello_world, I can then set up a working run config. 

To reproduce this, I clone an existing SAM git repo (that has worked in PyCharm with aws-toolkit). Open that repo in PyCharm and try to create a run config.I receive the error "Can not find app.lambda_handler"

**Comment by abrooksv** [comment]
We require the source folder to be marked. So whichever folder that contains app, must be marked by right clicking on it in the project view and going to **Mark Director as->Sources Root**

**Comment by Rubyj** [comment]
@abrooksv Ah, I see. Great thanks! Will make sure to do this next time!
