### ISSUE TITLE
Create a ktlint rule to standardize import

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#973]
Some of the rules we need to consider:
* Do we want `import as`?
* `import some.package.*` is not allowed

**Comment by rli** [comment]
ktlint has editorconfig support, maybe we just need to set that up.
[ktlint](https://github.com/pinterest/ktlint#editorconfig), [intellij plugin](https://plugins.jetbrains.com/plugin/7294-editorconfig)

couple of things i've noticed; there might be more:

* long code lines: when do we break?
* import ordering
* 4 vs 8 spaces for "Continuation indent"

**Comment by abrooksv** [comment]
We also need to migrate our ktlint rules to new package pattern and migrate to https://github.com/pinterest/ktlint

**Comment by abrooksv** [comment]
There is an experimental ktlint rule coming for this: https://github.com/pinterest/ktlint/issues/189

**Comment by abrooksv** [comment]
We differ in the fact that we group statics at the top first then everything else.
