### ISSUE TITLE
Build only the function I want to test

### ISSUE THREAD

**Issue by jfuss** [aws/aws-toolkit-jetbrains#983]
SAM CLI now supports building a single function instead of the whole template, as of [v0.16.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.16.0). Currently the toolkit will run `sam build` when debugging and invoking the function. This will build the whole template and increase the time for a customer to debug/invoke. If instead, the toolkit passes the Functions LogicalID from the template to the build command `sam build MyFunction`, build will only build that function. This should only be used in the debug/invoke cases and the full template will still need to be built before package/deploy to ensure all functions are built before uploading to the cloud.

**Comment by abrooksv** [comment]
I assume that if we pass the LogicalID pre 0.16, it fails to invoke?

**Comment by abrooksv** [comment]
NodeJS branch contains a min version bump to 0.16 already. We can either put in conditional logic, or wait for this optimization until NodeJS is ready.

**Comment by jfuss** [comment]
In version prior to v0.16, the command will fail if you try and pass the LogicalId to the build command. The output would be similar to:

```
$ samdev build MyFunciton
Usage: samdev build [OPTIONS]

Error: Got unexpected extra argument (MyFunciton)
```
